// 「今天吃什么」分片：健康地方菜与药膳四季（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const HEALTHY_REGION_DISHES: FoodDish[] = [
  { name: '开水白菜', tags: ['healthy'], note: '看着清汤，其实是功夫吊汤' },
  { name: '鸡豆花', tags: ['healthy'], note: '鸡茸做成豆花，汤清味极鲜' },
  { name: '清炖狮子头', tags: ['healthy'], note: '清汤慢煨，比红烧少一层油' },
  { name: '清蒸鲥鱼', tags: ['healthy'], note: '带鳞清蒸，时令肥美少放油' },
  { name: '石屏烧豆腐', tags: ['healthy'], note: '烤豆腐清淡，干碟少蘸提味' },
  { name: '云南香茅烤鱼', tags: ['healthy', 'diabetes'], note: '香茅塞鱼烤，野香解又腻' },
  { name: '个旧草芽米线', tags: ['healthy'], note: '草芽脆嫩，配清汤米线鲜甜' },
  { name: '竹筒鸡', tags: ['healthy'], note: '竹筒蒸鸡，清嫩带一股竹香' },
  { name: '白族清汤鱼', tags: ['healthy'], note: '洱海鱼清汤煮，鲜而不油腻' },
  { name: '凉拌折耳根', tags: ['healthy', 'gout'], note: '折耳根拌辣椒，贵州爽口令' },
  { name: '潮汕鱼饭', tags: ['healthy'], note: '盐水煮鱼晾食，潮汕古早鲜味' },
  { name: '海南陵水酸粉', tags: ['healthy'], note: '细粉配酸辣卤，卤汁偏咸少量' },
  { name: '椰青炖竹丝鸡', tags: ['healthy'], note: '椰青入盅炖鸡，清甜不上火' },
  { name: '清炖羊肉（撇油）', tags: ['healthy'], note: '冷水炖羊肉，撇净浮油暖身' },
  { name: '新疆那仁', tags: ['healthy'], note: '清炖羊肉盖面片，哈萨克待客' },
  { name: '新疆薄皮包子', tags: ['healthy'], note: '羊肉洋葱馅，蒸的比烤清爽' },
  { name: '荞面碗托', tags: ['healthy', 'diabetes', 'gout'], note: '荞麦占比看配料，辣子卤汁少量' },
  { name: '洋芋搅团', tags: ['healthy', 'gout'], note: '土豆捶成糊，汤水拌着来吃' },
  { name: '兰州三炮台', tags: ['healthy'], note: '八宝茶泡着喝，别再另加冰糖蜜' },
  { name: '顺德四色鱼面', tags: ['healthy', 'diabetes'], note: '鱼肉掺面粉做的面，算主食量' },
  { name: '张关合渣', tags: ['healthy'], note: '黄豆磨浆煮青菜，土家合渣' },
  { name: '腾冲土锅子', tags: ['healthy'], note: '陶锅慢煨荤素，汤清不上火' },
  { name: '白族海东素鱼', tags: ['healthy'], note: '萝卜豆腐塑形，浇汁似鱼鲜' },
  { name: '云南树番茄凉拌', tags: ['healthy', 'gout'], note: '烤树番茄捣酱，酸爽拌菜鲜' },
  { name: '傣味舂木瓜', tags: ['healthy'], note: '青木瓜舂碎，酸辣开胃低油' },
  { name: '云南酸木瓜煮鱼', tags: ['healthy'], note: '酸木瓜吊汤煮鱼，开胃不放油' },
  { name: '贵州独山盐酸', tags: ['healthy'], note: '盐酸菜是腌菜，少量不另加盐' },
  { name: '黔东南腌汤萝卜', tags: ['healthy'], note: '腌汤泡萝卜，苗家酸爽口' },
  { name: '潮汕薄壳米', tags: ['healthy'], note: '薄壳肉本身偏咸，炒时不放盐' },
  { name: '潮州菜脯蒸鱼', tags: ['healthy'], note: '菜脯偏咸控量，蒸鱼不另加盐' },
  { name: '客家艾糍', tags: ['healthy'], note: '艾草和糯米，蒸出清明香' },
  { name: '海南和乐蟹（清蒸）', tags: ['healthy'], note: '膏蟹清蒸原味，只吃蟹肉' },
  { name: '新疆清炖马肉', tags: ['healthy'], note: '哈萨克清炖马肉，少油原香' },
  { name: '宁夏手抓羊肉', tags: ['healthy'], note: '清水煮羊肉，蘸椒盐撇净油' },
  { name: '青海熬饭', tags: ['healthy'], note: '羊肉根菜一锅煮，清汤暖身' },
  { name: '陕西荞麦凉粉', tags: ['healthy', 'diabetes'], note: '荞麦成粉凉拌，三秦夏日凉' },
  { name: '山西榆皮面饸饹', tags: ['healthy', 'diabetes'], note: '杂面压饸饹，清汤少浇头' },
  { name: '甘肃洋芋蕨麻', tags: ['healthy'], note: '蕨麻配土豆，藏区清淡煮' },
  { name: '南京芦蒿炒香干', tags: ['healthy', 'gout'], note: '芦蒿脆嫩，香干少量提鲜' },
  { name: '淮扬软兜长鱼', tags: ['healthy'], note: '鳝背旺火快煸，少油嫩滑口' },
  { name: '宁波咸齑黄鱼汤', tags: ['healthy'], note: '咸齑吊汤鲜，控量不另加盐' },
  { name: '温州江蟹生', tags: ['healthy'], note: '生腌蟹有寄生虫风险，肠胃弱别碰' },
  { name: '台州家烧鳗鲞', tags: ['healthy'], note: '鳗鱼干家烧，咸鲜蒸着吃' },
  { name: '潮汕戈饭', tags: ['healthy'], note: '砂锅泡虾米饭，潮汕古早味' },
  { name: '漳州豆干面', tags: ['healthy'], note: '永安豆干配面，清汤闽南鲜' },
  { name: '均安蒸猪', tags: ['healthy'], note: '顺德蒸猪撒芝麻，夹瘦的那块' },
  { name: '东江盐焗鸡（去皮）', tags: ['healthy'], note: '盐焗手撕鸡，吃时撕去鸡皮' },
  { name: '潮汕橄榄糁蒸鱼', tags: ['healthy'], note: '橄榄糁是盐渍橄榄，控量免加盐' },
  { name: '广西五色糯米饭', tags: ['healthy'], note: '植物染糯米，一小块尝鲜别当饱' },
  { name: '侗家腌鱼', tags: ['healthy'], note: '酸腌鱼少量尝，风味偏咸' },
  { name: '湘西社饭', tags: ['healthy'], note: '蒿菜糯米蒸，带腊肉咸糯浅尝' },
  { name: '湖南藠头炒肉', tags: ['healthy'], note: '藠头脆辣提香，配瘦肉快炒' },
  { name: '恩施炕土豆', tags: ['healthy'], note: '小土豆干炕，土家炕菜香' },
  { name: '利川柏杨豆干', tags: ['healthy'], note: '豆干清卤，适量吃不齁咸' },
  { name: '香格里拉松茸炖鸡', tags: ['healthy'], note: '松茸配土鸡，高原清炖鲜汤' },
  { name: '白族三道茶', tags: ['healthy'], note: '一苦二甜三回味，甜茶浅尝' },
  { name: '大理雕梅', tags: ['healthy'], note: '青梅雕花腌，尝鲜一小颗' },
  { name: '德宏泡露', tags: ['healthy'], note: '傣家酸嘢泡，开胃浅尝吃' },
  { name: '傣味烤罗非鱼', tags: ['healthy', 'diabetes'], note: '香茅塞鱼炭烤，云南野香浓' },
  { name: '文山荷城鸡', tags: ['healthy'], note: '白斩土鸡配蘸，壮乡清爽鲜' },
  { name: '红河干巴菌', tags: ['healthy'], note: '干巴菌少油煸，云南菌中王' },
  { name: '保山火瓢牛肉', tags: ['healthy'], note: '铜瓢清煮牛肉，撇油配青菜' },
  { name: '黄芪炖鸡（去油）', tags: ['healthy'], note: '黄芪炖鸡撇油，孕哺婴幼儿遵医嘱' },
  { name: '山药枸杞粥', tags: ['healthy'], note: '山药枸杞同熬，温热清甜' },
  { name: '四神汤', tags: ['healthy', 'gout'], note: '茯山莲芡煮汤，清淡素版' },
  { name: '姜枣茶（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '姜丝煮枣片，枣两片提味不食枣' },
  { name: '芡实山药粥', tags: ['healthy'], note: '芡实配山药，熬得稠又绵' },
  { name: '莲子芡实羹', tags: ['healthy'], note: '莲子芡实熬羹，不加糖稠绵' },
  { name: '沙参玉竹瘦肉汤', tags: ['healthy'], note: '沙参玉竹煲瘦肉，清汤少盐' },
  { name: '麦冬玉竹茶', tags: ['healthy'], note: '麦冬玉竹泡水，口干时来杯' },
  { name: '茯苓山药粥', tags: ['healthy'], note: '茯苓粉调山药，煮碗早粥' },
  { name: '薏米茯苓粥', tags: ['healthy'], note: '薏米配茯苓，早上煮碗热粥' },
  { name: '山楂麦芽水', tags: ['healthy'], note: '山楂麦芽煮水，吃多了顺顺' },
  { name: '枸杞子粥', tags: ['healthy'], note: '枸杞后下锅，煮碗微甜早粥' },
  { name: '黄芪枸杞茶', tags: ['healthy'], note: '黄芪枸杞泡水，孕哺幼儿遵医嘱' },
  { name: '红枣小米粥', tags: ['healthy'], note: '红枣配小米，熬出暖胃香' },
  { name: '五红汤', tags: ['healthy'], note: '五样红色食材煮水，热乎甜口' },
  { name: '西洋参茶', tags: ['healthy'], note: '西洋参含片泡水，提神不上火' },
  { name: '玉竹粥', tags: ['healthy'], note: '玉竹煮碗粥，秋天常食不腻' },
  { name: '山药芡实粥', tags: ['healthy'], note: '山药芡实同煮，稠绵当早餐' },
  { name: '陈皮姜茶', tags: ['healthy'], note: '陈皮配姜丝，热热喝一杯' },
  { name: '玫瑰枸杞茶', tags: ['healthy'], note: '玫瑰配枸杞，泡杯花香茶饮' },
  { name: '决明子菊花茶', tags: ['healthy'], note: '决明子配菊花，微苦清口' },
  { name: '当归生姜羊肉汤', tags: ['healthy'], note: '当归姜炖羊肉，孕期忌多吃' },
  { name: '黄芪炖乌鸡', tags: ['healthy'], note: '黄芪炖乌鸡撇油，孕幼遵医嘱' },
  { name: '天麻炖鱼头', tags: ['healthy'], note: '天麻炖鱼头少盐，孕幼遵医嘱' },
  { name: '荷叶冬瓜饮', tags: ['healthy', 'diabetes'], note: '荷叶冬瓜煮水，夏天解暑湿' },
  { name: '陈皮红豆沙', tags: ['healthy'], note: '陈皮提香，少糖熬红豆沙' },
  { name: '佛手小米粥', tags: ['healthy', 'gout'], note: '佛手丝调小米，煮碗开胃粥' },
  { name: '雪耳百合饮', tags: ['healthy'], note: '雪耳配百合，滋润不加糖' },
  { name: '桂圆红枣汤', tags: ['healthy'], note: '桂圆红枣甜汤，一小碗足够' },
  { name: '桑葚枸杞饮', tags: ['healthy'], note: '桑葚配枸杞，煮水黑亮润' },
  { name: '砂仁排骨汤', tags: ['healthy'], note: '砂仁后下醒脾，撇油喝清汤' },
  { name: '扁豆薏仁汤', tags: ['healthy', 'diabetes'], note: '白扁豆配薏米煮透，当汤饮' },
  { name: '芡实莲子羹', tags: ['healthy'], note: '芡实煮莲子，稠羹少糖小碗' },
  { name: '玉竹百合汤', tags: ['healthy'], note: '玉竹配百合，煮碗清甜汤' },
  { name: '红枣花生浆', tags: ['healthy'], note: '花生红枣打浆，当早一杯' },
  { name: '陈皮山楂饮', tags: ['healthy'], note: '陈皮配山楂，解腻饭后顺' },
  { name: '山药糯米粥', tags: ['healthy', 'gout'], note: '山药配糯米煮粥，少量尝' },
  { name: '莲子心茶', tags: ['healthy'], note: '莲子心泡水，味苦不宜常饮' },
  { name: '百合雪梨盅', tags: ['healthy'], note: '百合配雪梨，隔水炖盅润' },
  { name: '山药百合羹', tags: ['healthy'], note: '山药配百合，煮碗热暖羹' },
  { name: '枸杞菊花茶', tags: ['healthy'], note: '枸杞配菊花，泡杯日常茶饮' },
  { name: '茯苓薏米糊', tags: ['healthy', 'gout'], note: '茯苓薏米磨糊，代早点半碗' },
  { name: '莲子红枣汤', tags: ['healthy'], note: '莲子配红枣，煮碗甜汤小份' },
  { name: '桂圆莲子羹', tags: ['healthy'], note: '桂圆煮莲子，甜羹一小碗' },
  { name: '陈皮普洱茶', tags: ['healthy'], note: '陈皮配普洱，去腻饭后一杯' },
  { name: '生姜大枣饮', tags: ['healthy'], note: '生姜配大枣，煮水暖脾胃' },
  { name: '山药茯苓糕', tags: ['healthy'], note: '山药茯苓蒸糕，少糖当点心' },
  { name: '红枣玫瑰饮', tags: ['healthy'], note: '红枣配玫瑰，煮水气色好' },
  { name: '莲子猪肚汤', tags: ['healthy'], note: '莲子煲猪肚，撇油喝清汤' },
  { name: '芡实茯苓粥', tags: ['healthy', 'gout'], note: '芡实配茯苓，煮粥当早餐' },
  { name: '百合鸡蛋羹', tags: ['healthy'], note: '百合粉调蛋液，蒸出嫩羹' },
  { name: '沙参麦冬汤', tags: ['healthy'], note: '沙参麦冬煮水，传统搭配' },
  { name: '桂圆枸杞茶', tags: ['healthy'], note: '桂圆配枸杞，泡水甜一点' },
  { name: '山药大枣粥', tags: ['healthy', 'gout'], note: '山药加大枣，枣一两枚调味' },
  { name: '茯苓饼（少糖）', tags: ['healthy'], note: '茯苓粉烙饼，老式少糖点心' },
  { name: '姜丝红糖水', tags: ['healthy'], note: '姜丝煮红糖，受寒来一杯' },
  { name: '玫瑰大枣茶', tags: ['healthy'], note: '玫瑰配大枣煮水，当日常饮' },
  { name: '凉拌蕨菜', tags: ['healthy', 'gout'], note: '春蕨焯水拌蒜，偶尔少量尝鲜' },
  { name: '凉拌蒲公英', tags: ['healthy', 'gout'], note: '蒲公英焯水，微苦清火凉拌' },
  { name: '生炒草头', tags: ['healthy', 'gout'], note: '草头旺火快炒，春天那口嫩' },
  { name: '葱油蚕豆', tags: ['healthy'], note: '蚕豆葱油焖，春末软糯清香' },
  { name: '清炒蒲菜', tags: ['healthy', 'gout'], note: '蒲菜切片清炒，水嫩江南春' },
  { name: '地皮菜炒蛋', tags: ['healthy', 'gout'], note: '地皮菜一两克泡发，淘净再炒' },
  { name: '腌韭菜花', tags: ['healthy'], note: '韭菜花腌小碟，春天开开胃' },
  { name: '薇菜炒鸡蛋', tags: ['healthy', 'gout'], note: '薇菜泡发透，偶尔少量尝鲜' },
  { name: '香椿拌凉粉', tags: ['healthy', 'gout'], note: '香椿焯水切碎，拌凉粉开胃' },
  { name: '凉拌蒲瓜', tags: ['healthy', 'gout'], note: '蒲瓜焯水凉拌，夏日水嫩清' },
  { name: '荷叶粥', tags: ['healthy', 'gout'], note: '鲜荷叶铺粥面，夏天一锅香' },
  { name: '水煮菱角', tags: ['healthy', 'gout'], note: '嫩菱角水煮，粉糯当季小食' },
  { name: '西瓜（一小块）', tags: ['healthy', 'gout'], note: '水分足解渴，糖偏高别贪多' },
  { name: '生啃鲜莲蓬', tags: ['healthy'], note: '莲子宜煮食，生啃洗净偶尔' },
  { name: '三豆饮', tags: ['healthy'], note: '绿豆赤小豆黑豆，夏天煮来喝' },
  { name: '薄荷拌冬瓜', tags: ['healthy', 'gout', 'diabetes'], note: '薄荷点冬瓜，清凉夏小碟' },
  { name: '凉拌子姜丝', tags: ['healthy', 'gout'], note: '嫩姜切丝拌，夏天开胃碟' },
  { name: '清炒瓠子', tags: ['healthy', 'gout'], note: '嫩瓠子清炒，夏季瓜菜水灵' },
  { name: '凉拌凉薯', tags: ['healthy', 'gout'], note: '凉薯生掰脆甜，秋天解秋燥' },
  { name: '冬枣（几颗）', tags: ['healthy', 'gout'], note: '冬枣脆甜，一小把解个馋' },
  { name: '冰糖山楂（少糖）', tags: ['healthy'], note: '山楂煮水少糖，秋天开胃消' },
  { name: '桂花蒸山药', tags: ['healthy', 'gout'], note: '山药蒸糯点桂花，秋补不腻' },
  { name: '鲜菱角炒肉片', tags: ['healthy'], note: '菱角配瘦肉，秋天水乡时令' },
  { name: '冬笋炒肉片', tags: ['healthy'], note: '冬笋切片炒，时令鲜掉眉' },
  { name: '慈姑烧肉片', tags: ['healthy'], note: '慈姑粉糯，配瘦肉冬天吃' },
  { name: '粉葛赤小豆汤', tags: ['healthy'], note: '粉葛煲豆汤，冬天生津润' },
  { name: '凉拌牛蒡丝', tags: ['healthy', 'gout'], note: '牛蒡切丝拌，根茎纤维高' },
  { name: '蒸铁棍山药', tags: ['healthy', 'gout'], note: '铁棍山药整根蒸，冬天当主食' },
  { name: '萝卜丝炖海带', tags: ['healthy', 'gout'], note: '白萝卜配泡发海带一小片同炖' },
  { name: '芹菜根香荽水', tags: ['healthy'], note: '芹菜根配香菜，煮水代饮' },
  { name: '头刀韭菜炒蛋', tags: ['healthy', 'gout'], note: '开春头刀韭，炒蛋最鲜嫩' },
  { name: '蒸紫心红薯', tags: ['healthy', 'gout'], note: '紫薯红薯蒸，冬天热乎甜' },
  { name: '冰糖炖荸荠', tags: ['healthy', 'gout'], note: '荸荠去皮煮透，冰糖一两点' },
  { name: '素扣肉', tags: ['healthy'], note: '芋头夹豆皮，蒸出素扣肉香' },
  { name: '鼎湖上素', tags: ['healthy', 'gout'], note: '菌笋慢煨，鲜菌嘌呤中，缓解期适量' },
  { name: '素火腿', tags: ['healthy', 'diabetes'], note: '豆皮卷卤制，切片赛过火腿' },
  { name: '素鲍鱼', tags: ['healthy'], note: '杏鲍菇改花刀，素席也显高档' },
  { name: '素鹅卷', tags: ['healthy'], note: '千张裹菜煎卤，少油卤汁控盐' },
  { name: '素四宝', tags: ['healthy', 'gout'], note: '寺中四宝烩一碟，菌豆适量吃' },
  { name: '十八罗汉斋', tags: ['healthy', 'gout'], note: '十八样素料合炒，菌豆适量' },
  { name: '香菇面筋', tags: ['healthy', 'gout'], note: '香菇烩面筋，鲜菇适量、缓解期浅尝' },
  { name: '素东坡肉', tags: ['healthy'], note: '芋头仿东坡，看着肥吃着素' },
  { name: '罗汉笋', tags: ['healthy', 'gout'], note: '竹笋配鲜菌适量，清淡罗汉菜' },
  { name: '素方糕', tags: ['healthy'], note: '千张压成方，卤汁控盐切片' },
  { name: '素咕咾肉', tags: ['healthy'], note: '杏鲍菇裹浆，少油酸甜口' },
  { name: '素肠旺', tags: ['healthy'], note: '豆腐皮灌菌，卤汁控盐切片' },
  { name: '素四喜', tags: ['healthy'], note: '笋耳菇腐烩，素席四样鲜' },
  { name: '藏式糌粑糊', tags: ['healthy', 'gout'], note: '糌粑调成糊，半碗算主食' },
  { name: '酥油茶（淡）', tags: ['healthy'], note: '砖茶打酥油，藏区御寒饮' },
  { name: '蒙古奶茶（咸淡）', tags: ['healthy'], note: '砖茶兑低脂奶，不放酥油不加糖' },
  { name: '奶皮子', tags: ['healthy'], note: '牛奶结一层皮，内蒙少量吃' },
  { name: '奶豆腐', tags: ['healthy'], note: '牛奶凝成块，牧区蛋白零食' },
  { name: '手把肉（撇油）', tags: ['healthy'], note: '清水煮羊肉，蘸韭菜花少盐' },
  { name: '朝鲜族拌桔梗', tags: ['healthy', 'gout'], note: '桔梗撕丝凉拌，朝鲜族咸菜' },
  { name: '朝鲜族酱汤豆腐', tags: ['healthy'], note: '大酱煮豆腐，适量配糙米饭' },
  { name: '彝族荞麦粑粑', tags: ['healthy', 'diabetes'], note: '荞面烙成粑，凉山低GI粮' },
  { name: '傣族香茅草包烧', tags: ['healthy'], note: '香茅裹菜烤，傣味少油烟' },
  { name: '白族乳扇（生）', tags: ['healthy'], note: '大理乳扇选杀菌奶，加热再吃' },
  { name: '壮族水糍粑', tags: ['healthy'], note: '糯米打糍粑，壮家无糖尝' },
  { name: '客家萝卜粄', tags: ['healthy'], note: '米皮包萝卜蒸，馅里猪油少量' },
  { name: '信阳炖菜', tags: ['healthy'], note: '大别山慢炖，少油又暖身' },
  { name: '洛阳牡丹燕菜', tags: ['healthy'], note: '萝卜丝仿燕菜，洛阳清汤' },
  { name: '黄陂三鲜', tags: ['healthy'], note: '鱼丸肉丸蒸，湖北清汤鲜' },
  { name: '洪湖粉蒸藕', tags: ['healthy'], note: '藕片裹米粉，蒸来当主食' },
  { name: '藜蒿炒腊香干', tags: ['healthy'], note: '鄱阳藜蒿脆，配香干快炒' },
  { name: '永和豆腐酿', tags: ['healthy'], note: '吉安酿豆腐，客家清蒸法' },
  { name: '四星望月蒸笼', tags: ['healthy'], note: '米粉裹菜蒸，兴国笼锅香' },
  { name: '庐山石耳炖蛋', tags: ['healthy'], note: '石耳配蛋炖，庐山清补汤' },
  { name: '拆烩鲢鱼头', tags: ['healthy'], note: '淮扬去骨烩鱼头，汤白不放油' },
  { name: '扬州烫干丝', tags: ['healthy'], note: '干丝焯水拌，早茶少油吃' },
  { name: '常州加蟹小笼', tags: ['healthy'], note: '薄皮小笼包，蟹鲜少量品' },
  { name: '衢州开化青蛳', tags: ['healthy'], note: '山溪清水蛳，务必煮透再吃' },
  { name: '丽水缙云敲肉羹', tags: ['healthy'], note: '番薯粉勾芡，薄羹暖胃肠' },
  { name: '舟山咸齑拖鱼', tags: ['healthy'], note: '海鱼裹粉煎，咸鲜少油吃' },
  { name: '潮汕菜心胆', tags: ['healthy'], note: '取菜心嫩胆，白灼蘸普宁' },
  { name: '梅州腌面配汤', tags: ['healthy'], note: '客家拌面少油，汤也少盐' },
  { name: '客家酿三宝', tags: ['healthy'], note: '苦瓜茄椒酿，蒸来不吃煎' },
  { name: '韶关炒山坑螺', tags: ['healthy'], note: '山溪螺紫苏炒，务必翻炒透' },
  { name: '湛江沙虫汤', tags: ['healthy'], note: '沙虫煮清汤，鲜甜不过咸' },
  { name: '茂名水东鸭', tags: ['healthy'], note: '白切水东鸭，蘸姜葱去皮' },
  { name: '顺德桑拿鸡', tags: ['healthy'], note: '上层隔水蒸，下层煮粥鲜' },
  { name: '中山崖鹰豆', tags: ['healthy'], note: '石崖豆干煸，少盐尝鲜吃' },
  { name: '云浮郁南笋干', tags: ['healthy'], note: '笋干煲清汤，山货不油腻' },
  { name: '北海沙虫干粥', tags: ['healthy'], note: '沙虫熬白粥，鲜掉眉毛梢' },
  { name: '百色芒果鸡', tags: ['healthy'], note: '青芒炒鸡丁，桂西酸甜鲜' },
  { name: '崇左甘蔗焖鱼', tags: ['healthy'], note: '蔗段焖河鱼，天然回甘鲜' },
  { name: '六盘水荷叶糯米', tags: ['healthy'], note: '荷叶蒸糯米，黔西清香饭' },
  { name: '毕节威宁炒苦菜', tags: ['healthy'], note: '苦菜清火炒，高原当季鲜' },
  { name: '铜仁江口米豆腐', tags: ['healthy'], note: '米豆腐凉拌，酸汤泡椒鲜' },
  { name: '镇远道肉干', tags: ['healthy'], note: '风干瘦肉嚼，尝咸小包装' },
  { name: '大理巍山扒肉饵丝', tags: ['healthy'], note: '饵丝配扒肉，撇油汤清鲜' },
  { name: '玉溪卤雕', tags: ['healthy'], note: '卤汁豆腐干，适量不齁咸' },
  { name: '百合杏仁粥', tags: ['healthy', 'gout'], note: '用甜杏仁煮透，配百合熬粥' },
  { name: '山药南瓜糊', tags: ['healthy', 'gout'], note: '山药南瓜打糊，算半碗主食' },
  { name: '红枣桂圆粥', tags: ['healthy'], note: '红枣桂圆熬粥，甜润不另加糖' },
  { name: '紫苏生姜饮', tags: ['healthy'], note: '紫苏配姜丝，煮杯水当茶饮' },
  { name: '山药小米羹', tags: ['healthy', 'gout'], note: '山药打泥调小米，糊羹当早点' },
  { name: '百合麦冬茶', tags: ['healthy'], note: '百合麦冬泡水，传统搭配饮品' },
  { name: '玫瑰佛手茶', tags: ['healthy'], note: '玫瑰配佛手泡，花香一杯' },
  { name: '山楂陈皮茶', tags: ['healthy'], note: '山楂配陈皮煮水，饭后一杯' },
  { name: '姜枣陈皮饮', tags: ['healthy'], note: '姜枣配陈皮煮，热热喝一杯' },
  { name: '茯苓百合粥', tags: ['healthy', 'gout'], note: '茯苓配百合，煮碗清甜粥' },
  { name: '薏米扁豆糊', tags: ['healthy', 'diabetes'], note: '薏米扁豆磨糊，当早半碗' },
  { name: '玉竹山药汤', tags: ['healthy'], note: '玉竹配山药，煮碗汤当水饮' },
  { name: '沙参莲藕汤', tags: ['healthy'], note: '沙参煲莲藕，素汤润秋燥' },
  { name: '玉竹老鸭汤', tags: ['healthy'], note: '玉竹煲鸭汤，去皮撇净油' },
  { name: '银耳杏仁露', tags: ['healthy'], note: '银耳甜杏仁打浆，不加糖' },
  { name: '芡实南瓜粥', tags: ['healthy', 'gout'], note: '芡实配南瓜，熬得稠绵' },
  { name: '白扁豆薏米汤', tags: ['healthy', 'diabetes'], note: '扁豆配薏米，煮透当汤饮' },
  { name: '红枣当归蛋', tags: ['healthy'], note: '当归红枣煮蛋，经期一个孕期忌多' },
  { name: '香椿拌粉丝', tags: ['healthy', 'gout'], note: '香椿焯水拌粉丝，春天一盘青' },
  { name: '栗子蒸南瓜', tags: ['healthy', 'gout'], note: '南瓜垫底蒸栗子，秋天粉糯香' },
]
