// 「今天吃什么」分片：健康特殊人群与世界轻食（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const HEALTHY_SPECIAL_DISHES: FoodDish[] = [
  { name: '虾皮蒸蛋（儿童版）', tags: ['healthy', 'gout'], note: '蛋嫩咸香，虾皮只微量提味别食渣' },
  { name: '三鲜小馄饨', tags: ['healthy'], note: '薄皮小个头，一口一个不烫嘴' },
  { name: '紫菜小馄饨', tags: ['healthy', 'diabetes', 'gout'], note: '紫菜一克提鲜就够，汤少喝' },
  { name: '番茄鸡蛋小馄饨', tags: ['healthy'], note: '番茄汤底酸甜，小馄饨好消化' },
  { name: '鸡丝小馄饨', tags: ['healthy'], note: '鸡丝做馅清淡，孩子一碗见底' },
  { name: '鲜虾小馄饨', tags: ['healthy'], note: '虾仁剁馅鲜甜，个头小更好煮' },
  { name: '蔬菜浓汤意大利面', tags: ['healthy', 'gout'], note: '面煮软烂，浓汤裹着每一根' },
  { name: '西兰花鸡肉小丸子', tags: ['healthy'], note: '鸡肉拌西兰花，给娃压扁掰小块' },
  { name: '奶香鳕鱼小菠菜盏', tags: ['healthy'], note: '鳕鱼碾碎拌煮菠菜，奶香一小盏' },
  { name: '鳕鱼豆腐小蒸碗', tags: ['healthy'], note: '鳕鱼碎配豆腐同蒸，软嫩好嚼' },
  { name: '自制鳕鱼肠', tags: ['healthy'], note: '自己蒸的鱼肠，没有添加剂' },
  { name: '自制鸡胸肉肠', tags: ['healthy'], note: '鸡胸打浆灌模，咬得到肉纤维' },
  { name: '鳕鱼小饼', tags: ['healthy'], note: '鳕鱼泥少油煎小饼，给娃好抓' },
  { name: '虾泥小方', tags: ['healthy'], note: '虾仁蒸成小方，切块捏着吃' },
  { name: '土豆胡萝卜浓汤', tags: ['healthy', 'gout'], note: '土豆煮到绵，打成糊孩子爱喝' },
  { name: '奶香南瓜糊', tags: ['healthy', 'gout'], note: '南瓜自带甜，加奶打糊顺滑' },
  { name: '蛋黄米糊', tags: ['healthy', 'gout'], note: '蛋黄碾进米糊，香得很下饭' },
  { name: '奶香豌豆浓汤', tags: ['healthy', 'gout'], note: '豌豆适量奶香非奶油，素汤底' },
  { name: '蔬菜软蛋饼', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜切丝拌蛋液，烙得软嫩的' },
  { name: '胡萝卜西兰花鸡蛋饼', tags: ['healthy', 'diabetes', 'gout'], note: '颜色好看营养全，切小块上手' },
  { name: '玉米酪酪小烤碗', tags: ['healthy', 'gout'], note: '奶酪一片封顶，小碗也别贪香' },
  { name: '蛋黄碎土豆泥', tags: ['healthy'], note: '土豆泥撒蛋黄碎，绵沙又顶饱' },
  { name: '西蓝花奶酪土豆泥', tags: ['healthy'], note: '奶酪撒一点提香，钠脂别多' },
  { name: '蛋皮虾仁卷', tags: ['healthy', 'diabetes'], note: '蛋皮摊薄卷虾仁，切段好入口' },
  { name: '蛋皮蔬菜卷', tags: ['healthy', 'diabetes', 'gout'], note: '薄蛋皮卷菜泥，蒸一下更软' },
  { name: '蛋奶烤馒头丁', tags: ['healthy', 'gout'], note: '馒头丁泡蛋奶烤，外脆里嫩' },
  { name: '全麦小馒头', tags: ['healthy', 'diabetes', 'gout'], note: '全麦掺一半，小个馒头好拿捏' },
  { name: '鸡肉馄饨', tags: ['healthy'], note: '鸡肉馅不油腻，皮薄汤也清' },
  { name: '鲜虾滑燕麦粥', tags: ['healthy', 'diabetes'], note: '虾仁燕麦同煮，鲜香又软糯' },
  { name: '鳕鱼蔬菜粥', tags: ['healthy'], note: '鳕鱼拆碎拌进蔬菜粥，软糯鲜' },
  { name: '牛肉碎蔬菜粥', tags: ['healthy', 'diabetes'], note: '牛肉碎粥别当水喝，半碗算主食' },
  { name: '番茄鸡肉碎意面', tags: ['healthy'], note: '鸡肉碎炒番茄，拌意面酸甜' },
  { name: '鸡肉时蔬软饭', tags: ['healthy'], note: '米饭焖软配鸡丁，蔬菜切小丁' },
  { name: '三文鱼炒饭', tags: ['healthy'], note: '熟三文鱼碾碎，少油炒着吃' },
  { name: '蛋黄豆腐羹', tags: ['healthy', 'diabetes', 'gout'], note: '咸蛋黄起沙豆腐适量，给娃少放盐' },
  { name: '菌菇鸡茸粥', tags: ['healthy', 'gout'], note: '菌菇鸡茸都中嘌呤，缓解期少量' },
  { name: '蛋花蔬菜米汤', tags: ['healthy', 'gout'], note: '米汤煮软烂，蛋花蔬菜漂里头' },
  { name: '蔬菜鸡蛋小麦芬', tags: ['healthy', 'diabetes', 'gout'], note: '麦芬精制粉加油，算主食吃半个' },
  { name: '山药红枣泥', tags: ['healthy'], note: '山药蒸熟配枣泥，甜得很自然' },
  { name: '苹果蒸蛋泥', tags: ['healthy', 'gout'], note: '苹果蒸到软，打泥带着酸香' },
  { name: '玉米蛋花小圆子', tags: ['healthy'], note: '糯米小圆子少给，压碎了再喂' },
  { name: '番茄豆腐蛋花小馄饨', tags: ['healthy'], note: '小馄饨浮在番茄汤，蛋花坠底' },
  { name: '鸡丝蛋花汤', tags: ['healthy', 'gout'], note: '蛋花为主鸡丝少，痛风少饮汤' },
  { name: '牛奶蛋花粥', tags: ['healthy', 'gout'], note: '牛奶煮粥蛋花飘，奶香扑鼻' },
  { name: '蛋黄泥（辅食）', tags: ['healthy', 'diabetes', 'gout'], note: '熟蛋黄碾细，小勺喂着加餐' },
  { name: '鸡茸蛋羹', tags: ['healthy', 'gout'], note: '鸡茸缓解期少量，蛋羹照样嫩' },
  { name: '鲜虾豆腐羹', tags: ['healthy', 'diabetes'], note: '虾仁豆腐同羹，鲜得眉毛掉' },
  { name: '番茄鸡丝面', tags: ['healthy'], note: '番茄熬汤鸡丝面，酸香开胃' },
  { name: '玉米鸡肉小丸子', tags: ['healthy'], note: '鸡肉拌玉米粒，小丸子一口俩' },
  { name: '时蔬虾滑汤', tags: ['healthy', 'diabetes'], note: '虾滑挤小团，蔬菜汤里煮着鲜' },
  { name: '奶香玉米糊', tags: ['healthy', 'gout'], note: '玉米打浆加奶煮，甜甜黄黄的' },
  { name: '鳕鱼泥', tags: ['healthy'], note: '鳕鱼蒸透压泥，一点刺都不留' },
  { name: '蛋奶小方', tags: ['healthy', 'gout', 'diabetes'], note: '鸡蛋牛奶蒸糕，切小方捏着吃' },
  { name: '胡萝卜奶香浓汤', tags: ['healthy', 'gout'], note: '胡萝卜煮软打泥，加奶更顺口' },
  { name: '菠菜猪肝汤（少量）', tags: ['healthy'], note: '猪肝补铁少放，每周一次就好' },
  { name: '南瓜杂粮软饭', tags: ['healthy', 'diabetes'], note: '南瓜掺进杂粮饭，焖得软甜' },
  { name: '小米燕麦糊', tags: ['healthy', 'diabetes', 'gout'], note: '小米燕麦熬到绵，控半碗算主食' },
  { name: '山药芙蓉粥', tags: ['healthy', 'gout'], note: '山药打茸入粥，滑得像芙蓉' },
  { name: '胡萝卜小米粥', tags: ['healthy', 'diabetes', 'gout'], note: '胡萝卜小米粥，稀的控半碗' },
  { name: '燕麦大米粥', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦掺大米煮，稠滑好消化' },
  { name: '鸡蛋软饼', tags: ['healthy', 'diabetes', 'gout'], note: '蛋饼摊得薄软，卷成小卷好入口' },
  { name: '烂糊面', tags: ['healthy'], note: '面条煮到烂糊，冬天吃顶饿' },
  { name: '烂糊白菜', tags: ['healthy', 'diabetes', 'gout'], note: '白菜炖到软烂，汤都能拌饭' },
  { name: '豆腐汤面', tags: ['healthy', 'diabetes', 'gout'], note: '嫩豆腐入汤面顺滑，豆腐适量' },
  { name: '肉末嫩豆腐', tags: ['healthy'], note: '豆腐嫩肉末香，不用嚼就滑下去' },
  { name: '虾仁蛋羹蒸小玉米', tags: ['healthy', 'diabetes'], note: '蛋羹卧虾仁，玉米提甜亮闪闪' },
  { name: '清炖萝卜丝粉丝', tags: ['healthy', 'gout'], note: '萝卜炖到透明，粉丝吸饱汤汁' },
  { name: '冬瓜烂饭', tags: ['healthy', 'diabetes'], note: '冬瓜切小丁，焖一碗软饭' },
  { name: '南瓜鸡丝粥', tags: ['healthy'], note: '鸡丝撕细入粥，南瓜自带甜' },
  { name: '冬瓜鸡肉粥', tags: ['healthy', 'diabetes', 'gout'], note: '缓解期喝一小碗，鸡丁少放' },
  { name: '萝卜丝咸蛋粥', tags: ['healthy'], note: '咸蛋只放半个，提味刚好' },
  { name: '鳕鱼软饭', tags: ['healthy'], note: '鳕鱼蒸碎拌饭，软香还没刺' },
  { name: '鸡丝荞麦烂饭', tags: ['healthy', 'diabetes', 'gout'], note: '荞麦米掺大米，鸡丝缓解期适量' },
  { name: '鸡茸蛋花粥', tags: ['healthy', 'gout'], note: '鸡茸一汤匙就好，缓解期喝' },
  { name: '鲈鱼软饭', tags: ['healthy'], note: '鲈鱼剔净刺，捣碎拌进软饭' },
  { name: '牛肉碎烂饭', tags: ['healthy', 'diabetes'], note: '牛肉剁得碎碎的，炖烂好嚼' },
  { name: '番茄鸡蛋软饭', tags: ['healthy', 'diabetes', 'gout'], note: '番茄炒蛋浇软饭，酸甜开胃' },
  { name: '豆腐蔬菜蛋煲', tags: ['healthy', 'diabetes', 'gout'], note: '豆腐蔬菜卧蛋煲，豆腐适量' },
  { name: '鸡蛋菜花炒饭', tags: ['healthy', 'diabetes', 'gout'], note: '菜花切碎炒饭，蛋香裹着粒' },
  { name: '山药蛋花羹', tags: ['healthy', 'diabetes', 'gout'], note: '山药打泥勾羹，算主食控半碗' },
  { name: '秋葵蛋花羹', tags: ['healthy', 'diabetes', 'gout'], note: '秋葵切小圈，蛋花羹里发亮' },
  { name: '番茄土豆软汤', tags: ['healthy', 'gout'], note: '土豆煮到沙，番茄酸甜汤软' },
  { name: '蒸南瓜燕麦泥', tags: ['healthy', 'diabetes', 'gout'], note: '南瓜蒸泥算主食，半碗刚好' },
  { name: '燕麦鸡蛋粥', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦煮开淋蛋花，稠而不噎' },
  { name: '燕麦软饭', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦米焖软，比白饭香得多' },
  { name: '咸香炒燕麦粥', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦先炒香再熬粥，稠滑' },
  { name: '黑米豌豆粥', tags: ['healthy', 'diabetes', 'gout'], note: '豌豆适量别多，黑米算主食' },
  { name: '百合小米粥', tags: ['healthy', 'diabetes', 'gout'], note: '百合熬小米粥，控半碗算主食' },
  { name: '豌豆糯米饭（软版）', tags: ['healthy'], note: '豌豆焖进糯米，软香一小碗' },
  { name: '绿豆百合粥', tags: ['healthy', 'diabetes'], note: '绿豆煮开花解暑，少米或不加米' },
  { name: '桂花粥', tags: ['healthy', 'gout'], note: '白粥起锅撒桂花，满屋香' },
  { name: '莲子芡实粥', tags: ['healthy', 'gout'], note: '莲子芡实熬到面，温和养人' },
  { name: '苹果小米粥', tags: ['healthy', 'diabetes', 'gout'], note: '苹果丁入小米粥，粥底控半碗' },
  { name: '香蕉米粥', tags: ['healthy', 'gout'], note: '香蕉一小根封顶，拌进粥里' },
  { name: '紫薯豆浆糊', tags: ['healthy', 'diabetes'], note: '紫薯打糊兑豆浆，淀粉算主食' },
  { name: '南瓜羹（少糖）', tags: ['healthy', 'diabetes', 'gout'], note: '南瓜羹靠代糖，照样只喝半碗' },
  { name: '清炖双茄', tags: ['healthy', 'gout'], note: '番茄炖茄子，软烂酸甜下饭' },
  { name: '清炖西葫芦', tags: ['healthy', 'diabetes', 'gout'], note: '西葫芦炖到软，清清淡淡鲜' },
  { name: '清炖莴笋白菜', tags: ['healthy', 'diabetes', 'gout'], note: '两样炖一锅，软烂清淡刚好' },
  { name: '清炖冬瓜土豆', tags: ['healthy', 'gout'], note: '冬瓜土豆同炖，汤稠食材软' },
  { name: '白菜炖土豆', tags: ['healthy', 'gout'], note: '土豆炖到面，白菜吸满汤汁' },
  { name: '奶香豌豆泥', tags: ['healthy', 'gout'], note: '豌豆泥小半碗，也得当主食' },
  { name: '胡萝卜冬瓜汤（老人软烂）', tags: ['healthy', 'diabetes', 'gout'], note: '炖到透，汤色清甜食材软' },
  { name: '山药胡萝卜炒泥', tags: ['healthy', 'diabetes', 'gout'], note: '两样都压成泥，当主食不算菜' },
  { name: '番茄豆腐三鲜小蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '嫩豆腐裹蛋液蒸，豆腐适量吃' },
  { name: '鲈鱼汤（撇油）', tags: ['healthy', 'diabetes'], note: '痛风吃鱼少饮汤，缓解期浅尝' },
  { name: '红枣核桃粥', tags: ['healthy', 'diabetes'], note: '红枣核桃熬粥，底用杂粮控小碗' },
  { name: '猪肝粥（每周一次）', tags: ['healthy'], note: '猪肝补铁适量，一周一次就好' },
  { name: '番茄虾仁盖饭（孕妇常餐）', tags: ['healthy'], note: '虾仁配番茄汁，盖在软饭上吃' },
  { name: '清炖草鱼萝卜汤', tags: ['healthy'], note: '草鱼炖萝卜，痛风喝汤适量' },
  { name: '鲈鱼蔬菜粥', tags: ['healthy'], note: '鲈鱼拆肉入粥，蔬菜切细末' },
  { name: '清炖鲢鱼豆腐汤', tags: ['healthy'], note: '鲢鱼豆腐同炖，汤鲜要撇油' },
  { name: '鲫鱼蛋花汤', tags: ['healthy', 'gout'], note: '鲫鱼少量缓解期，素清汤少喝' },
  { name: '三文鱼蒸蛋', tags: ['healthy'], note: '三文鱼碎铺蛋羹，蒸出来嫩' },
  { name: '黄鱼萝卜汤', tags: ['healthy'], note: '小黄鱼炖萝卜，痛风少饮汤' },
  { name: '番茄炖鲈鱼', tags: ['healthy', 'gout'], note: '番茄酸渗进鱼，鲈鱼缓解期适量' },
  { name: '南瓜山药糊', tags: ['healthy', 'diabetes', 'gout'], note: '南瓜山药同熬糊，算主食吃半碗' },
  { name: '山药蒸糕（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '山药浆上锅蒸，蓬松微甜' },
  { name: '亚麻籽酸奶', tags: ['healthy', 'diabetes', 'gout'], note: '亚麻籽粉拌酸奶，纤维丰富' },
  { name: '奇亚籽酸奶（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '奇亚籽泡酸奶，胀开像西米' },
  { name: '燕麦香蕉糊', tags: ['healthy', 'diabetes', 'gout'], note: '香蕉半根封顶，燕麦算主食' },
  { name: '鲜奶燕麦糊', tags: ['healthy', 'diabetes', 'gout'], note: '牛奶泡燕麦煮，一小杯刚好' },
  { name: '无糖酸奶配樱桃', tags: ['healthy', 'diabetes', 'gout'], note: '樱桃去核切小，拌无糖酸奶' },
  { name: '全麦贝果（低糖）', tags: ['healthy', 'gout'], note: '贝果嚼着韧，抹薄薄一层酱' },
  { name: '奶酪鸡蛋吐司', tags: ['healthy', 'gout'], note: '奶酪一片封顶，高脂高钠别贪' },
  { name: '鸡蛋牛油果三明治', tags: ['healthy', 'diabetes', 'gout'], note: '牛油果碾泥夹蛋，好脂肪顶饱' },
  { name: '牛油果鸡蛋吐司', tags: ['healthy', 'gout'], note: '吐司摊蛋铺牛油果，颜值高' },
  { name: '鸡胸藜麦沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '藜麦拌鸡胸，鸡胸适量、缓解期吃' },
  { name: '全麦鸡蛋三明治', tags: ['healthy', 'diabetes', 'gout'], note: '全麦夹水煮蛋，通勤路上吃' },
  { name: '蔬菜蛋饼', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜拌蛋摊饼，早餐五分钟' },
  { name: '玉米蛋饼', tags: ['healthy', 'gout'], note: '玉米粒粘进蛋饼，咬到爆甜' },
  { name: '虾皮蛋饼', tags: ['healthy'], note: '虾皮一小撮提味，钠高别多放' },
  { name: '鳕鱼吐司', tags: ['healthy'], note: '鳕鱼碎夹吐司，烤一下更香' },
  { name: '豆腐包子（适量）', tags: ['healthy', 'diabetes'], note: '豆腐馅暄软，一次一个皮算主食' },
  { name: '芝士鸡蛋饼', tags: ['healthy', 'gout'], note: '芝士一小片，裹蛋液煎着香' },
  { name: '鲜奶燕麦布丁', tags: ['healthy', 'diabetes', 'gout'], note: '牛奶燕麦蒸布丁，当早饭吃' },
  { name: '南瓜发糕（少糖）', tags: ['healthy', 'diabetes'], note: '南瓜和面蒸发糕，算主食限一块' },
  { name: '红豆包（低糖）', tags: ['healthy', 'diabetes'], note: '豆沙少糖自己炒，一个为限' },
  { name: '全麦鸡肉小卷', tags: ['healthy', 'diabetes'], note: '全麦饼卷鸡条，蔬菜随手加' },
  { name: '鸡丝荞麦温捞面', tags: ['healthy', 'diabetes'], note: '荞麦面温水过，鸡丝拌着吃' },
  { name: '虾仁炒蛋', tags: ['healthy', 'diabetes'], note: '虾仁裹蛋液同炒，入口滑嫩' },
  { name: '火腿蛋羹（低盐）', tags: ['healthy', 'gout'], note: '蛋羹铺火腿丁，加工肉痛风少食' },
  { name: '蒜蓉烤生蚝', tags: ['healthy'], note: '生蚝务必烤透，蒜香盖腥气' },
  { name: '清炖银鱼萝卜汤', tags: ['healthy', 'gout'], note: '鲜银鱼一小份缓解期，汤少喝' },
  { name: '银鱼粥', tags: ['healthy', 'gout'], note: '鲜银鱼一小撮调味，粥喝半碗' },
  { name: '鳕鱼蒸蛋', tags: ['healthy'], note: '鳕鱼一小块蒸蛋，嫩滑又补脑' },
  { name: '玉米鸡茸羹', tags: ['healthy', 'gout'], note: '玉米羹稠鲜，鸡茸点缀少饮浅尝' },
  { name: '南瓜鸡茸汤', tags: ['healthy', 'gout'], note: '南瓜打底鸡茸少，汤浅尝即可' },
  { name: '蔬菜鸡茸汤', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜为主鸡茸点缀，汤少喝' },
  { name: '虾滑冬瓜汤', tags: ['healthy', 'diabetes'], note: '虾滑挤冬瓜片，汤清鲜不腻' },
  { name: '丝瓜虾滑', tags: ['healthy', 'diabetes'], note: '丝瓜煮到软，虾滑嵌在缝里' },
  { name: '西兰花虾滑汤', tags: ['healthy', 'diabetes'], note: '虾滑配西兰花，绿白一碗鲜' },
  { name: '番茄虾滑汤', tags: ['healthy', 'diabetes'], note: '番茄煮汤挤虾滑，红白相间' },
  { name: '三鲜蛋卷', tags: ['healthy'], note: '蛋皮卷虾仁菜末，切段摆盘' },
  { name: '蓝莓奶昔（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '蓝莓冻牛奶打，浓稠一小杯' },
  { name: '覆盆子', tags: ['healthy', 'diabetes', 'gout'], note: '酸酸红红一小把，低糖果子' },
  { name: '小番茄（控量一小把）', tags: ['healthy', 'diabetes', 'gout'], note: '一小把解馋，给娃务必切半' },
  { name: '清炖鸽子汤（去皮撇油）', tags: ['healthy'], note: '鸽子炖汤去皮，撇油小碗喝' },
  { name: '乳鸽蒸米饭', tags: ['healthy'], note: '乳鸽撕碎蒸饭，肉香渗米粒' },
  { name: '鸡肝瘦肉粥（小份偶尔）', tags: ['healthy'], note: '一小碗、每月一两次，孕产妇别吃' },
  { name: '地中海烤蔬菜拼盘', tags: ['healthy', 'diabetes', 'gout'], note: '彩椒西葫芦淋油烤，蔬香浓' },
  { name: '西班牙冷蔬菜汤', tags: ['healthy', 'diabetes', 'gout'], note: '番茄黄瓜泡冰水，夏天一碗凉' },
  { name: '西西里番茄面包沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '旧面包拌新番茄，面包算主食' },
  { name: '希腊豆汤', tags: ['healthy'], note: '大白豆慢炖到面，挤柠檬吃' },
  { name: '突尼斯金枪鱼豆沙拉', tags: ['healthy', 'diabetes'], note: '金枪鱼一周一罐，孕幼别超' },
  { name: '西班牙蒜香虾', tags: ['healthy', 'takeout'], note: '橄榄油焖大虾，蒜香钻鼻子' },
  { name: '土耳其扁豆汤', tags: ['healthy', 'gout', 'takeout', 'diabetes'], note: '红扁豆为主料，中嘌呤适量吃' },
  { name: '土耳其烤蔬菜块', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜切大块串烤，撒孜然香' },
  { name: '以色列黄瓜番茄沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '黄瓜番茄切丁，薄荷柠檬汁' },
  { name: '黎巴嫩芝麻酱拌蔬菜', tags: ['healthy', 'gout'], note: '芝麻酱泄开淋烤蔬，香得很' },
  { name: '黎巴嫩扁豆糙米饭', tags: ['healthy'], note: '糙米配小扁豆，香糯软烂' },
  { name: '俄式荞麦粥', tags: ['healthy', 'diabetes', 'gout'], note: '荞麦粥滴几滴植物油，不放黄油' },
  { name: '乌克兰红菜蛋花汤', tags: ['healthy', 'gout'], note: '红菜汤配酸奶一匙，起锅再放' },
  { name: '波兰蔬菜汤', tags: ['healthy', 'gout'], note: '根茎蔬菜一锅炖，莳萝提香' },
  { name: '立陶宛冷甜菜汤', tags: ['healthy', 'gout'], note: '甜菜酸奶冷汤，粉色一碗凉' },
  { name: '高加索燕麦牛奶粥', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦牛奶慢熬，稠滑软糯' },
  { name: '高加索香草酸奶汤', tags: ['healthy', 'diabetes', 'gout'], note: '酸奶兑水撒莳萝，凉夏救星' },
  { name: '亚美尼亚小麦粥', tags: ['healthy', 'diabetes', 'gout'], note: '小麦仁泡一夜，熬到开花' },
  { name: '阿布哈兹玉米糊', tags: ['healthy', 'diabetes', 'gout'], note: '玉米面糊也升糖，半碗算主食' },
  { name: '黑海烤鳟鱼', tags: ['healthy'], note: '鳟鱼对半开烤，柠檬挤上面' },
  { name: '哈萨克酸奶疙瘩', tags: ['healthy', 'diabetes'], note: '酸奶晾干成小疙瘩，酸香' },
  { name: '乌孜别克蔬菜薄饼', tags: ['healthy', 'diabetes', 'gout'], note: '薄饼铺菜烤，饼算主食吃半张' },
  { name: '吉尔吉斯蔬菜拌面', tags: ['healthy', 'diabetes', 'gout'], note: '宽面过凉水浇番茄，面吃半份' },
  { name: '高加索野莓酸奶杯', tags: ['healthy', 'diabetes', 'gout'], note: '野莓撒在酸奶上，酸酸甜甜' },
  { name: '亚美尼亚杏干煮水', tags: ['healthy', 'diabetes'], note: '杏干含糖五成，一小杯或换鲜果' },
  { name: '日式鲑鱼茶泡饭', tags: ['healthy'], note: '烤鱼撒饭上，热茶一冲就吃' },
  { name: '日式时蔬汤', tags: ['healthy', 'diabetes', 'gout'], note: '泡发海带一小片吊鲜，蔬软' },
  { name: '日式烤豆腐', tags: ['healthy'], note: '豆腐烤出焦壳，淋酱汁适量' },
  { name: '日式山药纳豆饭', tags: ['healthy', 'diabetes'], note: '纳豆拉丝香，服抗凝药者慎吃' },
  { name: '日式海藻豆腐沙拉', tags: ['healthy'], note: '海藻配嫩豆腐，芝麻酱点半' },
  { name: '日式杂炊', tags: ['healthy'], note: '泡饭加高汤煮，煮到软烂' },
  { name: '挪威面包汤', tags: ['healthy', 'diabetes', 'gout'], note: '黑麦面包切块，泡进蔬菜汤' },
  { name: '瑞典根茎蔬菜汤', tags: ['healthy', 'diabetes', 'gout'], note: '汤白是土豆打泥，不是肉汤' },
  { name: '芬兰水果冻（少糖）', tags: ['healthy', 'diabetes'], note: '云莓做冻少糖，浆果季限定' },
  { name: '丹麦黑麦面包配鸡蛋', tags: ['healthy', 'diabetes'], note: '黑麦面包酸香，卧个水煮蛋' },
  { name: '北欧三文鱼冷盘', tags: ['healthy'], note: '熟三文鱼晾凉，莳萝芥末酱' },
  { name: '北欧黑麦脆片配烟熏三文鱼', tags: ['healthy', 'diabetes'], note: '烟熏三文鱼，孕期加热后再吃' },
  { name: '越式鸡丝清汤河粉', tags: ['healthy'], note: '河粉烫透，鸡丝沉在清汤底' },
  { name: '越式蔬菜米线', tags: ['healthy', 'gout'], note: '米线清汤烫，蔬菜铺一碗' },
  { name: '越式虾米纸卷', tags: ['healthy'], note: '米纸裹生菜，孕幼烫熟更稳妥' },
  { name: '泰式清汤粿条', tags: ['healthy'], note: '粿条清汤烫，配豆芽空心菜' },
  { name: '泰式鸡丝汤', tags: ['healthy', 'gout'], note: '鸡丝吃别多喝汤，缓解期适量' },
  { name: '新加坡鸡丝河粉汤', tags: ['healthy'], note: '河粉盛鸡丝，清汤不加椰浆' },
  { name: '菲式柠檬鸡粥', tags: ['healthy'], note: '鸡粥挤酸橙，酸得醒胃' },
  { name: '菲式芒果虾沙拉', tags: ['healthy'], note: '熟青虾配芒果，酸汁拌着吃' },
  { name: '缅式茶叶拌菜', tags: ['healthy'], note: '茶叶含咖啡因，孕幼小碟尝鲜' },
  { name: '柬式柠檬蒸鱼', tags: ['healthy'], note: '芭蕉叶包鱼蒸，柠檬香入肉' },
  { name: '印尼菜果清汤', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜清汤一碗，南瓜豆角同煮' },
  { name: '印尼蒸米糕（少糖）', tags: ['healthy'], note: '米浆蒸小糕，甜得很淡' },
  { name: '印度扁豆米糕', tags: ['healthy'], note: '米浆豆浆发酵蒸，配酸辣酱' },
  { name: '印度烤豆饼', tags: ['healthy'], note: '混合豆粉烙薄饼，嚼着豆香' },
  { name: '伊朗藏红花柠檬鸡汤', tags: ['healthy'], note: '鸡块柠檬慢炖，藏红花染黄' },
  { name: '摩洛哥烤蔬菜', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜烤到收边，孜然芫荽香' },
  { name: '埃塞俄比亚扁豆糊', tags: ['healthy', 'diabetes'], note: '黄扁豆熬成糊，抹薄饼吃' },
  { name: '埃及慢炖蚕豆', tags: ['healthy'], note: '蚕豆慢炖到裂口，淋橄榄油吃' },
  { name: '约旦烤花菜橄榄油', tags: ['healthy', 'diabetes', 'gout'], note: '花菜烤焦一点，橄榄油柠檬' },
  { name: '巴西黑豆炖锅（适量）', tags: ['healthy'], note: '黑豆炖到面，适量吃别贪' },
  { name: '秘鲁紫玉米饮（无糖）', tags: ['healthy', 'diabetes'], note: '紫玉米煮水，肉桂香微酸' },
  { name: '墨西哥烤玉米碗', tags: ['healthy'], note: '玉米粒烤焦香，青柠辣酱拌' },
  { name: '阿根廷蔬菜煎饺', tags: ['healthy', 'gout'], note: '薄皮包菜馅，少油煎或直接蒸' },
  { name: '智利玉米蛋羹', tags: ['healthy', 'gout'], note: '玉米蛋羹烤面，小碗趁热吃' },
  { name: '微波炉蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '蛋液加水叮两分钟，嫩得住' },
  { name: '隔夜燕麦杯', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦牛奶泡一夜，早上拿走' },
  { name: '罐罐沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '酱汁垫底菜封顶，摇一摇吃' },
  { name: '鸡胸蔬菜全麦卷', tags: ['healthy', 'diabetes'], note: '全麦皮卷鸡胸蔬菜，快手轻食' },
  { name: '全麦金枪鱼蔬菜卷', tags: ['healthy', 'diabetes', 'gout'], note: '金枪鱼一周一罐，缓解期适量' },
  { name: '鸡胸饭便当盒', tags: ['healthy', 'diabetes'], note: '杂粮饭配鸡胸，格子分装清楚' },
  { name: '鸡胸沙拉罐', tags: ['healthy', 'diabetes', 'gout'], note: '生菜鸡胸码进罐，缓解期适量' },
  { name: '蔬菜豆腐汤杯', tags: ['healthy', 'diabetes', 'gout'], note: '豆腐蔬菜装杯叮热，豆腐适量' },
  { name: '荞麦鸡丝面便当', tags: ['healthy', 'diabetes'], note: '荞麦面拌鸡丝，凉吃也不坨' },
  { name: '杂粮捏捏饭团', tags: ['healthy', 'diabetes', 'gout'], note: '整粒杂粮煮软再捏团，防噎' },
  { name: '杂粮蔬菜饭杯', tags: ['healthy', 'diabetes'], note: '一杯定量杂粮饭，下午不饿' },
  { name: '微波时蔬', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜装盒叮一下，比外卖清爽' },
  { name: '微波鸡蛋羹', tags: ['healthy', 'diabetes', 'gout'], note: '蛋液碗里叮，办公室现蒸' },
  { name: '即食鸡胸肉（低盐）', tags: ['healthy', 'diabetes', 'gout'], note: '开袋选低盐那款，痛风缓解期适量' },
  { name: '水煮蛋便当盒', tags: ['healthy', 'diabetes', 'gout'], note: '早上煮两颗，中午剥着吃' },
  { name: '魔芋饭碗', tags: ['healthy', 'diabetes', 'gout'], note: '魔芋掺米一碗，下午不犯困' },
  { name: '金枪鱼全麦饭团', tags: ['healthy', 'diabetes'], note: '金枪鱼一周一罐，掌心一个' },
  { name: '鸡胸杂粮饭卷', tags: ['healthy', 'diabetes', 'gout'], note: '鸡胸缓解期少量，饭算主食' },
  { name: '鸡胸蔬菜能量卷', tags: ['healthy', 'diabetes'], note: '全麦皮卷鸡胸，能量刚刚好' },
  { name: '即食燕麦麸杯', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦麸冲热水，三分钟早饭' },
  { name: '三文鱼便当', tags: ['healthy'], note: '煎三文鱼配饭，冷了也好吃' },
  { name: '三文鱼饭团', tags: ['healthy'], note: '便利店就有，鱼松裹米饭' },
  { name: '鸡胸饭团', tags: ['healthy', 'diabetes'], note: '鸡胸馅饭团，不超一个、算主食' },
  { name: '微波鸡丝盖被', tags: ['healthy', 'gout'], note: '鸡丝盖饭微波，缓解期适量' },
  { name: '冲泡燕麦粥（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '热水一冲就稠，抽屉常备' },
  { name: '无糖豆奶（盒装）', tags: ['healthy', 'diabetes'], note: '抽屉常备豆奶，加餐一盒' },
  { name: '坚果小袋（原味）', tags: ['healthy', 'diabetes', 'gout'], note: '整颗坚果别给幼娃，碾碎吃' },
  { name: '坚果脆片杯', tags: ['healthy', 'diabetes'], note: '挑无糖那款，给娃碾碎再吃' },
  { name: '香蕉奇亚燕麦杯', tags: ['healthy', 'diabetes'], note: '香蕉切片泡燕麦杯，十点加餐' },
  { name: '苹果片蘸花生酱', tags: ['healthy', 'diabetes', 'gout'], note: '苹果切薄条，酱抹薄薄一层' },
  { name: '鸡胸蔬菜微波杯', tags: ['healthy', 'diabetes'], note: '鸡胸蔬菜装杯，微波炉叮热' },
  { name: '鸡胸藜麦杯', tags: ['healthy', 'diabetes', 'gout'], note: '藜麦垫底拌鸡胸，缓解期适量' },
  { name: '吐司窝蛋', tags: ['healthy', 'gout'], note: '窝蛋烤到全熟，孕幼别吃嫩' },
  { name: '奇亚籽豆浆（无糖）', tags: ['healthy', 'diabetes'], note: '无糖豆浆泡奇亚，稠稠一杯' },
  { name: '苹果醋气泡饮（无糖）', tags: ['healthy', 'diabetes'], note: '气泡水兑苹果醋，饭前来一口' },
  { name: '即食玉米段', tags: ['healthy', 'diabetes'], note: '微波两分钟啃，甜玉米算半段主食' },
  { name: '老式凝固型酸奶', tags: ['healthy', 'diabetes', 'gout'], note: '选杀菌工艺那款，别吃自制' },
  { name: '鸡胸蔬菜豆皮卷', tags: ['healthy', 'diabetes'], note: '豆皮卷鸡胸蔬菜，蒸叮皆可' },
  { name: '鸡丝荞麦凉面罐', tags: ['healthy', 'diabetes'], note: '荞麦面装罐，鸡丝沉底' },
  { name: '鸡胸便当（食堂）', tags: ['healthy', 'diabetes'], note: '食堂打包鸡胸，米饭只打半份' },
  { name: '金枪鱼鸡蛋沙拉罐', tags: ['healthy', 'diabetes'], note: '金枪鱼一周一罐，午餐拌饭' },
  { name: '烟熏三文鱼全麦卷', tags: ['healthy', 'diabetes'], note: '烟熏三文鱼卷，孕幼加热后吃' },
  { name: '鸡蛋蔬菜杯（微波）', tags: ['healthy', 'diabetes', 'gout'], note: '鸡蛋蔬菜装杯叮熟，边走边吃' },
  { name: '鸡胸能量饭盒', tags: ['healthy', 'diabetes'], note: '鸡胸杂粮一锅装，明天午餐' },
]
