// 「今天吃什么」分片：糖尿病控糖甜品饮品零食（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const DIABETES_SWEET_DISHES: FoodDish[] = [
  { name: '赤藓糖醇蛋奶布丁', tags: ['diabetes'], note: '代糖布丁，无糖也别多吃' },
  { name: '无糖烤布蕾', tags: ['diabetes'], note: '焦面靠喷枪，无糖仍限量' },
  { name: '木糖醇蓝莓慕斯', tags: ['diabetes'], note: '代糖打奶油，半杯就够' },
  { name: '赤藓糖醇抹茶慕斯', tags: ['diabetes'], note: '抹茶代糖，无糖不随便吃' },
  { name: '无糖酸奶慕斯', tags: ['diabetes'], note: '酸奶打底少油，浅尝即止' },
  { name: '代糖黑巧慕斯（小份）', tags: ['diabetes'], note: '高可可代糖，一小杯封顶' },
  { name: '无糖草莓慕斯', tags: ['diabetes'], note: '草莓配代糖，控量解馋' },
  { name: '无糖西柚慕斯', tags: ['diabetes'], note: '西柚微苦代糖，半份刚好' },
  { name: '赤藓糖醇蒟蒻果冻', tags: ['diabetes'], note: '蒟蒻低热代糖，别当水喝' },
  { name: '无糖寒天冻', tags: ['diabetes'], note: '寒天凝块无糖，配餐少量' },
  { name: '木糖醇洋菜冻', tags: ['diabetes'], note: '洋菜代糖冻，无糖≠随便吃' },
  { name: '无糖莓果雪芭（小份）', tags: ['diabetes'], note: '莓果打雪芭，仍算总热量' },
  { name: '赤藓糖醇柠檬雪芭', tags: ['diabetes'], note: '柠檬代糖冰，少甜也少食' },
  { name: '木糖醇舒芙蕾（小份）', tags: ['diabetes'], note: '现烤舒芙蕾，代糖不等于零' },
  { name: '无糖柚子蛋奶盅', tags: ['diabetes'], note: '柚子蛋奶盅，半碗解个馋' },
  { name: '代糖五仁月饼（小份）', tags: ['diabetes'], note: '无糖月饼仍高油，吃四分之一' },
  { name: '无糖沙琪玛（一小块）', tags: ['diabetes'], note: '代糖沙琪玛，油糖热量都在' },
  { name: '木糖醇牛轧糖（少量）', tags: ['diabetes'], note: '无糖牛轧糖，两颗就该止住' },
  { name: '无糖雪花酥（少量）', tags: ['diabetes'], note: '代糖雪花酥，黄油热量别忽略' },
  { name: '赤藓糖醇生巧（一小块）', tags: ['diabetes'], note: '高可可代糖，一块封顶' },
  { name: '无糖太妃糖（少量）', tags: ['diabetes'], note: '代糖太妃，黏牙也黏热量' },
  { name: '木糖醇奶枣（少量）', tags: ['diabetes'], note: '无糖奶枣，枣本身含糖别贪' },
  { name: '无糖椰蓉球（小份）', tags: ['diabetes'], note: '椰蓉代糖球，两颗意思下' },
  { name: '赤藓糖醇椰丝糕', tags: ['diabetes'], note: '椰丝代糖糕，无糖也限一块' },
  { name: '无糖南瓜慕斯（小份）', tags: ['diabetes'], note: '南瓜泥少量，这杯算半份主食' },
  { name: '无糖紫薯布丁', tags: ['diabetes'], note: '紫薯代糖布丁，淀粉仍升糖' },
  { name: '赤藓糖醇芝麻糊', tags: ['diabetes'], note: '黑芝麻代糖糊，稠且热量高' },
  { name: '无糖花生酪（小碗）', tags: ['diabetes'], note: '花生酪香浓，代糖也半碗' },
  { name: '木糖醇红枣糕（小块）', tags: ['diabetes'], note: '红枣自带糖，代糖糕浅尝' },
  { name: '无糖蛋白椰蓉饼', tags: ['diabetes'], note: '蛋白椰蓉烤，代糖也少食' },
  { name: '赤藓糖醇奶酥球', tags: ['diabetes'], note: '代糖奶酥黄油打底别多吃' },
  { name: '无糖香草卡仕达', tags: ['diabetes'], note: '代糖卡仕达，蛋黄奶油量高' },
  { name: '无糖酸奶冰淇淋（小杯）', tags: ['diabetes'], note: '酸奶打冰淇淋，无糖≠随便' },
  { name: '无糖草莓酸奶冰', tags: ['diabetes'], note: '草莓酸奶冻，控量当甜点' },
  { name: '木糖醇桂花奶酪冻', tags: ['diabetes'], note: '桂花奶酪代糖，一小盏' },
  { name: '无糖豆乳布丁', tags: ['diabetes'], note: '豆乳代糖冻，豆制品适量' },
  { name: '无糖杏仁蛋白饼', tags: ['diabetes'], note: '杏仁粉蛋白饼，坚果热量高' },
  { name: '赤藓糖醇栗子蛋糕（小份）', tags: ['diabetes'], note: '栗子泥中GI，代糖也限量' },
  { name: '无糖可可燕麦杯', tags: ['diabetes'], note: '可可燕麦代糖，算进主食量' },
  { name: '代糖酸奶冻糕', tags: ['diabetes'], note: '酸奶代糖冻，切一小块' },
  { name: '无糖核桃酪（小碗）', tags: ['diabetes'], note: '核桃酪浓香，油脂热量别忽略' },
  { name: '赤藓糖醇黑巧燕麦脆', tags: ['diabetes'], note: '黑巧代糖脆，一小把解馋' },
  { name: '无糖烤苹果盏', tags: ['diabetes'], note: '苹果烤软代糖，中GI控半份' },
  { name: '木糖醇南瓜蛋奶盅', tags: ['diabetes'], note: '南瓜蛋奶，代糖仍算碳水' },
  { name: '无糖柚子奶冻', tags: ['diabetes'], note: '柚子奶冻，代糖不等于零负担' },
  { name: '无糖巧克力熔岩（小份）', tags: ['diabetes'], note: '高可可熔岩，代糖热量别忽略' },
  { name: '赤藓糖醇榛子黑巧', tags: ['diabetes'], note: '榛子黑巧代糖，一两块封顶' },
  { name: '无糖香草布丁', tags: ['diabetes'], note: '香草代糖布丁，无糖≠随便吃' },
  { name: '木糖醇酸奶雪酪', tags: ['diabetes'], note: '酸奶打雪酪，半杯刚好' },
  { name: '无糖柠檬塔（小件）', tags: ['diabetes'], note: '柠檬凝乳代糖，酥皮油脂别忽略' },
  { name: '无糖抹茶白巧慕斯', tags: ['diabetes'], note: '抹茶白巧代糖，一小杯解馋' },
  { name: '赤藓糖醇无花果冻', tags: ['diabetes'], note: '无花果代糖冻，鲜果含糖别贪' },
  { name: '五谷豆浆（无糖）', tags: ['diabetes', 'healthy'], note: '杂粮打浆，算进主食量' },
  { name: '核桃豆浆（无糖）', tags: ['diabetes', 'healthy'], note: '核桃豆乳，一杯限能量' },
  { name: '芝麻豆浆（无糖）', tags: ['diabetes', 'healthy'], note: '芝麻豆乳香浓别多喝' },
  { name: '燕麦豆浆（无糖）', tags: ['diabetes', 'healthy'], note: '燕麦掺豆打浆，这杯算主食' },
  { name: '红枣豆浆（无糖）', tags: ['diabetes', 'healthy'], note: '红枣提甜，本身含糖限量' },
  { name: '紫薯豆浆（无糖）', tags: ['diabetes', 'healthy'], note: '紫薯染豆乳，淀粉算主食' },
  { name: '黑苦荞茶', tags: ['diabetes', 'healthy'], note: '苦荞含芦丁，冲泡别太浓' },
  { name: '苦荞大麦茶', tags: ['diabetes', 'healthy'], note: '两样炒香泡水，代日常饮水' },
  { name: '苦荞枸杞茶', tags: ['diabetes', 'healthy'], note: '苦荞配枸杞，少量提个味' },
  { name: '玉米须荷叶茶', tags: ['diabetes', 'healthy'], note: '玉米须荷叶，淡泡忌浓' },
  { name: '玉米须荞麦茶', tags: ['diabetes', 'healthy'], note: '玉米须配苦荞，煮水代茶饮' },
  { name: '柠檬薄荷水（无糖）', tags: ['diabetes', 'healthy'], note: '柠檬薄荷泡，无糖更清爽' },
  { name: '黄瓜薄荷水（无糖）', tags: ['diabetes', 'healthy'], note: '黄瓜薄荷水，解渴不升糖' },
  { name: '桑叶茶（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '霜桑叶淡泡，当日常茶饮就好' },
  { name: '大麦若叶汁', tags: ['diabetes', 'healthy'], note: '青汁冲一杯，算日常蔬菜补充' },
  { name: '玄米茶（无糖）', tags: ['diabetes', 'healthy'], note: '炒米泡茶喝，香归香不加糖' },
  { name: '菊苣根咖啡', tags: ['diabetes', 'healthy'], note: '菊苣代咖啡，无咖啡因晚间' },
  { name: '蒲公英根茶', tags: ['diabetes', 'healthy'], note: '焙香蒲公英根，淡饮适量别贪杯' },
  { name: '牛蒡茶（无糖）', tags: ['diabetes', 'healthy'], note: '牛蒡切片泡，清香只是代茶饮' },
  { name: '山楂水（无糖）', tags: ['diabetes', 'healthy'], note: '山楂煮水，胃弱者少喝' },
  { name: '陈皮水', tags: ['diabetes', 'healthy'], note: '陈皮泡饮，理气不另加糖' },
  { name: '决明子茶', tags: ['diabetes', 'healthy'], note: '炒决明子泡，淡饮就好别说功效' },
  { name: '荷叶茶（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '荷叶淡泡着喝，别指望它降糖' },
  { name: '肉桂苹果水（无糖）', tags: ['diabetes', 'healthy'], note: '肉桂煮苹果水，淡饮图个香' },
  { name: '冷萃黑咖啡（无糖）', tags: ['diabetes', 'healthy'], note: '纯黑冷萃，一杯别加糖' },
  { name: '手冲黑咖啡', tags: ['diabetes', 'healthy'], note: '单品黑咖，无糖无奶最稳' },
  { name: '肉桂黑咖啡', tags: ['diabetes', 'healthy'], note: '黑咖撒肉桂，控量不晚饮' },
  { name: '无糖生椰美式', tags: ['diabetes'], note: '椰浆美式，无糖仍看脂肪' },
  { name: '抹茶脏脏咖（无糖）', tags: ['diabetes'], note: '抹茶兑黑咖，别叠糖浆' },
  { name: '燕麦奶（无糖）', tags: ['diabetes', 'healthy'], note: '无添加糖≠无糖，一杯算半碗主食' },
  { name: '无糖腰果奶', tags: ['diabetes', 'healthy'], note: '腰果打浆，坚果计入热量' },
  { name: '无糖核桃奶', tags: ['diabetes', 'healthy'], note: '核桃磨奶香浓限一杯' },
  { name: '无糖榛子奶', tags: ['diabetes', 'healthy'], note: '榛子植物奶，控量代牛奶' },
  { name: '柠檬气泡水（无糖）', tags: ['diabetes', 'healthy'], note: '柠檬打气，零糖解个馋' },
  { name: '莓果泡水（无糖）', tags: ['diabetes', 'healthy'], note: '莓果冷泡，不加糖不加奶' },
  { name: '亚麻籽水', tags: ['diabetes', 'healthy'], note: '亚麻籽粉冲一小杯，别空腹猛喝' },
  { name: '奇亚籽柠檬水', tags: ['diabetes', 'healthy'], note: '奇亚籽柠檬，泡开再喝' },
  { name: '姜黄奶（无糖）', tags: ['diabetes', 'healthy'], note: '姜黄植物奶，少量常饮' },
  { name: '菊花枸杞茶', tags: ['diabetes', 'healthy'], note: '菊花配枸杞，淡泡就好别说功效' },
  { name: '玫瑰茶（无糖）', tags: ['diabetes', 'healthy'], note: '玫瑰花泡，舒缓不升糖' },
  { name: '薄荷绿茶（无糖）', tags: ['diabetes', 'healthy'], note: '薄荷绿茶，清口不加糖' },
  { name: '无糖康普茶', tags: ['diabetes'], note: '发酵总有残糖，一小杯就好' },
  { name: '桂花乌龙（无糖）', tags: ['diabetes', 'healthy'], note: '桂花乌龙，茶香无添加糖' },
  { name: '燕麦麸饮', tags: ['diabetes', 'healthy'], note: '麸皮冲糊一碗，算进主食量' },
  { name: '乌梅汤（无糖）', tags: ['diabetes'], note: '乌梅淡煮，酸饮不额外加糖' },
  { name: '青柠苏打（无糖）', tags: ['diabetes', 'healthy'], note: '青柠打气，零卡又解腻' },
  { name: '无糖冬瓜荷叶茶', tags: ['diabetes', 'healthy'], note: '冬瓜荷叶，淡煮代饮料' },
  { name: '无糖洛神花茶', tags: ['diabetes', 'healthy'], note: '洛神酸饮，色艳不加糖' },
  { name: '淡苦丁茶', tags: ['diabetes', 'healthy'], note: '苦丁味微苦，淡泡着喝就够' },
  { name: '无糖罗汉果茶', tags: ['diabetes', 'healthy'], note: '罗汉果苷甜，无糖仍浅饮' },
  { name: '桂花红茶（无糖）', tags: ['diabetes', 'healthy'], note: '桂花红茶，无糖点一杯' },
  { name: '番茄汁（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '鲜番茄打汁，糖低不滤渣' },
  { name: '无糖豆浆奇亚籽饮', tags: ['diabetes', 'healthy'], note: '豆浆泡奇亚籽，纤维扛饿' },
  { name: '玉米胚芽茶', tags: ['diabetes', 'healthy'], note: '胚芽炒香泡水，当日常茶饮' },
  { name: '无糖杏仁五黑饮', tags: ['diabetes', 'healthy'], note: '五黑杂粮浆，坚果计入量' },
  { name: '雪梨无糖鲜榨汁', tags: ['diabetes'], note: '榨汁升糖快，半杯不如吃鲜果' },
  { name: '无糖山楂陈皮饮', tags: ['diabetes', 'healthy'], note: '山楂配陈皮，消食不加糖' },
  { name: '无糖绿豆薏米水', tags: ['diabetes', 'healthy'], note: '豆薏煮水，淡饮不添糖' },
  { name: '烤奶皮', tags: ['diabetes'], note: '奶皮烘烤微焦，少量解馋' },
  { name: '风干牛肉干（原味）', tags: ['diabetes'], note: '原味无糖水牛肉，30克封顶' },
  { name: '低盐牛肉条（无糖）', tags: ['diabetes'], note: '无糖咸香牛条，看配料表' },
  { name: '原味鸡肉干（无糖）', tags: ['diabetes'], note: '无添加糖鸡干，一小袋' },
  { name: '鸡胸肉丝（原味）', tags: ['diabetes', 'gout'], note: '手撕鸡丝，嘌呤中等，缓解期适量' },
  { name: '即食鱿鱼丝（少盐）', tags: ['diabetes'], note: '鱿鱼丝钠偏高，浅尝几根' },
  { name: '即食蟹柳（少盐一根）', tags: ['diabetes'], note: '蟹柳含淀粉钠，一根解馋' },
  { name: '帕玛森芝士脆片', tags: ['diabetes'], note: '芝士烘烤成脆，少量高脂' },
  { name: '低脂奶酪脆（少量）', tags: ['diabetes'], note: '奶酪烘脆，脂肪别忽略' },
  { name: '魔芋爽（无糖少盐）', tags: ['diabetes', 'healthy'], note: '魔芋低热，辣味控钠' },
  { name: '素毛肚（魔芋）', tags: ['diabetes', 'healthy'], note: '魔芋仿毛肚，凉拌少油' },
  { name: '冻干秋葵脆', tags: ['diabetes', 'healthy'], note: '非油炸秋葵脆，纤维保留' },
  { name: '冻干蔬菜脆（无油炸）', tags: ['diabetes', 'healthy'], note: '冻干蔬菜，看配料无糖' },
  { name: '羽衣甘蓝脆片', tags: ['healthy', 'diabetes', 'gout'], note: '刷薄油低温烤，脆当零食' },
  { name: '烤豌豆（无油少盐）', tags: ['diabetes', 'healthy'], note: '干烤豌豆，豆香耐嚼' },
  { name: '五香煮蚕豆（少盐）', tags: ['diabetes', 'healthy'], note: '蚕豆适量，胀气者少食' },
  { name: '原味爆米花（无油无糖）', tags: ['diabetes', 'healthy'], note: '空爆玉米花，无油又无糖' },
  { name: '松子（原味小把）', tags: ['diabetes', 'healthy'], note: '原味松子，十克左右' },
  { name: '碧根果（原味小把）', tags: ['diabetes', 'healthy'], note: '碧根果油脂高，几颗为止' },
  { name: '巴西坚果（一两颗）', tags: ['diabetes', 'healthy'], note: '一天一两颗，别让娃自己抓' },
  { name: '火麻仁（原味小把）', tags: ['diabetes', 'healthy'], note: '撒一小撮就够，娃和孕妈别吃' },
  { name: '香烤黑豆（少盐）', tags: ['diabetes', 'healthy'], note: '黑豆烤香，豆制品适量' },
  { name: '豆皮脆（无糖烤）', tags: ['diabetes', 'healthy'], note: '千张烤脆，豆制品适量' },
  { name: '无糖酸奶块（冻干）', tags: ['diabetes'], note: '冻干酸奶块，看有无加糖' },
  { name: '滤乳清酸奶（无糖）', tags: ['diabetes', 'gout'], note: '滤清酸奶浓稠，无糖低GI' },
  { name: '即食毛豆仁（少盐）', tags: ['diabetes', 'healthy'], note: '毛豆GI低，一小碗正好' },
  { name: '鸡胸肉肠（无淀粉）', tags: ['diabetes'], note: '无淀粉鸡肉肠，看含糖量' },
  { name: '冻干草莓（无糖）', tags: ['diabetes', 'healthy'], note: '多半加过糖，认准配料只有草莓' },
  { name: '腌萝卜（无糖）', tags: ['diabetes', 'healthy'], note: '无糖酸萝卜，爽脆低热' },
  { name: '泡菜（无糖自制）', tags: ['diabetes', 'healthy'], note: '自泡无糖酸菜，控盐适量' },
  { name: '原味花生酱（无糖）', tags: ['diabetes', 'healthy'], note: '无糖花生酱，抹一点就够' },
  { name: '杏仁酱（无糖）', tags: ['diabetes', 'healthy'], note: '无糖杏仁酱，坚果计入量' },
  { name: '火鸡胸肉干（无糖）', tags: ['diabetes'], note: '无糖火鸡胸，蛋白扛饿' },
  { name: '海苔卷豆干条', tags: ['diabetes'], note: '豆干条卷海苔，豆制品适量' },
  { name: '芝士肉松饼（无糖少量）', tags: ['diabetes'], note: '尝一个就好，甜面皮算主食' },
  { name: '无糖蛋白棒（半根）', tags: ['diabetes'], note: '蛋白棒看糖醇，半根为宜' },
  { name: '香酥鸡胸脆片（无油炸）', tags: ['diabetes'], note: '非炸鸡胸脆，低糖高蛋白' },
  { name: '即食鹰嘴豆仁（原味）', tags: ['diabetes', 'healthy'], note: '鹰嘴豆低GI，半碗封顶' },
  { name: '卤鹌鹑蛋（少盐两颗）', tags: ['diabetes'], note: '鹌鹑蛋卤香，两颗止住' },
  { name: '芝士脆脆球（少量）', tags: ['diabetes'], note: '芝士焗脆球，脂肪别忽略' },
  { name: '无糖芝麻丸（两颗）', tags: ['diabetes'], note: '芝麻丸油重，无糖也限量' },
  { name: '烤南瓜籽（原味小把）', tags: ['diabetes', 'healthy'], note: '南瓜籽补锌，一小把就好' },
  { name: '原味葵花籽（小把带壳）', tags: ['diabetes', 'healthy'], note: '带壳嗑得慢，控制总量' },
  { name: '无糖椰脆片', tags: ['diabetes'], note: '椰子肉烘干，饱和脂肪限量' },
  { name: '风干牦牛肉（原味少量）', tags: ['diabetes'], note: '牦牛干耐嚼，蛋白高少量' },
  { name: '魔芋果冻杯（代糖）', tags: ['diabetes'], note: '魔芋冻低热，别贪一整杯' },
  { name: '低钠鸡胸肉丸（无糖）', tags: ['diabetes', 'gout'], note: '自制鸡丸无淀粉，痛风缓解期适量' },
  { name: '无糖奶贝（少量）', tags: ['diabetes'], note: '奶粉压块，无糖仍高热量' },
  { name: '冻干蓝莓（无糖）', tags: ['diabetes', 'healthy'], note: '冻干蓝莓浓缩，一小撮' },
  { name: '椒盐花生（无油炸少量）', tags: ['diabetes', 'healthy'], note: '一小把就好，挑配料无糖那款' },
  { name: '无糖奶酥条（一小根）', tags: ['diabetes'], note: '奶酥条油糖高，一根封顶' },
  { name: '芝士夹心海苔（少量）', tags: ['diabetes'], note: '海苔夹芝士，钠与脂别多' },
  { name: '原味混合坚果（一小把）', tags: ['diabetes', 'healthy'], note: '原味无盐混合，十克为限' },
  { name: '无糖酸奶拌坚果', tags: ['diabetes', 'healthy', 'gout'], note: '酸奶加坚果，一小份刚好' },
  { name: '番茄黄瓜拼盘', tags: ['diabetes', 'healthy', 'gout'], note: '番茄黄瓜切块，饿了来点' },
  { name: '水煮蛋配小番茄', tags: ['diabetes', 'healthy', 'gout'], note: '鸡蛋加圣女果，抗饿稳糖' },
  { name: '溏心水煮蛋', tags: ['healthy', 'diabetes', 'gout'], note: '溏心蛋嫩，孕妈幼儿吃全熟' },
  { name: '温泉蛋（少盐）', tags: ['diabetes', 'healthy', 'gout'], note: '温泉蛋没全熟，孕幼老人慎吃' },
  { name: '少油荷包蛋', tags: ['diabetes', 'healthy', 'gout'], note: '不粘锅少油煎蛋' },
  { name: '苹果配无糖酸奶', tags: ['diabetes', 'healthy', 'gout'], note: '苹果蘸酸奶，纤维缓升糖' },
  { name: '芹菜条配无糖酸奶', tags: ['diabetes', 'healthy'], note: '芹菜蘸酸奶，脆爽又低卡' },
  { name: '圣女果配无糖酸奶', tags: ['diabetes', 'healthy'], note: '圣女果淋酸奶，GI低解馋' },
  { name: '黄瓜鸡蛋沙拉', tags: ['diabetes', 'healthy', 'gout'], note: '黄瓜鸡蛋拌，少酱低糖' },
  { name: '牛油果圣女果杯', tags: ['diabetes', 'healthy'], note: '牛油果配圣女果，脂肪别多' },
  { name: '柚子配无糖酸奶', tags: ['diabetes', 'healthy'], note: '柚子瓣拌酸奶，微苦开胃' },
  { name: '圣女果黄瓜杯', tags: ['diabetes', 'healthy', 'gout'], note: '圣女果加黄瓜，清爽低糖' },
  { name: '番茄西芹条', tags: ['diabetes', 'healthy'], note: '番茄配西芹，脆口解馋' },
  { name: '水煮蛋拌牛油果', tags: ['diabetes', 'healthy'], note: '鸡蛋拌牛油果，脂肪控量' },
  { name: '原味豆花（不加糖）', tags: ['diabetes', 'healthy'], note: '豆花适量，别浇糖桂花' },
  { name: '番茄蛋花小碗', tags: ['diabetes', 'healthy', 'gout'], note: '番茄冲蛋花，清淡又稳糖' },
  { name: '玉米粒小份（熟）', tags: ['diabetes', 'healthy'], note: '甜玉米算主食，半碗为宜' },
  { name: '牛油果抹全麦小片', tags: ['diabetes'], note: '全麦抹牛油果，加餐半片' },
  { name: '坚果能量小球（两颗）', tags: ['diabetes', 'healthy'], note: '两颗封顶，三岁别吃要碾碎' },
  { name: '无糖酸奶淋奇亚籽', tags: ['diabetes', 'healthy', 'gout'], note: '酸奶泡奇亚籽，纤维饱腹' },
  { name: '毛豆仁拌黄瓜', tags: ['diabetes', 'healthy'], note: '毛豆配黄瓜，两餐小碟' },
  { name: '水煮蛋白两枚', tags: ['diabetes', 'healthy', 'gout'], note: '只吃蛋白，加餐低负担' },
  { name: '蒸南瓜小块', tags: ['diabetes', 'healthy'], note: '贝贝南瓜一小块，算主食' },
  { name: '番茄片撒亚麻籽', tags: ['diabetes', 'healthy'], note: '番茄配亚麻籽，纤维缓糖' },
  { name: '无糖酸奶泡燕麦（小份）', tags: ['diabetes', 'healthy'], note: '燕麦泡酸奶，加餐半杯' },
  { name: '黄瓜条配鹰嘴豆泥', tags: ['diabetes', 'healthy'], note: '黄瓜蘸豆泥，蛋白扛饿' },
  { name: '菠菜烘蛋', tags: ['diabetes', 'healthy', 'gout'], note: '菠菜拌蛋烘熟，低糖早餐' },
  { name: '蘑菇烘蛋', tags: ['healthy', 'diabetes', 'gout'], note: '口蘑切碎烘蛋，半份几片就够' },
  { name: '西兰花烘蛋', tags: ['diabetes', 'healthy', 'gout'], note: '西兰花配蛋，烤成小块' },
  { name: '番茄芝士烘蛋', tags: ['healthy', 'diabetes', 'gout'], note: '番茄撒芝士烘蛋，量要少' },
  { name: '彩椒烘蛋', tags: ['diabetes', 'healthy', 'gout'], note: '彩椒切丁烘蛋，颜色丰富' },
  { name: '芦笋烘蛋', tags: ['diabetes', 'healthy', 'gout'], note: '芦笋嘌呤偏高，少量尝味就好' },
  { name: '西葫芦烘蛋', tags: ['healthy', 'diabetes', 'gout'], note: '瓜片铺底淋蛋，烘成整块' },
  { name: '豆腐烘蛋', tags: ['diabetes', 'gout'], note: '嫩豆腐拌蛋烘，豆制适量' },
  { name: '玉米鸡蛋饼', tags: ['diabetes', 'gout'], note: '玉米粒摊蛋饼，算主食量' },
  { name: '胡萝卜鸡蛋饼', tags: ['diabetes', 'gout'], note: '胡萝卜丝摊蛋，少油慢煎' },
  { name: '菠菜鸡蛋饼', tags: ['diabetes', 'healthy', 'gout'], note: '菠菜拌蛋摊饼，补铁控糖' },
  { name: '香菇鸡蛋饼', tags: ['diabetes', 'gout'], note: '香菇两朵提鲜，摊成蛋饼正够' },
  { name: '全麦鸡蛋牛油果三明治', tags: ['diabetes'], note: '全麦夹蛋牛油果，控量' },
  { name: '黑麦鸡蛋三明治', tags: ['diabetes'], note: '黑麦面包夹蛋，GI偏低' },
  { name: '全麦鸡丝蛋卷', tags: ['diabetes', 'healthy'], note: '全麦皮卷鸡丝蛋，少酱' },
  { name: '番茄鸡蛋全麦卷', tags: ['diabetes'], note: '全麦饼卷蛋蔬，早餐来一支刚好' },
  { name: '少油蛋沙拉全麦堡', tags: ['diabetes'], note: '蛋沙拉夹全麦，少酱低糖' },
  { name: '隔夜燕麦（无糖）', tags: ['diabetes', 'healthy', 'gout'], note: '燕麦冷藏泡发，无糖加料' },
  { name: '无糖酸奶燕麦杯', tags: ['diabetes', 'healthy', 'gout'], note: '酸奶浸燕麦，早餐别贪多' },
  { name: '奇亚籽燕麦杯', tags: ['diabetes', 'healthy', 'gout'], note: '奇亚籽泡燕麦，纤维扛饿' },
  { name: '藜麦牛奶粥', tags: ['diabetes', 'healthy', 'gout'], note: '藜麦煮奶粥，低GI高纤' },
  { name: '玉米面鸡蛋糊', tags: ['diabetes', 'healthy', 'gout'], note: '玉米面冲蛋花，算主食' },
  { name: '燕麦麸鸡蛋糊', tags: ['diabetes', 'healthy', 'gout'], note: '麸皮冲蛋花，高纤控糖' },
  { name: '蒸山药鸡蛋糕', tags: ['diabetes', 'healthy', 'gout'], note: '山药泥拌蛋蒸，这块抵半碗饭' },
  { name: '全麦香蕉松饼（无糖）', tags: ['diabetes'], note: '香蕉入糊煎松饼，中GI限量' },
  { name: '鸡丝豆腐脑', tags: ['diabetes', 'healthy'], note: '豆腐脑配鸡丝，咸香低糖' },
  { name: '杂粮鸡蛋饼', tags: ['diabetes', 'healthy', 'gout'], note: '杂粮粉摊蛋饼，这块算主食' },
  { name: '全麦发糕（无糖）', tags: ['diabetes'], note: '全麦发酵蒸糕，无糖少食' },
  { name: '燕麦馒头', tags: ['diabetes'], note: '燕麦至少一半，一个为限别贪' },
  { name: '黑麦馒头', tags: ['diabetes'], note: '黑麦面蒸馒头，低GI有嚼劲' },
  { name: '杂粮花卷（少油）', tags: ['diabetes'], note: '杂粮面搓花卷，少油无糖' },
  { name: '全麦豆渣饼', tags: ['diabetes', 'healthy'], note: '豆渣掺全麦少油煎，胀气少吃' },
  { name: '蔬菜蛋堡', tags: ['diabetes', 'healthy', 'gout'], note: '全麦堡夹蛋与生菜' },
  { name: '山药鸡蛋饼', tags: ['diabetes', 'healthy', 'gout'], note: '山药泥拌蛋摊饼，山药抵部分主食' },
  { name: '蘑菇芝士焗蛋', tags: ['diabetes'], note: '蘑菇芝士焗蛋，少量高脂' },
  { name: '玉米燕麦鸡蛋糊', tags: ['diabetes', 'healthy', 'gout'], note: '玉米燕麦冲蛋，算进主食' },
  { name: '紫薯燕麦牛奶杯', tags: ['diabetes', 'healthy'], note: '紫薯燕麦冲奶，淀粉算主食' },
  { name: '番茄蛋花全麦粥', tags: ['diabetes', 'healthy'], note: '全麦煮粥淋蛋花，稠一点' },
  { name: '荞麦鸡蛋软饼', tags: ['diabetes'], note: '荞麦调糊摊蛋，比白面稳糖' },
  { name: '无糖豆浆燕麦糊', tags: ['diabetes', 'healthy'], note: '豆浆冲燕麦，蛋白又高纤' },
  { name: '南瓜杂粮糊（少南瓜）', tags: ['diabetes', 'healthy'], note: '多豆少南瓜，糊要冲稀' },
  { name: '全麦金枪鱼蛋卷', tags: ['diabetes'], note: '金枪鱼拌蛋卷全麦，少酱' },
  { name: '鸡蛋豆腐脑', tags: ['diabetes', 'healthy'], note: '蛋花冲豆腐脑，咸口少卤' },
  { name: '蔬菜鸡蛋杂粮卷', tags: ['diabetes', 'healthy'], note: '杂粮皮卷蛋与菜，早餐可控' },
  { name: '黑芝麻燕麦糊（无糖）', tags: ['diabetes', 'healthy'], note: '芝麻燕麦冲糊，油香别多' },
  { name: '番茄烘蛋', tags: ['diabetes', 'healthy', 'gout'], note: '番茄切丁烘蛋，酸甜低糖' },
  { name: '青梅（少量）', tags: ['diabetes', 'gout'], note: '只吃鲜青梅，腌渍的先冲淡' },
  { name: '西梅（一两颗）', tags: ['diabetes', 'gout'], note: '鲜西梅一次控一两颗就收口' },
  { name: '雪莲果（生食小块）', tags: ['healthy', 'diabetes', 'gout'], note: '削皮洗净再啃，肠胃弱的少食' },
  { name: '火参果', tags: ['diabetes', 'healthy'], note: '清淡淡甜，升糖较低' },
  { name: '沙棘（少量）', tags: ['healthy', 'diabetes', 'gout'], note: '沙棘极酸，冲饮别加糖' },
  { name: '黑加仑（少量）', tags: ['healthy', 'diabetes', 'gout'], note: '酸甜深色，一小把当加餐' },
  { name: '姑娘果（少量）', tags: ['diabetes', 'healthy'], note: '灯笼果微甜，含糖不高' },
  { name: '葡萄柚（西柚）', tags: ['healthy', 'diabetes', 'gout'], note: '一次半个，服他汀/部分降压药者慎' },
  { name: '刺梨（少量）', tags: ['diabetes', 'gout'], note: '刺梨维C高极酸，鲜食少量' },
  { name: '鲜莲蓬（少量）', tags: ['healthy', 'diabetes', 'gout'], note: '莲子优先焯熟，生啃要洗净' },
  { name: '菱角（少量）', tags: ['diabetes'], note: '菱角含淀粉，当主食吃' },
  { name: '椰子肉（少量）', tags: ['diabetes', 'healthy'], note: '椰肉纤维高，几口就好' },
  { name: '柚子莓果沙拉', tags: ['diabetes', 'healthy'], note: '柚子配莓果，低GI加餐' },
  { name: '苹果配原味坚果', tags: ['diabetes', 'healthy'], note: '苹果搭坚果，脂肪缓升糖' },
  { name: '芭乐酸嘢（无糖）', tags: ['diabetes'], note: '番石榴蘸酸嘢，少盐无糖' },
  { name: '桑椹无糖果昔', tags: ['diabetes', 'healthy'], note: '鲜桑椹洗净打，一次一小杯' },
  { name: '蓝莓奇亚籽碗', tags: ['diabetes', 'healthy'], note: '蓝莓配奇亚籽，控一小份' },
  { name: '无糖蛋黄酥（小份）', tags: ['diabetes'], note: '无糖蛋黄酥，酥皮油重浅尝' },
  { name: '木糖醇枣泥酥', tags: ['diabetes'], note: '代糖枣泥酥，枣甜也含糖' },
  { name: '赤藓糖醇松露巧克力', tags: ['diabetes'], note: '高可可代糖，一小块化开' },
  { name: '无糖奶豆腐', tags: ['diabetes'], note: '牛奶凝结代糖，热量别忽略' },
  { name: '代糖椰汁糕（小份）', tags: ['diabetes'], note: '椰浆代糖糕，一块就该封顶' },
  { name: '五黑饮（无糖）', tags: ['diabetes', 'healthy'], note: '五黑杂粮浆，控量算主食' },
  { name: '无糖肉桂茶', tags: ['diabetes', 'healthy'], note: '肉桂煮水淡饮，别指望降糖' },
  { name: '无糖菊花普洱', tags: ['diabetes', 'healthy'], note: '菊花配普洱，去腻不加糖' },
  { name: '卤鸭胗（少盐）', tags: ['diabetes'], note: '鸭胗高蛋白，少盐嘌呤注意' },
  { name: '鳕鱼肠（无糖低盐）', tags: ['diabetes'], note: '无糖一根，淀粉算半份主食' },
  { name: '冻干无花果脆（无糖）', tags: ['diabetes'], note: '干脆片含糖五成，一两片为限' },
  { name: '紫薯鸡蛋饼', tags: ['diabetes', 'healthy', 'gout'], note: '紫薯泥拌蛋摊，颜色好看' },
  { name: '南瓜鸡蛋饼', tags: ['diabetes', 'healthy', 'gout'], note: '南瓜擦丝摊蛋，算进主食' },
  { name: '燕麦鸡蛋饼', tags: ['diabetes', 'healthy', 'gout'], note: '燕麦掺蛋煎饼，纤维扛饿' },
  { name: '杂粮鸡蛋糕', tags: ['diabetes', 'healthy'], note: '杂粮糊蒸蛋糕，松软也算主食' },
  { name: '全麦鸡蛋堡', tags: ['diabetes'], note: '全麦堡夹煎蛋，少酱低糖' },
  { name: '玉米烘蛋', tags: ['diabetes'], note: '玉米粒拌蛋烘，算主食量' },
  { name: '藜麦鸡蛋粥', tags: ['diabetes', 'healthy'], note: '藜麦冲蛋花，低GI早餐' },
  { name: '山药蒸蛋', tags: ['diabetes', 'healthy', 'gout'], note: '山药泥冲蛋蒸，半碗要算进主食' },
  { name: '百香果（一个）', tags: ['healthy', 'diabetes', 'gout'], note: '百香果冲饮，控糖不加蜜' },
  { name: '指橙（少量）', tags: ['diabetes', 'gout'], note: '鱼子似的果香，几瓣够了' },
  { name: '凉薯（生食小块）', tags: ['diabetes', 'healthy'], note: '脆甜似梨，升糖较低' },
  { name: '圣女果配坚果', tags: ['diabetes', 'healthy'], note: '圣女果撒坚果，两餐垫底' },
  { name: '番茄豆腐脑', tags: ['diabetes', 'healthy'], note: '豆腐脑淋番茄卤，少油' },
]
