// 「今天吃什么」分片：基线池（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const BASE_DISHES: FoodDish[] = [
  { name: '清蒸鲈鱼', tags: ['healthy', 'diabetes', 'gout'], note: '高蛋白低脂蒸制，中嘌呤缓解期适量' },
  { name: '清蒸鳕鱼', tags: ['healthy', 'diabetes'], note: '白肉鱼低脂鲜嫩（嘌呤中等，痛风缓解期适量）' },
  { name: '番茄龙利鱼', tags: ['healthy', 'diabetes', 'gout'], note: '番茄酸甜，鱼肉中嘌呤缓解期适量' },
  { name: '白灼虾', tags: ['healthy', 'diabetes'], note: '虾肉高蛋白低脂（痛风缓解期适量，急性期避开）' },
  { name: '蒜蓉西兰花', tags: ['healthy', 'diabetes', 'gout'], note: '高纤维低热量，蒜香少油' },
  { name: '西兰花炒虾仁', tags: ['healthy'], note: '虾仁高蛋白，西兰花脆嫩' },
  { name: '清炒菠菜', tags: ['healthy', 'diabetes', 'gout'], note: '深绿叶菜补铁，快炒少油' },
  { name: '凉拌黄瓜', tags: ['healthy', 'diabetes', 'gout'], note: '爽口低卡，蒜醋汁开胃' },
  { name: '西红柿炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '国民下饭菜，少油不放糖' },
  { name: '白灼菜心', tags: ['healthy', 'diabetes', 'gout'], note: '脆嫩清淡，低热量' },
  { name: '上汤娃娃菜', tags: ['healthy', 'diabetes', 'gout'], note: '素上汤底，皮蛋咸蛋少放去汤留菜' },
  { name: '蒸蛋羹', tags: ['healthy', 'diabetes', 'gout'], note: '嫩滑高蛋白，好消化' },
  { name: '白菜炖豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '白菜豆腐保平安，少油清淡' },
  { name: '凉拌木耳', tags: ['healthy', 'diabetes', 'gout'], note: '爽脆低卡，开胃小菜' },
  { name: '苦瓜炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '苦瓜清爽，鸡蛋高蛋白' },
  { name: '清蒸南瓜', tags: ['healthy', 'gout'], note: '软糯微甜（适量当主食）' },
  { name: '凉拌豆腐丝', tags: ['healthy', 'diabetes', 'gout'], note: '豆制品适量，清爽开胃别贪多' },
  { name: '番茄豆腐汤', tags: ['healthy', 'diabetes', 'gout'], note: '酸甜开胃，豆腐嫩滑' },
  { name: '香菇青菜', tags: ['healthy', 'diabetes'], note: '鲜香家常（菌菇痛风者适量）' },
  { name: '紫菜蛋花汤', tags: ['healthy', 'gout'], note: '紫菜少许提鲜，清淡暖胃汤别多喝' },
  { name: '西葫芦炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '清爽低卡，适合减脂' },
  { name: '手撕包菜', tags: ['healthy', 'diabetes', 'gout'], note: '爽脆微辣，少油快炒' },
  { name: '蒜蓉油麦菜', tags: ['healthy', 'diabetes', 'gout'], note: '绿叶菜低热量，蒜香提味' },
  { name: '凉拌莴笋', tags: ['healthy', 'diabetes'], note: '脆嫩清爽，低热量' },
  { name: '蒸紫薯', tags: ['healthy', 'diabetes', 'gout'], note: '粗粮饱腹（适量当主食）' },
  { name: '藜麦蔬菜沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '高蛋白低GI，油醋汁拌' },
  { name: '秋葵炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '秋葵脆滑，低卡营养' },
  { name: '清炒荷兰豆', tags: ['healthy'], note: '脆嫩清甜，低热量' },
  { name: '杂粮饭', tags: ['healthy', 'diabetes', 'gout'], note: '糙米燕麦混合，低GI饱腹' },
  { name: '蒸红薯', tags: ['healthy', 'diabetes', 'gout'], note: '香甜饱腹（适量当主食）' },
  { name: '蒸玉米', tags: ['healthy', 'diabetes', 'gout'], note: '清甜粗粮，替代主食少选糯玉米' },
  { name: '水煮蛋', tags: ['healthy', 'diabetes', 'gout'], note: '优质蛋白，早餐必备' },
  { name: '无糖豆浆', tags: ['healthy', 'diabetes', 'gout'], note: '植物蛋白无糖（豆制品痛风缓解期可适量）' },
  { name: '燕麦粥', tags: ['healthy', 'diabetes', 'gout'], note: '早餐暖胃，选需煮原粒别即食' },
  { name: '生菜沙拉（油醋汁）', tags: ['healthy', 'diabetes', 'gout'], note: '低卡爽口，酱汁选油醋' },
  { name: '芹菜炒香干', tags: ['healthy', 'diabetes', 'gout'], note: '芹菜脆爽，香干高蛋白（豆制品适量）' },
  { name: '蚝油生菜', tags: ['healthy', 'diabetes', 'gout'], note: '脆嫩清甜（蚝油少许）' },
  { name: '什锦蔬菜汤', tags: ['healthy'], note: '多色蔬菜，清汤少油' },
  { name: '清蒸豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '豆香嫩滑，淋少许酱油' },
  { name: '白萝卜炖牛肉', tags: ['healthy', 'diabetes'], note: '牛肉适量，萝卜清甜（痛风缓解期可适量）' },
  { name: '冬瓜汤', tags: ['healthy', 'gout'], note: '清淡消暑，低热量' },
  { name: '蒜蓉空心菜', tags: ['healthy', 'diabetes', 'gout'], note: '夏日绿叶菜，快炒脆嫩' },
  { name: '清炒丝瓜', tags: ['healthy', 'diabetes', 'gout'], note: '清甜软嫩，清热解暑' },
  { name: '糙米饭', tags: ['diabetes', 'gout'], note: '掺一半杂豆燕麦更稳' },
  { name: '荞麦面', tags: ['diabetes', 'gout'], note: '看配料，选荞麦占比高的' },
  { name: '全麦馒头', tags: ['diabetes', 'gout'], note: '看配料全麦比例，主食控量' },
  { name: '杂豆饭', tags: ['diabetes'], note: '豆米同煮，低GI高纤维' },
  { name: '藜麦饭', tags: ['diabetes', 'gout'], note: '藜麦掺白米，一小碗当主食' },
  { name: '魔芋凉皮', tags: ['diabetes'], note: '近零热量，低GI' },
  { name: '清蒸鸡胸肉', tags: ['healthy', 'diabetes'], note: '高蛋白低脂，蒸制少油' },
  { name: '凉拌鸡丝', tags: ['healthy', 'diabetes'], note: '鸡胸肉撕丝拌黄瓜，清爽高蛋白' },
  { name: '苦瓜炒肉片', tags: ['diabetes'], note: '苦瓜清苦，少油快炒不放糖' },
  { name: '菠菜豆腐汤', tags: ['healthy', 'diabetes', 'gout'], note: '菠菜先焯水，豆腐适量清汤少油' },
  { name: '无糖酸奶', tags: ['diabetes', 'gout'], note: '奶制品低嘌呤，选无糖' },
  { name: '原味坚果（适量）', tags: ['diabetes'], note: '优质脂肪，每天一小把' },
  { name: '蓝莓', tags: ['diabetes'], note: '一小把两餐之间吃，别榨果汁' },
  { name: '草莓', tags: ['diabetes'], note: '几颗当加餐，别配奶油糖酱' },
  { name: '柚子', tags: ['diabetes'], note: '几瓣解馋，服他汀者先问医生' },
  { name: '黄瓜炒蛋', tags: ['diabetes', 'gout'], note: '清爽家常，少油快炒不放糖' },
  { name: '冬瓜海带汤', tags: ['diabetes', 'gout'], note: '清淡低卡（海带量少）' },
  { name: '杂粮煎饼（无糖）', tags: ['diabetes'], note: '不加薄脆、酱减半' },
  { name: '山药紫薯粥', tags: ['diabetes'], note: '豆多料整别熬糊，算主食' },
  { name: '白灼秋葵', tags: ['healthy', 'diabetes', 'gout'], note: '爽滑低嘌呤，酱油蒜末' },
  { name: '上汤西兰花', tags: ['gout'], note: '素上汤清煮，去汤留菜别喝汤' },
  { name: '低脂牛奶', tags: ['healthy', 'diabetes', 'gout'], note: '温奶好入口，促尿酸排泄' },
  { name: '清汤面条', tags: ['gout'], note: '清汤素底无肉汤，少油少盐' },
  { name: '粉丝汤', tags: ['gout'], note: '清水素汤煮粉丝，低嘌呤主食' },
  { name: '蔬菜粥', tags: ['gout'], note: '温和好消化，低嘌呤' },
  { name: '蒸芋头', tags: ['healthy', 'diabetes', 'gout'], note: '低嘌呤主食，软糯饱腹' },
  { name: '凉拌莲藕', tags: ['healthy', 'diabetes', 'gout'], note: '脆爽低嘌呤，夏日开胃' },
  { name: '木瓜', tags: ['gout'], note: '低嘌呤水果，清甜' },
  { name: '银耳汤（无糖）', tags: ['diabetes', 'gout'], note: '银耳一两朵泡发煨煮，无糖润燥' },
  { name: '咸豆腐脑', tags: ['diabetes', 'gout', 'takeout'], note: '豆制品植物嘌呤影响小，缓解期可适量' },
  { name: '蒸山药', tags: ['healthy', 'diabetes', 'gout'], note: '低嘌呤主食，替代部分米饭' },
  { name: '清汤馄饨（素馅）', tags: ['healthy', 'gout'], note: '低嘌呤，选素馅更清爽' },
  { name: '黄焖鸡米饭', tags: ['takeout'], note: '砂锅鸡块浇汁饭，油大撇汤少喝汁' },
  { name: '轻食沙拉（鸡胸肉）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '鸡胸掌心大小，低卡缓解期适量' },
  { name: '饺子（素馅/鸡肉馅）', tags: ['takeout'], note: '实惠管饱，素馅更清爽' },
  { name: '皮蛋瘦肉粥', tags: ['gout', 'takeout'], note: '粥底低嘌呤，瘦肉适量' },
  { name: '兰州拉面（清汤）', tags: ['takeout'], note: '清汤少辣，面量控制' },
  { name: '沙县蒸饺', tags: ['takeout'], note: '快捷实惠，蒸的比炸的健康' },
  { name: '蛋炒饭', tags: ['takeout'], note: '国民快餐，油偏多' },
  { name: '螺蛳粉', tags: ['takeout'], note: '酸辣开胃，汤底偏咸' },
  { name: '麻辣香锅', tags: ['takeout'], note: '选蔬菜菌菇，少油少辣' },
  { name: '清汤米线', tags: ['gout', 'takeout'], note: '云南米线选素汤底，汤别多喝' },
  { name: '蔬菜披萨（薄底）', tags: ['takeout'], note: '选薄底蔬菜款，少芝士' },
  { name: '烧烤（鸡翅/蔬菜串）', tags: ['takeout'], note: '选瘦肉蔬菜，少刷酱' },
  { name: '番茄鸡蛋盖饭', tags: ['takeout'], note: '相对清爽的盖饭，酸甜下饭' },
  { name: '煎饼果子', tags: ['takeout'], note: '早餐经典，酱少放' },
  { name: '素包子', tags: ['takeout'], note: '清淡管饱，早餐友好' },
  { name: '小笼包', tags: ['takeout'], note: '皮薄汁多，趁热吃' },
  { name: '肠粉', tags: ['takeout'], note: '广式早餐，清淡爽滑' },
  { name: '白切鸡饭', tags: ['takeout'], note: '清淡鲜嫩，配姜葱' },
  { name: '清汤火锅（单人小锅）', tags: ['healthy', 'takeout'], note: '蔬菜豆腐为主，低嘌呤友好' },
  { name: '麻辣拌', tags: ['takeout'], note: '东北黏糊麻酱麻辣拌，自选配菜' },
  { name: '关东煮', tags: ['healthy', 'diabetes', 'takeout'], note: '选萝卜海带豆腐，避丸子别喝汤' },
  { name: '石锅拌饭', tags: ['takeout'], note: '辣酱米饭锅巴脆，加蛋更香' },
  { name: '紫菜包饭', tags: ['takeout'], note: '米饭蔬菜卷，方便携带' },
  { name: '三明治（可选鸡胸/鸡蛋/火腿芝士）', tags: ['healthy', 'diabetes', 'takeout'], note: '选配料首位全麦或黑麦那款' },
  { name: '越南春卷', tags: ['takeout'], note: '米皮蔬菜清爽，选纯素款' },
  { name: '鱼香肉丝饭', tags: ['takeout'], note: '下饭神器，油糖偏多' },
  { name: '宫保鸡丁饭', tags: ['takeout'], note: '花生香脆，偏油' },
  { name: '地三鲜盖饭', tags: ['takeout'], note: '茄子土豆吸油，偶尔吃' },
  { name: '大盘鸡', tags: ['takeout'], note: '新疆大盘鸡配宽面，土豆吸汁' },
  { name: '羊肉泡馍', tags: ['takeout'], note: '西北风味，暖胃管饱' },
  { name: '酸菜鱼', tags: ['takeout'], note: '鱼肉嫩滑，酸辣开胃（痛风避开鱼汤）' },
  { name: '冒菜', tags: ['takeout'], note: '成都串串冒菜，自选烫菜蘸干碟' },
  { name: '潮汕粿条汤', tags: ['takeout'], note: '清汤粿条，低嘌呤友好' },
  { name: '云吞面', tags: ['takeout'], note: '竹升面爽弹，鲜香' },
  { name: '菜煎饼', tags: ['healthy', 'takeout'], note: '蔬菜多，少酱更清爽' },
  { name: '干炒牛河', tags: ['takeout'], note: '镬气十足，油多' },
  { name: '热干面', tags: ['takeout'], note: '武汉过早，芝麻酱浓' },
  { name: '炸酱面', tags: ['takeout'], note: '酱香浓郁，偏咸' },
  { name: '西红柿鸡蛋面', tags: ['takeout'], note: '选杂粮面减量，汤底不放糖' },
  { name: '阳春面', tags: ['gout', 'takeout'], note: '清汤细面，简单暖胃' },
  { name: '葱油拌面', tags: ['takeout'], note: '葱香扑鼻，油稍多' },
  { name: '油泼面', tags: ['takeout'], note: '辣子香，宽面劲道' },
  { name: '刀削面', tags: ['takeout'], note: '山西刀削面配番茄卤，筋道酸香' },
  { name: '重庆小面', tags: ['takeout'], note: '麻辣重油，偶尔解馋' },
  { name: '日式拉面', tags: ['takeout'], note: '汤浓味重，偶尔吃' },
  { name: '卤味拼盘（素菜/豆干）', tags: ['diabetes', 'takeout'], note: '下酒小菜，选素菜更清爽' },
  { name: '清炒茼蒿', tags: ['healthy', 'diabetes', 'gout'], note: '春日时令菜，脆嫩清香' },
  { name: '蒜蓉菠菜', tags: ['healthy', 'diabetes', 'gout'], note: '快手绿叶菜，补铁好帮手' },
  { name: '白灼芥蓝', tags: ['healthy', 'diabetes', 'gout'], note: '爽脆回甘，淋豉油就够味' },
  { name: '上汤豆苗', tags: ['healthy', 'gout'], note: '豆苗嘌呤偏高少食，素汤少皮蛋' },
  { name: '清炒豌豆苗', tags: ['healthy', 'diabetes', 'gout'], note: '豌豆苗嘌呤偏高，清炒少量' },
  { name: '凉拌西芹', tags: ['healthy', 'diabetes', 'gout'], note: '脆爽低卡，焯水拌醋蒜' },
  { name: '凉拌海带丝', tags: ['healthy', 'diabetes', 'gout'], note: '爽脆开胃，海带痛风缓解期少量' },
  { name: '凉拌三丝', tags: ['healthy'], note: '土豆胡萝卜青椒丝，爽口家常' },
  { name: '醋溜白菜', tags: ['healthy', 'diabetes', 'gout'], note: '酸香开胃，少油快炒' },
  { name: '清炒豆芽', tags: ['healthy', 'gout'], note: '豆芽嘌呤偏高，去根少量清炒' },
  { name: '韭菜炒豆芽', tags: ['healthy', 'diabetes', 'gout'], note: '豆芽去根少量炒，家常快手' },
  { name: '蒜蓉蒸丝瓜', tags: ['healthy', 'diabetes', 'gout'], note: '丝瓜整盘蒸，宴客也清淡' },
  { name: '蒜蓉粉丝蒸娃娃菜', tags: ['healthy'], note: '粉丝吸汁，娃娃菜清甜' },
  { name: '冬瓜炒虾仁', tags: ['healthy'], note: '冬瓜清淡，虾仁提鲜（痛风缓解期适量）' },
  { name: '虾仁蒸蛋', tags: ['healthy', 'diabetes'], note: '嫩滑蛋羹配虾仁，高蛋白' },
  { name: '丝瓜蛋汤', tags: ['healthy', 'diabetes', 'gout'], note: '清淡解暑，夏天最爱' },
  { name: '黄瓜皮蛋汤', tags: ['healthy'], note: '清爽解腻，夏天喝舒服' },
  { name: '海带豆腐汤', tags: ['healthy', 'diabetes', 'gout'], note: '汤清味鲜，低卡管饱（海带量少）' },
  { name: '蘑菇豆腐汤', tags: ['healthy'], note: '菌菇提鲜，豆腐嫩滑（痛风者适量）' },
  { name: '冬瓜排骨汤（撇油）', tags: ['healthy'], note: '撇去浮油，清甜不腻（痛风缓解期适量）' },
  { name: '萝卜丝汤', tags: ['healthy', 'gout'], note: '萝卜清甜，素汤煮奶白非肉汤' },
  { name: '山药排骨汤', tags: ['healthy'], note: '撇净浮油，山药软糯汤别多喝' },
  { name: '玉米排骨汤', tags: ['healthy'], note: '玉米清甜，撇净浮油别多喝汤' },
  { name: '番茄牛腩煲', tags: ['healthy', 'diabetes'], note: '番茄炖软，不放糖不勾芡' },
  { name: '土豆炖牛腩', tags: ['healthy'], note: '家常炖菜，少放油' },
  { name: '芹菜炒牛肉', tags: ['healthy', 'diabetes'], note: '芹菜脆，牛肉嫩，下饭' },
  { name: '青椒炒牛肉', tags: ['healthy'], note: '简单快炒，蛋白质在线' },
  { name: '彩椒炒鸡丁', tags: ['healthy', 'diabetes'], note: '颜色好看，低脂高蛋白' },
  { name: '香菇滑鸡', tags: ['healthy'], note: '蒸制少油，香菇提鲜（痛风者适量）' },
  { name: '口水鸡（少油版）', tags: ['healthy', 'diabetes'], note: '红油减半，另调酱汁不加糖' },
  { name: '白切鸡', tags: ['healthy', 'diabetes', 'gout'], note: '白煮清淡高蛋白，中嘌呤缓解期适量' },
  { name: '卤鸡腿（去皮）', tags: ['healthy', 'diabetes'], note: '去皮少油，卤香入味' },
  { name: '黑椒鸡胸肉', tags: ['healthy', 'diabetes'], note: '只用黑椒碎自调，不用现成黑椒汁' },
  { name: '香煎鸡胸肉', tags: ['healthy', 'diabetes'], note: '提前腌过不柴，减脂标配' },
  { name: '鸡肉蔬菜卷', tags: ['healthy', 'diabetes'], note: '鸡胸肉卷蔬菜，营养均衡' },
  { name: '彩椒炒虾仁', tags: ['healthy'], note: '色彩缤纷，低脂高蛋白（痛风缓解期适量）' },
  { name: '蒜香虾仁', tags: ['healthy', 'diabetes'], note: '虾仁弹嫩，蒜香扑鼻（痛风缓解期适量）' },
  { name: '虾仁滑蛋', tags: ['healthy', 'diabetes'], note: '嫩滑下饭，蛋白质管够' },
  { name: '香煎三文鱼', tags: ['healthy'], note: '富含Omega-3，少油煎（适量）' },
  { name: '清蒸多宝鱼', tags: ['healthy', 'diabetes'], note: '肉质细嫩，蒸制最鲜' },
  { name: '清蒸桂鱼', tags: ['healthy', 'diabetes', 'gout'], note: '肉嫩清蒸，中嘌呤缓解期适量' },
  { name: '红烧带鱼（少油）', tags: ['healthy'], note: '刺多慢吃，少油先煎不炒糖色' },
  { name: '葱姜焖大虾', tags: ['healthy'], note: '葱姜提鲜，肉质弹嫩（痛风缓解期适量）' },
  { name: '蒜蓉开背虾', tags: ['healthy'], note: '蒜香浓郁，宴客硬菜（痛风缓解期适量）' },
  { name: '紫菜虾皮汤', tags: ['healthy'], note: '鲜上加鲜，清淡暖胃（痛风者适量）' },
  { name: '荷塘小炒', tags: ['healthy', 'gout'], note: '莲藕木耳荷兰豆，清爽脆嫩' },
  { name: '清炒山药', tags: ['healthy', 'diabetes', 'gout'], note: '脆嫩爽口，山药算主食减饭' },
  { name: '山药炒木耳', tags: ['healthy', 'diabetes', 'gout'], note: '黑白爽脆，山药算主食减饭' },
  { name: '木耳炒鸡蛋', tags: ['healthy', 'diabetes', 'gout'], note: '木耳脆，鸡蛋香，十分钟搞定' },
  { name: '韭菜炒鸡蛋', tags: ['healthy', 'diabetes', 'gout'], note: '春天的味道，快手下饭' },
  { name: '香椿炒蛋', tags: ['healthy', 'gout'], note: '季节限定，香味独特' },
  { name: '蒜黄炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '蒜香柔和，嫩滑下饭' },
  { name: '小葱炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '简单到不行，香得很' },
  { name: '蒸胡萝卜', tags: ['healthy', 'diabetes', 'gout'], note: '蒸软当主食适量吃，别打汁' },
  { name: '凉拌秋葵', tags: ['healthy', 'diabetes', 'gout'], note: '焯水淋汁，滑嫩爽口' },
  { name: '蒜蓉蒸茄子', tags: ['healthy', 'diabetes', 'gout'], note: '蒸着吃，少油又入味' },
  { name: '凉拌茄子', tags: ['healthy', 'diabetes', 'gout'], note: '手撕茄子拌蒜醋，清爽开胃' },
  { name: '烧茄子（少油版）', tags: ['healthy'], note: '先蒸后烧，省油版' },
  { name: '清炒苦瓜', tags: ['healthy', 'diabetes', 'gout'], note: '焯水去苦，清火开胃' },
  { name: '苦瓜酿肉', tags: ['healthy', 'diabetes'], note: '苦瓜清苦，肉馅鲜香（适量）' },
  { name: '凉拌苦瓜', tags: ['healthy', 'diabetes', 'gout'], note: '冰镇更脆，消暑一绝' },
  { name: '清炒娃娃菜', tags: ['healthy', 'gout'], note: '清甜爽脆，五分钟上桌' },
  { name: '白灼罗马生菜', tags: ['healthy', 'diabetes', 'gout'], note: '简单白灼，脆嫩清甜' },
  { name: '上汤菠菜', tags: ['healthy', 'diabetes', 'gout'], note: '汤是高汤少喝，去汤留菜' },
  { name: '蒜蓉菜心', tags: ['healthy', 'diabetes', 'gout'], note: '广式经典，爽脆清甜' },
  { name: '蚝油芥蓝', tags: ['healthy', 'gout'], note: '芥蓝脆嫩，蚝油少许别多放' },
  { name: '清炒红苋菜', tags: ['healthy', 'diabetes', 'gout'], note: '紫红汤汁拌饭，补铁不错' },
  { name: '上汤苋菜', tags: ['healthy', 'gout'], note: '苋菜滑嫩，素上汤少皮蛋别喝汤' },
  { name: '清炒小白菜', tags: ['healthy', 'diabetes', 'gout'], note: '家常绿叶菜，清淡爽口' },
  { name: '香菇油菜', tags: ['healthy', 'diabetes'], note: '香菇香，油菜脆（痛风者适量）' },
  { name: '蒜蓉茼蒿', tags: ['healthy', 'diabetes', 'gout'], note: '茼蒿清香，蒜蓉绝配' },
  { name: '凉拌菠菜', tags: ['healthy', 'diabetes', 'gout'], note: '焯水拌麻酱，补铁开胃' },
  { name: '芝麻拌菠菜', tags: ['healthy', 'diabetes', 'gout'], note: '芝麻香，菠菜嫩' },
  { name: '清炒芥菜', tags: ['healthy', 'diabetes', 'gout'], note: '微苦回甘，清热下火' },
  { name: '蒜蓉生菜', tags: ['healthy', 'diabetes', 'gout'], note: '爽脆清甜，三分钟出锅' },
  { name: '醋溜土豆丝', tags: ['healthy', 'diabetes', 'gout'], note: '土豆当主食算，别配双份饭' },
  { name: '清炒土豆丝', tags: ['healthy', 'gout'], note: '爽脆家常，少油快炒' },
  { name: '尖椒土豆丝', tags: ['healthy'], note: '微辣下饭，少油快炒当主食' },
  { name: '家常豆腐（少油版）', tags: ['healthy'], note: '豆腐煎香，勾芡少油' },
  { name: '番茄豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '酸甜茄汁裹豆腐，下饭' },
  { name: '麻婆豆腐', tags: ['healthy', 'takeout'], note: '麻辣下饭，家常少油外卖慎点' },
  { name: '香煎豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '外焦里嫩，淋生抽' },
  { name: '凉拌内酯豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '冰冰凉凉，皮蛋香菜' },
  { name: '皮蛋拌豆腐', tags: ['healthy', 'gout'], note: '简单快手，下酒开胃' },
  { name: '虾皮蒸豆腐', tags: ['healthy', 'diabetes'], note: '虾皮提鲜，豆腐嫩滑（痛风者适量）' },
  { name: '丝瓜炒豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '清甜软嫩，夏日清爽' },
  { name: '菠菜拌粉丝', tags: ['healthy', 'diabetes', 'gout'], note: '清爽小凉菜，蒜醋汁' },
  { name: '凉拌金针菇', tags: ['healthy', 'diabetes'], note: '酸辣爽口（痛风者适量）' },
  { name: '拍黄瓜', tags: ['healthy', 'diabetes', 'gout'], note: '蒜香醋香，夏日标配' },
  { name: '凉拌西红柿', tags: ['healthy', 'diabetes', 'gout'], note: '番茄生拌，不撒糖' },
  { name: '果仁菠菜', tags: ['healthy', 'diabetes'], note: '花生米增香，菠菜补铁' },
  { name: '芹菜拌花生', tags: ['healthy', 'diabetes'], note: '爽脆香，下酒小菜' },
  { name: '盐水毛豆', tags: ['healthy', 'diabetes', 'gout'], note: '追剧标配，少盐（痛风缓解期适量）' },
  { name: '蒸玉米粒', tags: ['healthy', 'diabetes', 'gout'], note: '清甜粗粮，当主食也行' },
  { name: '山药薏米粥', tags: ['healthy', 'diabetes', 'gout'], note: '煮到粒粒分明，当主食替换' },
  { name: '小米粥', tags: ['healthy', 'gout'], note: '养胃经典，晚上来一碗' },
  { name: '南瓜小米粥', tags: ['healthy', 'gout'], note: '南瓜清甜，小米暖胃' },
  { name: '玉米糊', tags: ['healthy', 'gout'], note: '粗粮糊糊，早餐暖胃' },
  { name: '红豆薏米粥', tags: ['healthy'], note: '祛湿甜粥（控糖少糖）' },
  { name: '绿豆汤', tags: ['healthy', 'gout'], note: '消暑少豆多加水，无糖偶尔一碗' },
  { name: '蔬菜豆腐煲', tags: ['healthy', 'diabetes', 'gout'], note: '一锅炖，少油清淡' },
  { name: '白菜粉丝煲', tags: ['healthy', 'diabetes', 'gout'], note: '清淡管饱，冬日暖身' },
  { name: '萝卜炖粉条', tags: ['healthy', 'diabetes', 'gout'], note: '萝卜清甜，粉条吸汁' },
  { name: '蒜蓉蒸金针菇', tags: ['healthy', 'diabetes'], note: '蒜香开胃，蒸制少油（痛风者适量）' },
  { name: '清蒸娃娃菜', tags: ['healthy', 'gout'], note: '简单蒸制，清甜多汁' },
  { name: '白灼芦笋', tags: ['healthy', 'diabetes', 'gout'], note: '芦笋焯透，植物嘌呤影响小' },
  { name: '清炒芦笋', tags: ['healthy', 'diabetes', 'gout'], note: '清脆爽口，植物嘌呤影响小' },
  { name: '芦笋炒虾仁', tags: ['healthy', 'diabetes'], note: '双鲜搭配，低脂高蛋白（痛风缓解期适量）' },
  { name: '口蘑炒青菜', tags: ['healthy', 'diabetes'], note: '口蘑鲜，青菜脆（痛风者适量）' },
  { name: '菌菇汤', tags: ['healthy'], note: '多种菌菇，汤鲜味美（痛风者适量）' },
  { name: '萝卜牛腩汤', tags: ['healthy', 'diabetes'], note: '汤清味浓，萝卜吸油（适量）' },
  { name: '冬瓜虾皮汤', tags: ['healthy', 'gout'], note: '虾皮高嘌呤仅点缀，汤别多喝' },
  { name: '丝瓜毛豆汤', tags: ['healthy', 'gout'], note: '毛豆缓解期适量，清甜时令' },
  { name: '燕麦饭', tags: ['diabetes', 'gout'], note: '燕麦掺米煮，低GI饱腹' },
  { name: '黑米饭', tags: ['diabetes', 'gout'], note: '花青素多，掺白米一半控小碗' },
  { name: '小米饭', tags: ['diabetes', 'gout'], note: '小米掺白米，控小碗别熬粥' },
  { name: '玉米碴粥', tags: ['diabetes', 'gout'], note: '粗粮小碗算主食，别熬太稀' },
  { name: '全麦面条', tags: ['diabetes', 'gout'], note: '粗粮面条，别煮太烂' },
  { name: '玉米面条', tags: ['diabetes', 'gout'], note: '选真玉米面杂豆面的' },
  { name: '莜面栲栳栳', tags: ['diabetes'], note: '粗粮面食，蘸料清淡' },
  { name: '全麦吐司', tags: ['diabetes', 'gout'], note: '早餐常备，选无糖款' },
  { name: '杂粮馒头', tags: ['diabetes', 'gout'], note: '全麦玉米面混合，控糖' },
  { name: '燕麦片（无糖）', tags: ['diabetes'], note: '选需煮的原粒燕麦，别速溶' },
  { name: '蒸荞麦馒头', tags: ['diabetes', 'gout'], note: '掺荞麦比例看配料，主食减量' },
  { name: '魔芋面', tags: ['diabetes', 'gout'], note: '低热量主食，凉拌好吃' },
  { name: '魔芋结', tags: ['diabetes', 'gout'], note: '涮锅凉拌都行，几乎零卡' },
  { name: '蒸土豆（带皮）', tags: ['diabetes', 'gout'], note: '饱腹感强，别当菜吃多' },
  { name: '蒜蓉秋葵', tags: ['diabetes', 'gout'], note: '秋葵脆滑爽口，蒜蓉少油炒' },
  { name: '清炒西葫芦', tags: ['diabetes', 'gout'], note: '清爽低卡，少油不放糖可常备' },
  { name: '番茄炒西葫芦', tags: ['diabetes'], note: '酸甜清爽，低卡' },
  { name: '凉拌西葫芦丝', tags: ['diabetes', 'gout'], note: '脆嫩爽口，夏日凉菜' },
  { name: '清炒冬瓜', tags: ['diabetes', 'gout'], note: '清淡低卡，少油快炒不放糖' },
  { name: '冬瓜盅', tags: ['diabetes'], note: '挖空蒸汤，清淡鲜甜' },
  { name: '清炒佛手瓜', tags: ['diabetes', 'gout'], note: '脆嫩清甜，低GI' },
  { name: '凉拌佛手瓜', tags: ['diabetes'], note: '爽脆开胃，热量低' },
  { name: '上汤丝瓜', tags: ['diabetes', 'gout'], note: '清甜丝瓜，素上汤去汤留菜' },
  { name: '苦瓜酿虾滑', tags: ['diabetes'], note: '清苦配鲜甜，控糖菜（痛风缓解期适量）' },
  { name: '芹菜炒百合', tags: ['diabetes', 'gout'], note: '清爽脆嫩，痛风缓解期适量' },
  { name: '清炒芥蓝', tags: ['diabetes', 'gout'], note: '芥蓝脆嫩回甘，清炒少油少盐' },
  { name: '西兰花炒木耳', tags: ['diabetes', 'gout'], note: '双脆搭配，清淡' },
  { name: '荷兰豆炒木耳', tags: ['diabetes', 'gout'], note: '脆嫩清爽' },
  { name: '清炒豌豆荚', tags: ['diabetes', 'gout'], note: '清甜脆嫩，时令' },
  { name: '蒜蓉豇豆', tags: ['diabetes'], note: '豇豆清炒，下饭' },
  { name: '凉拌豇豆', tags: ['diabetes', 'gout'], note: '焯水拌蒜，爽口' },
  { name: '麻酱豇豆（少酱）', tags: ['diabetes'], note: '麻酱适量，爽脆' },
  { name: '擂辣椒茄子', tags: ['diabetes'], note: '湘味开胃，少油版' },
  { name: '洋葱炒蛋', tags: ['diabetes', 'gout'], note: '洋葱微甜，少油快炒不放糖' },
  { name: '洋葱炒牛肉', tags: ['diabetes'], note: '洋葱甜，牛肉嫩（适量）' },
  { name: '蒜苔炒肉丝', tags: ['diabetes'], note: '蒜苔脆嫩，肉丝适量' },
  { name: '蒜苔炒鸡蛋', tags: ['healthy', 'diabetes'], note: '时令家常，下饭' },
  { name: '韭菜炒豆干', tags: ['diabetes'], note: '韭菜香，豆干弹（豆制品适量）' },
  { name: '青椒炒鸡蛋', tags: ['diabetes', 'gout'], note: '简单快手，微辣下饭' },
  { name: '虎皮青椒（少油）', tags: ['diabetes'], note: '微焦香，少油版' },
  { name: '西红柿炖茄子', tags: ['diabetes'], note: '茄汁浓郁，低油' },
  { name: '番茄炖豆腐', tags: ['diabetes', 'gout'], note: '茄汁浓郁，豆腐入味' },
  { name: '清蒸鸡腿（去皮）', tags: ['healthy', 'diabetes', 'gout'], note: '去皮蒸制低脂，中嘌呤少量' },
  { name: '手撕鸡', tags: ['diabetes'], note: '葱油拌鸡丝，鲜香' },
  { name: '香煎龙利鱼', tags: ['diabetes'], note: '少油煎，肉质细嫩' },
  { name: '鲫鱼豆腐汤', tags: ['diabetes'], note: '汤白味鲜（痛风缓解期适量）' },
  { name: '白灼基围虾', tags: ['healthy', 'diabetes'], note: '简单白灼，鲜甜弹嫩（痛风缓解期适量）' },
  { name: '盐水虾', tags: ['healthy', 'diabetes'], note: '盐水煮虾，原味鲜甜（痛风缓解期适量）' },
  { name: '豆腐蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '嫩上加嫩，高蛋白' },
  { name: '肉末蒸蛋', tags: ['diabetes'], note: '咸鲜下饭，肉末少许' },
  { name: '酱牛肉', tags: ['diabetes', 'gout'], note: '优质蛋白冷切，中嘌呤缓解期适量' },
  { name: '卤牛腱', tags: ['diabetes', 'gout'], note: '高蛋白冷切，中嘌呤缓解期适量' },
  { name: '白切牛肉', tags: ['diabetes', 'gout'], note: '清淡高蛋白，中嘌呤缓解期适量' },
  { name: '番茄牛肉汤', tags: ['diabetes'], note: '酸甜浓郁，暖胃' },
  { name: '蔬菜鸡胸汤', tags: ['diabetes'], note: '清淡高蛋白' },
  { name: '鸡丝凉面（荞麦）', tags: ['diabetes', 'gout', 'takeout'], note: '芝麻酱糖醋汁都减半拌' },
  { name: '杂粮饭团', tags: ['diabetes'], note: '糙米饭团，上班带饭' },
  { name: '燕麦能量棒（无糖）', tags: ['diabetes'], note: '自制款，不加糖' },
  { name: '无糖黑咖啡', tags: ['diabetes', 'gout'], note: '提神零卡，别加糖' },
  { name: '柠檬水（无糖）', tags: ['diabetes', 'gout'], note: '清爽解腻，代替甜饮料' },
  { name: '无糖苏打水', tags: ['diabetes', 'gout'], note: '气泡感满足，零糖零卡' },
  { name: '绿茶', tags: ['diabetes', 'gout'], note: '无糖茶饮，解腻' },
  { name: '玉米须茶', tags: ['diabetes', 'gout'], note: '玉米须泡水煮，清香代茶' },
  { name: '苦荞茶', tags: ['diabetes', 'gout'], note: '麦香浓郁，无糖' },
  { name: '无糖杏仁奶', tags: ['diabetes', 'gout'], note: '植物奶，热量低' },
  { name: '蒸豌豆', tags: ['diabetes', 'gout'], note: '豌豆算进主食量，小份尝鲜' },
  { name: '圣女果', tags: ['diabetes', 'gout'], note: '低糖水果，当零食' },
  { name: '猕猴桃', tags: ['diabetes', 'gout'], note: '一天一个，两餐之间吃别榨汁' },
  { name: '苹果', tags: ['diabetes', 'gout'], note: '带皮一个中等大小，两餐间吃' },
  { name: '梨', tags: ['diabetes', 'gout'], note: '水分足，一次一个两餐之间吃' },
  { name: '樱桃', tags: ['diabetes', 'gout'], note: '低GI，别一次吃太多' },
  { name: '桃子', tags: ['diabetes', 'gout'], note: '一次一个两餐间吃，不选罐头' },
  { name: '橙子', tags: ['diabetes'], note: '酸甜维C多，吃整果别喝橙汁' },
  { name: '火龙果', tags: ['diabetes'], note: '半个即可两餐间吃，红心更少' },
  { name: '清炒莴笋', tags: ['diabetes', 'gout'], note: '脆嫩清甜，低嘌呤' },
  { name: '莴笋炒木耳', tags: ['diabetes', 'gout'], note: '双脆清爽，低嘌呤' },
  { name: '上汤小白菜', tags: ['gout'], note: '清爽不油，素上汤去汤留菜' },
  { name: '白灼小白菜', tags: ['diabetes', 'gout'], note: '简单白灼，清淡' },
  { name: '清炒苋菜', tags: ['diabetes', 'gout'], note: '滑嫩清甜，低嘌呤' },
  { name: '清炒盖菜', tags: ['gout'], note: '微苦回甘，清热' },
  { name: '醋溜藕片', tags: ['gout'], note: '酸脆开胃，低嘌呤' },
  { name: '凉拌藕丁', tags: ['diabetes', 'gout'], note: '爽脆小凉菜' },
  { name: '玉米胡萝卜汤', tags: ['gout'], note: '清甜蔬菜汤，低嘌呤' },
  { name: '番茄蛋汤', tags: ['diabetes', 'gout'], note: '家常快手，酸甜开胃' },
  { name: '黄瓜蛋汤', tags: ['gout'], note: '清淡爽口，低嘌呤' },
  { name: '冬瓜豆腐汤', tags: ['gout'], note: '清淡低嘌呤' },
  { name: '萝卜豆腐汤', tags: ['gout'], note: '清甜嫩滑' },
  { name: '山药豆腐汤', tags: ['gout'], note: '温和养胃' },
  { name: '白菜豆腐汤', tags: ['gout'], note: '白菜豆腐保平安' },
  { name: '清汤豆腐脑', tags: ['gout'], note: '咸甜自选，嫩滑' },
  { name: '蒸豆腐脑', tags: ['diabetes', 'gout'], note: '简单蒸制，淋酱油' },
  { name: '凉拌腐竹（适量）', tags: ['diabetes', 'gout'], note: '豆制品适量，清爽' },
  { name: '凉拌千张', tags: ['diabetes', 'gout'], note: '千张豆制品适量，爽口开胃' },
  { name: '千张炒青菜', tags: ['diabetes', 'gout'], note: '千张豆制品适量，家常快手' },
  { name: '素炒三丁', tags: ['gout'], note: '土豆胡萝卜黄瓜丁，清爽' },
  { name: '醋溜西葫芦', tags: ['diabetes', 'gout'], note: '酸爽开胃' },
  { name: '清炒黄瓜', tags: ['diabetes', 'gout'], note: '脆嫩低卡' },
  { name: '蒜蓉蒸冬瓜', tags: ['diabetes', 'gout'], note: '清甜软糯' },
  { name: '蒸冬瓜夹', tags: ['diabetes', 'gout'], note: '冬瓜夹肉末，适量' },
  { name: '清炒白萝卜', tags: ['gout'], note: '萝卜清甜，通气' },
  { name: '萝卜丝炒粉条', tags: ['gout'], note: '家常下饭' },
  { name: '蒸萝卜糕', tags: ['gout'], note: '清淡点心，素蒸不放腊味虾米' },
  { name: '清炒土豆片', tags: ['gout'], note: '家常快炒' },
  { name: '红薯粥', tags: ['gout'], note: '粗粮粥，低嘌呤' },
  { name: '大米粥', tags: ['gout'], note: '清淡米粥，配蛋配蔬菜' },
  { name: '八宝粥（无糖）', tags: ['diabetes', 'gout'], note: '杂粮豆粥，豆类适量' },
  { name: '绿豆粥', tags: ['gout'], note: '消暑绿豆少放，无糖偶尔一碗' },
  { name: '红豆粥', tags: ['gout'], note: '红豆干豆，小碗偶尔别当主食' },
  { name: '燕麦牛奶粥', tags: ['diabetes', 'gout'], note: '选原粒非即食燕麦，别熬糊' },
  { name: '酸奶水果碗', tags: ['diabetes', 'gout'], note: '无糖酸奶，水果一小份避罐头' },
  { name: '鸡蛋煎饼', tags: ['gout'], note: '蛋香浓郁，少油' },
  { name: '蔬菜鸡蛋饼', tags: ['gout'], note: '蔬菜多多，早餐友好' },
  { name: '西葫芦鸡蛋饼', tags: ['gout'], note: '清甜软嫩' },
  { name: '土豆鸡蛋饼', tags: ['gout'], note: '管饱早餐' },
  { name: '韭菜盒子（少油）', tags: ['gout'], note: '素馅更清爽，煎的适量' },
  { name: '荠菜馅饺子', tags: ['gout'], note: '清淡管饱，野菜鲜' },
  { name: '青菜香菇馄饨', tags: ['gout'], note: '清汤煮，鲜' },
  { name: '玉米面窝头', tags: ['gout'], note: '粗粮窝头，低嘌呤' },
  { name: '杂粮发糕', tags: ['gout'], note: '粗粮松软' },
  { name: '炒时蔬', tags: ['gout'], note: '冰箱有啥炒啥，少油' },
  { name: '白灼时蔬', tags: ['diabetes', 'gout'], note: '简单白灼，清爽' },
  { name: '上汤时蔬', tags: ['gout'], note: '时蔬清鲜，素上汤去汤留菜' },
  { name: '清汤蔬菜面', tags: ['gout'], note: '素面一碗，无肉汤底更清淡' },
  { name: '清汤挂面', tags: ['gout'], note: '清汤挂面，无肉汤底快手清淡' },
  { name: '疙瘩汤', tags: ['gout'], note: '面疙瘩汤，暖胃' },
  { name: '番茄疙瘩汤', tags: ['gout'], note: '番茄蛋花拉丝，酸甜开胃' },
  { name: '蔬菜疙瘩汤', tags: ['gout'], note: '菜多面少' },
  { name: '蛋花汤', tags: ['gout'], note: '简单快手，清淡' },
  { name: '冬瓜丸子汤（素丸）', tags: ['gout'], note: '素丸子清汤' },
  { name: '萝卜丸子汤（素丸）', tags: ['gout'], note: '清甜' },
  { name: '白菜粉丝汤', tags: ['gout'], note: '清淡管饱' },
  { name: '菠菜粉丝汤', tags: ['gout'], note: '清淡鲜甜' },
  { name: '红枣银耳汤', tags: ['diabetes', 'gout'], note: '银耳润燥无糖，红枣几颗限量' },
  { name: '百合银耳羹', tags: ['gout'], note: '清甜滑口，银耳少量泡发无糖' },
  { name: '莲子银耳羹', tags: ['gout'], note: '银耳一两朵莲子十几颗，无糖' },
  { name: '红枣枸杞茶', tags: ['gout'], note: '暖身养生，几颗淡饮不加糖' },
  { name: '黄瓜汁', tags: ['diabetes', 'gout'], note: '清爽解腻' },
  { name: '芹菜汁', tags: ['diabetes', 'gout'], note: '芹菜榨汁，清爽解腻' },
  { name: '冬瓜茶', tags: ['gout'], note: '清热解暑，自熬无糖别买甜的' },
  { name: '苏打水', tags: ['gout'], note: '碱化尿液，痛风友好' },
  { name: '蒸苹果', tags: ['diabetes', 'gout'], note: '苹果蒸软，果胶更温' },
  { name: '烤梨', tags: ['gout'], note: '热乎甜润，冰糖蜂蜜少放些' },
  { name: '葡萄（适量）', tags: ['gout'], note: '低嘌呤水果' },
  { name: '香蕉', tags: ['gout'], note: '低嘌呤，补钾' },
  { name: '汉堡（牛肉单层）', tags: ['takeout'], note: '快餐经典，选单层更可控' },
  { name: '炸鸡汉堡套餐', tags: ['takeout'], note: '快乐餐，偶尔吃' },
  { name: '鸡米花', tags: ['takeout'], note: '追剧零食，热量预警' },
  { name: '新奥尔良烤翅', tags: ['takeout'], note: '甜辣入味，一盒不够' },
  { name: '蛋挞', tags: ['takeout'], note: '酥皮嫩蛋挞，下午茶小确幸' },
  { name: '奶茶（三分糖）', tags: ['takeout'], note: '快乐水，减糖版' },
  { name: '杨枝甘露', tags: ['takeout'], note: '芒果西米，甜品快乐' },
  { name: '双皮奶', tags: ['takeout'], note: '广式甜品，奶香浓郁' },
  { name: '红豆沙', tags: ['takeout'], note: '甜品，少糖' },
  { name: '绿豆沙', tags: ['takeout'], note: '消暑甜品' },
  { name: '芋圆烧仙草', tags: ['takeout'], note: '配料丰富，选少糖' },
  { name: '冰粉', tags: ['takeout'], note: '川渝甜品，清爽' },
  { name: '凉皮', tags: ['takeout'], note: '酸辣爽口，夏日必点' },
  { name: '擀面皮', tags: ['takeout'], note: '劲道酸辣' },
  { name: '米皮', tags: ['takeout'], note: '软糯爽滑' },
  { name: '肉夹馍', tags: ['takeout'], note: '馍酥肉香，西安味道' },
  { name: '烤冷面', tags: ['takeout'], note: '东北铁板烤冷面，酸香甜辣' },
  { name: '手抓饼', tags: ['takeout'], note: '早餐快手，加蛋加肠' },
  { name: '酱香饼', tags: ['takeout'], note: '酱香浓郁，按斤称' },
  { name: '鸡蛋灌饼', tags: ['takeout'], note: '外酥里嫩，早餐顶配' },
  { name: '驴肉火烧', tags: ['takeout'], note: '保定名吃，火烧酥脆' },
  { name: '灌汤包', tags: ['takeout'], note: '一口爆汁，小心烫' },
  { name: '生煎包', tags: ['takeout'], note: '底脆汁多，上海味道' },
  { name: '锅贴', tags: ['takeout'], note: '底部焦脆，肉馅香' },
  { name: '烧麦', tags: ['takeout'], note: '糯米馅，顶饱' },
  { name: '奶黄包', tags: ['takeout'], note: '流心奶黄，甜口' },
  { name: '叉烧包', tags: ['takeout'], note: '广式早茶，咸甜口' },
  { name: '虾饺', tags: ['takeout'], note: '晶莹剔透，鲜弹（痛风急性期避开）' },
  { name: '凤爪', tags: ['takeout'], note: '早茶必点，软糯脱骨' },
  { name: '糯米鸡', tags: ['takeout'], note: '荷叶香，管饱' },
  { name: '艇仔粥', tags: ['takeout'], note: '料足粥滑' },
  { name: '及第粥', tags: ['takeout'], note: '广式名粥' },
  { name: '砂锅粥', tags: ['takeout'], note: '鲜虾膏蟹砂锅粥，痛风慎喝' },
  { name: '潮汕牛肉火锅（外卖套餐）', tags: ['takeout'], note: '牛肉鲜切，清汤锅底' },
  { name: '重庆火锅（外卖）', tags: ['takeout'], note: '麻辣过瘾，锅底自煮' },
  { name: '番茄锅底火锅外卖', tags: ['takeout'], note: '酸甜锅底，老少皆宜' },
  { name: '寿司拼盘', tags: ['takeout'], note: '清爽精致，芥末酱油' },
  { name: '鳗鱼饭', tags: ['takeout'], note: '蒲烧鳗鱼，甜咸下饭' },
  { name: '天妇罗', tags: ['takeout'], note: '酥脆不腻，配饭刚好' },
  { name: '咖喱饭', tags: ['takeout'], note: '日式咖喱，浓郁下饭' },
  { name: '蛋包饭', tags: ['takeout'], note: '嫩滑蛋皮裹炒饭' },
  { name: '韩式炸鸡', tags: ['takeout'], note: '甜辣酱，配可乐' },
  { name: '部队锅', tags: ['takeout'], note: '芝士拉面，韩式锅物' },
  { name: '石锅鱼', tags: ['takeout'], note: '鱼肉嫩滑（痛风避开鱼汤）' },
  { name: '烤鱼', tags: ['takeout'], note: '万州纸包烤鱼，配菜吸汁（痛风避开）' },
  { name: '水煮鱼', tags: ['takeout'], note: '麻辣鲜香（痛风避开鱼汤）' },
  { name: '麻辣小龙虾', tags: ['takeout'], note: '夏天标配，手套备好' },
  { name: '蒜蓉小龙虾', tags: ['takeout'], note: '蒜香浓郁，嗦壳停不下' },
  { name: '炸串', tags: ['takeout'], note: '童年味道，油大' },
  { name: '臭豆腐', tags: ['takeout'], note: '闻着臭吃着香，长沙味' },
  { name: '长沙大香肠', tags: ['takeout'], note: '外焦里嫩' },
  { name: '章鱼小丸子', tags: ['takeout'], note: '酱汁木鱼花小丸子，街头现烫' },
  { name: '烤红薯', tags: ['takeout'], note: '冬天暖手神器，外卖也有' },
  { name: '糖炒栗子', tags: ['takeout'], note: '秋天限定，香甜粉糯' },
  { name: '泡面（加蛋加菜）', tags: ['takeout'], note: '深夜泡面加蛋加菜，滤汤少料包' },
  { name: '自热小火锅', tags: ['takeout'], note: '宿舍神器，料包自选' },
  { name: '麻辣鸭脖', tags: ['takeout'], note: '辣卤鸭脖追剧，钠高嘌呤偏高少量' },
  { name: '卤鸭翅', tags: ['takeout'], note: '卤香入味' },
  { name: '凉拌鸡爪', tags: ['takeout'], note: '酸辣开胃，追剧神器' },
  { name: '红油抄手', tags: ['takeout'], note: '川味馄饨，红油香' },
  { name: '钟水饺', tags: ['takeout'], note: '红油蒜泥甜水面皮，成都名饺' },
  { name: '担担面', tags: ['takeout'], note: '芝麻酱花生碎，川味灵魂' },
  { name: '宜宾燃面', tags: ['takeout'], note: '干拌面，香辣' },
  { name: '沙茶面', tags: ['takeout'], note: '闽南沙茶汤底，自选浇头' },
  { name: '过桥米线', tags: ['takeout'], note: '滚汤烫料，仪式感' },
  { name: '炒河粉', tags: ['takeout'], note: '广式炒河粉配虾仁，镬气香（痛风适量）' },
  { name: '炒米粉', tags: ['takeout'], note: '干香爽口' },
  { name: '桂林米粉', tags: ['takeout'], note: '卤水香，锅烧脆' },
  { name: '南昌拌粉', tags: ['takeout'], note: '酱油麻酱拌米粉，香辣爽滑' },
  { name: '新疆炒米粉', tags: ['takeout'], note: '酱香浓郁，辣到上头' },
  { name: '手抓饭', tags: ['takeout'], note: '羊肉胡萝卜，西北风味' },
  { name: '新疆烤包子', tags: ['takeout'], note: '皮酥肉香' },
  { name: '烤羊肉串', tags: ['takeout'], note: '孜然香，撸串快乐（痛风急性期避开）' },
  { name: '红柳烤肉', tags: ['takeout'], note: '大串过瘾' },
  { name: '羊蝎子火锅', tags: ['takeout'], note: '冬日暖身（痛风者适量）' },
  { name: '涮羊肉', tags: ['takeout'], note: '铜锅涮肉，麻酱蘸（痛风缓解期适量）' },
  { name: '煎饺', tags: ['takeout'], note: '底部焦脆，蘸醋香' },
  { name: '白粥配小菜', tags: ['takeout'], note: '清淡养胃，配咸菜' },
  { name: '豆浆油条', tags: ['takeout'], note: '早餐经典组合' },
  { name: '油条', tags: ['takeout'], note: '香脆，偶尔吃' },
  { name: '麻团', tags: ['takeout'], note: '芝麻香，甜糯' },
  { name: '冷面（朝鲜族）', tags: ['takeout'], note: '荞麦冷面冰汤酸甜，可选拌/汤' },
  { name: '披萨（肉食爱好者）', tags: ['takeout'], note: '芝士拉丝，热量炸弹，一片顶饭' },
  { name: '意面（肉酱）', tags: ['takeout'], note: '西式快餐，酱浓' },
  { name: '焗饭', tags: ['takeout'], note: '芝士焗饭，香浓' },
  { name: '北京烤鸭（外卖）', tags: ['takeout'], note: '片鸭卷饼，仪式感' },
  { name: '脆皮烧鸭饭', tags: ['takeout'], note: '皮脆肉嫩，广式经典' },
  { name: '叉烧饭', tags: ['takeout'], note: '蜜汁叉烧，甜咸下饭' },
  { name: '烧鹅饭', tags: ['takeout'], note: '皮脆油亮，配酸梅酱' },
  { name: '煲仔饭', tags: ['takeout'], note: '锅巴香脆，腊味香' },
  { name: '猪脚饭', tags: ['takeout'], note: '软糯入味，胶质满满' },
  { name: '海南鸡饭', tags: ['takeout'], note: '鸡肉嫩滑，鸡油饭香' },
  { name: '咖喱鸡饭', tags: ['takeout'], note: '椰香浓郁' },
  { name: '冬阴功汤', tags: ['takeout'], note: '酸辣鲜，泰式灵魂（加虾痛风避开）' },
  { name: '越南牛肉河粉', tags: ['takeout'], note: '清汤鲜甜，九层塔香' },
  { name: '糖油粑粑', tags: ['takeout'], note: '长沙小吃，甜糯' },
]
