// 「今天吃什么」分片：痛风低嘌呤汤羹主食饮品（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const GOUT_SOUP_DISHES: FoodDish[] = [
  { name: '番茄蛋花莴笋汤（无肉底）', tags: ['healthy', 'diabetes', 'gout'], note: '莴笋清甜，清水做底' },
  { name: '番茄魔芋汤（清汤）', tags: ['gout', 'diabetes'], note: '魔芋低嘌呤，番茄提酸香' },
  { name: '番茄圆子汤（素丸）', tags: ['gout'], note: '豆腐适量捏素丸，番茄清汤' },
  { name: '番茄白萝卜汤', tags: ['gout'], note: '萝卜煮透明，茄香清汤底' },
  { name: '番茄白菜帮汤', tags: ['gout'], note: '白菜帮软烂，茄香清汤' },
  { name: '番茄千张汤（适量千张）', tags: ['gout'], note: '千张两三条就够，番茄打底' },
  { name: '番茄黄瓜汤', tags: ['gout', 'diabetes'], note: '黄瓜起锅前放，清爽少盐' },
  { name: '茄汁粉条汤（清汤）', tags: ['gout'], note: '红薯粉条低嘌呤，清汤煮' },
  { name: '番茄老南瓜羹（无奶油）', tags: ['gout'], note: '南瓜熬稠代奶油，无肉汤' },
  { name: '番茄海带芽汤', tags: ['gout'], note: '海带少量提鲜，浓汁别喝' },
  { name: '冬瓜木耳汤', tags: ['healthy', 'diabetes', 'gout'], note: '双脆清汤，不放骨头汤' },
  { name: '冬瓜豌豆汤（鲜豌豆少）', tags: ['gout'], note: '鲜豌豆一小把，冬瓜管够' },
  { name: '冬瓜菜花汤', tags: ['gout', 'diabetes'], note: '两样清淡，汤稀可喝两碗' },
  { name: '冬瓜烩粉条（清汤）', tags: ['gout', 'diabetes'], note: '粉条冬瓜清煮，盐放少许' },
  { name: '冬瓜山药汤', tags: ['gout'], note: '山药滑冬瓜软，全素汤底' },
  { name: '冬瓜黄豆芽汤', tags: ['gout'], note: '豆芽适量下锅，汤喝小半碗' },
  { name: '冬瓜鲜扁豆汤（豆少）', tags: ['gout'], note: '鲜扁豆中嘌呤，十几条尝味' },
  { name: '冬瓜芡实汤（少量芡实）', tags: ['gout'], note: '芡实十几粒，冬瓜煮到烂' },
  { name: '丝瓜豆腐汤', tags: ['gout'], note: '豆腐适量，丝瓜清甜' },
  { name: '丝瓜木耳汤', tags: ['healthy', 'diabetes', 'gout'], note: '丝瓜配木耳，清汤少盐' },
  { name: '丝瓜山药汤', tags: ['gout'], note: '两样都软嫩，好消化低嘌呤' },
  { name: '丝瓜口蘑汤（适量口蘑）', tags: ['gout'], note: '口蘑三五片提鲜就够' },
  { name: '毛瓜清汤', tags: ['gout'], note: '冬瓜嫩瓜叫毛瓜，清煮' },
  { name: '佛手瓜汤', tags: ['gout'], note: '佛手瓜清煮，脆甜低嘌呤' },
  { name: '节瓜汤', tags: ['gout'], note: '两广小冬瓜，清汤煮软' },
  { name: '黄瓜豆腐汤', tags: ['gout', 'diabetes'], note: '豆腐适量，黄瓜后放下锅' },
  { name: '南瓜土豆羹（不加奶）', tags: ['gout'], note: '两样熬稠代奶油，无肉汤' },
  { name: '莴笋叶汤', tags: ['gout', 'diabetes'], note: '叶子别扔，清汤微苦香' },
  { name: '莴笋豆腐汤', tags: ['gout'], note: '莴笋脆豆腐嫩，豆腐适量就好' },
  { name: '菜花汤（清汤蛋花）', tags: ['gout'], note: '菜花煮软打蛋花，全素底' },
  { name: '清汤苦瓜', tags: ['gout', 'diabetes'], note: '苦瓜薄片清煮，不配豆豉鱼' },
  { name: '鲜藕汤', tags: ['gout'], note: '鲜藕清煮微甜，不放排骨' },
  { name: '洋芋浓汤（无肉汤）', tags: ['gout'], note: '云南叫洋芋，熬化增稠' },
  { name: '胡萝卜浓汤（无奶油）', tags: ['gout', 'diabetes'], note: '胡萝卜熬甜，不勾奶油' },
  { name: '茄子清汤', tags: ['gout'], note: '茄子煮化，蒜香清汤底' },
  { name: '塌棵菜汤', tags: ['gout'], note: '冷天塌棵菜，煮汤软嫩' },
  { name: '卷心菜汤', tags: ['gout'], note: '包菜煮软，家常素汤' },
  { name: '鸡毛菜汤', tags: ['gout'], note: '鸡毛菜易熟，汤清味淡' },
  { name: '空心菜杆汤', tags: ['gout'], note: '菜杆切段煮软，清热利水' },
  { name: '大叶芥菜汤', tags: ['gout'], note: '芥菜微苦，煮汤下火' },
  { name: '油菜汤', tags: ['gout'], note: '小油菜清煮，汤绿味淡' },
  { name: '荠菜豆腐汤', tags: ['gout'], note: '豆腐适量，荠菜提香' },
  { name: '茼蒿豆腐汤', tags: ['gout'], note: '茼蒿清香，豆腐放半块' },
  { name: '腐皮清汤（适量腐皮）', tags: ['gout'], note: '腐皮一两片，清汤煮软' },
  { name: '扁豆胡萝卜汤', tags: ['gout'], note: '鲜扁豆中嘌呤，一次半碗' },
  { name: '红豆羹（少豆半碗）', tags: ['gout'], note: '干豆嘌呤偏高，只喝稀的' },
  { name: '绿豆冬瓜汤', tags: ['gout'], note: '豆少瓜多，夏天喝清汤' },
  { name: '豌豆苗汤', tags: ['gout'], note: '豆苗嘌呤偏高，撒一小撮' },
  { name: '马齿苋蛋汤', tags: ['gout'], note: '野菜酸软，打蛋花清汤' },
  { name: '口蘑清汤（适量）', tags: ['gout'], note: '鲜口蘑三五个，只喝清汤' },
  { name: '鲜菇清汤（少量菌菇）', tags: ['gout'], note: '菌菇适量不贪多，清汤底' },
  { name: '竹荪清汤（少量竹荪）', tags: ['gout'], note: '竹荪一两段提鲜就够' },
  { name: '平菇蛋花汤（少量平菇）', tags: ['gout'], note: '平菇一小把，蛋花打底' },
  { name: '圆白菜番茄汤', tags: ['gout'], note: '三丝番茄熬，不放肉汤' },
  { name: '俄式红菜汤（素版无肉汤）', tags: ['healthy', 'gout', 'takeout'], note: '素炖不放黄油糖，酸奶油另盛' },
  { name: '百合小米羹（无糖）', tags: ['gout'], note: '鲜百合几瓣，小米熬羹' },
  { name: '海带芽蛋花汤（少量）', tags: ['gout'], note: '干海藻嘌呤高，一撮提鲜' },
  { name: '山药玉米汤', tags: ['gout'], note: '山药配玉米粒，素汤清甜' },
  { name: '昆布清汤（少量）', tags: ['gout'], note: '泡发海带一小片吊鲜' },
  { name: '芹菜豆腐汤', tags: ['gout'], note: '芹菜香豆腐嫩，豆腐适量少盐' },
  { name: '番茄芹菜汤', tags: ['gout'], note: '芹菜段配番茄，清汤少盐' },
  { name: '甜玉米冬瓜汤（清煮）', tags: ['gout'], note: '玉米粒配冬瓜，清甜无肉' },
  { name: '丝瓜烩粉丝（素汤）', tags: ['gout'], note: '丝瓜出汁粉丝软，素汤' },
  { name: '莴笋黄瓜清汤', tags: ['gout', 'diabetes'], note: '两样青绿煮清汤，最后下瓜' },
  { name: '茄子炖土豆（无肉）', tags: ['gout'], note: '东北炖菜，不放肉片' },
  { name: '绿豆粉（清汤煮）', tags: ['gout'], note: '温州薯粉条，清汤煮软' },
  { name: '毛豆冬瓜汤（少量毛豆）', tags: ['gout'], note: '毛豆一小把，冬瓜打底' },
  { name: '紫菜萝卜汤（少量紫菜）', tags: ['gout'], note: '紫菜一克，萝卜丝煮软' },
  { name: '清汤素面（无肉汤底）', tags: ['gout'], note: '挂面清水煮，葱花几滴油' },
  { name: '素菜汤面（番茄底）', tags: ['gout'], note: '香菇两朵青菜打底，清汤' },
  { name: '白菜汤面', tags: ['gout'], note: '白菜煮软下面，暖胃清淡' },
  { name: '丝瓜汤面', tags: ['gout'], note: '丝瓜滑汤下面，闽南吃法' },
  { name: '菠菜汤面', tags: ['gout'], note: '菠菜先焯水，再下面条' },
  { name: '紫菜清汤面', tags: ['gout'], note: '紫菜一克提鲜，不放骨汤' },
  { name: '番茄浓汤面', tags: ['gout'], note: '番茄熬浓做底，不配肉酱' },
  { name: '蛋花烩粉条（清汤）', tags: ['gout'], note: '粉条打蛋花，无肉汤底' },
  { name: '清汤面疙瘩', tags: ['gout'], note: '小疙瘩煮清汤，配些菜丁' },
  { name: '剪刀面（清汤）', tags: ['gout'], note: '面糊现剪下锅，清汤煮食' },
  { name: '玉米面漏鱼（凉鱼）', tags: ['gout'], note: '玉米面漏成鱼，凉吃少酱' },
  { name: '荞麦宽条（清汤）', tags: ['gout', 'diabetes'], note: '荞麦低GI，清汤煮着吃' },
  { name: '荞麦馄饨（素馅）', tags: ['gout', 'diabetes'], note: '荞麦皮包菜馅，清汤煮' },
  { name: '荞麦烧饼（无糖）', tags: ['gout', 'diabetes'], note: '杂粮烙饼，无糖少油' },
  { name: '藜麦杂粮团子（无咸菜）', tags: ['gout', 'diabetes'], note: '藜麦饭捏团，夹菜不放榨菜' },
  { name: '莜面疙瘩（清汤）', tags: ['gout', 'diabetes'], note: '莜面捏疙瘩，清汤煮软' },
  { name: '燕麦面（清汤）', tags: ['gout', 'diabetes'], note: '燕麦面低GI，清汤做底' },
  { name: '玉米面汤饭', tags: ['gout'], note: '玉米碴煮稀饭，北方家常' },
  { name: '玉米面团子（菜馅）', tags: ['gout'], note: '瓜菜掺玉米面蒸，管饱' },
  { name: '贴饼子（玉米面，少油）', tags: ['gout'], note: '锅边贴烙，不炸不放糖' },
  { name: '玉米馒头', tags: ['gout'], note: '白面掺玉米面，松软微甜' },
  { name: '发面饽饽（玉米面）', tags: ['gout'], note: '酵子发面烙，暄软好消化' },
  { name: '小米馒头', tags: ['gout'], note: '小米面掺白面蒸馒头' },
  { name: '小米蒸糕（少糖）', tags: ['gout'], note: '小米面蒸糕，一点糖提味' },
  { name: '小米凝膏（无糖小碗）', tags: ['gout'], note: '小米汁凝冻，暑天小碗' },
  { name: '燕麦麸馒头', tags: ['gout', 'diabetes'], note: '麸皮纤维高，掺白面蒸' },
  { name: '青稞米饭（掺白米）', tags: ['gout', 'diabetes'], note: '青稞β葡聚糖，掺半升糖慢' },
  { name: '糜子米饭', tags: ['gout'], note: '黄米蒸饭，北方杂粮' },
  { name: '黍米饭', tags: ['gout'], note: '黏黄米蒸饭，小份就好' },
  { name: '山药馒头', tags: ['gout'], note: '山药泥和面，松软低嘌呤' },
  { name: '山药发糕', tags: ['gout'], note: '山药泥发酵蒸，蓬松' },
  { name: '山药面条', tags: ['gout'], note: '山药汁和面，清汤煮食' },
  { name: '山药小包子', tags: ['gout'], note: '山药素馅小笼，蒸制清淡' },
  { name: '土豆馒头', tags: ['gout'], note: '土豆蒸熟和面，暄软不柴' },
  { name: '土豆泥花卷', tags: ['gout'], note: '土豆泥卷进面里，松软' },
  { name: '南瓜花卷', tags: ['gout'], note: '南瓜泥揉面，天然微甜' },
  { name: '南瓜馒头', tags: ['gout'], note: '南瓜和面蒸，颜色金黄' },
  { name: '紫薯花卷', tags: ['gout'], note: '紫薯泥夹层，颜色好看' },
  { name: '红薯馒头', tags: ['gout'], note: '红薯泥掺面蒸，香甜软' },
  { name: '芋头馒头', tags: ['gout'], note: '芋头压泥和面，粉香' },
  { name: '花卷（清蒸原味）', tags: ['gout'], note: '原味花卷，别刷葱油' },
  { name: '银丝卷（少油）', tags: ['gout'], note: '细丝卷蒸透，撕着吃' },
  { name: '刀切馒头（原味）', tags: ['gout'], note: '机器刀切馒头，配料最简' },
  { name: '清汤米粉', tags: ['gout'], note: '米粉清水煮，低嘌呤打底' },
  { name: '番茄素米线', tags: ['gout'], note: '番茄做卤拌米线，无肉汤' },
  { name: '拌米粉（少油蒜汁）', tags: ['gout'], note: '过凉拌蒜汁，油放几滴' },
  { name: '清汤土豆粉', tags: ['gout'], note: '土豆粉清煮，别配麻辣' },
  { name: '凉拌土豆粉', tags: ['gout'], note: '过凉拌醋蒜，麻酱减半' },
  { name: '粉干（清汤素）', tags: ['gout'], note: '温州粉干清汤，不放肉燥' },
  { name: '蝴蝶面（清汤素）', tags: ['gout'], note: '意面清汤煮，配黄瓜丁' },
  { name: '素汤宽粉（免麻辣底）', tags: ['gout'], note: '宽粉清汤煮，不放辣油' },
  { name: '猫耳朵（素打卤）', tags: ['gout'], note: '面猫耳配番茄木耳卤' },
  { name: '麻食（清汤）', tags: ['gout'], note: '搓麻食煮清汤，配青菜' },
  { name: '搓鱼面（素炒少油）', tags: ['gout'], note: '面鱼配瓜菜快炒，少油' },
  { name: '拉条子（清汤拌）', tags: ['gout'], note: '手工面过水，清汤少油' },
  { name: '荞麦碗饦', tags: ['gout', 'diabetes'], note: '荞麦蒸碗定型，蘸蒜醋汁' },
  { name: '荞麦扒糕', tags: ['gout', 'diabetes'], note: '荞麦成糕切条，凉拌少酱' },
  { name: '西宁大酿皮（酱减半）', tags: ['gout'], note: '酿皮过凉拌，酱别多加' },
  { name: '春卷皮（自烙）', tags: ['gout'], note: '平底锅烙皮，包菜生食' },
  { name: '土豆丝卷饼（少油）', tags: ['gout'], note: '薄饼卷素丝，不放火腿' },
  { name: '荷叶饼（夹素菜）', tags: ['gout'], note: '小饼夹瓜菜，清淡管饱' },
  { name: '烩饼（素清汤）', tags: ['gout'], note: '死面饼切条，清汤烩软' },
  { name: '黄米黏糕（小块）', tags: ['gout'], note: '糯性升糖快，一小块意思' },
  { name: '藜麦发糕（少糖）', tags: ['gout', 'diabetes'], note: '藜麦米蒸糕，蓬松微甜' },
  { name: '豆面窝头（少糖）', tags: ['gout'], note: '杂豆面掺白面蒸，一小个就好' },
  { name: '麦芬（少糖无油）', tags: ['gout'], note: '全麦小蛋糕，无油少糖' },
  { name: '烙馍（白面无油）', tags: ['gout'], note: '薄烙馍卷菜，不抹油' },
  { name: '死面饼（薄）', tags: ['gout'], note: '冷水和面烙薄，卷菜吃' },
  { name: '烫面饼（少油）', tags: ['gout'], note: '烫面暄软，一层油就够' },
  { name: '奶香鸡蛋饼（低脂）', tags: ['gout'], note: '牛奶鸡蛋摊薄，少油烙' },
  { name: '全麦口袋饼', tags: ['gout', 'diabetes'], note: '鼓口袋烙饼，夹菜不抹酱' },
  { name: '米苔目（清汤）', tags: ['gout'], note: '米浆漏条，清汤煮软' },
  { name: '粄条（清汤素）', tags: ['gout'], note: '客家粄条清煮，不浇肉臊' },
  { name: '泡粑（米浆蒸，无糖）', tags: ['gout'], note: '米浆发酵蒸，一小块' },
  { name: '兴化米粉（清汤）', tags: ['gout'], note: '福建细米粉，清汤煮软' },
  { name: '濑粉（清汤素）', tags: ['gout'], note: '两广濑粉清汤，配葱蒜' },
  { name: '包谷饭（玉米掺米）', tags: ['gout'], note: '云南包谷焖饭，粗粮管饱' },
  { name: '薏米米饭（掺白米）', tags: ['gout'], note: '薏米掺米焖，嚼劲足' },
  { name: '苦荞米饭', tags: ['gout', 'diabetes'], note: '苦荞米焖饭，滇西北吃法' },
  { name: '土豆芸豆饭（豆少）', tags: ['gout'], note: '芸豆别超米量四分之一，土豆算主食' },
  { name: '发芽米焖饭（低GI）', tags: ['gout', 'diabetes'], note: '糙米发芽口感软，升糖慢' },
  { name: '燕麦花卷（原味）', tags: ['gout', 'diabetes'], note: '燕麦面擀卷，不刷咸油' },
  { name: '小米摊饼（少油）', tags: ['gout'], note: '小米面摊薄饼，烙到微焦' },
  { name: '红薯粉（清汤煮）', tags: ['gout'], note: '薯粉清煮，不配辣油' },
  { name: '芋头糕（素蒸）', tags: ['gout'], note: '芋头切糕蒸，不放腊味' },
  { name: '荞麦粑（蒸）', tags: ['gout', 'diabetes'], note: '荞麦面蒸粑，蘸蒜汁吃' },
  { name: '山药南瓜米糊（无糖）', tags: ['gout'], note: '山药南瓜同打糊，早餐一碗' },
  { name: '包谷糊糊（稀，无糖）', tags: ['gout'], note: '云南叫包谷，稀糊暖胃' },
  { name: '南瓜玉米面粥', tags: ['gout'], note: '南瓜配玉米面，金黄稠香' },
  { name: '血糯米饭（小份）', tags: ['gout'], note: '血糯软糯，升糖快吃小碗' },
  { name: '芋头米粉（清汤）', tags: ['gout'], note: '芋头块配米粉，清汤煮' },
  { name: '青菜焖饭（无油）', tags: ['gout'], note: '青菜丁焖饭，不放猪油' },
  { name: '上海素菜饭（少油）', tags: ['gout'], note: '咸菜换青菜，油点几滴' },
  { name: '冬瓜饭', tags: ['gout'], note: '冬瓜丁焖饭，清甜省水' },
  { name: '黄瓜鸡蛋盖饭', tags: ['gout'], note: '黄瓜炒蛋少油，盖半碗饭' },
  { name: '番茄素盖饭', tags: ['gout'], note: '番茄豆腐做浇，米饭半碗' },
  { name: '黄瓜蛋饭团', tags: ['gout', 'diabetes'], note: '米饭捏团夹蛋，无咸菜' },
  { name: '乌米饭（南烛叶汁）', tags: ['gout'], note: '树叶汁染黑，小碗掺白米' },
  { name: '红米饭（红糙米掺焖）', tags: ['gout', 'diabetes'], note: '红米掺白米焖，低GI粗粮' },
  { name: '线面（清汤素）', tags: ['gout'], note: '细线面清汤，易消化' },
  { name: '莜面素蒸饺', tags: ['gout', 'diabetes'], note: '莜面包菜馅蒸，蘸蒜汁' },
  { name: '玉米面饺（素馅）', tags: ['gout'], note: '玉米面包菜馅，蒸制' },
  { name: '冬瓜素蒸饺', tags: ['gout'], note: '冬瓜丝做馅，皮薄清淡' },
  { name: '西葫芦素蒸饺', tags: ['gout'], note: '西葫芦擦丝做馅，低嘌呤' },
  { name: '茴香鸡蛋饺', tags: ['gout'], note: '茴香馅配蛋碎，北方时令' },
  { name: '荠菜豆腐饺', tags: ['gout'], note: '豆腐适量，荠菜提香' },
  { name: '胡萝卜鸡蛋饺', tags: ['gout'], note: '胡萝卜擦丝配蛋，蒸制少油' },
  { name: '小馄饨（清汤素馅）', tags: ['gout'], note: '菜馅薄皮小馄饨，汤清' },
  { name: '荠菜小馄饨', tags: ['gout'], note: '荠菜馅薄皮，清汤一小碗' },
  { name: '青菜小馄饨', tags: ['gout'], note: '菜馅小馄饨，汤清少盐' },
  { name: '蒸饺（黄瓜鸡蛋素馅）', tags: ['gout'], note: '素馅蒸饺，蘸醋不放辣油' },
  { name: '菠菜素烙盒（少油）', tags: ['gout'], note: '菜馅烙盒，油刷一层' },
  { name: '弱碱性气泡水（无糖）', tags: ['gout', 'diabetes'], note: '气体水代替甜饮料，解馋' },
  { name: '冰镇青柠气泡饮', tags: ['gout'], note: '挤几滴青柠，不放糖浆' },
  { name: '鲜橙肉气泡饮（无糖）', tags: ['gout', 'diabetes'], note: '橙肉两瓣提香，别榨成汁' },
  { name: '姜汁汽水（自煮无糖）', tags: ['gout', 'diabetes'], note: '煮姜兑气泡，夏天暖胃' },
  { name: '留兰香冰水（无糖淡）', tags: ['healthy', 'gout'], note: '几片薄荷，冰镇慢喝' },
  { name: '留兰香青瓜浸泡水', tags: ['healthy', 'gout'], note: '黄瓜几片泡，全天分次' },
  { name: '洛神花水（无糖）', tags: ['gout', 'diabetes'], note: '三朵泡出红，酸得清爽' },
  { name: '菊花山楂水（无糖）', tags: ['gout', 'diabetes'], note: '菊花配山楂，酸香解腻' },
  { name: '淡竹叶水（无糖）', tags: ['gout'], note: '煮得淡淡的，多排尿' },
  { name: '白茅根煮水（无糖）', tags: ['gout'], note: '一小把煮水，清热利水' },
  { name: '玉米须陈皮水（无糖）', tags: ['gout', 'diabetes'], note: '干玉米须配陈皮一小条' },
  { name: '玉米须荷叶水（无糖）', tags: ['gout', 'diabetes'], note: '半张荷叶煮，别喝冰的' },
  { name: '冬瓜皮煮水（无糖）', tags: ['gout', 'diabetes'], note: '削下的皮别扔，煮水喝' },
  { name: '炒麦香饮（自制无糖）', tags: ['gout'], note: '小麦焙香冲泡，代替奶茶' },
  { name: '荞麦香茶（无糖烘焙）', tags: ['gout', 'diabetes'], note: '苦荞焙香，低GI又暖胃' },
  { name: '牛蒡根茶（淡，无糖）', tags: ['gout', 'diabetes'], note: '两片牛蒡煮，别放太浓' },
  { name: '菊苣根焙茶（无糖）', tags: ['gout', 'diabetes'], note: '焙香像咖啡，不含咖啡因' },
  { name: '蒲公英叶茶（淡）', tags: ['gout'], note: '嫩叶煮淡茶，利尿多饮' },
  { name: '杭白菊枸杞水（淡）', tags: ['gout'], note: '枸杞十几粒，别放糖' },
  { name: '罗汉果水（半个，无糖）', tags: ['gout', 'diabetes'], note: '半个煮甜，代糖不升糖' },
  { name: '乌梅洛神饮（无糖）', tags: ['gout', 'diabetes'], note: '自煮不放糖，酸得爽口' },
  { name: '高钙低脂鲜奶（早餐杯）', tags: ['gout'], note: '奶嘌呤低，早餐一杯' },
  { name: '舒化奶（乳糖不耐）', tags: ['gout'], note: '喝了不胀气，嘌呤照样低' },
  { name: '鲜牛奶（温热小杯）', tags: ['gout'], note: '纯奶嘌呤低，一小杯就够' },
  { name: '酪浆饮（低脂无糖）', tags: ['gout'], note: '乳清稀释喝，奶香清淡' },
  { name: '无糖乳清饮（小杯）', tags: ['gout', 'diabetes'], note: '一小杯就够，酸香顺口' },
  { name: '低脂乳（睡前一杯）', tags: ['healthy', 'gout'], note: '温热喝，睡前一小杯' },
  { name: '核桃露（无糖小杯）', tags: ['gout'], note: '两三个核桃打浆，限一小杯' },
  { name: '扁桃仁浆（自磨无糖）', tags: ['gout'], note: '七八粒打浆，坚果别贪多' },
  { name: '黑芝麻米浆（无糖小碗）', tags: ['gout'], note: '米浆打底，芝麻一小勺' },
  { name: '可可牛乳（低脂无糖）', tags: ['gout'], note: '纯可可粉，不加糖冲奶' },
  { name: '西芹汁（少量兑水）', tags: ['gout', 'diabetes'], note: '一小段就够，兑淡喝' },
  { name: '青瓜汁（自榨淡饮）', tags: ['gout'], note: '黄瓜榨淡，不放一粒糖' },
  { name: '苹果醋水（冲淡无糖）', tags: ['gout', 'diabetes'], note: '一勺醋冲大杯，别直接喝' },
  { name: '现熬米汤（无糖）', tags: ['gout'], note: '焖饭上清汤，暖胃不额外糖' },
  { name: '葛根粉糊（无糖小碗）', tags: ['gout'], note: '冲成透明糊，不放糖' },
  { name: '亚麻籽泡水（无糖）', tags: ['gout', 'diabetes'], note: '一小勺籽泡开，喝前搅一搅' },
  { name: '白开水（全天分次喝）', tags: ['healthy', 'gout'], note: '每天两三千毫升，多排尿' },
  { name: '淡矿泉水（全天备一壶）', tags: ['healthy', 'gout'], note: '别等渴了喝，随身带' },
  { name: '太阳蛋（少油煎）', tags: ['gout'], note: '不粘锅一点油，蛋黄流心' },
  { name: '荷包蛋（清煮）', tags: ['healthy', 'gout'], note: '水微沸磕蛋，比煎的清爽' },
  { name: '蛋皮摊薄（无油）', tags: ['gout'], note: '不粘锅摊薄，包菜包饭都行' },
  { name: '蛋皮卷黄瓜丝', tags: ['gout'], note: '蛋皮卷青瓜，切段摆盘' },
  { name: '芙蓉蛋（清蒸）', tags: ['healthy', 'gout'], note: '蛋液兑温水蒸，嫩得像豆腐' },
  { name: '芝士焗蛋（小份）', tags: ['gout'], note: '芝士一片封顶，高脂少量' },
  { name: '芝士蛋饼（少油）', tags: ['gout'], note: '蛋饼撒碎芝士，一小片就够' },
  { name: '全麦蛋饼（少油）', tags: ['gout', 'diabetes'], note: '全麦粉调糊摊饼，升糖慢' },
  { name: '蛋饼卷豆腐（无火腿）', tags: ['gout'], note: '豆腐适量，别夹加工肉' },
  { name: '牛奶煮蛋花（无糖）', tags: ['gout', 'diabetes'], note: '蛋花冲牛奶，嫩滑一小碗' },
  { name: '山药蛋糊（蒸软）', tags: ['gout'], note: '山药压泥拌蛋液，蒸得软' },
  { name: '芝士蔬菜蛋饼（少油）', tags: ['gout'], note: '碎芝士一小片封顶，少油煎' },
  { name: '奶香炖蛋（无糖小碗）', tags: ['gout', 'diabetes'], note: '奶加蛋蒸凝，一小碗解馋' },
  { name: '酸奶慕斯（无糖小杯）', tags: ['gout', 'diabetes'], note: '明胶凝酸奶，一小杯为准' },
  { name: '莓果酸奶冰沙（无糖）', tags: ['gout', 'diabetes'], note: '冻莓打酸奶，稠稠一小杯' },
  { name: '莓果酸奶杯（三种）', tags: ['gout', 'diabetes'], note: '三种莓铺酸奶，不另外加糖' },
  { name: '芹菜条蘸酸奶酱', tags: ['gout'], note: '酸奶调蒜盐，当酱代替沙拉酱' },
  { name: '奶酪土豆饼（少油）', tags: ['gout'], note: '土豆泥掺碎酪，煎一小块' },
  { name: '奶酪烤番茄（少量）', tags: ['gout'], note: '芝士撒一点，烤箱烤软' },
  { name: '素蛋饺（白菜馅）', tags: ['gout'], note: '蛋皮包白菜馅，不掺肉' },
  { name: '蛋包豆腐（无肉）', tags: ['gout'], note: '豆腐适量，蛋液裹着煎' },
  { name: '鸭蛋烘蛋（少油）', tags: ['gout'], note: '鸭蛋大，半个进锅就够' },
  { name: '姜汁奶冻（少糖）', tags: ['gout'], note: '姜汁撞牛奶，糖放一丁点' },
  { name: '杏仁奶冻（无糖小份）', tags: ['gout', 'diabetes'], note: '杏仁粉调奶，凝一小碗' },
  { name: '蛋皮吐司卷（无火腿）', tags: ['gout'], note: '蛋皮卷全麦条，夹黄瓜' },
  { name: '全麦蛋液吐司（煎）', tags: ['gout', 'diabetes'], note: '全麦裹蛋液，少油煎一块' },
  { name: '番茄蛋饼（少油）', tags: ['gout'], note: '番茄丁进蛋液，摊成小饼' },
  { name: '青瓜烘蛋（少油）', tags: ['gout'], note: '瓜丝挤水拌蛋，烘得嫩' },
  { name: '丝瓜烘蛋（少油）', tags: ['gout'], note: '丝瓜出水少放油，蛋香清甜' },
  { name: '苦瓜烘蛋（少油）', tags: ['gout', 'diabetes'], note: '苦瓜焯水去涩，配蛋同烘' },
  { name: '木耳烘蛋（少油）', tags: ['gout'], note: '木耳切碎进蛋，煎得脆软' },
  { name: '日式蛋卷（无糖少油）', tags: ['gout', 'diabetes'], note: '不放糖卷蛋，切段当加餐' },
  { name: '滑蛋（无奶少油）', tags: ['gout'], note: '关火推蛋，嫩滑不用奶' },
  { name: '低脂奶酪黄瓜片', tags: ['gout', 'diabetes'], note: '一片酪夹两片瓜，当加餐' },
  { name: '芝士焗口蘑（少量）', tags: ['gout'], note: '三只口蘑撒碎酪，别贪多' },
  { name: '滚水冲蛋（香油少许）', tags: ['gout'], note: '滚水冲蛋花，滴两滴香油' },
  { name: '牛奶煮玉米段（无糖）', tags: ['gout'], note: '牛奶煮玉米，不放一粒糖' },
  { name: '虎皮鸡蛋（无油炸）', tags: ['gout'], note: '先煮后煎皮，不走油锅' },
  { name: '蛋松（无油炒散）', tags: ['gout'], note: '蛋液炒散成松，拌粥吃' },
  { name: '山里红（鲜几颗）', tags: ['gout'], note: '酸口几颗，不碰山楂片' },
  { name: '油桃（一个）', tags: ['gout'], note: '洗净水分两吃，一次一个' },
  { name: '杏子（两三颗）', tags: ['gout'], note: '鲜杏两三颗，酸别多吃' },
  { name: '欧李（钙果几颗）', tags: ['gout', 'diabetes'], note: '北方钙果，酸口几颗就好' },
  { name: '越橘（野生小把）', tags: ['gout', 'diabetes'], note: '花青素高，糖低限一小把' },
  { name: '灯笼果（姑娘果）', tags: ['gout'], note: '撕皮吃七八颗，酸甜适中' },
  { name: '沙果（海棠果）', tags: ['gout'], note: '东北小果，酸得很一个够' },
  { name: '人心果（一小个）', tags: ['gout'], note: '熟软才甜，果糖偏高浅尝' },
  { name: '嘉宝果（树葡萄少量）', tags: ['gout'], note: '十颗八颗，糖分不低' },
  { name: '黄皮果（几颗）', tags: ['gout'], note: '南方时令，一两把为止' },
  { name: '余甘子（油甘几颗）', tags: ['gout'], note: '先涩后甜，嚼三颗就好' },
  { name: '水果黄瓜（生食）', tags: ['healthy', 'gout'], note: '当水果啃，脆甜无负担' },
  { name: '羊角蜜瓜（一个）', tags: ['gout'], note: '羊角蜜甜度高，一次吃半根' },
  { name: '血橙（一个）', tags: ['gout'], note: '花青素多的橙，一个为准' },
  { name: '蒲桃（几颗）', tags: ['gout'], note: '南方铃铛果，嚼几颗闻香' },
  { name: '青提（一小串）', tags: ['gout'], note: '葡萄近亲，糖高十几颗止' },
  { name: '白兰瓜（一小盘）', tags: ['gout'], note: '比哈密瓜淡，一小盘收住' },
  { name: '醋栗（红醋栗几颗）', tags: ['gout'], note: '欧李似的酸，十几颗刚好' },
  { name: '冻干草莓脆（无糖）', tags: ['gout', 'diabetes'], note: '配料表只有草莓那种' },
  { name: '山楂卷（少糖一小条）', tags: ['gout'], note: '自制减糖，一小条就行' },
  { name: '低糖果盘（三样）', tags: ['gout', 'diabetes'], note: '莓果加桃橙，拼一小盘' },
  { name: '莓果冰沙（无糖）', tags: ['gout', 'diabetes'], note: '冻莓打碎，不添一滴糖浆' },
  { name: '清炒红菜薹', tags: ['gout'], note: '南方紫薹，快炒脆甜' },
  { name: '蒜香炒小松菜', tags: ['healthy', 'gout'], note: '日式青菜，蒜片快翻' },
  { name: '清炒京水菜', tags: ['healthy', 'gout'], note: '水菜易熟，三十秒出锅' },
  { name: '凉拌穿心莲', tags: ['gout'], note: '焯水过凉，蒜醋拌开' },
  { name: '麻酱拌茄子', tags: ['gout'], note: '蒸软撕条，酱放半勺' },
  { name: '白菜帮炒木耳', tags: ['gout'], note: '帮子别扔，配木耳脆' },
  { name: '圆白菜炒粉条', tags: ['gout'], note: '包菜手撕，粉条吸味' },
  { name: '番茄炒圆白菜', tags: ['gout'], note: '茄汁裹菜，酸甜下饭' },
  { name: '西葫芦炒木耳', tags: ['gout'], note: '瓜片脆木耳弹，两点油' },
  { name: '荷兰豆炒山药', tags: ['gout'], note: '两样都脆，配色好看' },
  { name: '素炒瓜豆菌', tags: ['gout'], note: '瓜豆角菌菇各一小把，别堆满' },
  { name: '荠菜拌千张（适量）', tags: ['gout'], note: '千张一小条，荠菜提香' },
  { name: '蒸三样（南瓜山药土豆）', tags: ['gout'], note: '三样同蒸，当主食吃' },
  { name: '南瓜烧豆腐（适量）', tags: ['gout'], note: '豆腐半块，南瓜自带甜' },
  { name: '冬瓜炒木耳', tags: ['gout', 'diabetes'], note: '冬瓜易出水，一滴油不放大' },
  { name: '土豆炖冬瓜', tags: ['gout'], note: '土豆绵冬瓜软，素炖' },
  { name: '烤土豆块（带皮少油）', tags: ['gout'], note: '带皮切块，喷一点油烤' },
  { name: '清蒸苦瓜段（少油）', tags: ['gout', 'diabetes'], note: '蒸熟再淋汁，苦味变淡' },
  { name: '烤秋葵（少油）', tags: ['gout'], note: '刷薄油烤脆，比炸的清爽' },
  { name: '佛手瓜炒木耳', tags: ['gout'], note: '佛手瓜脆甜，配木耳同炒' },
  { name: '蒜蓉白苋菜', tags: ['gout'], note: '白苋菜比红的不涩，快炒' },
  { name: '凉拌马兰头', tags: ['gout'], note: '焯水挤干，拌香干丁' },
  { name: '清炒红薯梗', tags: ['gout'], note: '梗撕皮后炒，脆得像蕨菜' },
  { name: '烤西兰花（少油）', tags: ['gout'], note: '烤到焦边，比水煮香' },
  { name: '烤花菜（少油）', tags: ['gout'], note: '花菜烤黄，撒点椒粉' },
  { name: '丝瓜烩魔芋结', tags: ['gout', 'diabetes'], note: '魔芋结低能量，丝瓜出汁' },
  { name: '山药炒黄瓜', tags: ['gout'], note: '两片白两片刻绿，脆口' },
  { name: '芹菜炒荸荠', tags: ['gout'], note: '马蹄几颗，芹菜脆响' },
  { name: '西芹炒山药', tags: ['gout', 'diabetes'], note: '斜切片同炒，低GI爽口' },
  { name: '胡萝卜炒粉皮', tags: ['gout'], note: '粉皮软胡萝卜脆，一点葱' },
  { name: '白菜炒粉丝', tags: ['gout'], note: '白菜帮先下，粉丝吸汤' },
  { name: '茄子胡萝卜蒸泥', tags: ['gout'], note: '两样同蒸，捣泥淋蒜汁' },
  { name: '冬瓜炒粉丝', tags: ['gout', 'diabetes'], note: '冬瓜片配粉丝，炒得干爽' },
  { name: '清蒸节瓜（两广时令）', tags: ['gout'], note: '小冬瓜蒸软，淋少许豉油' },
  { name: '青瓜拌粉丝（蒜香）', tags: ['gout'], note: '粉丝过凉，蒜末醋汁拌' },
  { name: '素烧萝卜（少油）', tags: ['gout'], note: '萝卜焖到透明，不放肉' },
  { name: '炒双冬（冬瓜冬笋）', tags: ['gout'], note: '冬笋少量，配冬瓜同烧' },
  { name: '荷兰豆炒藕丁', tags: ['gout'], note: '两样都脆，颜色清爽' },
  { name: '烤三样菌（少油限量）', tags: ['gout'], note: '鲜菌三样共小半盘，尝味' },
  { name: '蒸鲜蘑（限量小份）', tags: ['gout'], note: '一次五六个，尝味就好' },
  { name: '凉拌猴头菇', tags: ['gout'], note: '泡发撕条蒜汁拌开，适量尝味' },
  { name: '清炒慈姑片', tags: ['gout'], note: '慈姑去苦，切片快炒' },
  { name: '素炒扁豆丝（焖透）', tags: ['gout'], note: '扁豆务必焖透，一次半碗' },
  { name: '焖豆角（素少油）', tags: ['gout'], note: '豆角焖软，不放肉末' },
  { name: '蒸萝卜缨', tags: ['gout'], note: '缨子拌面蒸，别扔菜叶' },
  { name: '素炒双脆（藕丁笋丁）', tags: ['gout'], note: '藕笋切丁同炒，脆上加脆' },
  { name: '洋葱炒土豆片', tags: ['gout'], note: '洋葱炒到透明，土豆片香' },
  { name: '素烧冬瓜（无油）', tags: ['healthy', 'gout', 'diabetes'], note: '水焖冬瓜，不放一匙油' },
  { name: '焯拌海菜花（少量）', tags: ['gout'], note: '云南湖菜，焯后淋醋' },
  { name: '烤茭白（少油）', tags: ['gout'], note: '刷薄油烤软，撒几粒盐' },
  { name: '蒸樱桃萝卜（小个）', tags: ['gout'], note: '蒸到微透，蘸生抽一点点' },
  { name: '蒜香拌莼菜', tags: ['gout'], note: '罐装要冲淡，滑口少盐' },
  { name: '清炒水芹（少油蒜香）', tags: ['gout'], note: '水芹易熟，快翻几下' },
  { name: '清蒸芥蓝（蒜汁）', tags: ['gout'], note: '蒸到翠绿，淋蒜汁少盐' },
  { name: '白灼四角豆（少量）', tags: ['gout'], note: '四角豆焯透，拌蒜少盐' },
  { name: '烤胡萝卜条（无糖）', tags: ['gout'], note: '胡萝卜切条烤甜，不裹糖' },
  { name: '蒸茼蒿（蒜汁）', tags: ['gout'], note: '蒸茼蒿拌蒜汁，清香软口' },
  { name: '清炒苤蓝丝', tags: ['gout'], note: '苤蓝切丝快炒，脆而微甜' },
  { name: '烤西葫芦片（少油）', tags: ['gout'], note: '厚片刷油烤软，撒点黑椒' },
]
