// 「今天吃什么」分片：外卖版异国深挖与烘焙饮品（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const TAKEOUT_INTL2_DISHES: FoodDish[] = [
  { name: '以色列夏苏卡（Shakshuka）', tags: ['healthy', 'gout', 'takeout'], note: '番茄辣椒炖鸡蛋，配饼蘸汁' },
  { name: '椰奶冬阴功', tags: ['takeout'], note: '加椰浆版冬阴功，酸辣柔润' },
  { name: '马沙文咖喱面包鸡', tags: ['takeout'], note: '咖喱之王配松面包，拌饭绝了' },
  { name: '红咖喱炒鲜虾', tags: ['takeout'], note: '红咖喱辣度偏高，虾鲜酱浓' },
  { name: '泰式宽粉炒肉（Pad See Ew）', tags: ['takeout'], note: '酱油炒宽粉配滑蛋，甜香' },
  { name: '泰式椰汁香茅鸡汤', tags: ['healthy', 'takeout'], note: '椰汁香茅煮鸡，撇浮油可选清汤版' },
  { name: '泰式鲜虾柚子卷', tags: ['healthy', 'takeout', 'diabetes'], note: '柚子叶包鲜虾薄荷，清甜口' },
  { name: '泰式香茅炸鲈鱼', tags: ['takeout'], note: '整鱼裹香茅炸酥脆，蘸鱼露' },
  { name: '泰式炭烧猪颈肉', tags: ['takeout'], note: '炭火慢烤切片，蘸甜辣酱' },
  { name: '泰式南姜炒蛤蜊', tags: ['takeout'], note: '南姜打抛叶爆炒，鲜辣开胃' },
  { name: '泰式香蕉煎饼', tags: ['takeout'], note: '薄脆饼裹香蕉炼乳，甜口' },
  { name: '泰式鲜芒果沙拉', tags: ['takeout'], note: '青芒果拌鱼露辣椒，酸甜辣' },
  { name: '泰式虾酱炒空心菜', tags: ['takeout'], note: '虾酱大火炒通菜，咸鲜下饭' },
  { name: '泰式香兰叶包鸡', tags: ['takeout'], note: '斑斓叶裹炸鸡块，叶香肉嫩' },
  { name: '冬阴功妈妈面', tags: ['takeout'], note: '冬阴功汤底泡方便面，网红款' },
  { name: '泰式黄咖喱大虾', tags: ['takeout'], note: '黄咖喱炖大虾，椰香浓郁' },
  { name: '泰式冰咖啡（Oliang）', tags: ['takeout'], note: '炼乳黑咖啡加冰，又甜又浓' },
  { name: '泰式柠檬清蒸鱼', tags: ['healthy', 'gout', 'takeout'], note: '柠檬蒸鱼清淡鲜，缓解期适量' },
  { name: '泰式椰汁班兰冻', tags: ['takeout'], note: '班兰叶椰汁冻糕，Q弹清甜' },
  { name: '泰式手撕鸡青木瓜沙拉', tags: ['healthy', 'takeout'], note: '鸡丝拌青木瓜，酸辣爽口' },
  { name: '泰式蟹肉滑蛋', tags: ['healthy', 'takeout'], note: '蟹肉配滑蛋，鲜到眉毛掉' },
  { name: '泰式酸辣海鲜拌', tags: ['takeout'], note: '鱼露青柠拌海鲜，泰式Yum' },
  { name: '泰式咖喱炒软壳蟹', tags: ['takeout'], note: '软壳蟹炸后翻炒咖喱，连壳吃' },
  { name: '泰式炸鸡配香茅', tags: ['takeout'], note: '香茅腌炸鸡，皮酥肉多汁' },
  { name: '粉红冻奶（泰式）', tags: ['takeout'], note: '粉色炼乳冰饮，颜值解辣' },
  { name: '泰式烤三文鱼配辣酱', tags: ['healthy', 'takeout'], note: '炭烤三文鱼，蘸泰式辣酱' },
  { name: '泰式炸猪皮', tags: ['takeout'], note: '猪皮炸蓬脆，蘸甜辣酱零嘴' },
  { name: '泰式虾饼', tags: ['takeout'], note: '手打虾饼炸弹牙，配酸梅酱' },
  { name: '泰式椰香玉米烙', tags: ['takeout'], note: '椰浆裹玉米粒煎成饼，甜脆' },
  { name: '泰式罗勒海鲜炒饭', tags: ['takeout'], note: '打抛叶炒饭，虾仁鱿鱼十足' },
  { name: '泰式椰子冰淇淋', tags: ['takeout'], note: '椰壳装冰淇淋撒椰肉，清甜' },
  { name: '泰式鸟眼椒爆鲜鱿', tags: ['takeout'], note: '鸟眼椒炒鱿鱼圈，辣得过瘾' },
  { name: '泰式三巴酱烤茄子', tags: ['healthy', 'takeout'], note: '烤茄子淋三巴酱，软糯微辣' },
  { name: '泰式花蛤煲冬阴功', tags: ['takeout'], note: '冬阴功煮花蛤，一嗦满口鲜' },
  { name: '泰式班兰叶椰浆饭', tags: ['takeout'], note: '班兰叶蒸椰浆饭，东南亚主食' },
  { name: '越南牛腩粉', tags: ['takeout'], note: '慢炖牛腩配河粉，汤浓粉滑' },
  { name: '越南三鲜河粉', tags: ['takeout'], note: '牛丸牛筋牛肉三拼，料足' },
  { name: '越南海鲜河粉', tags: ['takeout'], note: '大虾鱿鱼配河粉，汤底浓鲜' },
  { name: '越南牛肉丸河粉', tags: ['takeout'], note: '手打牛丸弹牙，汤带八角香' },
  { name: '越南扎肉法包', tags: ['takeout'], note: '法包夹越南火腿，配腌菜香菜' },
  { name: '越南烤猪颈肉法包', tags: ['takeout'], note: '焦香猪颈肉夹法包，酸甜口' },
  { name: '越南素春卷', tags: ['healthy', 'gout', 'takeout'], note: '米纸卷豆腐蔬菜，无肉豆制品适量' },
  { name: '越南炸春卷', tags: ['takeout'], note: '米纸炸至金黄酥脆，蘸鱼露' },
  { name: '越南牛肉粒捞檬', tags: ['takeout'], note: '冷檬面配炒牛肉粒，夏口' },
  { name: '越南虾饼', tags: ['takeout'], note: '米纸裹虾炸蓬，生菜包着吃' },
  { name: '越南漏奶华', tags: ['takeout'], note: '港式茶餐厅甜品，炼乳吐司少食' },
  { name: '越南滴漏咖啡', tags: ['takeout'], note: '铁滴慢滤浓咖啡，加炼乳' },
  { name: '越南鸡蛋咖啡', tags: ['takeout'], note: '打发蛋黄铺咖啡上，河内特色' },
  { name: '越南椰青咖啡', tags: ['takeout'], note: '椰青水冲咖啡，清甜顺口' },
  { name: '越南牛肉火锅', tags: ['takeout'], note: '汤底涮牛肉配香草面' },
  { name: '越南法式黄油虾', tags: ['takeout'], note: '蒜香黄油煎大虾，法越融合' },
  { name: '越南牛肉炒面（Xao Bo）', tags: ['takeout'], note: '宽面炒牛肉配豆芽，镬气足' },
  { name: '越南鸡肉捞檬', tags: ['healthy', 'takeout'], note: '鸡丝冷檬配鱼露汁，夏天感' },
  { name: '越南烤牛肉法包', tags: ['takeout'], note: '法包夹炭烤牛肉，配萝卜丝' },
  { name: '越南冰柠檬茶', tags: ['takeout'], note: '鲜柠檬捣碎加冰，酸甜解腻' },
  { name: '越南芒果西柚捞', tags: ['takeout'], note: '芒果西柚配西米椰浆，热带感' },
  { name: '越南肉丸法包', tags: ['takeout'], note: '法包夹手打肉丸，配香菜' },
  { name: '越南越式煎饼（Banh Xeo）', tags: ['takeout'], note: '姜黄米浆煎饼裹虾肉，生菜包' },
  { name: '越南顺化牛肉粉', tags: ['takeout'], note: '粗粉辣汤牛肉，顺化风味' },
  { name: '越南螺丝粉（Bun Rieu）', tags: ['takeout'], note: '蟹膏番茄汤底配螺丝粉' },
  { name: '越南牛油果奶昔', tags: ['takeout'], note: '牛油果打奶昔，浓稠顺滑' },
  { name: '越南咖啡冻牛奶', tags: ['takeout'], note: '咖啡冻倒炼乳奶，分层好看' },
  { name: '越南香茅烤排骨', tags: ['takeout'], note: '香茅腌烤排骨，焦香多汁' },
  { name: '越南牛肉炒空心菜', tags: ['takeout'], note: '牛肉片炒通菜，蒜香大火' },
  { name: '越南腰果鸡肉', tags: ['takeout'], note: '腰果滑鸡配彩椒，坚果香' },
  { name: '越南椰奶西米露', tags: ['takeout'], note: '椰浆煮西米配荸荠，小甜品' },
  { name: '越南炸鸡翅鱼露', tags: ['takeout'], note: '鱼露腌炸鸡翅，咸甜酥香' },
  { name: '蒜香馕饼（Garlic Naan）', tags: ['takeout'], note: '馕炉现烤蒜香发面饼，配咖喱蘸' },
  { name: '芝士馕饼（Paneer Naan）', tags: ['takeout'], note: '馕饼夹融化芝士，拉丝香' },
  { name: '辣味青椒馕饼', tags: ['takeout'], note: '青椒碎撒馕面烤，微辣鲜香' },
  { name: '全麦印度烤饼（Chapati）', tags: ['healthy', 'takeout', 'diabetes'], note: '全麦薄饼无油烙，配咖喱卷' },
  { name: '咖喱角（Samosa）', tags: ['takeout'], note: '三角炸饺土豆馅，蘸薄荷酱' },
  { name: '印度脆球（Pani Puri）', tags: ['takeout'], note: '空心脆球灌酸辣汁，一口爆' },
  { name: '印度香饭（羊肉）', tags: ['takeout'], note: '羊肉焖香饭，海德拉巴辣' },
  { name: '印度香饭（素菜）', tags: ['healthy', 'gout', 'takeout'], note: '低嘌呤素香饭，酥油重可选少油版' },
  { name: '印度黄油扁豆（Dal Makhani）', tags: ['takeout'], note: '黑扁豆慢炖黄油，浓滑配馕' },
  { name: '印度炸蔬菜饼（Pakora）', tags: ['takeout'], note: '蔬菜裹鹰嘴豆面糊炸，酥脆' },
  { name: '南印度米饼（Dosa）', tags: ['healthy', 'takeout', 'gout'], note: '发酵米浆煎薄脆，蘸豆酱一小勺' },
  { name: '马萨拉多莎（Masala Dosa）', tags: ['takeout'], note: '多莎卷土豆馅，配酸辣酱' },
  { name: '印度奶酪咖喱（Paneer Butter Masala）', tags: ['takeout'], note: '芝士块炖番茄酱，素食浓香' },
  { name: '印度菠菜奶酪（Palak Paneer）', tags: ['healthy', 'takeout'], note: '菠菜泥炖芝士块，绿色浓香' },
  { name: '印度烤花菜（Gobi Manchurian）', tags: ['takeout', 'gout'], note: '炸花菜裹甜辣酱，裹酱少、偶尔吃' },
  { name: '印度烤虾（Tandoori Jhinga）', tags: ['takeout'], note: '泥炉烤大虾，香料腌入味' },
  { name: '巴基斯坦手抓羊肉饭', tags: ['takeout'], note: '羊肉铺饭蒸焖，油润香料足' },
  { name: '巴基斯坦烤羊排', tags: ['takeout'], note: '孜然辣椒腌羊排，炭香浓' },
  { name: '印度酸奶拉锡（Lassi）', tags: ['healthy', 'takeout'], note: '甜lassi糖多，选咸口或无糖款' },
  { name: '芒果拉锡（Mango Lassi）', tags: ['takeout'], note: '芒果酸奶昔，甜浓解辣' },
  { name: '印度煎饼（Paratha）', tags: ['takeout'], note: '层叠酥饼烙土豆馅，配酸奶' },
  { name: '印度鹰嘴豆咖喱（Chana Masala）', tags: ['healthy', 'gout', 'takeout', 'diabetes'], note: '鹰嘴豆炖番茄辣酱，适量' },
  { name: '印度土豆花菜咖喱（Aloo Gobi）', tags: ['healthy', 'gout', 'takeout'], note: '土豆花菜姜黄炖，素食暖' },
  { name: '印度香辣虾（Prawn Balchao）', tags: ['takeout'], note: '果醋番茄焖大虾，酸辣风' },
  { name: '印度塔利套餐（Thali）', tags: ['takeout'], note: '一盘多种咖喱配饼饭，尝遍' },
  { name: '印度烤芝士（Paneer Tikka）', tags: ['takeout'], note: '芝士块腌烤焦香，配彩椒' },
  { name: '印度甜球（Gulab Jamun）', tags: ['takeout'], note: '奶球泡玫瑰糖浆，外酥内软' },
  { name: '印度米布丁（Kheer）', tags: ['takeout'], note: '牛奶慢炖米粒坚果，甜暖' },
  { name: '印度香料饭（Jeera Rice）', tags: ['takeout'], note: '孜然粒炒饭，配咖喱底' },
  { name: '印度炒蛋（Egg Bhurji）', tags: ['healthy', 'takeout', 'gout'], note: '香料碎炒蛋，配面包快手' },
  { name: '印度烤蘑菇（Mushroom Tandoori）', tags: ['healthy', 'takeout'], note: '蘑菇腌香料泥炉烤，素也香' },
  { name: '印度罗望子汤（Rasam）', tags: ['healthy', 'gout', 'takeout'], note: '罗望子酸汤微辣，认准素汤底、豆适量' },
  { name: '印度椰奶鱼汤（Kerala Fish Curry）', tags: ['takeout'], note: '椰浆炖鱼，南印酸香不腻' },
  { name: '巴基斯坦烤肉串（Seekh Kebab）', tags: ['takeout'], note: '碎肉裹铁签炭烤，孜然浓' },
  { name: '巴基斯坦炖牛肉（Nihari）', tags: ['takeout'], note: '骨汤慢炖牛肉糊，早午餐' },
  { name: '印度脆米饼（Papadum）', tags: ['takeout'], note: '薄脆饼配咖喱开胃小食' },
  { name: '法拉费', tags: ['takeout'], note: '鹰嘴豆炸丸夹饼，外脆内绿（豆适量）' },
  { name: '法拉费卷饼', tags: ['takeout'], note: '炸豆丸裹皮塔饼配蔬菜酱' },
  { name: '法拉费沙拉碗', tags: ['healthy', 'takeout'], note: '碗底仍是炸豆丸，轻食别多要' },
  { name: '沙威玛牛肉卷', tags: ['takeout'], note: '薄切烤牛肉夹饼，中东快餐' },
  { name: '法拉费拼盘（含鹰嘴豆泥）', tags: ['takeout', 'diabetes'], note: '炸豆丸配鹰嘴豆泥和腌菜' },
  { name: '烤茄子泥（Baba Ghanoush）', tags: ['healthy', 'takeout'], note: '炭烤茄子打泥配芝麻酱，蘸饼' },
  { name: '黎巴嫩塔布勒沙拉', tags: ['healthy', 'takeout', 'gout'], note: '碎麦配大量香草番茄，清爽' },
  { name: '法图什沙拉（Fattoush）', tags: ['healthy', 'takeout', 'gout'], note: '烤面包碎拌蔬菜，酸香' },
  { name: '皮塔饼（中东口袋饼）', tags: ['takeout'], note: '鼓起来的中东烤饼，夹肉蘸酱' },
  { name: '中东烤肉饼（Kibbeh）', tags: ['takeout'], note: '碎肉拌小麦炸成橄榄形' },
  { name: '烤哈罗米芝士（Halloumi）', tags: ['takeout'], note: '煎烤芝士片，外焦里韧不化' },
  { name: '穆哈玛拉酱（Muhammara）', tags: ['takeout'], note: '烤红椒核桃酱，微辣浓香' },
  { name: '中东扁豆饼（Adasi）', tags: ['healthy', 'gout', 'takeout', 'diabetes'], note: '扁豆慢炖配橄榄油，适量' },
  { name: '土耳其咖啡', tags: ['takeout'], note: '细粉煮浓咖啡带渣，杯底占卜' },
  { name: '土耳其烤鱼（Levrek）', tags: ['healthy', 'takeout'], note: '海鲈鱼整条炭烤，配柠檬' },
  { name: '土耳其扁豆沙拉', tags: ['healthy', 'takeout', 'diabetes'], note: '绿扁豆拌红椒香芹，酸爽' },
  { name: '希腊穆萨卡（Moussaka）', tags: ['takeout'], note: '茄层肉末白酱焗，希腊国菜' },
  { name: '希腊烤肉卷（Gyros）', tags: ['takeout'], note: '旋转烤肉卷饼配薯条' },
  { name: '菲达奶酪烤蔬菜', tags: ['healthy', 'takeout', 'gout'], note: '蔬菜为主菲达少量，咸香高脂' },
  { name: '西班牙海鲜饭（Paella）', tags: ['takeout'], note: '藏红花饭铺虾贝，锅底脆饭' },
  { name: '意大利烤蔬菜拼盘', tags: ['healthy', 'takeout', 'gout'], note: '彩椒茄子西葫芦烤，橄榄油' },
  { name: '意大利番茄布拉塔', tags: ['healthy', 'takeout'], note: '布拉塔奶油芯高脂，配番茄少量' },
  { name: '黎巴嫩蒜酱虾', tags: ['takeout'], note: '蒜香腌烤虾串，中东炭火' },
  { name: '中东烤蔬菜串', tags: ['healthy', 'gout', 'takeout'], note: '西葫芦彩椒洋葱串烤，素口' },
  { name: '伊朗藏红花饭（Tadchin）', tags: ['takeout'], note: '藏红花锅巴饭，金黄酥底' },
  { name: '摩洛哥塔吉锅（Tagine）', tags: ['takeout'], note: '陶罐焖鸡肉杏干，甜咸融合' },
  { name: '突尼斯鱼籽酱沙拉', tags: ['healthy', 'takeout'], note: '金枪鱼橄榄番茄拌，北非口' },
  { name: '地中海烤三文鱼柳', tags: ['healthy', 'diabetes', 'takeout'], note: '柠檬橄榄油烤，低脂高蛋白' },
  { name: '西班牙冷番茄汤（Gazpacho）', tags: ['healthy', 'gout', 'takeout'], note: '生番茄打冷汤，夏天开胃' },
  { name: '西西里炖蔬菜（Caponata）', tags: ['healthy', 'takeout', 'gout'], note: '茄子甜酸炖，传统过油可选少油' },
  { name: '土耳其曼提（Manti 小馄饨）', tags: ['takeout'], note: '小馄饨配酸奶辣椒油' },
  { name: '中东碎肉串（Kufta）', tags: ['takeout'], note: '孜然腌碎羊肉串，炭火香' },
  { name: '黎巴嫩扁豆饭（Mujadara）', tags: ['healthy', 'gout', 'takeout', 'diabetes'], note: '扁豆米饭炸洋葱香，扁豆适量吃' },
  { name: '盐烤银杏', tags: ['takeout'], note: '锡纸烤白果撒盐，下酒小食' },
  { name: '烤鸡肉棒（Tsukune）', tags: ['takeout'], note: '手打鸡肉丸子串烤，蘸蛋液' },
  { name: '明太子烤土豆', tags: ['takeout'], note: '土豆泥铺明太子焗烤，咸鲜' },
  { name: '居酒屋炸薯饼', tags: ['takeout'], note: '土豆泥炸成饼，外酥内绵' },
  { name: '烤秋葵（日式）', tags: ['healthy', 'takeout', 'diabetes'], note: '整条秋葵炭烤撒酱油，黏滑' },
  { name: '唐扬鸡块', tags: ['takeout'], note: '日式炸鸡块挤美乃滋，外酥' },
  { name: '日式炸茄子', tags: ['takeout'], note: '茄子裹面衣炸，蘸柴鱼汁' },
  { name: '日式炸牡蛎', tags: ['takeout'], note: '生蚝裹面包糠炸，爆浆鲜' },
  { name: '相扑锅（外带）', tags: ['takeout'], note: '大锅炖肉丸蔬菜，味噌汤底' },
  { name: '日式味噌炖牛筋锅', tags: ['takeout'], note: '味噌炖牛筋萝卜，软糯胶质感' },
  { name: '日式猪肉生姜烧锅', tags: ['takeout'], note: '姜汁煎猪肉配豆芽锅' },
  { name: '奶油炖菜（日式柯克）', tags: ['takeout'], note: '白酱炖鸡肉蔬菜，北海道风' },
  { name: '韩式鱼饼年糕串', tags: ['takeout'], note: '鱼饼串配辣酱年糕，街头感' },
  { name: '韩式海鲜葱饼', tags: ['takeout'], note: '大葱铺面糊煎饼配海鲜' },
  { name: '韩式海苔牛肉饭卷', tags: ['takeout'], note: '海苔卷米饭牛肉条，便当感' },
  { name: '韩式年糕鱼饼汤', tags: ['takeout'], note: '鳀鱼汤煮年糕鱼饼，简餐' },
  { name: '韩式辣拌冷面', tags: ['takeout'], note: '荞麦冷面拌辣醋汁，夏天感' },
  { name: '韩式水冷面', tags: ['takeout'], note: '冷牛肉汤底配冰荞麦面' },
  { name: '韩式包肉五花', tags: ['takeout'], note: '厚切五花烤焦，包生菜蒜片' },
  { name: '韩式芝士排骨', tags: ['takeout'], note: '辣酱排骨裹融化芝士，拉丝' },
  { name: '韩式辣炖排骨', tags: ['takeout'], note: '土豆萝卜辣炖排骨，下饭' },
  { name: '韩式蒸土豆饺', tags: ['takeout'], note: '土豆淀粉包皮，馅粉条肉' },
  { name: '韩式米酒（玛格丽）', tags: ['takeout'], note: '微甜浊米酒，配炸鸡绝搭' },
  { name: '日式出汁卷蛋', tags: ['healthy', 'gout', 'takeout'], note: '柴鱼出汁嘌呤偏高，卷蛋少蘸汁' },
  { name: '日式土豆炖肉（肉じゃが）', tags: ['takeout'], note: '土豆萝卜炖肉片，家常味' },
  { name: '日式筑前炖鸡', tags: ['takeout'], note: '炸鸡肉裹甜醋汁，北九州' },
  { name: '铁板饺子（日式）', tags: ['takeout'], note: '平底锅煎饺子，脆底多汁' },
  { name: '日式味噌田乐茄子', tags: ['takeout'], note: '烤茄子涂味噌酱，甜咸香' },
  { name: '日式亲子锅', tags: ['takeout'], note: '鸡肉洋葱鸡蛋煮，甜酱油汁' },
  { name: '韩式参鸡汤面', tags: ['takeout'], note: '参鸡汤底配细面，滋补暖' },
  { name: '韩式烤鸡腿肉串', tags: ['takeout'], note: '酱油糖腌鸡腿串，炭焦香' },
  { name: '日式梅子茶泡饭', tags: ['healthy', 'gout', 'takeout'], note: '咸梅半颗提味，血压高别常吃' },
  { name: '俱乐部三明治', tags: ['takeout'], note: '三层吐司夹火鸡培根蔬菜' },
  { name: '帕尼尼（番茄马苏里拉）', tags: ['takeout'], note: '压烤面包夹番茄芝士，热乎' },
  { name: '帕尼尼（烤鸡青酱）', tags: ['healthy', 'takeout'], note: '烤鸡胸配青酱薄抹，青酱高脂' },
  { name: '古巴三明治', tags: ['takeout'], note: '火腿烤猪肉酸黄瓜压脆饼' },
  { name: '法式火腿黄油三明治', tags: ['takeout'], note: '法棍夹生火腿黄油，极简' },
  { name: '牛肉费城三明治', tags: ['takeout'], note: '铁板牛肉配融化芝士洋葱' },
  { name: '龙虾卷（新英格兰）', tags: ['takeout'], note: '热面包夹龙虾肉拌美乃滋' },
  { name: '纽约贝果配烟熏三文鱼', tags: ['takeout'], note: '贝果切半铺奶油芝士三文鱼' },
  { name: '全麦贝果配牛油果', tags: ['healthy', 'takeout'], note: '贝果抹牛油果泥撒胡椒' },
  { name: '碱水贝果', tags: ['takeout'], note: '碱水面包体有嚼劲，麦香浓' },
  { name: '北欧豆蔻肉桂卷', tags: ['takeout'], note: '豆蔻面团卷肉桂馅，松软' },
  { name: '芝加哥热狗', tags: ['takeout'], note: '全料热狗加芥末酸黄瓜小番茄' },
  { name: '纽约经典热狗', tags: ['takeout'], note: '蒸面包夹烤肠淋酸菜芥末' },
  { name: '韩式热狗（芝士棒）', tags: ['takeout'], note: '热狗裹面糊炸撒糖粉' },
  { name: '芝士热狗棒', tags: ['takeout'], note: '香肠裹芝士拉丝，外脆里滑' },
  { name: '德式香肠面包', tags: ['takeout'], note: '软面包夹烤香肠配芥末' },
  { name: '奶酪拼盘', tags: ['takeout'], note: '多种芝士配饼干葡萄，下酒' },
  { name: '新英格兰蛤蜊浓汤', tags: ['takeout'], note: '奶油蛤蜊浓汤配苏打饼' },
  { name: '意式蔬菜汤（Minestrone）', tags: ['healthy', 'gout', 'takeout'], note: '杂蔬煮汤豆半勺，确认素汤底' },
  { name: '西班牙冷坚果汤', tags: ['healthy', 'takeout'], note: '杏仁葡萄冷打汤，安达卢西亚' },
  { name: '英式烤豆吐司', tags: ['takeout'], note: '茄汁焗豆铺烤吐司，早餐感' },
  { name: '法式咸派（Quiche Lorraine）', tags: ['takeout'], note: '酥皮蛋奶培根派，配沙拉' },
  { name: '墨西哥大卷饼（Burrito）', tags: ['takeout'], note: '大饼卷饭豆鸡肉酱，扎实' },
  { name: '墨西哥玉米片配莎莎酱', tags: ['takeout'], note: '脆玉米片蘸番茄莎莎，零嘴' },
  { name: '意式烤面包（Bruschetta）', tags: ['healthy', 'takeout', 'gout'], note: '烤法棍铺番茄罗勒橄榄油' },
  { name: '美式烤肉肋排', tags: ['takeout'], note: 'BBQ酱慢烤猪肋排，脱骨' },
  { name: '德式烤猪肘', tags: ['takeout'], note: '整只猪肘烤脆皮，配酸菜' },
  { name: '加拿大肉汁芝士薯条（Poutine）', tags: ['takeout'], note: '魁北克名物，奶酪粒浇肉汁酱' },
  { name: '法式薄饼（Crepe 甜）', tags: ['takeout'], note: '极薄饼卷香蕉巧克力酱' },
  { name: '法式咸薄饼（Galettes）', tags: ['takeout', 'healthy'], note: '荞麦薄饼铺蛋火腿，午餐感' },
  { name: '美式花生酱香蕉吐司', tags: ['takeout'], note: '花生酱铺香蕉片夹吐司' },
  { name: '开放式牛油果蛋吐司', tags: ['healthy', 'takeout', 'gout'], note: '吐司铺牛油果水波蛋，早午餐' },
  { name: '西班牙土豆烘蛋（Tortilla）', tags: ['takeout', 'gout'], note: '厚蛋饼炖土豆洋葱，冷吃也香' },
  { name: '杏仁可颂', tags: ['takeout'], note: '可颂铺杏仁酱烤，焦香酥脆' },
  { name: '火腿芝士可颂', tags: ['takeout'], note: '可颂夹火腿芝士焗，正餐感' },
  { name: '抹茶可颂', tags: ['takeout'], note: '可颂撒抹茶粉配白巧克力' },
  { name: '焦糖可颂', tags: ['takeout'], note: '可颂表面裹脆焦糖壳，微苦甜' },
  { name: '扁可颂（Pain au Raisin）', tags: ['takeout'], note: '葡萄干卷起酥烤，松软多层' },
  { name: '蔓越莓贝果', tags: ['takeout'], note: '面团揉入蔓越莓干，微酸有嚼' },
  { name: '黑芝麻贝果', tags: ['takeout'], note: '黑芝麻面团贝果，坚果香' },
  { name: '洋葱贝果', tags: ['takeout'], note: '表面裹炸洋葱碎，咸甜口' },
  { name: '蓝莓芝士贝果', tags: ['takeout'], note: '贝果配蓝莓奶油芝士馅' },
  { name: '红酒无花果司康', tags: ['takeout'], note: '红酒浸无花果入司康，湿润' },
  { name: '燕麦提子曲奇', tags: ['takeout'], note: '燕麦片拌提子烤，酥软有嚼' },
  { name: '黑麦杂粮面包', tags: ['healthy', 'diabetes', 'takeout'], note: '杂粮籽铺满，低GI扎实' },
  { name: '迷迭香佛卡夏', tags: ['takeout'], note: '橄榄油烤饼按压孔洞，香草' },
  { name: '肉桂吐司', tags: ['takeout'], note: '厚切吐司裹蛋液煎撒肉桂' },
  { name: '蜂蜜厚多士', tags: ['takeout'], note: '厚吐司炸至金黄淋蜂蜜' },
  { name: '日式生吐司', tags: ['takeout'], note: '奶香绵软手撕吐司，空口吃' },
  { name: '抹茶泡芙', tags: ['takeout'], note: '泡芙壳挤抹茶卡仕达，微苦甜' },
  { name: '芒果泡芙', tags: ['takeout'], note: '鲜芒果卡仕达馅，轻盈夏味' },
  { name: '肉桂苹果丹麦', tags: ['takeout'], note: '丹麦酥铺苹果肉桂，层酥' },
  { name: '杏仁丹麦', tags: ['takeout'], note: '酥皮铺杏仁片蛋奶酱，焦香' },
  { name: '核桃布朗尼', tags: ['takeout'], note: '巧克力蛋糕塞核桃，绵密湿' },
  { name: '海盐布朗尼', tags: ['takeout'], note: '布朗尼撒海盐，咸甜对比' },
  { name: '开心果马卡龙', tags: ['takeout'], note: '绿白壳夹开心果酱，坚果甜' },
  { name: '百香果马卡龙', tags: ['takeout'], note: '壳里灌百香果凝，酸香' },
  { name: '柠檬塔', tags: ['takeout'], note: '酥脆塔壳填柠檬凝，酸爽' },
  { name: '巧克力熔岩蛋糕', tags: ['takeout'], note: '外壳切开流心巧克力，浓郁' },
  { name: '巴斯克烤芝士', tags: ['takeout'], note: '焦黑表面，内里半熟浓滑' },
  { name: '歌剧院杏子挞', tags: ['takeout'], note: '杏仁奶油铺杏子，法式挞' },
  { name: '法式焦糖炖蛋（Crème Brûlée）', tags: ['takeout'], note: '蛋奶烤布丁扣焦糖，滑嫩' },
  { name: '葡式蛋挞', tags: ['takeout'], note: '千层酥皮焦糖面，蛋香浓' },
  { name: '榴莲酥', tags: ['takeout'], note: '酥皮包榴莲馅烤，重口爱' },
  { name: '蝴蝶酥', tags: ['takeout'], note: '起酥双面撒糖烤，焦糖脆' },
  { name: '布里欧修', tags: ['takeout'], note: '高黄油面包体，松软蛋奶香' },
  { name: '全麦肉桂葡萄卷', tags: ['takeout'], note: '全麦面团裹肉桂葡萄干，暖香' },
  { name: '碱水面包（Pretzel）', tags: ['takeout'], note: '扭结面包碱水香，粗盐粒' },
  { name: '全麦坚果棒', tags: ['healthy', 'takeout', 'diabetes'], note: '全麦粉裹核桃蔓越莓，有嚼' },
  { name: '杂粮软欧', tags: ['healthy', 'takeout', 'diabetes'], note: '杂粮内馅软欧包，低糖饱腹' },
  { name: '抹茶红豆软欧', tags: ['takeout'], note: '抹茶面团裹红豆，日式欧包' },
  { name: '脏脏咖啡（Dirty）', tags: ['takeout'], note: '冰牛奶浇热浓缩，分层浓烈' },
  { name: '冰博克拿铁', tags: ['takeout'], note: '提纯奶做拿铁，更浓更甜' },
  { name: '燕麦奶脏脏咖', tags: ['takeout'], note: '燕麦奶底浇热浓缩，麦香浓' },
  { name: '燕麦奶美式', tags: ['healthy', 'takeout', 'diabetes'], note: '燕麦奶配黑咖啡，低脂顺口' },
  { name: '燕麦奶摩卡', tags: ['takeout'], note: '燕麦奶加巧克力酱浓缩，甜' },
  { name: '生酪拿铁', tags: ['takeout'], note: '芝士酪加拿铁，咸香浓稠' },
  { name: '桂花拿铁', tags: ['takeout'], note: '桂花糖浆配拿铁，秋天感' },
  { name: '海盐焦糖拿铁', tags: ['takeout'], note: '焦糖海盐调味拿铁，微咸' },
  { name: '黑糖姜拿铁', tags: ['takeout'], note: '黑糖姜汁冲咖啡，暖身浓香' },
  { name: '冷萃咖啡', tags: ['healthy', 'diabetes', 'takeout'], note: '低温慢萃黑咖啡，不苦顺口' },
  { name: '冰滴咖啡', tags: ['takeout'], note: '一滴一滴滤8小时，醇柔' },
  { name: '手冲单品咖啡', tags: ['healthy', 'diabetes', 'takeout'], note: '单一产地手冲，果酸花香' },
  { name: '气泡美式', tags: ['takeout'], note: '苏打水加浓缩柠檬，气泡咖' },
  { name: '气泡水（原味）', tags: ['healthy', 'diabetes', 'takeout'], note: '无糖气泡水，打嗝解腻' },
  { name: '接骨木气泡水', tags: ['takeout'], note: '接骨木花风味气泡，微甜' },
  { name: '西柚气泡水', tags: ['healthy', 'takeout', 'diabetes'], note: '西柚果粒加气泡水，服药者慎柚' },
  { name: '乌龙梅子酒', tags: ['takeout'], note: '乌龙茶底梅子酒，度数低' },
  { name: '青梅酒', tags: ['takeout'], note: '青梅泡烧酒，酸甜微醺' },
  { name: '柚子酒', tags: ['takeout'], note: '高知柚子酒配冰，清甜果香' },
  { name: '百香果酒', tags: ['takeout'], note: '百香果利口酒，酸甜热带' },
  { name: '荔枝气泡酒', tags: ['takeout'], note: '荔枝汁加气泡，低度甜水' },
  { name: '桂花米酒', tags: ['takeout'], note: '糯米酒飘桂花，甜暖微醺' },
  { name: '无糖抹茶鲜奶', tags: ['healthy', 'diabetes', 'takeout'], note: '纯抹茶配鲜奶，不另外加糖' },
  { name: '玄米茶拿铁', tags: ['takeout'], note: '炒米香混奶茶，日式谷香' },
  { name: '茉莉花茶拿铁', tags: ['takeout'], note: '茉莉茶汤配鲜奶，花香' },
  { name: '鸭屎香柠檬茶', tags: ['takeout'], note: '单丛茶手打柠檬，潮汕特色' },
  { name: '大红袍奶茶', tags: ['takeout'], note: '岩茶底奶茶，焙火回甘' },
  { name: '茉莉绿茶鲜奶', tags: ['takeout'], note: '茉莉绿茶配奶，清爽不腻' },
  { name: '黑糖姜汁奶茶', tags: ['takeout'], note: '黑糖姜底冲奶茶，冬暖胃' },
  { name: '椰香西米奶茶', tags: ['takeout'], note: '椰浆西米配红茶底，甜品感' },
  { name: '玫瑰红茶拿铁', tags: ['takeout'], note: '玫瑰花茶底配奶，浪漫香' },
  { name: '桃桃乌龙冰饮', tags: ['takeout'], note: '白桃果粒配乌龙，清甜夏' },
  { name: '百香果养乐多', tags: ['takeout'], note: '百香果配养乐多，酸甜冰爽' },
  { name: '椰青美式', tags: ['takeout'], note: '鲜椰青水兑浓缩，清甜咖' },
  { name: '陈皮气泡美式', tags: ['takeout'], note: '陈皮糖浆气泡水配浓缩，微苦回甘' },
]
