// 「今天吃什么」分片：外卖版中餐（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const TAKEOUT_CN_DISHES: FoodDish[] = [
  { name: '麻辣烫', tags: ['healthy', 'takeout'], note: '汤煮版选清汤底，麻酱辣油另放少要' },
  { name: '卤肉饭', tags: ['takeout'], note: '卤肉加蛋配青菜，浇汁白米饭，台湾古早味' },
  { name: '清蒸石斑鱼', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '粤菜清蒸天花板，鱼鲜嫩低脂（中嘌呤缓解期少量）' },
  { name: '蒜蓉蒸扇贝', tags: ['healthy', 'takeout'], note: '海鲜蒜香蒸，痛风急性期避开' },
  { name: '盐水鸭', tags: ['healthy', 'takeout'], note: '南京桂花鸭皮白肉嫩，少盐版更清爽' },
  { name: '黑米粥', tags: ['healthy', 'gout', 'takeout'], note: '外卖默认加糖，控糖同样选无糖' },
  { name: '大拌菜', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '生菜紫甘蓝拌酸甜汁，清爽解腻' },
  { name: '照烧鸡腿饭', tags: ['takeout'], note: '甜酱油煎鸡腿铺饭，酱汁含糖油控量' },
  { name: '卤蛋', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '五香卤蛋当零食，蛋白管够（卤汁咸，钠控量）' },
  { name: '发面饼', tags: ['gout', 'takeout'], note: '发面好消化，烙制少油' },
  { name: '素鸡（卤汁）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '豆制品卤制切片，素食蛋白（痛风适量）' },
  { name: '素什锦', tags: ['healthy', 'gout', 'takeout'], note: '十种素菜常含菌豆，豆制品适量' },
  { name: '回锅肉', tags: ['takeout'], note: '川菜之王，肥而不腻下饭狠' },
  { name: '水煮肉片', tags: ['takeout'], note: '麻辣鲜烫，油大别喝汤' },
  { name: '辣子鸡', tags: ['takeout'], note: '辣椒里找鸡丁，越嚼越香' },
  { name: '干煸四季豆', tags: ['takeout'], note: '干香微辣，少油版更清爽' },
  { name: '夫妻肺片', tags: ['takeout'], note: '红油牛肉杂拌凉菜，前菜硬货（嘌呤偏高）' },
  { name: '毛血旺', tags: ['takeout'], note: '重油重辣大杂烩，解馋（痛风避开）' },
  { name: '钵钵鸡', tags: ['takeout'], note: '冷泡串串，藤椒清爽味' },
  { name: '甜水面', tags: ['takeout'], note: '粗面条甜辣酱，成都味道' },
  { name: '伤心凉粉', tags: ['takeout'], note: '安岳客家豌豆凉粉，辣得过瘾' },
  { name: '老妈蹄花', tags: ['takeout'], note: '芸豆炖猪蹄软烂，嘌呤高适量' },
  { name: '灯影牛肉', tags: ['takeout'], note: '薄如纸酥脆，达州名吃' },
  { name: '自贡冷吃兔', tags: ['takeout'], note: '麻辣干香，兔肉越嚼越上头' },
  { name: '酸菜肥肠', tags: ['takeout'], note: '酸香解腻卤肠爆炒，嘌呤高适量' },
  { name: '蒜泥白肉', tags: ['takeout'], note: '薄切五花肉拌蒜泥酱油' },
  { name: '粉蒸肉', tags: ['takeout'], note: '米粉裹肉蒸，软糯咸香' },
  { name: '烧白', tags: ['takeout'], note: '梅菜扣肉四川叫法，肥香' },
  { name: '炝炒莲白', tags: ['takeout'], note: '手撕圆白菜快炒，爽脆微辣' },
  { name: '酸菜豆花鱼', tags: ['takeout'], note: '豆花嫩鱼鲜，酸汤开胃（痛风避开鱼汤）' },
  { name: '藤椒鸡', tags: ['takeout'], note: '青花椒麻香，鸡肉嫩滑' },
  { name: '来凤鱼', tags: ['takeout'], note: '重庆璧山名菜，麻辣鲜鱼片（痛风避开）' },
  { name: '泉水鸡', tags: ['takeout'], note: '南山泉水鸡，麻辣带甜' },
  { name: '临江鳝丝', tags: ['takeout'], note: '黄鳝丝爆炒，乐山非遗名菜（嘌呤高）' },
  { name: '蜜汁叉烧', tags: ['takeout'], note: '焦香甜润，广式烧腊经典' },
  { name: '脆皮烧肉', tags: ['takeout'], note: '五花烧肉皮脆肉香，蘸白糖' },
  { name: '豉汁蒸排骨', tags: ['takeout'], note: '早茶经典，豆豉香排骨嫩' },
  { name: '啫啫鸡煲', tags: ['takeout'], note: '砂锅生啫，焦香扑鼻（嘌呤偏高适量）' },
  { name: '老火靓汤', tags: ['takeout'], note: '广式煲汤慢炖数小时（痛风少喝浓汤）' },
  { name: '白灼生蚝', tags: ['healthy', 'diabetes', 'takeout'], note: '鲜甜多汁，蒜蓉酱油（痛风避开）' },
  { name: '客家酿豆腐', tags: ['takeout'], note: '豆腐酿肉煎焖，客家风味' },
  { name: '梅菜扣肉', tags: ['takeout'], note: '梅菜吸油，五花肉软烂（适量）' },
  { name: '避风塘炒蟹', tags: ['takeout'], note: '蒜香面包糠裹蟹，痛风避开' },
  { name: '煎酿三宝', tags: ['takeout'], note: '酿茄子青椒豆腐，港式街头（适量）' },
  { name: '潮汕卤鹅', tags: ['takeout'], note: '卤水鹅肉香，蘸蒜醋汁（适量）' },
  { name: '煲仔莲藕汤', tags: ['takeout'], note: '粉糯莲藕煲老火，清热（痛风适量）' },
  { name: '客家梅子肉', tags: ['takeout'], note: '酸甜梅子酱裹肉，开胃下饭' },
  { name: '豉油皇炒面', tags: ['takeout'], note: '生抽炒粗面配豆芽，镬气足' },
  { name: '剁椒鱼头', tags: ['takeout'], note: '蒸鱼头铺满剁椒，辣得鲜（痛风避开鱼汤）' },
  { name: '辣椒炒肉', tags: ['takeout'], note: '湖南家常第一菜，螺丝椒炒五花' },
  { name: '毛氏红烧肉', tags: ['takeout'], note: '无糖版红烧肉，肥瘦相间入口化' },
  { name: '口味虾', tags: ['takeout'], note: '长沙紫苏味小龙虾，异于麻辣版（痛风避开）' },
  { name: '腊味合蒸', tags: ['takeout'], note: '腊肉腊鱼腊鸭同蒸，湘味浓（嘌呤偏高）' },
  { name: '紫苏炒田螺', tags: ['takeout'], note: '夏日夜市标配，紫苏去腥（痛风避开）' },
  { name: '永州血鸭', tags: ['takeout'], note: '鸭血裹鸭肉香辣，永州名菜（嘌呤高）' },
  { name: '小炒黄牛肉', tags: ['takeout'], note: '湘菜馆必点，嫩牛肉尖椒爆炒' },
  { name: '擂辣椒皮蛋', tags: ['takeout'], note: '虎皮辣椒擂皮蛋，下饭开胃' },
  { name: '农家小炒肉', tags: ['takeout'], note: '瘦肉辣椒干煸，比回锅肉清爽' },
  { name: '糖醋排骨', tags: ['takeout'], note: '全国馆子通用甜口排骨，酸甜焦香' },
  { name: '常德牛肉粉', tags: ['takeout'], note: '红烧牛肉粉，湖南米粉代表' },
  { name: '东安子鸡', tags: ['takeout'], note: '酸辣鸡块嫩滑，永州东安名菜' },
  { name: '湘西外婆菜', tags: ['takeout'], note: '酸菜炒肉末配饭，湘西风味' },
  { name: '酱椒鱼头', tags: ['takeout'], note: '酱椒蒸鱼头，比剁椒更咸鲜（痛风避开）' },
  { name: '攸县香干炒肉', tags: ['takeout'], note: '攸县豆干炒肉，家常下饭（豆制品适量）' },
  { name: '衡阳土鸡煲', tags: ['takeout'], note: '衡阳砂锅酱香土鸡，区别于汽锅鸡原汁（痛风适量）' },
  { name: '糖醋鲤鱼', tags: ['takeout'], note: '济南名菜外酥里嫩浇糖醋汁' },
  { name: '九转大肠', tags: ['takeout'], note: '酸甜苦辣咸五味肠，济南硬菜（嘌呤高）' },
  { name: '葱烧海参', tags: ['takeout'], note: '鲁菜天花板，海参葱香浓郁（痛风适量）' },
  { name: '油爆双脆', tags: ['takeout'], note: '鸡胗猪肚仁现爆，多为鲁菜馆套餐' },
  { name: '把子肉', tags: ['takeout'], note: '酱油炖五花肉配饭，济南/徐州都有' },
  { name: '锅塌豆腐', tags: ['takeout'], note: '鸡蛋裹豆腐煎塌，鲁菜家常' },
  { name: '四喜丸子', tags: ['takeout'], note: '大肉丸红烧，也叫狮子头（适量）' },
  { name: '拔丝地瓜', tags: ['takeout'], note: '拉糖丝甜地瓜，趁热吃（高糖）' },
  { name: '辣炒花蛤', tags: ['takeout'], note: '胶东夜市必点，干辣贝肉（痛风避开）' },
  { name: '海鲜疙瘩汤', tags: ['takeout'], note: '青岛虾蛤煮面疙瘩（痛风避开）' },
  { name: '德州扒鸡', tags: ['takeout'], note: '骨酥肉烂五香鸡，鲁西名产' },
  { name: '红烧带鱼', tags: ['takeout'], note: '带鱼红烧浓香，山东称渤海刀（痛风避开鱼）' },
  { name: '松鼠鳜鱼', tags: ['takeout'], note: '苏帮刀工花刀鱼，糖醋酥脆（痛风适量）' },
  { name: '大煮干丝', tags: ['healthy', 'diabetes', 'takeout'], note: '淮扬豆腐干切丝高汤煮，鲜而不油' },
  { name: '无锡酱排骨', tags: ['takeout'], note: '甜口酱骨头，肉酥脱骨（控糖少喝汁）' },
  { name: '蟹粉小笼', tags: ['takeout'], note: '蟹黄汤包鲜到眉毛掉（嘌呤高适量）' },
  { name: '三套鸭', tags: ['takeout'], note: '鸭套鸽套鸡，淮扬功夫汤（痛风适量）' },
  { name: '碧螺虾仁', tags: ['takeout'], note: '龙井虾仁姊妹篇，茶香配虾（痛风适量）' },
  { name: '文思豆腐', tags: ['diabetes', 'takeout'], note: '刀工豆腐丝如发，清汤淮扬' },
  { name: '无锡小笼包', tags: ['takeout'], note: '甜口汤包皮薄汁多，趁热小口' },
  { name: '南京烤鸭', tags: ['takeout'], note: '金陵片皮鸭，卤汁甜香' },
  { name: '藏书羊肉', tags: ['takeout'], note: '苏州白切羊肉，冬天暖身（痛风适量）' },
  { name: '西湖醋鱼', tags: ['takeout'], note: '酸甜草鱼杭帮名菜（痛风避开鱼汤）' },
  { name: '东坡肉', tags: ['takeout'], note: '慢火红烧五花肉，入口即化' },
  { name: '叫化鸡', tags: ['takeout'], note: '荷叶泥烤整鸡，撕开鲜香' },
  { name: '龙井虾仁', tags: ['takeout'], note: '茶香配河虾仁，清淡精致（痛风适量）' },
  { name: '干炸响铃', tags: ['takeout'], note: '豆腐皮卷笋末炸脆，杭帮下酒小食' },
  { name: '宋嫂鱼羹', tags: ['takeout'], note: '酸辣鱼茸羹浓稠，杭城古早味（痛风适量）' },
  { name: '雪菜大黄鱼', tags: ['takeout'], note: '宁波雪菜焖黄鱼，咸鲜透骨（痛风避开）' },
  { name: '金华火腿冬瓜煲', tags: ['takeout'], note: '火腿炖冬瓜提鲜，浙味浓汤（痛风适量）' },
  { name: '宁波汤圆', tags: ['takeout'], note: '猪油芝麻馅甜糯，小心烫芯' },
  { name: '温州鱼丸', tags: ['takeout'], note: '不规则手打鱼丸，清汤鲜甜（痛风适量）' },
  { name: '缙云烧饼', tags: ['takeout'], note: '梅干菜五花肉馅贴炉烤饼，浙江名小吃' },
  { name: '衢州三头一掌', tags: ['takeout'], note: '兔头鸭头鱼头加鸭掌卤，衢州重辣' },
  { name: '佛跳墙', tags: ['takeout'], note: '鲍参翅盅慢煨，闽菜至尊（痛风避开）' },
  { name: '海蛎煎', tags: ['takeout'], note: '厦门蚵仔煎蛋，蘸甜辣酱（痛风避开）' },
  { name: '姜母鸭', tags: ['takeout'], note: '老姜麻油焖鸭肉，冬日暖身（痛风适量）' },
  { name: '福州鱼丸', tags: ['takeout'], note: '包心大鱼丸Q弹，鳗鱼做皮（痛风适量）' },
  { name: '沙县扁肉', tags: ['takeout'], note: '皮薄馅弹小馄饨，清汤鲜甜' },
  { name: '泉州卤面', tags: ['takeout'], note: '泉州重卤汁浇面线，异于莆田海鲜卤' },
  { name: '同安封肉', tags: ['takeout'], note: '大块的肉用布包蒸烂，厦门古早（适量）' },
  { name: '生滚鱼片粥', tags: ['takeout'], note: '广式粥铺鲜鱼片烫滚粥底，清淡暖（痛风适量）' },
  { name: '莆田卤面', tags: ['takeout'], note: '海鲜浇头粗面线，莆田宴席面（痛风适量）' },
  { name: '臭鳜鱼', tags: ['takeout'], note: '腌鲜鳜鱼红烧，钠与嘌呤更高（痛风避开）' },
  { name: '毛豆腐', tags: ['takeout'], note: '发酵长毛豆腐煎，蘸辣酱（豆制品适量）' },
  { name: '胡适一品锅', tags: ['takeout'], note: '绩溪多层炖锅，徽州宴席大菜（嘌呤偏高）' },
  { name: '徽州刀板香', tags: ['takeout'], note: '腌猪肉铺木板蒸，咸香解馋' },
  { name: '问政山笋', tags: ['takeout'], note: '歙县冬笋蒸火腿，鲜掉眉毛（痛风适量）' },
  { name: '李鸿章杂烩', tags: ['takeout'], note: '合肥十几种食材烩一锅（嘌呤偏高）' },
  { name: '无为板鸭', tags: ['takeout'], note: '芜湖熏板鸭骨架酥，卤香透骨' },
  { name: '符离集烧鸡', tags: ['takeout'], note: '宿州名烧鸡，骨酥肉烂五香' },
  { name: '三河米饺', tags: ['takeout'], note: '庐江油炸饺子外皮酥脆，馅鲜（适量）' },
  { name: '格拉条', tags: ['takeout'], note: '阜阳粗面条拌辣椒酱，皖北特色' },
  { name: '梅菜肉饼饭', tags: ['takeout'], note: '广式蒸肉饼配梅菜，咸香下饭' },
  { name: '豉汁排骨饭', tags: ['takeout'], note: '蒸排骨配米饭，豆豉咸香' },
  { name: '滑蛋牛肉饭', tags: ['takeout'], note: '港式滑蛋半熟浇饭，嫩滑鲜香' },
  { name: '咖喱牛腩饭', tags: ['takeout'], note: '港式咖喱炖牛腩，浓郁拌饭' },
  { name: '黑椒牛柳饭', tags: ['takeout'], note: '黑椒汁裹牛柳条，铁板香气' },
  { name: '回锅肉盖饭', tags: ['takeout'], note: '川味回锅肉盖饭，酱汁拌饭绝' },
  { name: '酸豆角肉末饭', tags: ['takeout'], note: '酸辣豆角炒肉末，米饭杀手' },
  { name: '腊味煲仔饭', tags: ['takeout'], note: '腊肠腊肉铺饭焦底，淋酱油（适量）' },
  { name: '滑鸡煲仔饭', tags: ['takeout'], note: '生鸡铺饭慢煲，锅巴蘸汁香' },
  { name: '牛肉煲仔饭', tags: ['takeout'], note: '鲜切牛肉粒配煲仔，焦香（适量）' },
  { name: '木桶饭', tags: ['takeout'], note: '木桶蒸饭配炒菜，江西快餐代表' },
  { name: '排骨饭', tags: ['takeout'], note: '清炖排骨汤饭，客家经典' },
  { name: '黄焖排骨饭', tags: ['takeout'], note: '酱焖排骨浓汁泡饭，下饭神器' },
  { name: '香菇滑鸡饭', tags: ['takeout'], note: '香菇焖鸡蒸饭，滑嫩咸鲜' },
  { name: '铁板鸡排饭', tags: ['takeout'], note: '铁板上现煎鸡排配饭，滋滋响' },
  { name: '蒜香排骨饭', tags: ['takeout'], note: '蒜香焗排骨配米饭，广式风味' },
  { name: '台式三杯鸡饭', tags: ['takeout'], note: '一杯麻油一杯酒一杯酱，台式焖鸡' },
  { name: '打卤面', tags: ['takeout'], note: '北方勾芡卤子浇面，配蒜更香' },
  { name: '牛肉板面', tags: ['takeout'], note: '安徽太和板面，宽面辣卤入味' },
  { name: '淮南牛肉汤面', tags: ['takeout'], note: '千张粉丝配牛肉汤，早餐来碗（痛风适量）' },
  { name: '襄阳牛肉面', tags: ['takeout'], note: '碱水面配牛油辣汤，过早标配（痛风适量）' },
  { name: '武汉牛杂面', tags: ['takeout'], note: '卤牛杂浇碱面，武汉过早硬货（嘌呤偏高）' },
  { name: '宜昌凉虾', tags: ['takeout'], note: '米浆漏成虾状配糖水，宜昌消暑甜品' },
  { name: '湖南米粉（长沙扁粉/常德圆粉）', tags: ['takeout'], note: '扁粉圆粉配肉丝码子，湖南早餐魂' },
  { name: '衡阳鱼粉', tags: ['takeout'], note: '鲜鱼煮粉，衡阳名吃（痛风避开鱼）' },
  { name: '郴州鱼粉', tags: ['takeout'], note: '鱼汤浓粉嫩滑，湘南名小吃（痛风适量）' },
  { name: '干捞螺蛳粉', tags: ['takeout'], note: '螺蛳粉无汤版，干拌卤水香' },
  { name: '南宁老友粉', tags: ['takeout'], note: '酸笋豆豉爆炒煮粉，老友味冲' },
  { name: '北海海鲜粉', tags: ['takeout'], note: '沙虫虾贝煮粉，鲜掉眉毛（痛风避开）' },
  { name: '湛江白切粉', tags: ['takeout'], note: '薄切白猪杂配粉，蘸酱油（痛风适量）' },
  { name: '昆明小锅米线', tags: ['takeout'], note: '单锅现煮米线，肉酱酸菜鲜' },
  { name: '曲靖蒸饵丝', tags: ['takeout'], note: '蒸饵丝拌甜酱花生碎，曲靖早点' },
  { name: '遵义羊肉粉', tags: ['takeout'], note: '贵州羊肉米粉，糊辣椒油香（痛风适量）' },
  { name: '花溪牛肉粉', tags: ['takeout'], note: '贵阳清汤牛肉粉，汤清肉烂（痛风适量）' },
  { name: '凯里酸汤粉', tags: ['takeout'], note: '黔东南红酸汤煮粉，酸辣开胃' },
  { name: '重庆豌杂面', tags: ['takeout'], note: '豌杂小面耙豌豆配肉酱，干拌' },
  { name: '勾魂面', tags: ['takeout'], note: '自贡干拌宽面，脆臊花生芝麻香' },
  { name: '牛肉面（红烧）', tags: ['takeout'], note: '红烧牛肉大块面，全国连锁经典（适量）' },
  { name: '酸菜肉丝面', tags: ['takeout'], note: '四川酸菜肉丝煮面，酸香开胃' },
  { name: '肥肠面', tags: ['takeout'], note: '卤肥肠浇面，重口爱好者（嘌呤高）' },
  { name: '河南烩面', tags: ['takeout'], note: '羊肉汤扯宽面，河南名吃（痛风适量）' },
  { name: '陕西biangbiang面', tags: ['takeout'], note: '裤带宽面扯面，油泼辣子香' },
  { name: '岐山臊子面', tags: ['takeout'], note: '酸辣肉臊浇面，陕西宝鸡古法' },
  { name: '兰州炒刀削', tags: ['takeout'], note: '刀削面配羊肉臊子爆炒，非炒饭' },
  { name: '麻酱凉面', tags: ['takeout'], note: '夏日冰镇凉面配芝麻酱，爽口' },
  { name: '四川凉面', tags: ['takeout'], note: '麻辣红油细凉面，配菜码丰富' },
  { name: '过水凉面', tags: ['takeout'], note: '筋面过水拌酱，夏日爽口' },
  { name: '虾子面', tags: ['takeout'], note: '湖南虾子酱捞面，鲜香小辣（痛风适量）' },
  { name: '三鲜面', tags: ['takeout'], note: '肉丝虾仁鸡蛋面，家常清汤（痛风适量）' },
  { name: '三鲜水饺', tags: ['takeout'], note: '猪肉虾仁韭菜馅，北方年夜饭（痛风适量）' },
  { name: '鲅鱼水饺', tags: ['takeout'], note: '胶东鱼肉大馅饺子，鲜到爆（痛风避开鱼）' },
  { name: '猪肉大葱饺', tags: ['takeout'], note: '经典肉馅水饺，蘸醋蒜开吃' },
  { name: '韭菜鸡蛋饺', tags: ['healthy', 'takeout'], note: '韭菜鸡蛋香菇素馅饺，薄皮大馅清爽' },
  { name: '羊肉胡萝卜饺', tags: ['takeout'], note: '西北风味饺子，羊肉馅多汁（痛风适量）' },
  { name: '酸菜猪肉饺', tags: ['takeout'], note: '东北酸菜配猪肉馅，酸香解腻' },
  { name: '老麻抄手', tags: ['takeout'], note: '重庆抄手麻到嘴唇抖，红油香' },
  { name: '清汤抄手', tags: ['healthy', 'takeout'], note: '川味小馄饨清汤，皮薄馅鲜' },
  { name: '虾仁云吞', tags: ['takeout'], note: '广式大云吞整颗虾仁（痛风适量）' },
  { name: '猪肉白菜饺', tags: ['takeout'], note: '最家常饺子馅，皮薄一咬就破' },
  { name: '狗不理包子', tags: ['takeout'], note: '天津名包，十八褶肉馅（适量）' },
  { name: '扬州大包', tags: ['takeout'], note: '三丁包蟹黄包，淮扬早茶（适量）' },
  { name: '破酥包', tags: ['takeout'], note: '云南层酥包子，松软掉渣' },
  { name: '肉末饼', tags: ['takeout'], note: '发面饼裹肉馅烤脆，北方早点' },
  { name: '公安锅盔', tags: ['takeout'], note: '湖北荆州贴炉大饼，芝麻焦香' },
  { name: '胡辣汤（逍遥镇）', tags: ['takeout'], note: '河南早餐灵魂，胡椒辣冲开窍' },
  { name: '豆腐脑（姜糖水）', tags: ['takeout'], note: '南方甜豆花配姜糖水，嫩滑清甜' },
  { name: '小米南瓜粥', tags: ['healthy', 'gout', 'takeout'], note: '养胃早餐粥，金黄浓稠好消化' },
  { name: '皮蛋鸡粥', tags: ['takeout'], note: '粤式鸡丝粥底绵滑，配油条' },
  { name: '生滚牛肉粥', tags: ['takeout'], note: '广式鲜牛肉烫粥底，滑嫩鲜（痛风适量）' },
  { name: '红豆豆浆', tags: ['diabetes', 'takeout'], note: '选无糖款，配油条需另计主食量' },
  { name: '烧饼夹鸡蛋', tags: ['takeout'], note: '现烤烧饼夹荷包蛋，街头标配' },
  { name: '菜团子', tags: ['healthy', 'diabetes', 'takeout'], note: '玉米面裹青菜蒸团，低卡粗粮' },
  { name: '云片糕', tags: ['takeout'], note: '层层薄糕入口即化，苏式点心' },
  { name: '桃酥', tags: ['takeout'], note: '酥脆掉渣老式点心，配茶正好' },
  { name: '麻酱烧饼', tags: ['takeout'], note: '层层麻酱烙饼烤脆，北方早点' },
  { name: '牛肉馅饼', tags: ['takeout'], note: '皮薄馅大汁多馅饼，小心烫嘴' },
  { name: '鸡蛋饼（加火腿）', tags: ['takeout'], note: '早餐加料鸡蛋饼，卷一切' },
  { name: '烤茄子（蒜蓉）', tags: ['diabetes', 'takeout'], note: '整条茄子铺蒜蓉烤软，吸汁入味' },
  { name: '烤韭菜', tags: ['takeout'], note: '一把韭菜刷油烤，烧烤摊素食担当' },
  { name: '烤馒头片', tags: ['gout', 'takeout'], note: '刷腐乳薄薄一层，偶尔解馋' },
  { name: '烤鱿鱼', tags: ['takeout'], note: '铁板鱿鱼刷辣酱（痛风避开海鲜）' },
  { name: '烤生蚝（蒜蓉）', tags: ['takeout'], note: '整只生蚝铺蒜蓉烤（痛风避开）' },
  { name: '十三香小龙虾', tags: ['takeout'], note: '香料卤煮小龙虾，夜宵顶流（痛风避开）' },
  { name: '冰镇小龙虾', tags: ['takeout'], note: '熟醉冰镇龙虾，酒香清甜（痛风避开）' },
  { name: '椒盐皮皮虾', tags: ['takeout'], note: '濑尿虾椒盐炸香，壳脆肉鲜（痛风避开）' },
  { name: '锡纸花甲粉', tags: ['takeout'], note: '锡纸蒜蓉花甲粉，鲜汁泡面（痛风避开贝类）' },
  { name: '炒钉螺', tags: ['takeout'], note: '酱爆钉螺嗦半天，夏夜配啤酒（痛风避开）' },
  { name: '卤味烧烤拼盘', tags: ['takeout'], note: '先卤后烤肉香四溢，重口快乐（痛风适量）' },
  { name: '烤面筋', tags: ['takeout'], note: '螺旋面筋刷辣酱烤，嚼劲十足' },
  { name: '烤玉米', tags: ['gout', 'takeout'], note: '整根玉米刷酱炭烤，甜香解饿' },
  { name: '干锅牛蛙', tags: ['takeout'], note: '干锅蛙肉麻辣焦香（嘌呤偏高适量）' },
  { name: '绝味鸭脖', tags: ['takeout'], note: '连锁卤味，追剧辣脖（嘌呤偏高）' },
  { name: '周黑鸭', tags: ['takeout'], note: '武汉甜辣鸭货，真空锁鲜' },
  { name: '卤猪蹄', tags: ['takeout'], note: '酱油卤猪蹄胶质厚，下酒（嘌呤高适量）' },
  { name: '卤牛肉', tags: ['diabetes', 'takeout'], note: '五香卤牛腱切片，冷盘硬货（适量）' },
  { name: '口水鸭', tags: ['takeout'], note: '麻辣红油浇鸭片，川味凉菜' },
  { name: '卤鸡爪', tags: ['takeout'], note: '虎皮凤爪卤到脱骨，追剧零食' },
  { name: '酱板鸭', tags: ['takeout'], note: '常德风干酱鸭，越嚼越香（嘌呤偏高）' },
  { name: '卤肥肠', tags: ['takeout'], note: '老汤卤肥肠，重口爱好者（嘌呤高）' },
  { name: '豆干（卤味）', tags: ['diabetes', 'takeout'], note: '卤水豆干有嚼劲，下酒小菜（豆制品适量）' },
  { name: '卤藕片', tags: ['diabetes', 'takeout'], note: '卤水藕片脆爽，素食卤味担当' },
  { name: '猪头肉（酱卤）', tags: ['takeout'], note: '六合猪头肉卤香切片，下酒（嘌呤偏高）' },
  { name: '熏酱拼盘', tags: ['takeout'], note: '东北熏酱肘花拼盘，蘸蒜酱吃（嘌呤偏高）' },
  { name: '凉拌猪耳', tags: ['takeout'], note: '卤猪耳切丝拌香菜，脆骨感（嘌呤高）' },
  { name: '泡椒凤爪', tags: ['takeout'], note: '酸辣泡椒凤爪，开胃小零食' },
  { name: '川北凉粉', tags: ['diabetes', 'gout', 'takeout'], note: '豌豆凉粉红油，广元名小吃' },
  { name: '凉糕', tags: ['takeout'], note: '四川米凉糕蘸红糖，夏天甜品' },
  { name: '冰镇酸梅汤', tags: ['takeout'], note: '乌梅山楂熬冷饮，解腻消暑' },
  { name: '口水鸡（红油）', tags: ['takeout'], note: '藤椒红油浇鸡片，麻辣鲜香' },
  { name: '棒棒鸡', tags: ['takeout'], note: '四川麻酱拌鸡丝，甜辣交融' },
  { name: '蒜泥茄子', tags: ['healthy', 'diabetes', 'takeout'], note: '蒸茄子撕条拌蒜汁，夏日凉菜' },
  { name: '老醋花生', tags: ['takeout'], note: '醋汁拌炸花生米，下酒小菜' },
  { name: '糖蒜', tags: ['gout', 'takeout'], note: '糖渍品半头尝味，配涮肉解腻' },
  { name: '皮蛋拌黄瓜', tags: ['gout', 'takeout'], note: '夏天凉菜，皮蛋黄瓜拍一拍（适量）' },
  { name: '酸辣白菜', tags: ['diabetes', 'takeout'], note: '酸辣白菜快炒，低卡开胃（痛风适量）' },
  { name: '锅包肉', tags: ['takeout'], note: '东北酸甜大肉片，炸壳裹汁脆' },
  { name: '地三鲜', tags: ['takeout'], note: '茄子土豆青椒炒，东北素菜天花板' },
  { name: '小鸡炖蘑菇', tags: ['takeout'], note: '东北炖菜经典，榛蘑炖鸡（痛风适量）' },
  { name: '猪肉炖粉条', tags: ['takeout'], note: '五花肉炖粉条白菜，冬天一碗（适量）' },
  { name: '铁锅炖大鹅', tags: ['takeout'], note: '铁锅慢炖大鹅，贴饼子吸汁（嘌呤偏高）' },
  { name: '东北大拉皮', tags: ['takeout'], note: '麻酱拉皮拌蔬菜丝，东北凉菜' },
  { name: '杀猪菜', tags: ['takeout'], note: '酸菜血肠白肉一锅，东北年俗（嘌呤高）' },
  { name: '得莫利炖鱼', tags: ['takeout'], note: '东北铁锅炖活鱼，豆腐粉条入味（痛风避开鱼）' },
  { name: '哈尔滨红肠', tags: ['takeout'], note: '果木熏香，切片下酒' },
  { name: '炮仗面', tags: ['takeout'], note: '青海炮仗面切段爆炒，西北特色' },
  { name: '羊肉小揪面', tags: ['takeout'], note: '宁夏羊肉搓面揪面片，汤浓肉烂（痛风适量）' },
  { name: '新疆椒麻鸡', tags: ['diabetes', 'takeout'], note: '椒麻撕鸡凉拌，麻到嘴唇颤' },
  { name: '酸汤水饺', tags: ['takeout'], note: '西北酸汤泡饺子，酸辣开新吃法' },
  { name: '洋芋擦擦', tags: ['takeout'], note: '陕西土豆丝蒸后炒，西北粗粮菜' },
  { name: '甘肃酿皮', tags: ['takeout'], note: '兰州酿皮配麻酱醋，酸辣滑口' },
  { name: '天水麻辣烫', tags: ['takeout'], note: '甘肃辣子香而不辣，洋芋丸子吸汁' },
  { name: '汽锅鸡', tags: ['takeout'], note: '云南蒸汽炖鸡，汤鲜原汁（痛风适量）' },
  { name: '大救驾', tags: ['takeout'], note: '腾冲炒饵块，酸汤配菜云南味' },
  { name: '菌子火锅', tags: ['takeout'], note: '野生菌汤锅，缓解期适量、发作期避开' },
  { name: '宣威小炒肉', tags: ['takeout'], note: '云腿炒肉辣香，云南下饭菜' },
  { name: '傣味菠萝饭', tags: ['takeout'], note: '菠萝壳蒸糯米饭，酸甜云南傣味' },
  { name: '酸汤鱼（贵州）', tags: ['takeout'], note: '毛辣果酸汤煮鱼，凯里名菜（痛风避开鱼汤）' },
  { name: '丝娃娃', tags: ['takeout'], note: '贵阳薄饼卷素菜浇酸辣汁，DIY乐趣' },
  { name: '恋爱豆腐果', tags: ['takeout'], note: '贵阳烤豆腐塞折耳根，街头名小吃（豆制品适量）' },
  { name: '雷家豆腐圆子', tags: ['takeout'], note: '贵阳炸豆腐圆配蘸水，外酥里嫩（豆制品适量）' },
  { name: '竹筒饭', tags: ['takeout'], note: '竹筒蒸糯米饭带竹香，云南傣家味' },
  { name: '景颇手撕鸡', tags: ['takeout'], note: '云南手撕鸡配腌菜，酸辣清爽' },
  { name: '丽江鸡豆凉粉', tags: ['takeout'], note: '丽江鸡豆粉煎脆，蘸辣椒面（痛风适量）' },
  { name: '海南文昌鸡', tags: ['takeout'], note: '白切配鸡油饭，海南四大名菜' },
  { name: '海南抱罗粉', tags: ['takeout'], note: '粗米粉腌后浇卤汁，文昌名粉' },
  { name: '嘉积鸭', tags: ['takeout'], note: '白切嘉积鸭蘸姜蒜汁，海南名菜' },
  { name: '椰子饭', tags: ['takeout'], note: '椰青蒸糯米，海南清甜主食' },
  { name: '广西柠檬鸭', tags: ['takeout'], note: '南宁酸柠檬焖鸭，酸香解腻（嘌呤偏高）' },
  { name: '老友面', tags: ['takeout'], note: '老友粉同味型的面版，豆豉酸笋干捞' },
  { name: '阳朔啤酒鱼', tags: ['takeout'], note: '漓江鱼焖啤酒，桂林名菜（痛风避开）' },
  { name: '武汉豆皮', tags: ['takeout'], note: '三鲜豆皮蛋米煎脆，武汉过早' },
  { name: '面窝', tags: ['takeout'], note: '米浆炸成圈，武汉早餐（偶尔吃）' },
  { name: '糊汤粉', tags: ['takeout'], note: '鲜鱼糊煮米粉，武汉过早（痛风避开鱼）' },
  { name: '排骨藕汤', tags: ['takeout'], note: '湖北洪湖藕炖排骨，粉糯浓汤（痛风适量）' },
  { name: '潜江油焖大虾', tags: ['takeout'], note: '小龙虾油焖做法，鲜辣浓香（痛风避开）' },
  { name: '南京鸭血粉丝汤', tags: ['takeout'], note: '鸭血鸭肠粉丝浇老鸭汤，金陵名吃（嘌呤偏高）' },
  { name: '镇江锅盖面', tags: ['takeout'], note: '小锅煮面配长鱼腰花，镇江味（痛风适量）' },
  { name: '砂锅土豆粉', tags: ['takeout'], note: '砂锅慢煮土豆粉，配菜自选' },
  { name: '砂锅米线', tags: ['takeout'], note: '小砂锅煮米线，肥汁重口汤少喝（痛风适量）' },
  { name: '鸡公煲', tags: ['takeout'], note: '重庆鸡公煲浓汁焖鸡，加配菜（嘌呤偏高）' },
  { name: '牛蛙煲', tags: ['takeout'], note: '紫苏焖牛蛙，啫啫香气（嘌呤偏高适量）' },
  { name: '牛腩煲', tags: ['takeout'], note: '柱侯酱焖牛腩煲，萝卜吸味（适量）' },
  { name: '羊肉煲', tags: ['takeout'], note: '蘸腐乳酱汁焖羊肉，冬天暖身（痛风适量）' },
  { name: '猪肚鸡', tags: ['takeout'], note: '白胡椒猪肚包鸡，浓汤痛风慎喝' },
  { name: '肥肠鸡', tags: ['takeout'], note: '肥肠配土鸡干锅，重口快乐（嘌呤高）' },
  { name: '牛骨煲', tags: ['takeout'], note: '大块牛骨焖煲，吸髓啃肉（痛风适量）' },
  { name: '麻辣小龙虾面', tags: ['takeout'], note: '龙虾汁拌面配虾球，重口鲜（痛风避开）' },
  { name: '花胶鸡汤', tags: ['takeout'], note: '胶原蛋白煲鸡汤，滋补（痛风适量）' },
  { name: '椰子鸡火锅', tags: ['takeout'], note: '椰青锅底涮鸡肉，清甜不上火（痛风适量）' },
  { name: '香煎素牛排', tags: ['takeout'], note: '植物蛋白素排，素食外卖新选' },
  { name: '素锅贴', tags: ['healthy', 'takeout'], note: '少油煎、沥油再吃' },
  { name: '干锅茶树菇', tags: ['takeout'], note: '干锅茶树菇配青红椒，咸鲜下饭（痛风适量）' },
  { name: '斋菜煲', tags: ['healthy', 'takeout'], note: '煲仔版素什锦，闽南过年斋菜' },
  { name: '素鸭', tags: ['takeout'], note: '豆腐皮卷馅料煎，上海素菜（豆制品适量）' },
  { name: '蒜烧杏鲍菇', tags: ['healthy', 'takeout'], note: '整根杏鲍菇蒜汁焖，肉感素食' },
  { name: '铁板素三鲜', tags: ['healthy', 'takeout'], note: '铁板豆腐木耳笋片，低脂（痛风适量）' },
  { name: '扬州炒饭', tags: ['takeout'], note: '蛋粒火腿青豆炒饭，镬气足（适量）' },
  { name: '干锅花菜', tags: ['takeout'], note: '干锅花菜配五花肉，焦香下饭可选盖饭' },
  { name: '蒜苔炒肉丝饭', tags: ['takeout'], note: '快餐三件套：蒜苔肉丝+饭+汤' },
  { name: '土豆烧牛肉饭', tags: ['takeout'], note: '红烧土豆牛肉焖饭，肉烂汁浓（适量）' },
  { name: '小炒肉盖饭', tags: ['takeout'], note: '青椒肉片盖饭，湘菜快餐标配' },
  { name: '酸辣粉（重庆）', tags: ['takeout'], note: '红薯粉酸辣汤，加花生榨菜' },
  { name: '烤脑花', tags: ['takeout'], note: '锡纸烤脑花麻辣嫩滑（嘌呤高，痛风避开）' },
  { name: '牛杂煲', tags: ['takeout'], note: '广式柱侯牛杂煲，萝卜吸汁（嘌呤高）' },
  { name: '牛腩粉', tags: ['takeout'], note: '清汤牛腩河粉，港式粉面（痛风适量）' },
  { name: '猪肚面', tags: ['takeout'], note: '白胡椒猪肚面线，暖胃福建味（痛风适量）' },
  { name: '炸蛋螺蛳粉', tags: ['takeout'], note: '螺蛳粉加料款，虎皮炸蛋吸汁更香' },
  { name: '芝士焗土豆粉', tags: ['takeout'], note: '土豆粉铺芝士焗烤，拉丝奶香' },
  { name: '热卤拼盘', tags: ['takeout'], note: '现捞热卤荤拼，区别于冷卤鸭脖' },
  { name: '炒饼（圆白菜）', tags: ['gout', 'takeout'], note: '北方炒饼丝配鸡蛋圆白菜，快手主食' },
  { name: '炒年糕', tags: ['takeout'], note: '韩式辣酱炒年糕条，甜辣软糯' },
  { name: '炒方便面', tags: ['takeout'], note: '方便面配鸡蛋火腿炒干，街头夜宵' },
  { name: '牛柳意面', tags: ['takeout'], note: '黑椒牛柳炒意面，中西结合' },
  { name: '番茄牛腩面', tags: ['takeout'], note: '浓番茄汤炖牛腩配面（适量）' },
  { name: '葱香花卷', tags: ['gout', 'takeout'], note: '发面花卷配葱，早餐面食' },
  { name: '红糖糍粑', tags: ['takeout'], note: '糯米糍粑淋红糖黄豆粉，甜品' },
  { name: '鸡蛋仔（可选巧克力夹心）', tags: ['takeout'], note: '港式街头鸡蛋仔，外脆里嫩' },
  { name: '车仔面', tags: ['takeout'], note: '港式车仔面配咖喱鱼蛋，自选配料' },
  { name: '咖喱鱼蛋', tags: ['takeout'], note: '港式街头咖喱鱼蛋（痛风适量）' },
]
