// 「今天吃什么」分片：外卖版异国与甜品饮品（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const TAKEOUT_INTL_DISHES: FoodDish[] = [
  { name: '茶碗蒸', tags: ['healthy', 'diabetes', 'takeout'], note: '日式蒸蛋藏鲜料，滑嫩温和' },
  { name: '凯撒沙拉', tags: ['healthy', 'takeout'], note: '面包干帕玛森，凯撒酱减半更清爽' },
  { name: '希腊沙拉', tags: ['healthy', 'diabetes', 'takeout'], note: '番茄黄瓜橄榄，淋油醋汁' },
  { name: '牛油果吐司', tags: ['healthy', 'takeout'], note: '捣牛油果抹吐司，撒黑胡椒' },
  { name: '鸡肉凯撒卷', tags: ['healthy', 'takeout'], note: '凯撒酱减半，多点蔬菜' },
  { name: '味噌汤', tags: ['healthy', 'gout', 'takeout'], note: '豆酱汤暖胃，缓解期适量（钠高少量）' },
  { name: '亲子丼', tags: ['takeout'], note: '鸡肉滑蛋甜口汁，酱汁含糖控糖注意' },
  { name: '参鸡汤', tags: ['healthy', 'takeout'], note: '童子鸡塞糯米炖整只，去皮去油' },
  { name: '大酱汤', tags: ['healthy', 'gout', 'takeout'], note: '豆酱煮豆腐西葫芦，认准素汤底' },
  { name: '烤五花肉', tags: ['takeout'], note: '孜然炭香，撸串快乐（痛风适量）' },
  { name: '馕坑烤肉', tags: ['takeout'], note: '馕坑焖烤大块肉，油香（适量）' },
  { name: '三文鱼刺身', tags: ['healthy', 'diabetes', 'takeout'], note: '优质脂肪高蛋白，痛风者适量' },
  { name: '金枪鱼刺身', tags: ['healthy', 'diabetes', 'takeout'], note: '赤身低脂，酱油芥末一蘸' },
  { name: '鲷鱼刺身', tags: ['healthy', 'gout', 'takeout'], note: '白身鱼嘌呤中等，缓解期少量' },
  { name: '刺身拼盘', tags: ['takeout'], note: '多种生鱼片，鲜字当头（痛风避开）' },
  { name: '三文鱼握寿司', tags: ['healthy', 'takeout'], note: '一口一贯，醋饭微凉回甜' },
  { name: '金枪鱼握寿司', tags: ['healthy', 'takeout'], note: '赤身配醋饭，江户前味道' },
  { name: '海胆寿司', tags: ['takeout'], note: '海胆金黄绵密，一口爆鲜' },
  { name: '加州卷', tags: ['takeout'], note: '蟹柳牛油果，不吃生的也友好' },
  { name: '牛油果卷', tags: ['healthy', 'gout', 'takeout'], note: '素食卷清爽，牛油果好脂' },
  { name: '黄瓜细卷', tags: ['healthy', 'gout', 'takeout'], note: '一根黄瓜的极简脆爽' },
  { name: '稻荷寿司', tags: ['takeout'], note: '甜炸豆腐皮包饭，小朋友爱' },
  { name: '鳗鱼卷', tags: ['takeout'], note: '蒲烧鳗配黄瓜，甜咸交织' },
  { name: '火炙三文鱼卷', tags: ['takeout'], note: '喷枪炙过鱼脂，酱香更浓' },
  { name: '辣金枪鱼卷', tags: ['takeout'], note: '辣酱拌鱼碎，越吃越上头' },
  { name: '散寿司', tags: ['takeout'], note: '一碗铺满刺身料，豪华版' },
  { name: '手卷寿司', tags: ['takeout'], note: '锥形手持款，海苔现卷脆' },
  { name: '押寿司', tags: ['takeout'], note: '模具压制成块，古都朴素味' },
  { name: '鲑鱼籽丼', tags: ['takeout'], note: '鱼籽在嘴里爆开，咸香' },
  { name: '葱香金枪鱼腩丼', tags: ['takeout'], note: '鱼腩油香足，葱花解腻' },
  { name: '炸猪排丼', tags: ['takeout'], note: '厚炸猪排卧蛋汁，下饭' },
  { name: '牛肉丼', tags: ['takeout'], note: '肥牛洋葱盖饭，甜咸快手' },
  { name: '天丼', tags: ['takeout'], note: '天妇罗盖饭，甜汁吸满脆衣' },
  { name: '炸猪排', tags: ['takeout'], note: '厚切酥脆，配卷心菜丝解腻' },
  { name: '日式炸鸡块', tags: ['takeout'], note: '卡啦奇热辣多汁，配柠檬' },
  { name: '鸡肉串烧', tags: ['takeout'], note: '盐烤酱烤二选一，下酒一流' },
  { name: '烤鸡皮串', tags: ['takeout'], note: '炭烤鸡皮焦香，油脂的快乐' },
  { name: '寿喜烧', tags: ['takeout'], note: '甜咸锅物涮牛肉，蘸生蛋液' },
  { name: '涮涮锅', tags: ['healthy', 'takeout'], note: '清汤涮肉涮菜，蘸料控量' },
  { name: '中华海藻', tags: ['healthy', 'takeout'], note: '腌渍半成品，选低糖款麻油少放' },
  { name: '玉子烧', tags: ['takeout'], note: '层层卷蛋微甜，早餐感足' },
  { name: '大阪烧', tags: ['takeout'], note: '卷心菜煎饼，木鱼花会跳舞' },
  { name: '土豆可乐饼', tags: ['takeout'], note: '外酥内绵，蘸酱汁更香' },
  { name: '素面（冷制）', tags: ['takeout'], note: '冰镇细面，配鸡丝黄瓜丝' },
  { name: '盐味拉面', tags: ['takeout'], note: '清汤系拉面，相对不那么咸' },
  { name: '豚骨拉面', tags: ['takeout'], note: '猪骨浓汤白面，汤别喝完' },
  { name: '味噌拉面', tags: ['takeout'], note: '味噌汤底醇厚，配玉米叉烧' },
  { name: '酱油拉面', tags: ['takeout'], note: '经典褐汤底，卤蛋叉烧双拼' },
  { name: '蘸面', tags: ['takeout'], note: '凉面蘸浓汁，夏天吃正好' },
  { name: '羊羹', tags: ['takeout'], note: '红豆凝冻配清茶，古都甜品' },
  { name: '铜锣烧', tags: ['takeout'], note: '红豆夹两张小饼，叮当爱' },
  { name: '大福（冰淇淋）', tags: ['takeout'], note: '糯米皮包雪糕，Q弹冰凉' },
  { name: '鲷鱼烧', tags: ['takeout'], note: '鱼形饼夹红豆，冬天暖手' },
  { name: '韩式烤牛肉', tags: ['takeout'], note: '甜咸腌牛肉，生菜包着吃' },
  { name: '白切猪五花', tags: ['takeout'], note: '水煮厚五花，蘸虾酱解腻' },
  { name: '辣炒年糕', tags: ['takeout'], note: '甜辣年糕条，配鱼糕片' },
  { name: '鱼糕串', tags: ['takeout'], note: '串串鱼糕蘸辣酱，街头感' },
  { name: '韩式炒冬粉', tags: ['takeout'], note: '红薯粉炒时蔬，酱香弹滑' },
  { name: '酱油蒜香炸鸡', tags: ['takeout'], note: '酱蒜裹炸，咸甜冲鼻上头' },
  { name: '蜂蜜奶油炸鸡', tags: ['takeout'], note: '蜂蜜奶油裹衣，咸甜怪好' },
  { name: '生拌牛肉', tags: ['takeout'], note: '牛肉蛋黄拌梨丝（肠胃弱慎）' },
  { name: '韩式炸酱面', tags: ['takeout'], note: '春酱甜口，配黄萝卜解腻' },
  { name: '泡菜锅', tags: ['takeout'], note: '酸辣锅物，豆腐五花肉同煮' },
  { name: '海带汤', tags: ['takeout'], note: '海带牛肉清汤，生日标配' },
  { name: '韩式米肠', tags: ['takeout'], note: '糯米灌肠蘸干料（内脏类适量）' },
  { name: '韩式炸蔬菜', tags: ['takeout'], note: '炸蔬菜丝虾，蘸甜辣酱' },
  { name: '辣炒鱿鱼', tags: ['takeout'], note: '辣酱爆鱿鱼圈，下饭（痛风避开）' },
  { name: '韩式辣炖鸡', tags: ['takeout'], note: '辣酱土豆炖鸡，锅边结锅巴' },
  { name: '泡菜炒饭', tags: ['takeout'], note: '泡菜煎蛋配饭，酸辣香' },
  { name: '油蜜果', tags: ['takeout'], note: '韩果伴手礼，炸蜜点心偶尔' },
  { name: '甜米露', tags: ['takeout'], note: '韩式米仁发酵甜饮，选低糖' },
  { name: '金枪鱼饭团', tags: ['takeout'], note: '海苔卷饭团，便携顶饿' },
  { name: '黄豆粉打糕', tags: ['takeout'], note: '糯打糕裹豆粉，甜粘弹' },
  { name: '青咖喱鸡', tags: ['takeout'], note: '椰香青椒咖喱，鸡肉嫩' },
  { name: '黄咖喱牛腩', tags: ['takeout'], note: '椰浆咖喱慢炖牛腩，浓' },
  { name: '泰式打抛饭', tags: ['takeout'], note: '罗勒肉碎盖煎蛋，泰式下饭' },
  { name: '菠萝海鲜饭', tags: ['takeout'], note: '菠萝壳盛咖喱饭，甜香（贝类慎）' },
  { name: '泰式柠檬鸡', tags: ['takeout'], note: '香茅柠檬撕鸡，酸辣清爽' },
  { name: '泰式烤鸡', tags: ['healthy', 'takeout'], note: '香茅炭烤鸡，蘸青辣酱' },
  { name: '沙嗲串', tags: ['takeout'], note: '炭烤鸡肉串，蘸花生酱' },
  { name: '芒果糯米饭', tags: ['takeout'], note: '椰浆糯米配熟芒果，甜糯' },
  { name: '青木瓜沙拉', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '让店家不加椰糖才稳' },
  { name: '泰式金边粉', tags: ['takeout'], note: '罗望子炒粉，花生豆芽配' },
  { name: '香茅烤牛肉', tags: ['diabetes', 'takeout'], note: '香茅腌烤牛肉粒，东南亚香' },
  { name: '泰式船粉', tags: ['takeout'], note: '浓汤小碗粉，加九层塔' },
  { name: '叻沙', tags: ['takeout'], note: '椰浆辣汤粗米粉，浓郁霸道' },
  { name: '鸡肉河粉', tags: ['healthy', 'takeout'], note: '清汤鸡粉，配青柠豆芽' },
  { name: '越南法包', tags: ['takeout'], note: 'bánh mì 越式三明治，夹肉入味' },
  { name: '越南烤肉捞檬', tags: ['takeout'], note: '炭烤猪肉米线下捞，鱼露酸' },
  { name: '越南鲜虾卷', tags: ['healthy', 'takeout'], note: '米纸裹鲜虾蔬菜，越式春卷虾仁版' },
  { name: '辣椒螃蟹', tags: ['takeout'], note: '甜辣蟹汁浓，蘸馒头（痛风避开）' },
  { name: '肉骨茶', tags: ['takeout'], note: '胡椒蒜香炖肋排，蘸酱油' },
  { name: '椰浆饭', tags: ['takeout'], note: '椰香饭配辣酱花生（小鱼嘌呤高）' },
  { name: '咖椰吐司', tags: ['takeout'], note: '咖椰酱夹黄油，南洋早餐' },
  { name: '泰式奶茶', tags: ['takeout'], note: '橙红浓茶奶香重，糖分偏高' },
  { name: '香茅柠檬茶', tags: ['takeout'], note: '香茅柠檬冰茶，解辣（选少糖）' },
  { name: '印度飞饼', tags: ['takeout'], note: '甩薄黄油饼，蘸咖喱汁' },
  { name: '玛格丽特披萨', tags: ['takeout'], note: '番茄芝士罗勒，薄底经典' },
  { name: '培根披萨', tags: ['takeout'], note: '培根咸香芝士厚，趁热拉丝' },
  { name: '夏威夷披萨', tags: ['takeout'], note: '菠萝火腿，甜咸党的心头好' },
  { name: '四芝士披萨', tags: ['takeout'], note: '四款芝士拉丝，浓郁流心' },
  { name: '海鲜披萨', tags: ['takeout'], note: '虾仁鱿鱼铺面（痛风避开贝类）' },
  { name: '榴莲披萨', tags: ['takeout'], note: '榴莲果肉铺满，重口最爱' },
  { name: '黑松露菌菇披萨', tags: ['takeout'], note: '松露菌香薄底，高级感足' },
  { name: '卡邦尼意面', tags: ['takeout'], note: '蛋黄芝士培根，浓酱挂面' },
  { name: '蒜辣意面', tags: ['takeout'], note: '蒜片辣椒橄榄油，相对清爽' },
  { name: '青酱意面', tags: ['takeout'], note: '罗勒松子青酱，拌面冷吃也香' },
  { name: '海鲜意面', tags: ['takeout'], note: '番茄底蛤蜊虾仁（痛风避开）' },
  { name: '奶油蘑菇意面', tags: ['takeout'], note: '菌菇奶油酱，宽面更挂汁' },
  { name: '芝士焗通心粉', tags: ['takeout'], note: '通心粉焗芝士，绵密拉丝' },
  { name: '千层面', tags: ['takeout'], note: '肉酱白酱层层烤，扎实' },
  { name: '尼斯沙拉', tags: ['healthy', 'diabetes', 'takeout'], note: '金枪鱼蛋豆角，一盘顶饱' },
  { name: '卡普雷塞', tags: ['healthy', 'takeout'], note: '番茄配水牛芝士，高脂前菜少量' },
  { name: '牛油果沙拉', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '牛油果配蔬菜，好脂低负担' },
  { name: '田园沙拉', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '生菜番茄黄瓜，酱汁选油醋' },
  { name: '土豆沙拉', tags: ['takeout'], note: '蛋黄酱拌土豆，凉口顶饿' },
  { name: '金枪鱼三明治', tags: ['healthy', 'takeout'], note: '拌酱用酸奶替代沙拉酱' },
  { name: '西冷牛排', tags: ['takeout'], note: '外焦里嫩五分熟，黑椒汁' },
  { name: '菲力牛排', tags: ['takeout'], note: '里脊最嫩，少油煎正合适' },
  { name: '丁骨牛排', tags: ['takeout'], note: '带骨大份，两人分刚好' },
  { name: '慢烤牛肉', tags: ['healthy', 'diabetes', 'takeout'], note: '粉嫩烤牛肉切片，蘸汁少放' },
  { name: '法式洋葱汤', tags: ['takeout'], note: '焦糖洋葱，芝士面包盖顶' },
  { name: '炸鱼薯条', tags: ['takeout'], note: '英式脆皮炸鱼，蘸塔塔酱' },
  { name: '奶油蘑菇汤', tags: ['takeout'], note: '浓菇汤配法棍，菌香足（适量）' },
  { name: '黑松露烩饭', tags: ['takeout'], note: '意式米烩浓香，配牛排解腻' },
  { name: '芝士焗土豆', tags: ['takeout'], note: '奶油芝士焗薯片，绵香' },
  { name: '油封鸭腿', tags: ['takeout'], note: '慢油封鸭腿，皮酥肉烂咸香' },
  { name: '培根生菜番茄三明治', tags: ['takeout'], note: 'BLT 三件套，烟熏培根香' },
  { name: '芝士汉堡', tags: ['takeout'], note: '芝士融化裹牛肉，快餐魂' },
  { name: '双层牛肉汉堡', tags: ['takeout'], note: '双层肉饼芝士，一顿顶饱' },
  { name: '鳕鱼堡', tags: ['takeout'], note: '炸鱼柳配塔塔酱，老牌经典' },
  { name: '炸鸡堡', tags: ['takeout'], note: '脆皮鸡排生菜酱，一口爆汁' },
  { name: '烤鸡腿堡', tags: ['healthy', 'takeout'], note: '选烤不选炸，相对清爽' },
  { name: '薯条', tags: ['takeout'], note: '细薯撒盐趁热吃，蘸番茄酱' },
  { name: '薯角', tags: ['takeout'], note: '带皮粗薯角，比薯条扛饿' },
  { name: '洋葱圈', tags: ['takeout'], note: '炸洋葱圈，甜辣面衣趁热' },
  { name: '脆皮鸡翅', tags: ['takeout'], note: '快餐炸翅，咬开冒汁' },
  { name: '水牛城辣鸡翅', tags: ['takeout'], note: '辣酱黄油裹翅，蘸蓝纹酱' },
  { name: '鸡肉卷', tags: ['takeout'], note: '饼卷鸡肉蔬菜酱，便携' },
  { name: '香草甜筒', tags: ['takeout'], note: '脆皮甜筒香草味，化了快吃' },
  { name: '巧克力圣代', tags: ['takeout'], note: '巧克力酱浇冰淇淋球，甜' },
  { name: '草莓奶昔', tags: ['takeout'], note: '浓稠甜奶昔，偶尔喝一杯' },
  { name: '火腿蛋堡（早餐）', tags: ['takeout'], note: '松饼夹火腿蛋，早餐顶饿' },
  { name: '芝心披萨', tags: ['takeout'], note: '卷边芝士拉丝，热量拉满' },
  { name: '手抛薄底披萨', tags: ['takeout'], note: '手抛饼底，边脆心软' },
  { name: '小食拼盘', tags: ['takeout'], note: '薯条鸡翅一篮端，分享装' },
  { name: '现烤汉堡（中式堡）', tags: ['takeout'], note: '手擀现烤堡皮，馅儿接地气' },
  { name: '塔可', tags: ['takeout'], note: '脆壳碎肉生菜芝士，撒辣酱' },
  { name: '卷饼（墨西哥）', tags: ['takeout'], note: '大面饼卷饭豆肉，一餐管饱' },
  { name: '芝士烤饼', tags: ['takeout'], note: '芝士鸡肉烤饼，对角切开吃' },
  { name: '可乐（无糖版）', tags: ['takeout'], note: '代糖零卡，气泡水解馋' },
  { name: '沙威玛', tags: ['takeout'], note: '中东鸡肉卷饼，蒜酱腌黄瓜' },
  { name: '土耳其烤肉', tags: ['takeout'], note: '旋转烤炉削肉，洋葱饼卷香' },
  { name: '土耳其烤饼', tags: ['takeout'], note: '芝麻孜然现烤饼，出炉脆' },
  { name: '鹰嘴豆泥', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '豆泥抹面包，缓解期适量吃' },
  { name: '希腊酸奶碗', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '选无糖款，别加蜂蜜' },
  { name: '中东烤鸡串', tags: ['takeout'], note: '酸奶腌烤鸡串，孜然香浓' },
  { name: '中东混烤拼盘', tags: ['takeout'], note: '牛鸡羊杂拼，配饼配沙拉' },
  { name: '印度坦都里鸡', tags: ['healthy', 'diabetes', 'takeout'], note: '香料腌炭烤鸡块，选无糖配' },
  { name: '黄油鸡', tags: ['takeout'], note: '番茄奶油炖鸡块，浓香微辣' },
  { name: '印度咖喱羊肉', tags: ['takeout'], note: '香料慢炖羊肉，masala 浓香' },
  { name: '印度豆糊', tags: ['gout', 'takeout'], note: '扁豆浓汤配烤饼，豆类适量' },
  { name: '印度香饭', tags: ['takeout'], note: '长米香料焖鸡饭，印度版抓饭' },
  { name: '印度香料茶', tags: ['takeout'], note: '姜煮浓奶茶，糖分偏高' },
  { name: '中东小菜拼盘', tags: ['takeout'], note: 'mezze 多碟分享，鹰嘴豆泥配饼' },
  { name: '新疆拉条子', tags: ['takeout'], note: '手拉拌面，菜码浇头' },
  { name: '土耳其布丁', tags: ['takeout'], note: '米香奶冻撒开心果' },
  { name: '果仁蜜饼', tags: ['takeout'], note: '酥皮坚果泡糖浆，甜到齁' },
  { name: '黄油可颂', tags: ['takeout'], note: '层次起酥，掉渣的黄油香' },
  { name: '巧克力可颂', tags: ['takeout'], note: '酥皮裹巧克力馅，微苦回甜' },
  { name: '肉桂卷', tags: ['takeout'], note: '糖霜肉桂卷，刚烤最好吃' },
  { name: '葡萄干面包', tags: ['takeout'], note: '果干甜面包，早餐两片' },
  { name: '肉松面包', tags: ['takeout'], note: '肉松沙拉酱软包，顶饿' },
  { name: '芝士软包', tags: ['takeout'], note: '夹心软面包，芝士拉丝' },
  { name: '红豆面包', tags: ['takeout'], note: '豆沙包松软，微甜扎实' },
  { name: '法棍', tags: ['takeout'], note: '硬壳嚼着香，配汤配酱' },
  { name: '黑麦酸种欧包', tags: ['healthy', 'diabetes', 'takeout'], note: '酸种发酵，升糖相对慢' },
  { name: '贝果', tags: ['takeout'], note: '耐嚼早餐圈，抹芝士更香' },
  { name: '黑麦脆片', tags: ['healthy', 'diabetes', 'takeout'], note: '薄脆代餐饼，配奶酪蔬菜' },
  { name: '北海道牛奶面包', tags: ['takeout'], note: '撕着吃的软奶香，甜' },
  { name: '布丁面包', tags: ['takeout'], note: '面包里灌蛋奶布丁，嫩' },
  { name: '佛卡夏', tags: ['takeout'], note: '橄榄油凹坑香草饼，蘸油醋' },
  { name: '夏巴塔', tags: ['takeout'], note: '大气孔意式硬皮，夹肉绝配' },
  { name: '蒜香面包', tags: ['takeout'], note: '蒜香黄油烤面包片，咸香' },
  { name: '司康', tags: ['takeout'], note: '黄油司康配果酱，下午茶' },
  { name: '丹麦酥', tags: ['takeout'], note: '果酱卡仕达起酥，一层层' },
  { name: '重芝士蛋糕', tags: ['takeout'], note: '烤芝士绵密厚重，配红茶' },
  { name: '流心芝士蛋糕', tags: ['takeout'], note: '切开流心的芝士，微咸甜' },
  { name: '提拉米苏', tags: ['takeout'], note: '咖啡酒渍马斯卡彭，经典' },
  { name: '黑森林蛋糕', tags: ['takeout'], note: '樱桃奶油巧克力，老派浪漫' },
  { name: '千层蛋糕', tags: ['takeout'], note: '二十层薄饼夹奶霜，细腻' },
  { name: '歌剧院蛋糕', tags: ['takeout'], note: '咖啡杏仁巧克力层，法式' },
  { name: '草莓鲜奶蛋糕', tags: ['takeout'], note: '海绵胚草莓奶油，生日款' },
  { name: '长崎蛋糕', tags: ['takeout'], note: '蜂蜜蛋糕绵密，边皮香' },
  { name: '瑞士卷', tags: ['takeout'], note: '奶油卷蛋糕，一卷停不下' },
  { name: '布朗尼', tags: ['takeout'], note: '扎实巧克力，软心或脆边' },
  { name: '马卡龙', tags: ['takeout'], note: '杏仁小圆饼，甜到一口一个' },
  { name: '杏仁瓦片', tags: ['takeout'], note: '薄脆杏仁甜片，配茶正好' },
  { name: '巧克力豆曲奇', tags: ['takeout'], note: '软曲奇嵌巧克力豆，温的最好' },
  { name: '无糖燕麦饼干', tags: ['diabetes', 'gout', 'takeout'], note: '一两块当加餐，油脂高别多吃' },
  { name: '奶油泡芙', tags: ['takeout'], note: '脆壳挤满卡仕达，一口爆浆' },
  { name: '闪电泡芙', tags: ['takeout'], note: '长条泡芙淋巧克力，精致' },
  { name: '焦糖布丁', tags: ['takeout'], note: '蛋奶冻晃悠悠，焦糖微苦' },
  { name: '比利时华夫', tags: ['takeout'], note: '格子饼浇巧克力，趁热脆' },
  { name: '荷兰松饼', tags: ['takeout'], note: '烤箱大松饼，柠檬糖粉' },
  { name: '茉莉花茶（无糖）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '冷萃零卡，花香打底' },
  { name: '乌龙茶（无糖）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '醇厚回甘，解腻无负担' },
  { name: '普洱茶（无糖）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '熟普温润，饭后一杯' },
  { name: '大麦茶（无糖）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '炒麦香解腻，零糖零卡' },
  { name: '柠檬捶捶茶（无糖）', tags: ['healthy', 'diabetes', 'takeout'], note: '手捶柠檬无糖版，酸爽醒神' },
  { name: '珍珠奶茶', tags: ['takeout'], note: '奶香配珍珠，糖分预警' },
  { name: '奶茶（无糖）', tags: ['diabetes', 'takeout'], note: '无糖还不要小料，小料都泡糖浆' },
  { name: '茉莉奶绿', tags: ['takeout'], note: '茉莉绿茶兑奶，选少糖' },
  { name: '芝士奶盖茶', tags: ['takeout'], note: '咸奶盖厚一层，糖油双高' },
  { name: '芝士葡萄', tags: ['takeout'], note: '葡萄果肉打底，芝士封顶' },
  { name: '生椰奶绿', tags: ['takeout'], note: '椰浆配绿茶，热带清爽' },
  { name: '布丁奶茶', tags: ['takeout'], note: '奶冻滑进奶茶，吸管戳破' },
  { name: '黑糖脏脏奶茶', tags: ['takeout'], note: '黑糖挂壁焦香，甜度爆表' },
  { name: '拿铁（无糖）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '纯奶兑浓缩，不加糖版' },
  { name: '卡布奇诺（无糖）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '厚奶泡咖啡，无糖更纯粹' },
  { name: '冰美式', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '零卡提神，夏日冰感足' },
  { name: '澳白（无糖）', tags: ['diabetes', 'takeout'], note: '奶薄咖浓，无糖点单' },
  { name: '摩卡', tags: ['takeout'], note: '巧克力酱咖啡奶，甜派爱' },
  { name: '焦糖玛奇朵', tags: ['takeout'], note: '香草糖底花纹，偏甜' },
  { name: '生椰拿铁', tags: ['takeout'], note: '椰乳兑浓缩，香但选无糖' },
  { name: '橙C美式', tags: ['takeout'], note: '橙汁加浓缩，微苦带酸' },
  { name: '意式浓缩', tags: ['diabetes', 'takeout'], note: '一小杯 shot，零糖提神' },
  { name: '抹茶拿铁（无糖）', tags: ['healthy', 'diabetes', 'takeout'], note: '抹茶打奶无糖版，微苦回甘' },
  { name: '焙茶拿铁（无糖）', tags: ['diabetes', 'takeout'], note: '烘焙茶低咖，晚间也能喝' },
  { name: '燕麦奶拿铁', tags: ['takeout'], note: '植物奶版，甜感来自燕麦' },
  { name: '百香果柠檬茶', tags: ['takeout'], note: '果籽酸爽，选三分糖' },
  { name: '蜜桃乌龙果茶', tags: ['takeout'], note: '蜜桃乌龙，果肉酱糖都多' },
  { name: '满杯水果茶', tags: ['takeout'], note: '一堆水果泡乌龙，微甜清爽' },
  { name: '蜂蜜柠檬（热）', tags: ['takeout'], note: '润喉热饮，蜂蜜别放多' },
  { name: '椰子水（纯）', tags: ['gout', 'takeout'], note: '天然电解质，糖不低限一杯一天' },
  { name: '甘蔗汁', tags: ['takeout'], note: '现榨清甜，糖分偏高' },
  { name: '乳酸菌饮品', tags: ['takeout'], note: '酸甜小瓶装，菌多糖也多' },
  { name: '热巧克力', tags: ['takeout'], note: '浓可可热奶，加糖饮' },
  { name: '冰咖啡冻', tags: ['takeout'], note: '咖啡冻滑溜，微苦配奶' },
  { name: '柠檬红茶（冰）', tags: ['takeout'], note: '快餐店经典，糖分偏高' },
  { name: '姜撞奶', tags: ['takeout'], note: '姜汁撞凝奶，广式热甜' },
  { name: '鲜奶冻', tags: ['gout', 'takeout'], note: '纯奶蒸凝微甜，低嘌呤甜品' },
  { name: '雪媚娘', tags: ['takeout'], note: '糯米皮包奶油水果，软凉' },
  { name: '莲子百合糖水', tags: ['gout', 'takeout'], note: '莲子百合清润，无糖或半糖小碗' },
  { name: '芋头西米露', tags: ['takeout'], note: '香芋椰浆西米，粉糯滑' },
  { name: '红豆糕', tags: ['takeout'], note: '豆沙凝糕，一口一块' },
  { name: '黑凉粉', tags: ['takeout'], note: '凉粉滑溜，配蜂蜜水' },
  { name: '芋泥麻薯', tags: ['takeout'], note: '芋泥拉丝麻薯，厚糯甜' },
  { name: '绿豆糕', tags: ['takeout'], note: '绿豆粉糕绵密，冰过好吃' },
  { name: '杏仁豆腐', tags: ['gout', 'takeout'], note: '杏仁奶冻低嘌呤，选无糖小份' },
  { name: '桂花糖藕', tags: ['takeout'], note: '糯米灌藕淋桂花，甜糯' },
  { name: '桂花藕粉', tags: ['gout', 'takeout'], note: '冲调用无糖或代糖，小碗暖胃' },
  { name: '冰糖雪梨', tags: ['takeout'], note: '炖梨润燥，冰糖量偏大' },
  { name: '炸鲜奶', tags: ['takeout'], note: '奶冻裹浆炸，外脆内凉' },
  { name: '桂花糕', tags: ['takeout'], note: '糯米小方糕，桂花清甜' },
  { name: '香草冰淇淋', tags: ['takeout'], note: '一球香草，化了就吃' },
  { name: '刨冰（糖水）', tags: ['takeout'], note: '碎冰淋糖水，暑气全消' },
  { name: '芒果绵绵冰', tags: ['takeout'], note: '芒果冰沙绵密，偏甜' },
  { name: '椰子冻', tags: ['takeout'], note: '椰汁凝冻，椰香弹滑' },
  { name: '意式冰淇淋', tags: ['takeout'], note: 'Gelato 空气感，口味多' },
  { name: '冻酸奶', tags: ['healthy', 'diabetes', 'takeout'], note: '选无糖款配莓果' },
  { name: '抹茶布丁', tags: ['takeout'], note: '抹茶奶冻分层，苦甜平衡' },
  { name: '咖啡冻奶茶', tags: ['takeout'], note: '咖啡冻滑进奶茶，双重苦甜' },
  { name: '杏仁露（无糖）', tags: ['diabetes', 'gout', 'takeout'], note: '无糖杏仁露，坚果香低糖' },
  { name: '仙草冻', tags: ['takeout'], note: '黑凉草冻，蜂蜜柠檬自选' },
  { name: '红糖凉糕', tags: ['takeout'], note: '米糕淋红糖浆，川渝冰甜品' },
  { name: '椰汁香芋', tags: ['takeout'], note: '椰浆煮芋头，粉糯香浓' },
  { name: '草莓大福', tags: ['takeout'], note: '整颗草莓裹糯米豆沙' },
  { name: '马苏里拉芝士条', tags: ['takeout'], note: '拉丝芝士条，蘸番茄酱' },
  { name: '纳乔芝士玉米片', tags: ['takeout'], note: '芝士酱淋脆片，莎莎酱蘸' },
  { name: '黄油爆米花', tags: ['takeout'], note: '影院同款，追剧一桶' },
  { name: '辣条', tags: ['takeout'], note: '重油重辣，偶尔解馋' },
  { name: '薯片', tags: ['takeout'], note: '原味脆片，盐分预警' },
  { name: '海苔脆片', tags: ['healthy', 'takeout'], note: '烤海苔薄片，鲜咸低卡' },
  { name: '芒果干', tags: ['takeout'], note: '厚切芒果干，糖分浓缩' },
  { name: '黑巧克力（高可可）', tags: ['healthy', 'diabetes', 'takeout'], note: '选 85% 以上，每次一小块' },
  { name: '酸黄瓜', tags: ['gout', 'takeout'], note: '腌小黄瓜解腻，钠偏高' },
  { name: '卷心菜沙拉（西式）', tags: ['gout', 'takeout'], note: '蛋黄酱拌菜丝，配炸物解腻' },
  { name: '蘸酱蔬菜条（胡萝卜芹菜）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '菜条蘸鹰嘴豆泥，豆泥一小勺' },
  { name: '烤坚果拼盘', tags: ['healthy', 'diabetes', 'takeout'], note: '原味烘焙，每天一小把' },
  { name: '果干燕麦棒', tags: ['takeout'], note: '燕麦压果干，垫肚小条' },
  { name: '蛋酥卷（蜂蜜）', tags: ['takeout'], note: '蜂蜜蛋酥卷，配茶零嘴' },
]
