// 「今天吃什么」分片：健康家常菜（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const HEALTHY_HOME_DISHES: FoodDish[] = [
  { name: '清蒸黄花鱼', tags: ['healthy', 'diabetes'], note: '刺少肉嫩蒸出来鲜，葱姜简单提味' },
  { name: '清蒸鲳鱼', tags: ['healthy', 'diabetes'], note: '扁鱼细嫩少刺，豉油葱丝是灵魂' },
  { name: '剁椒蒸芋头', tags: ['healthy', 'diabetes'], note: '剁椒先冲洗少放，芋头当主食' },
  { name: '豆豉蒸排骨', tags: ['healthy'], note: '豉香渗进骨头，蒸出来比烧清爽' },
  { name: '香芋蒸排骨', tags: ['healthy'], note: '香芋垫底吸肉汁，排骨蒸到软烂' },
  { name: '清蒸白鱼', tags: ['healthy'], note: '淡水白鱼嫩无腥，原汁原味最鲜' },
  { name: '蒜蓉蒸生蚝', tags: ['healthy', 'diabetes'], note: '肥蚝一口一个，蒜蓉粉丝铺底鲜' },
  { name: '蛤蜊蒸蛋', tags: ['healthy', 'diabetes'], note: '蛤蜊藏在蛋羹里，鲜到眉毛掉下来' },
  { name: '清蒸鳊鱼', tags: ['healthy', 'gout'], note: '鳊鱼清蒸，缓解期一块为度' },
  { name: '萝卜丝蒸肉丸', tags: ['healthy'], note: '萝卜垫底解腻，肉丸蒸出鲜嫩汁' },
  { name: '糯米蒸鸡翅', tags: ['healthy'], note: '糯米少量，优先鸡腿去皮蒸' },
  { name: '蒜蓉蒸秋葵', tags: ['healthy', 'diabetes', 'gout'], note: '秋葵切段铺蒜蓉，蒸好淋豉油就吃' },
  { name: '清蒸比目鱼', tags: ['healthy', 'diabetes'], note: '扁平鱼身肉细白，豉油热油最后淋' },
  { name: '虫草花蒸鸡', tags: ['healthy'], note: '虫草花金黄铺鸡上，蒸出菌香鲜甜' },
  { name: '豉油蒸鸡翅', tags: ['healthy'], note: '简单腌一蒸就好，豉油香入骨头' },
  { name: '清蒸狮子鱼', tags: ['healthy'], note: '鱼肉雪白一片一片，蘸豉油鲜甜' },
  { name: '蒜蓉蒸带子', tags: ['healthy'], note: '带子比扇贝肥，粉丝垫底蒜香浓' },
  { name: '梅菜蒸肉饼（少盐）', tags: ['healthy'], note: '梅菜先泡洗，选瘦肉不另加盐' },
  { name: '清蒸武昌鱼', tags: ['healthy'], note: '才饮长沙水又食武昌鱼，葱丝热油' },
  { name: '茶树菇蒸鸡块', tags: ['healthy'], note: '茶树菇干香有嚼劲，裹着鸡块同蒸' },
  { name: '蒜蓉蒸冬瓜盒', tags: ['healthy', 'diabetes', 'gout'], note: '冬瓜切盒夹肉末一小撮同蒸' },
  { name: '清蒸罗非鱼', tags: ['healthy', 'diabetes', 'gout'], note: '便宜刺少到处有，家常蒸鱼首选（中嘌呤缓解期少量）' },
  { name: '清炒莴笋片', tags: ['healthy', 'diabetes', 'gout'], note: '莴笋切片翠绿脆嫩，大火翻几下就好' },
  { name: '蒜蓉西葫芦', tags: ['healthy', 'diabetes', 'gout'], note: '西葫芦软嫩清甜，蒜蓉爆香快炒' },
  { name: '醋炒白菜帮', tags: ['healthy', 'diabetes'], note: '白菜帮切丝，醋酸脆爽开胃下饭' },
  { name: '蒜蓉豆苗', tags: ['healthy'], note: '豌豆苗嫩到掐出水，蒜蓉大火快翻' },
  { name: '小炒藕片', tags: ['healthy', 'gout'], note: '藕片脆生生微甜，青椒配色好看' },
  { name: '蒜蓉佛手瓜', tags: ['healthy', 'gout'], note: '佛手瓜脆嫩清甜，少油少盐原味鲜' },
  { name: '辣炒芦笋段', tags: ['healthy', 'diabetes'], note: '芦笋切段微辣炒，时令脆嫩低热量' },
  { name: '蒜苔炒百合', tags: ['healthy'], note: '蒜苔辛香百合粉糯，秋燥来一盘' },
  { name: '清炒马齿苋', tags: ['healthy'], note: '选可靠来源焯水，孕早期少量' },
  { name: '素炒三丝', tags: ['healthy'], note: '胡萝卜青椒豆皮切丝，清爽快炒' },
  { name: '清炒南瓜藤', tags: ['healthy', 'gout'], note: '只取嫩尖微苦回甘，夏天清火蔬菜' },
  { name: '蒜香炒芥蓝', tags: ['healthy', 'diabetes'], note: '芥蓝茎脆叶微苦，大火蒜香快炒' },
  { name: '清炒马兰头', tags: ['healthy'], note: '春日野菜清香独特，拌香干一绝' },
  { name: '素炒莴笋木耳', tags: ['healthy', 'diabetes', 'gout'], note: '莴笋脆木耳弹，双脆组合少油清爽' },
  { name: '清炒儿菜', tags: ['healthy'], note: '冬日四川时蔬，脆嫩微甜清炒就好' },
  { name: '蒜香炒苦菊', tags: ['healthy'], note: '苦菊微辛清火，蒜蓉快炒去涩味' },
  { name: '清炒塔菜', tags: ['healthy', 'gout'], note: '上海冬天的小油菜，脆嫩带点甜' },
  { name: '清炒洋丝瓜', tags: ['healthy', 'diabetes'], note: '云南夏日小瓜，切片清炒脆嫩鲜' },
  { name: '小炒花生芽', tags: ['healthy'], note: '花生发芽爆炒，脆甜像小笋低卡' },
  { name: '清炒芦蒿', tags: ['healthy'], note: '南京春天特有的香，清炒几秒出锅' },
  { name: '炒魔芋丝', tags: ['healthy', 'diabetes', 'gout'], note: '魔芋近零卡，配青椒蒜片炒饱腹' },
  { name: '清炒芝麻菜', tags: ['healthy'], note: '微辛意式蔬菜改中炒，蒜香几秒鲜' },
  { name: '小炒茭白丝', tags: ['healthy', 'gout'], note: '茭白水嫩微甜，切丝快炒少油香' },
  { name: '清炒雪里蕻', tags: ['healthy'], note: '腌鲜雪菜少盐版，炒蛋炒豆腐都行' },
  { name: '素炒玉米粒', tags: ['healthy', 'gout'], note: '甜玉米粒配松子，低卡小炒当零食' },
  { name: '凉拌海带结', tags: ['healthy', 'diabetes', 'gout'], note: '海带结泡发一小片，蒜醋凉拌' },
  { name: '凉拌豆皮黄瓜', tags: ['healthy', 'diabetes'], note: '豆腐皮切丝配黄瓜，清爽低卡夏天吃' },
  { name: '凉拌鲜笋丝', tags: ['healthy', 'diabetes'], note: '春笋焯水撕丝，淋麻油生抽脆嫩' },
  { name: '姜汁拌藕片', tags: ['healthy'], note: '藕片焯水过凉，姜汁微辛暖胃鲜' },
  { name: '冰镇苦瓜圈', tags: ['healthy'], note: '蘸少许蜂蜜或原味，幼儿勿食蜜' },
  { name: '手撕杏鲍菇', tags: ['healthy'], note: '蒸熟撕条，麻辣汁少放改蒜醋' },
  { name: '凉拌魔芋结', tags: ['healthy', 'diabetes', 'gout'], note: '魔芋结Q弹近零卡，酸辣汁开胃' },
  { name: '黄瓜拌粉皮', tags: ['healthy', 'gout'], note: '粉皮滑溜黄瓜脆，蒜醋汁夏天标配' },
  { name: '凉拌紫甘蓝', tags: ['healthy', 'diabetes'], note: '紫甘蓝切细丝，醋拌保持脆和颜色' },
  { name: '麻酱拌油麦菜', tags: ['healthy', 'diabetes'], note: '绿叶菜焯水拌，麻酱少许控量' },
  { name: '凉拌蕨根粉', tags: ['healthy'], note: '选无铝产品，偶尔解馋别当主食' },
  { name: '芥末拌木耳', tags: ['healthy', 'diabetes', 'gout'], note: '木耳脆弹芥末微冲，开胃上头小凉菜' },
  { name: '蒜醋拌莴笋', tags: ['healthy', 'diabetes', 'gout'], note: '莴笋切细条腌出水，蒜醋汁脆爽' },
  { name: '凉拌油豆腐', tags: ['healthy'], note: '油豆腐油炸过，焯水去油少量' },
  { name: '花椒拌花菜', tags: ['healthy'], note: '花菜焯水拌花椒油，微麻清香低卡' },
  { name: '柠檬手撕鸡', tags: ['healthy'], note: '鸡胸蒸熟撕丝，柠檬汁拌清香低脂' },
  { name: '凉拌海蜇丝', tags: ['healthy'], note: '海蜇多换水泡去盐矾再拌' },
  { name: '老醋花生拌菜', tags: ['healthy'], note: '用水煮花生米，别用油炸的' },
  { name: '凉拌青红椒圈', tags: ['healthy', 'diabetes'], note: '彩椒切圈生拌，蒜醋汁微甜脆爽' },
  { name: '麻酱拌豆角', tags: ['healthy'], note: '豆角务必煮至软熟变色再拌' },
  { name: '糖醋藕带', tags: ['healthy'], note: '夏天小嫩藕带，少糖醋拌脆生生' },
  { name: '竹荪豆腐汤', tags: ['healthy'], note: '竹荪吸满鲜汤，嫩豆腐入口即化' },
  { name: '薏米冬瓜汤', tags: ['healthy', 'gout'], note: '薏米配冬瓜，夏天煮碗清汤' },
  { name: '霸王花猪骨汤', tags: ['healthy'], note: '霸王花猪骨，撇油喝清汤' },
  { name: '丝瓜鱼片汤', tags: ['healthy'], note: '丝瓜煮到软嫩，薄鱼片滑鲜好喝' },
  { name: '紫菜豆腐汤', tags: ['healthy', 'diabetes', 'gout'], note: '紫菜一克豆腐半块，三分钟出锅' },
  { name: '莲藕玉米素汤', tags: ['healthy', 'gout'], note: '莲藕粉糯玉米甜，煮碗素汤' },
  { name: '鲜菇丝瓜汤', tags: ['healthy'], note: '菌菇鲜丝瓜滑，清汤低卡夏天喝' },
  { name: '萝卜丝虾皮汤', tags: ['healthy'], note: '萝卜丝煮到透明，虾皮提鲜补钙' },
  { name: '冬瓜蛤蜊汤', tags: ['healthy'], note: '蛤蜊鲜掉眉毛，冬瓜消暑低热量' },
  { name: '番茄金针菇汤', tags: ['healthy', 'gout'], note: '鲜金针菇适量，番茄煮清汤' },
  { name: '玉米胡萝卜素汤', tags: ['healthy'], note: '三种蔬菜清甜汤，小朋友也爱喝' },
  { name: '猴头菇鸡汤', tags: ['healthy'], note: '猴头菇配鸡，去皮炖清汤' },
  { name: '木瓜鲫鱼汤', tags: ['healthy'], note: '鲫鱼煎后撇净浮油，炖木瓜' },
  { name: '松茸菌菇汤', tags: ['healthy'], note: '松茸香气馥郁，纯素煲汤鲜到底' },
  { name: '白萝卜海带汤', tags: ['healthy', 'diabetes', 'gout'], note: '白萝卜煮海带一小片，清汤低卡' },
  { name: '扁豆山药汤', tags: ['healthy'], note: '白扁豆务必煮透，配山药煲汤' },
  { name: '番茄丝瓜蛋汤', tags: ['healthy', 'gout'], note: '红番茄绿丝瓜蛋花飘，鲜甜低卡' },
  { name: '莲子猪心汤', tags: ['healthy'], note: '猪心属内脏偶尔小份，撇油' },
  { name: '花生鸡脚汤', tags: ['healthy'], note: '鸡脚炖到脱骨，花生香浓撇油喝' },
  { name: '花生芽豆腐汤', tags: ['healthy'], note: '花生芽鲜甜，嫩豆腐化在清汤里' },
  { name: '萝卜丝炖粉条', tags: ['healthy', 'diabetes', 'gout'], note: '萝卜丝清甜粉条软，冬天暖身汤' },
  { name: '南瓜浓汤（无奶油）', tags: ['healthy', 'gout'], note: '蒸熟打成泥，南瓜自然甜不加油' },
  { name: '香菇蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '鲜香菇适量铺蛋面，蒸嫩滑' },
  { name: '银鱼蒸蛋', tags: ['healthy', 'diabetes'], note: '小银鱼嵌在蛋羹里，补钙又鲜嫩' },
  { name: '文蛤蒸蛋', tags: ['healthy', 'diabetes'], note: '蛤蜊藏在嫩蛋里，咬开一口鲜汁' },
  { name: '蟹柳蒸蛋', tags: ['healthy', 'diabetes'], note: '蟹柳选低钠少量提味，蒸蛋' },
  { name: '肉末蒸水蛋', tags: ['healthy'], note: '经典水蒸蛋铺肉末，嫩滑下早餐饭' },
  { name: '虾仁豆腐蒸蛋', tags: ['healthy', 'diabetes'], note: '三层嫩滑叠一起，高蛋白一蒸搞定' },
  { name: '秋葵蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '秋葵切片摆花形，蒸在蛋羹上好看' },
  { name: '干贝蒸蛋', tags: ['healthy', 'diabetes'], note: '瑶柱撕丝铺面，蛋面蒸得光滑如镜' },
  { name: '西兰花蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '绿白配色营养好，蛋羹裹住小花' },
  { name: '咸蛋蒸豆腐', tags: ['healthy'], note: '咸蛋黄只取少量提味' },
  { name: '番茄蛋花羹', tags: ['healthy', 'gout'], note: '蛋花飘在番茄浓汤里，酸甜暖胃' },
  { name: '木耳蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '碎木耳拌蛋液蒸，补铁嫩滑口感好' },
  { name: '豆腐抱蛋', tags: ['healthy', 'diabetes'], note: '嫩豆腐打鸡蛋同煎，少油版蒸出来' },
  { name: '清炒杏鲍菇', tags: ['healthy'], note: '杏鲍菇切厚片干煸，口感赛肉有嚼劲' },
  { name: '蒜蓉蒸平菇', tags: ['healthy', 'diabetes'], note: '平菇铺盘撒蒜蓉，蒸出原汁菌菇汁' },
  { name: '干煸茶树菇', tags: ['healthy'], note: '茶树菇撕条少油煸，干香耐嚼下酒菜' },
  { name: '蚝油双菇', tags: ['healthy'], note: '鲜菇适量，蚝油少量不另加盐' },
  { name: '素炒海鲜菇', tags: ['healthy'], note: '海鲜菇脆嫩白净，蒜蓉爆香快炒鲜' },
  { name: '红烧鸡腿菇', tags: ['healthy'], note: '鸡腿菇形似肉，少油焖烧酱香浓郁' },
  { name: '炒双耳', tags: ['healthy'], note: '黑木耳银耳同炒，双脆组合清肠爽口' },
  { name: '白玉菇炒芦笋', tags: ['healthy', 'diabetes', 'gout'], note: '鲜菌适量配芦笋，清炒低卡' },
  { name: '绣球菌炒鸡丁', tags: ['healthy'], note: '绣球菌脆如珊瑚，配鸡丁炒鲜弹' },
  { name: '香菇烧豆腐', tags: ['healthy', 'diabetes'], note: '冬菇汁浓豆腐入味，少油炖一炖就好' },
  { name: '口蘑炒荷兰豆', tags: ['healthy', 'diabetes'], note: '口蘑鲜甜荷兰豆脆，清炒少油两分钟' },
  { name: '素炒牛肝菌', tags: ['healthy'], note: '云南珍菌大火快炒，鲜香浓郁低脂版' },
  { name: '菌菇炒山药', tags: ['healthy'], note: '菌菇配山药片，脆嫩爽口' },
  { name: '猴头菇炒菜心', tags: ['healthy', 'diabetes'], note: '猴头菇软糯像肉，菜心清脆配色鲜' },
  { name: '秀珍菇炒蛋', tags: ['healthy'], note: '秀珍菇撕小朵炒蛋，菌香裹蛋嫩滑' },
  { name: '草菇炒青椒', tags: ['healthy', 'diabetes'], note: '粤式小炒草菇滑，青椒微辣提鲜香' },
  { name: '素烧菌菇煲', tags: ['healthy'], note: '杂菇一锅蚝油焖，少盐低卡鲜到底' },
  { name: '金针菇炒豆皮', tags: ['healthy', 'diabetes'], note: '金针菇缠豆皮，蒜蓉生抽炒出鲜香' },
  { name: '鸡腿菇炒芦笋', tags: ['healthy'], note: '鸡腿菇切滚刀芦笋配，双鲜白绿' },
  { name: '菌菇炒时蔬', tags: ['healthy'], note: '杂菌配当季蔬菜，少油大火炒鲜香' },
  { name: '清炒羽衣甘蓝', tags: ['healthy', 'diabetes'], note: '洋超级菜撕片炒，蒜香脆嫩花青素高' },
  { name: '蒜蓉红凤菜', tags: ['healthy'], note: '紫背天葵蒜蓉快炒，紫汁好看' },
  { name: '白灼番薯叶', tags: ['healthy', 'diabetes'], note: '红薯叶焯水淋豉油蒜末，软滑清香' },
  { name: '蒜炒木耳菜', tags: ['healthy', 'diabetes'], note: '木耳菜滑嫩补铁补钙，大火蒜香炒' },
  { name: '上汤紫背菜', tags: ['healthy'], note: '皮蛋仅少许提味，幼儿不食' },
  { name: '白灼豌豆尖', tags: ['healthy', 'diabetes', 'gout'], note: '只取最嫩的尖，白灼蘸酱油清甜' },
  { name: '蒜泥茼蒿杆', tags: ['healthy', 'diabetes'], note: '只取茼蒿茎段，蒜泥拌着吃脆爽' },
  { name: '清炒荠菜', tags: ['healthy', 'diabetes', 'gout'], note: '选可靠来源，洗净焯水再炒' },
  { name: '上汤枸杞叶', tags: ['healthy'], note: '枸杞叶做汤，皮蛋少许幼儿不食' },
  { name: '白灼灰灰菜', tags: ['healthy'], note: '焯水弃汁少食，光敏者别碰' },
  { name: '蒜蓉紫菜薹', tags: ['healthy', 'diabetes'], note: '红菜薹冬令珍贵，蒜蓉炒脆甜紫汁' },
  { name: '清炒莼菜', tags: ['healthy', 'gout'], note: '太湖莼菜滑如绸，清汤最鲜低热量' },
  { name: '清炒南瓜苗', tags: ['healthy'], note: '掐南瓜嫩尖蒜蓉炒，夏秋微甜清火' },
  { name: '白灼紫苏叶', tags: ['healthy'], note: '紫苏叶香气独特，焯水蘸酱解腥增香' },
  { name: '蒜蓉炒落葵', tags: ['healthy'], note: '紫滑微黏补铁好蔬，蒜蓉大火快炒' },
  { name: '清炒野荠菜', tags: ['healthy'], note: '野菜选可靠来源，洗净焯水' },
  { name: '蚝油紫叶甜菜', tags: ['healthy'], note: '含花青素，蚝油少量不另加盐' },
  { name: '雪菜炒豆干', tags: ['healthy'], note: '腌鲜雪菜少盐水洗，配豆干炒提香' },
  { name: '清炒香椿芽', tags: ['healthy'], note: '四月的香椿金芽，焯水炒蛋最香' },
  { name: '蒜蓉穿心莲', tags: ['healthy'], note: '蒜蓉快炒微苦蔬菜，苦味少量' },
  { name: '白灼空心菜梗', tags: ['healthy', 'diabetes'], note: '只取脆梗切段白灼，腐乳蘸着吃' },
  { name: '上汤荠菜', tags: ['healthy'], note: '荠菜入清汤，皮蛋仅少许' },
  { name: '清蒸黄辣丁', tags: ['healthy', 'diabetes'], note: '小河鱼嫩无大刺，葱姜紫苏简单蒸' },
  { name: '滑炒鱼片', tags: ['healthy'], note: '薄鱼片蛋清浆过，滑炒嫩滑少油' },
  { name: '清蒸昂刺鱼', tags: ['healthy'], note: '昂刺鱼个头小，蒸出来肉细无腥气' },
  { name: '白灼鱿鱼圈', tags: ['healthy'], note: '鱿鱼切圈焯几秒，蘸芥末酱油Q弹' },
  { name: '清蒸泥鳅', tags: ['healthy', 'diabetes'], note: '河中小鲜泥鳅，紫苏姜丝蒸出鲜味' },
  { name: '蒜蓉蒸花甲', tags: ['healthy'], note: '花甲蒸到开口，蒜蓉粉丝铺底鲜甜' },
  { name: '白灼章鱼足', tags: ['healthy'], note: '章鱼足务必烫熟，勿食半生' },
  { name: '清蒸海鲈鱼', tags: ['healthy'], note: '海鲈刺少肉肥，豉油葱丝清蒸最鲜' },
  { name: '葱姜炒蛏子', tags: ['healthy'], note: '蛏子爆炒吐汁，葱姜蒜大火快翻' },
  { name: '清蒸小鲍鱼', tags: ['healthy'], note: '小鲍切花刀铺蒜蓉，蒸弹牙一口鲜' },
  { name: '韭菜炒河虾', tags: ['healthy'], note: '小河虾连壳嚼脆，韭菜辛香提鲜' },
  { name: '清蒸草鱼段', tags: ['healthy', 'gout'], note: '草鱼切段蒸，缓解期少量' },
  { name: '白灼海螺片', tags: ['healthy', 'diabetes'], note: '螺片煮至刚熟，勿食半生' },
  { name: '番茄炖巴沙鱼', tags: ['healthy'], note: '巴沙鱼片嫩无刺，茄汁炖酸甜下饭' },
  { name: '清蒸青口贝', tags: ['healthy'], note: '青口蒸到张口，柠檬蒜蓉去腥鲜' },
  { name: '清蒸金鲳鱼', tags: ['healthy'], note: '金鲳肉厚少刺，豉油热油最后淋上' },
  { name: '滑炒墨鱼片', tags: ['healthy'], note: '墨鱼白嫩切花片，配荷兰豆快炒脆' },
  { name: '清蒸黑鱼片', tags: ['healthy'], note: '黑鱼片薄如纸，清蒸细嫩不放酸菜' },
  { name: '白灼鲜贝柱', tags: ['healthy'], note: '扇贝柱白灼蘸酱油，鲜甜弹牙原味' },
  { name: '清蒸鲫鱼', tags: ['healthy'], note: '小鲫鱼蒸到骨肉分离，葱姜去腥鲜' },
  { name: '蒜蓉蒸元贝', tags: ['healthy'], note: '元贝比扇贝肥，蒜蓉粉丝蒸出鲜汁' },
  { name: '清蒸昂公鱼', tags: ['healthy'], note: '昂公鱼头大肉嫩，家常红烧或清蒸' },
  { name: '荠菜拌豆腐', tags: ['healthy', 'diabetes'], note: '焯水荠菜碎撒在嫩豆腐上，清香鲜' },
  { name: '肉末酿豆腐', tags: ['healthy', 'diabetes'], note: '豆腐掏洞塞薄肉馅，蒸出来嫩滑鲜' },
  { name: '番茄蛋花豆腐羹', tags: ['healthy'], note: '豆腐切丁蛋花飘，番茄浓汁暖胃鲜' },
  { name: '小葱拌豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '嫩豆腐适量，香油少许提豆香' },
  { name: '五香豆腐干', tags: ['healthy', 'diabetes', 'gout'], note: '豆干适量，卤汁慢煮切丁' },
  { name: '白菜炖冻豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '冻豆腐适量吸汁，白菜炖一锅' },
  { name: '素鸡炒青菜', tags: ['healthy'], note: '素鸡先焯水去油，不再煎' },
  { name: '千张包肉', tags: ['healthy'], note: '薄豆皮裹肉馅蒸熟，少油版红烧鲜' },
  { name: '豆花鱼片（清汤）', tags: ['healthy'], note: '嫩豆花配薄鱼片，清汤低脂鲜滑' },
  { name: '鸡蛋炒碎豆腐', tags: ['healthy'], note: '碎豆腐裹蛋液炒，嫩香低脂快手下饭' },
  { name: '腐竹炒芹菜', tags: ['healthy', 'diabetes'], note: '腐竹泡软有嚼头，芹菜脆爽少油炒' },
  { name: '毛豆炒香干', tags: ['healthy', 'diabetes'], note: '双豆蛋白组合，毛豆鲜香干弹牙' },
  { name: '素什锦拌菜', tags: ['healthy'], note: '腐竹木耳花生面筋丁，卤汁凉拌' },
  { name: '鱼豆腐炒韭菜', tags: ['healthy'], note: '韭菜辛香配弹嫩鱼豆腐，快手小炒' },
  { name: '蒸蛋豆腐盅', tags: ['healthy', 'diabetes'], note: '内酯豆腐掏空打蛋蒸，嫩上加嫩' },
  { name: '豆干炒蒜苗', tags: ['healthy', 'diabetes'], note: '蒜苗辛香豆干有嚼头，少油快炒' },
  { name: '丝瓜炖面筋', tags: ['healthy'], note: '丝瓜清甜面筋吸汁，夏天炖一锅' },
  { name: '百叶包鸡丝', tags: ['healthy'], note: '薄百叶裹嫩鸡丝蒸切，造型鲜爽' },
  { name: '冻豆腐菌菇汤', tags: ['healthy'], note: '冻豆腐吸满菌菇鲜汤，低脂暖身' },
  { name: '豆皮卷时蔬', tags: ['healthy'], note: '千张皮卷胡萝卜黄瓜丝，蒸好切段' },
  { name: '腐乳蒸白豆腐', tags: ['healthy'], note: '腐乳半块提味，不再加盐' },
  { name: '香椿拌豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '嫩豆腐适量，香椿焯水拌' },
  { name: '什锦小炒', tags: ['healthy'], note: '玉米胡萝卜青椒丁，色香味全少油炒' },
  { name: '荷兰豆炒百合', tags: ['healthy', 'gout'], note: '荷兰豆脆绿百合白，少油小炒' },
  { name: '胡萝卜炒西葫芦', tags: ['healthy', 'diabetes', 'gout'], note: '橙绿相间好看，少油快炒清甜脆嫩' },
  { name: '莴笋炒豆皮', tags: ['healthy', 'diabetes'], note: '莴笋脆绿豆皮柔韧，蒜蓉生抽炒香' },
  { name: '青椒炒藕丁', tags: ['healthy', 'diabetes'], note: '藕丁脆甜配青椒圈，大火快炒低脂' },
  { name: '蒜香焖四季豆', tags: ['healthy'], note: '四季豆焖到熟透，蒜香入味少油版' },
  { name: '西芹炒花生米', tags: ['healthy'], note: '西芹脆花生香，经典小炒下酒菜' },
  { name: '木耳炒笋片', tags: ['healthy', 'diabetes'], note: '木耳脆笋片嫩，双脆搭配清肠刮油' },
  { name: '小炒秋葵蛋', tags: ['healthy', 'diabetes'], note: '秋葵切片配蛋碎，脆滑结合快手炒' },
  { name: '黄瓜炒肉片', tags: ['healthy'], note: '黄瓜清甜肉片薄嫩，少油快炒下饭' },
  { name: '洋葱炒木耳', tags: ['healthy', 'diabetes'], note: '洋葱微甜木耳脆口，少油家常小炒' },
  { name: '小炒藕带', tags: ['healthy'], note: '夏天嫩藕带脆生生，酸辣大火快炒' },
  { name: '韭菜炒绿豆芽', tags: ['healthy', 'diabetes'], note: '豆芽水灵韭菜香，两分钟出锅快手' },
  { name: '彩椒炒豆干丁', tags: ['healthy', 'diabetes'], note: '三色椒配豆干丁，好看好吃蛋白够' },
  { name: '西芹炒鲜百合', tags: ['healthy', 'gout'], note: '芹菜脆百合粉，少油清炒' },
  { name: '丝瓜炒毛豆仁', tags: ['healthy', 'diabetes'], note: '丝瓜软嫩毛豆甜，夏天清炒低脂鲜' },
  { name: '西葫芦炒粉丝', tags: ['healthy'], note: '瓜片软粉丝弹，吸了汤汁鲜香家常' },
  { name: '蒜苔炒鸡杂', tags: ['healthy'], note: '鸡杂是内脏，偶尔小份痛风慎' },
  { name: '小炒素三鲜', tags: ['healthy'], note: '木耳黄瓜鸡蛋同炒，清爽鲜香快' },
  { name: '紫薯燕麦粥', tags: ['healthy', 'gout'], note: '紫薯切丁拌燕麦，早餐绵滑微甜饱' },
  { name: '荞麦蒸饺（素馅）', tags: ['healthy', 'diabetes'], note: '荞麦面皮裹时蔬馅，蒸出来清爽' },
  { name: '玉米面发糕', tags: ['healthy', 'diabetes'], note: '粗粮发糕松软，不加糖也能当早餐' },
  { name: '蒸芋头蘸酱油', tags: ['healthy', 'diabetes'], note: '芋头蒸到粉糯，蘸一点鲜酱油就好' },
  { name: '南瓜燕麦粥', tags: ['healthy', 'gout'], note: '南瓜蒸烂拌燕麦，绵滑自然甜暖胃' },
  { name: '全麦蔬菜饼', tags: ['healthy'], note: '全麦面糊摊薄饼卷蔬菜，少油煎' },
  { name: '糯米蒸藕', tags: ['healthy'], note: '蒸藕清淡，桂花蜜可省' },
  { name: '糙米蔬菜饭团', tags: ['healthy', 'diabetes'], note: '糙米饭捏成团裹海苔，带饭上班吃' },
  { name: '红豆薏米水', tags: ['healthy'], note: '红豆薏米煮水，少糖代茶' },
  { name: '蔬菜蛋花面片汤', tags: ['healthy'], note: '手擀面片配蛋花青菜，清淡一碗' },
  { name: '蒸山药泥', tags: ['healthy', 'diabetes', 'gout'], note: '山药蒸烂压泥，当早吃一碗' },
  { name: '番茄鸡蛋面片', tags: ['healthy'], note: '北方家常面片汤，番茄蛋花酸甜' },
  { name: '杂粮粥（无糖）', tags: ['healthy', 'diabetes'], note: '十几种杂粮一锅煮，仍算碳水' },
  { name: '蒸南瓜百合', tags: ['healthy', 'gout'], note: '南瓜清甜百合粉糯，蒸出来低脂' },
  { name: '玉米碴糊糊', tags: ['healthy', 'gout'], note: '细玉米碴熬到黏稠，北方老式早餐' },
  { name: '清炖乌鸡汤（去皮）', tags: ['healthy'], note: '乌鸡去皮撇净油，喝清汤' },
  { name: '蒜爆鸡胸丁', tags: ['healthy'], note: '鸡胸切丁蒜香裹，少油煎嫩不柴' },
  { name: '荷叶包鸡', tags: ['healthy'], note: '荷叶裹住鸡肉香，蒸制少油清爽' },
  { name: '柠檬烤鸡腿（去皮）', tags: ['healthy', 'diabetes'], note: '柠檬去腥鸡腿嫩，去皮烤少油香' },
  { name: '药膳蒸鸭', tags: ['healthy'], note: '黄芪蒸鸭，孕哺婴幼儿遵医嘱' },
  { name: '清炒虾仁', tags: ['healthy', 'diabetes'], note: '蛋清浆虾仁滑嫩，不放重料鲜甜' },
  { name: '孜然鸡胸肉片', tags: ['healthy'], note: '孜然粉裹鸡胸片，少油煎到焦边香' },
  { name: '白卤鹅翅（适量）', tags: ['healthy'], note: '白卤不加糖色，鹅翅撕着吃低脂' },
  { name: '葱烤大排（少油）', tags: ['healthy'], note: '葱香猪大排，少油版嫩烤不煎炸' },
]
