// 「今天吃什么」分片：糖尿病低GI（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const DIABETES_DISHES: FoodDish[] = [
  { name: '荞麦米饭', tags: ['diabetes', 'gout'], note: '荞麦掺米煮，低GI主食' },
  { name: '燕麦杂豆饭', tags: ['diabetes', 'gout'], note: '杂豆饭整豆少量，算进主食' },
  { name: '玉米面杂豆馒头', tags: ['diabetes', 'gout'], note: '豆面适量掺，馒头算主食控量' },
  { name: '荞麦煎饼（无糖）', tags: ['diabetes', 'gout'], note: '荞麦摊糊饼，酱料少放无糖' },
  { name: '荞麦蒸饺', tags: ['diabetes'], note: '荞麦皮蒸饺，菜馅为主' },
  { name: '黑麦面包', tags: ['diabetes'], note: '选真黑麦粉为主，看配料表' },
  { name: '全麦烧饼（无糖）', tags: ['diabetes', 'gout'], note: '无糖款才可选，别多吃' },
  { name: '全麦水煎包（少油）', tags: ['diabetes'], note: '全麦皮少油煎，菜馅优先' },
  { name: '杂粮包子（全麦皮）', tags: ['diabetes'], note: '全麦皮素馅，控糖早餐' },
  { name: '大麦仁饭', tags: ['diabetes'], note: '嚼劲足，整粒大麦煮透当主食' },
  { name: '大麦杂豆饭', tags: ['diabetes'], note: '大麦加杂豆，掺一半白米算主食' },
  { name: '小麦粒饭', tags: ['diabetes'], note: '整粒小麦煮透，一小碗替代白米' },
  { name: '青稞杂豆饭', tags: ['diabetes', 'gout'], note: '青稞配杂豆，整豆少量算主食' },
  { name: '黑米杂粮饭', tags: ['diabetes', 'gout'], note: '黑米掺白米，花青素多' },
  { name: '玉米杂豆饭', tags: ['diabetes', 'gout'], note: '玉米豌豆掺米，低GI饱腹' },
  { name: '酸汤莜面鱼鱼', tags: ['diabetes'], note: '莜面一小碗算主食，酸汤少油' },
  { name: '通心粉拌蔬菜（少油）', tags: ['diabetes', 'gout'], note: '硬质小麦通心粉，GI偏低' },
  { name: '全麦三明治（鸡蛋蔬菜）', tags: ['diabetes'], note: '夹蛋夹菜，别加沙拉酱' },
  { name: '蒸土豆拌茄泥', tags: ['diabetes', 'gout'], note: '凉透升糖更慢，当主食吃' },
  { name: '煮玉米（控半根）', tags: ['diabetes', 'gout'], note: '甜玉米中GI，半根当主食' },
  { name: '蒸荸荠', tags: ['diabetes', 'gout'], note: '替代部分主食，清甜爽口' },
  { name: '清汤鸡丝荞麦面', tags: ['diabetes'], note: '荞麦面配鸡丝，别煮太烂' },
  { name: '荞麦面片汤（清汤）', tags: ['diabetes'], note: '菜多米少，清汤不勾芡' },
  { name: '烤鳕鱼（少油）', tags: ['diabetes'], note: '烤箱少油版，鱼肉细嫩' },
  { name: '柠檬烤三文鱼', tags: ['diabetes'], note: '烤箱逼出油脂，优质脂肪' },
  { name: '香煎带鱼（少油）', tags: ['diabetes'], note: '少油煎香，别挂糊油炸' },
  { name: '盐水煮鸡腿（去皮）', tags: ['healthy', 'diabetes'], note: '鸡腿去皮盐水煮，蛋白实在' },
  { name: '烤鸡胸肉块', tags: ['healthy', 'diabetes'], note: '烤制少油，一次别超一掌' },
  { name: '炖鸡（去皮撇油）', tags: ['diabetes'], note: '去皮撇油，汤别当水喝' },
  { name: '虾仁炒豆腐', tags: ['diabetes'], note: '双蛋白嫩滑，少油清炒' },
  { name: '清蒸鸡蛋羹（少酱油）', tags: ['healthy', 'diabetes', 'gout'], note: '嫩滑好消化，淋汁减量' },
  { name: '五香煮蛋', tags: ['diabetes', 'gout'], note: '水煮加香料，无糖低嘌呤' },
  { name: '炖蛋（牛奶蒸蛋）', tags: ['diabetes', 'gout'], note: '牛奶代水蒸蛋，嫩滑好消化' },
  { name: '炒豆腐皮', tags: ['diabetes', 'gout'], note: '豆皮切条快炒，蛋白要适量' },
  { name: '蒸豆腐条', tags: ['diabetes', 'gout'], note: '老豆腐蒸透蘸生抽，豆制品适量' },
  { name: '无糖豆腐花', tags: ['diabetes', 'gout'], note: '咸口无糖嫩滑，豆制品适量' },
  { name: '少油卤汁鸡蛋干', tags: ['diabetes'], note: '卤香蛋干，看配料表选' },
  { name: '五香煮毛豆', tags: ['healthy', 'diabetes', 'gout'], note: '毛豆带壳五香煮，一小把刚好' },
  { name: '无糖甜豆浆', tags: ['diabetes', 'gout'], note: '无糖淡饮，豆浆一天限一杯' },
  { name: '黑豆豆浆（无糖）', tags: ['diabetes', 'gout'], note: '黑豆打浆无糖，淡饮限一杯' },
  { name: '无糖花生豆浆', tags: ['diabetes', 'gout'], note: '无糖淡饮限一杯，花生一小把' },
  { name: '清煮豌豆（当主食）', tags: ['diabetes', 'gout'], note: '豆类适量算主食，当菜吃要减饭' },
  { name: '蒸鹰嘴豆（少盐）', tags: ['diabetes', 'gout'], note: '鹰嘴豆当主食算，一小把加餐' },
  { name: '水煮扁豆（当主食）', tags: ['diabetes'], note: '扁豆低GI，替代部分米' },
  { name: '五香煮芸豆（适量）', tags: ['diabetes'], note: '芸豆低GI，胀气别贪多' },
  { name: '无糖黑芝麻奶', tags: ['diabetes', 'gout'], note: '黑芝麻少量打浆，无糖' },
  { name: '脱脂牛奶', tags: ['diabetes', 'gout'], note: '脂肪降到零，蛋白质照样在' },
  { name: '白灼芥菜头', tags: ['diabetes', 'gout'], note: '芥菜头白灼，微苦回甘清火' },
  { name: '蒜蓉芥菜', tags: ['diabetes', 'gout'], note: '蒜蓉炒芥菜，微苦清热下火' },
  { name: '白灼苤蓝', tags: ['healthy', 'diabetes', 'gout'], note: '球茎切片灼，脆嫩低卡' },
  { name: '炝炒圆白菜', tags: ['diabetes', 'gout'], note: '圆白菜手撕炝炒，脆爽少油' },
  { name: '清炒油菜', tags: ['healthy', 'diabetes', 'gout'], note: '家常绿叶菜，十分钟出锅' },
  { name: '蒜蓉塔菜', tags: ['diabetes', 'gout'], note: '塔菜冬令脆，少油清炒' },
  { name: '清炒乌菜', tags: ['diabetes', 'gout'], note: '乌菜又叫黑菜，清炒特软嫩' },
  { name: '白灼莙荙菜', tags: ['diabetes', 'gout'], note: '牛皮菜白灼，淋少许豉油' },
  { name: '蒜蓉马齿苋', tags: ['diabetes', 'gout'], note: '马齿苋微酸，焯水后快炒' },
  { name: '清炒紫背天葵', tags: ['diabetes'], note: '小众绿叶菜，清爽少油' },
  { name: '清炒血皮菜', tags: ['diabetes', 'gout'], note: '补血菜名头，清炒脆嫩' },
  { name: '清炒树仔菜', tags: ['diabetes', 'gout'], note: '台湾绿叶菜，急火少油' },
  { name: '白灼菊花脑', tags: ['diabetes', 'gout'], note: '菊花脑白灼，南京人的夏汤' },
  { name: '清炒藜蒿', tags: ['diabetes', 'gout'], note: '鄱阳湖边草，脆香快炒' },
  { name: '清炒芭蕉心', tags: ['diabetes', 'gout'], note: '芭蕉心焯去涩，清炒像笋' },
  { name: '凉拌鹿角菜', tags: ['diabetes'], note: '鹿角菜凉拌脆嫩，几乎无糖' },
  { name: '白灼山苏菜', tags: ['diabetes', 'gout'], note: '山苏是蕨类嫩叶，白灼最稳' },
  { name: '上汤枸杞芽', tags: ['diabetes', 'gout'], note: '春令微苦，素清汤底非肉汤' },
  { name: '清炒萝卜缨', tags: ['diabetes', 'gout'], note: '萝卜叶别扔，微辣脆嫩' },
  { name: '清炒白菜帮', tags: ['diabetes', 'gout'], note: '帮子丝快炒，甜脆低卡' },
  { name: '清炒莴笋丝', tags: ['diabetes', 'gout'], note: '细丝快炒，莴笋低GI' },
  { name: '清炒黄瓜丁', tags: ['diabetes', 'gout'], note: '黄瓜丁低卡清爽，正常控油盐' },
  { name: '蒜蓉冬瓜片', tags: ['diabetes', 'gout'], note: '冬瓜刨片蒜蓉炒，低卡清甜' },
  { name: '白灼黄瓜片', tags: ['diabetes', 'gout'], note: '灼一下更脆，蘸汁少酱' },
  { name: '清炒丝瓜尖', tags: ['diabetes', 'gout'], note: '丝瓜尖急火炒，滑嫩清甜' },
  { name: '番茄菜花炒', tags: ['diabetes', 'gout'], note: '茄汁烩菜花，酸甜少油' },
  { name: '清炒西兰花梗', tags: ['diabetes', 'gout'], note: '西兰花粗梗去皮，切片脆炒' },
  { name: '清炒芥兰叶', tags: ['diabetes', 'gout'], note: '芥兰叶也嫩，少油快炒' },
  { name: '白灼紫角叶', tags: ['diabetes', 'gout'], note: '紫角叶即木耳菜，白灼滑口' },
  { name: '秋葵炒木耳', tags: ['diabetes', 'gout'], note: '秋葵斜切炒木耳，双脆低卡' },
  { name: '秋葵拌木耳', tags: ['diabetes', 'gout'], note: '秋葵木耳焯水同拌，蒜香足' },
  { name: '木耳拌黄花菜', tags: ['diabetes'], note: '黄花菜泡发同拌木耳，很爽口' },
  { name: '木耳拌百叶丝', tags: ['diabetes', 'gout'], note: '百叶丝豆制品适量，木耳不限' },
  { name: '雪魔芋烧白菜', tags: ['diabetes', 'gout'], note: '魔芋多孔吸汁，少油炖' },
  { name: '芥末海带结', tags: ['diabetes', 'gout'], note: '海带一小片泡发，别超一小把' },
  { name: '海带结炖萝卜', tags: ['diabetes', 'gout'], note: '萝卜清甜，海带一小片限量' },
  { name: '裙带菜豆腐汤', tags: ['diabetes', 'gout'], note: '裙带菜一撮豆腐半块，汤清' },
  { name: '凉拌冰草', tags: ['diabetes', 'gout'], note: '冰晶口感，芝麻酱少许' },
  { name: '凉拌竹笋', tags: ['diabetes', 'gout'], note: '竹笋切丝凉拌，脆嫩要焯透' },
  { name: '笋片炒鸡蛋', tags: ['diabetes', 'gout'], note: '笋片炒鸡蛋，鲜上加鲜少油' },
  { name: '清炒芦笋木耳', tags: ['diabetes', 'gout'], note: '芦笋痛风少选，木耳搭脆' },
  { name: '清炒佛手瓜片', tags: ['diabetes', 'gout'], note: '瓜片脆甜，低GI清爽' },
  { name: '凉拌莼菜', tags: ['healthy', 'diabetes', 'gout'], note: '莼菜滑溜，开水烫过就拌' },
  { name: '清炒西葫芦片', tags: ['diabetes', 'gout'], note: '西葫芦低卡，快炒少油少盐' },
  { name: '番茄炒丝瓜', tags: ['diabetes', 'gout'], note: '丝瓜吸茄汁，软嫩清甜' },
  { name: '清炒双菇（口蘑鲜菇）', tags: ['diabetes'], note: '菌菇鲜，少油焖炒（适量）' },
  { name: '杏鲍菇手撕条', tags: ['diabetes'], note: '干煸少油，像吃肉嚼劲' },
  { name: '腌黄瓜（无糖快版）', tags: ['diabetes', 'gout'], note: '无糖快腌，一两块解馋' },
  { name: '无糖茄汁拌番茄', tags: ['diabetes'], note: '醋汁代糖版，酸甜解馋' },
  { name: '番茄西葫芦汤', tags: ['diabetes', 'gout'], note: '西葫芦配番茄，快手素汤' },
  { name: '番茄金针菇蛋汤', tags: ['diabetes', 'gout'], note: '金针菇一小把，少油蛋花提鲜' },
  { name: '番茄冬瓜汤', tags: ['diabetes', 'gout'], note: '冬瓜块煮番茄，淡口又生津' },
  { name: '冬瓜蘑菇汤', tags: ['diabetes', 'gout'], note: '清炖不勾芡（菌菇适量）' },
  { name: '黄瓜豆皮汤', tags: ['diabetes', 'gout'], note: '豆皮两三条适量，汤清味鲜' },
  { name: '黄瓜木耳蛋花汤', tags: ['diabetes', 'gout'], note: '黄瓜木耳蛋花汤，快手清淡' },
  { name: '大白菜心汤', tags: ['diabetes', 'gout'], note: '白菜心撕条煮，甜到心里' },
  { name: '油麦菜蛋汤', tags: ['diabetes', 'gout'], note: '绿叶配蛋花，五分钟汤' },
  { name: '芹菜叶蛋汤', tags: ['diabetes', 'gout'], note: '芹菜叶别扔，清香滑汤' },
  { name: '芥菜豆腐汤', tags: ['diabetes', 'gout'], note: '芥菜豆腐清汤，豆制品适量' },
  { name: '小白菜豆腐汤', tags: ['diabetes', 'gout'], note: '青菜豆腐清汤，豆制品适量少盐' },
  { name: '苦瓜瘦肉汤', tags: ['diabetes'], note: '苦瓜配瘦肉，清火少油别多汤' },
  { name: '山药木耳汤', tags: ['diabetes', 'gout'], note: '山药算主食，汤里少放' },
  { name: '胡萝卜香菇汤', tags: ['diabetes'], note: '汤色金黄（菌菇适量）' },
  { name: '杂菜瘦身汤', tags: ['diabetes', 'gout'], note: '冰箱蔬菜一锅煮，清汤' },
  { name: '无糖罗宋汤', tags: ['diabetes'], note: '甜菜根番茄，不加糖不勾芡' },
  { name: '清炖小黄鱼（少油）', tags: ['diabetes'], note: '清炖不放煎，痛风少喝汤' },
  { name: '文蛤豆腐汤（少量）', tags: ['diabetes'], note: '贝类嘌呤高，解馋两三只' },
  { name: '鲫鱼萝卜丝汤', tags: ['diabetes'], note: '汤鲜不奶白浓炖，适量' },
  { name: '泥鳅豆腐汤', tags: ['diabetes'], note: '高蛋白低脂，痛风缓解期适量' },
  { name: '鸡蛋豆腐汤', tags: ['diabetes', 'gout'], note: '蛋花豆腐汤，豆制品适量' },
  { name: '瘦肉青菜汤（去油）', tags: ['diabetes'], note: '瘦肉末青菜，撇净浮油' },
  { name: '去油鸡汤（撇油少量）', tags: ['diabetes'], note: '去皮撇油，吃肉为主喝汤辅' },
  { name: '扁豆土豆汤（少料）', tags: ['diabetes'], note: '扁豆低GI，土豆当主食' },
  { name: '燕麦麸牛奶粥', tags: ['diabetes', 'gout'], note: '选需煮燕麦麸，别用即食冲调' },
  { name: '黑米燕麦粥（豆多米少）', tags: ['diabetes'], note: '黑米加燕麦熬，豆多米少' },
  { name: '红豆薏米燕麦粥（无糖）', tags: ['diabetes'], note: '红豆薏米燕麦原粒需煮，无糖小碗' },
  { name: '绿豆薏米粥（无糖）', tags: ['diabetes', 'gout'], note: '绿豆薏米为主，无糖小碗偶尔' },
  { name: '红绿豆燕麦粥（无糖）', tags: ['diabetes'], note: '双豆压半烂，燕麦收汁' },
  { name: '鹰嘴豆燕麦粥（无糖）', tags: ['diabetes', 'gout'], note: '鹰嘴豆燕麦原粒需煮，无糖半碗' },
  { name: '芸豆杂粮粥（无糖）', tags: ['diabetes'], note: '白芸豆配米，一小碗就够' },
  { name: '扁豆杂粮粥（无糖）', tags: ['diabetes'], note: '白扁豆煮开花，米放一点点' },
  { name: '豌豆玉米碴粥（无糖）', tags: ['diabetes'], note: '豌豆玉米碴为主，小碗别熬稀' },
  { name: '青稞燕麦粥（无糖）', tags: ['diabetes'], note: '青稞燕麦掺米豆，原粒需煮小碗' },
  { name: '黑米杂豆粥（无糖）', tags: ['diabetes', 'gout'], note: '杂豆少放米为主，小碗无糖' },
  { name: '荞麦糁粥（无糖）', tags: ['diabetes'], note: '荞麦糁算主食，配蛋白一起吃' },
  { name: '全麦粒粥（无糖）', tags: ['diabetes', 'gout'], note: '整粒小麦慢煮，纤维完整' },
  { name: '小米燕麦杂豆粥（豆多米少）', tags: ['diabetes'], note: '小米别单打，掺豆掺燕麦' },
  { name: '玉米面杂豆粥（豆多米少）', tags: ['diabetes'], note: '玉米面加豆，无糖小碗' },
  { name: '山药燕麦粥（无糖）', tags: ['diabetes', 'gout'], note: '山药算主食，块状别打糊' },
  { name: '南瓜芸豆粥（少南瓜）', tags: ['diabetes'], note: '芸豆当主力，南瓜只提味' },
  { name: '豆浆燕麦粥（无糖）', tags: ['diabetes', 'gout'], note: '豆浆燕麦选原粒非即食，无糖' },
  { name: '牛奶麦片粥（无糖）', tags: ['diabetes', 'gout'], note: '原麦片非即食，牛奶煮' },
  { name: '杂粮豆糊（少而稠）', tags: ['diabetes'], note: '打糊升糖快，半碗尝个味' },
  { name: '桑葚', tags: ['diabetes'], note: '桑葚一小把解馋，两餐间吃' },
  { name: '杨梅（少量）', tags: ['diabetes'], note: '杨梅低糖酸甜，两三颗尝个味' },
  { name: '酸枣（少量）', tags: ['diabetes'], note: '酸枣极酸，几颗尝尝就好' },
  { name: '橄榄（少量鲜食）', tags: ['diabetes'], note: '鲜橄榄少量，腌制品含糖盐别选' },
  { name: '原味核桃仁（两颗）', tags: ['diabetes', 'gout'], note: '优质脂肪，两颗别多吃' },
  { name: '原味巴旦木（一小把）', tags: ['diabetes', 'gout'], note: '杏仁GI低，原味不加盐' },
  { name: '原味开心果（一小把）', tags: ['diabetes'], note: '剥壳慢吃，原味才可选' },
  { name: '原味腰果（小半把）', tags: ['healthy', 'diabetes', 'gout'], note: '生腰果控油，七八颗刚好' },
  { name: '原味榛子（几颗）', tags: ['diabetes'], note: '原味榛子香浓，一次几颗' },
  { name: '原味夏威夷果（两颗）', tags: ['diabetes'], note: '夏威夷果油脂高，两颗解馋' },
  { name: '原味南瓜子（小把）', tags: ['diabetes'], note: '补锌小零食，无盐原味' },
  { name: '原味葵花籽仁（小把）', tags: ['diabetes', 'gout'], note: '磕仁别磕袋，小把封顶' },
  { name: '原味花生（一小把）', tags: ['diabetes', 'gout'], note: '水煮最佳，油炸放盐都不行' },
  { name: '无糖酸奶拌蓝莓', tags: ['diabetes'], note: '无糖酸奶，莓果十几颗' },
  { name: '无糖酸奶拌草莓', tags: ['diabetes'], note: '草莓切片，代替甜品碗' },
  { name: '无糖酸奶（奇亚籽泡）', tags: ['diabetes'], note: '奇亚籽泡酸奶，泡开来稠稠的' },
  { name: '无糖可可酸奶', tags: ['diabetes'], note: '纯可可粉拌，微苦解馋' },
  { name: '低脂奶酪（一小块）', tags: ['diabetes', 'gout'], note: '奶酪补钙，一小块看钠量' },
  { name: '水煮鹌鹑蛋（三颗）', tags: ['diabetes', 'gout'], note: '小蛋高蛋白，三颗刚好' },
  { name: '草莓番茄（无糖）', tags: ['diabetes', 'gout'], note: '代糖拌番茄，别当零食多吃' },
  { name: '柠檬黄瓜水（无糖）', tags: ['diabetes', 'gout'], note: '柠檬黄瓜泡白水，零糖解腻' },
  { name: '西芹苹果汁（少苹果）', tags: ['diabetes'], note: '芹菜为主，果汁别滤渣' },
  { name: '无糖绿豆汤（豆少半碗）', tags: ['diabetes'], note: '不加糖，连豆一起吃更稳' },
  { name: '栗子（两三颗）', tags: ['diabetes', 'gout'], note: '栗子淀粉足，替代部分主食' },
  { name: '凉拌黄瓜豆腐丝', tags: ['diabetes', 'gout'], note: '清爽凉菜，豆腐丝豆制品适量' },
  { name: '凉拌西芹腐竹（适量）', tags: ['diabetes'], note: '芹菜脆，腐竹豆制品适量' },
  { name: '凉拌白萝卜丝', tags: ['diabetes', 'gout'], note: '萝卜丝盐腌，醋拌开胃' },
  { name: '凉拌心里美萝卜丝', tags: ['diabetes', 'gout'], note: '紫红丝脆辣，醋香解腻' },
  { name: '凉拌圆白菜', tags: ['diabetes', 'gout'], note: '手撕包菜生拌，酸甜少酱' },
  { name: '凉拌茼蒿', tags: ['diabetes', 'gout'], note: '茼蒿焯水凉拌，清香独特' },
  { name: '凉拌芹菜叶', tags: ['diabetes', 'gout'], note: '芹菜叶比茎香，烫过凉拌' },
  { name: '凉拌油菜心', tags: ['diabetes', 'gout'], note: '小油菜烫后凉拌，脆嫩少酱' },
  { name: '凉拌塔菜', tags: ['diabetes', 'gout'], note: '冬塔菜生拌，芝麻少许' },
  { name: '凉拌豇豆段', tags: ['diabetes', 'gout'], note: '豇豆烫透切段，蒜末麻油拌' },
  { name: '凉拌韭菜姜丝', tags: ['diabetes', 'gout'], note: '韭菜烫熟拌姜丝，开胃少量' },
  { name: '凉拌豆芽粉丝', tags: ['diabetes', 'gout'], note: '豆芽焯脆拌粉丝，醋香爽口' },
  { name: '凉拌莴笋粉丝', tags: ['diabetes', 'gout'], note: '莴笋丝配粉丝，醋香脆爽' },
  { name: '凉拌莴笋百叶', tags: ['diabetes', 'gout'], note: '莴笋配千张百叶，豆制品适量' },
  { name: '凉拌苦瓜黄瓜', tags: ['diabetes', 'gout'], note: '苦瓜黄瓜同拌，冰镇更脆' },
  { name: '凉拌丝瓜（冰镇）', tags: ['diabetes', 'gout'], note: '嫩丝瓜烫熟冰镇，入口滑溜' },
  { name: '凉拌茄条（蒜泥）', tags: ['diabetes', 'gout'], note: '整条蒸茄撕条，蒜泥浇' },
  { name: '凉拌青椒丝', tags: ['diabetes', 'gout'], note: '青椒切丝烫软，微辣脆爽' },
  { name: '凉拌菠菜菌菇（适量）', tags: ['diabetes'], note: '菠菜菌菇拌木耳，适量就好' },
  { name: '凉拌双耳', tags: ['healthy', 'diabetes', 'gout'], note: '黑木耳银耳同拌，脆糯' },
  { name: '凉拌海带结黄瓜', tags: ['diabetes', 'gout'], note: '泡发海带一小把上限，拍黄瓜' },
  { name: '凉拌裙带菜', tags: ['diabetes', 'gout'], note: '干裙带菜少量泡发，少盐凉拌' },
  { name: '凉拌魔芋块', tags: ['diabetes', 'gout'], note: '魔芋切块，蒜醋汁零脂' },
  { name: '凉拌千张丁芹菜', tags: ['diabetes', 'gout'], note: '千张切丁芹菜同拌，豆制品适量' },
  { name: '凉拌五香豆干', tags: ['diabetes', 'gout'], note: '五香豆干适量，一两块封顶' },
  { name: '紫甘蓝拌豆腐丝', tags: ['diabetes', 'gout'], note: '紫甘蓝拌豆皮丝，豆制品适量' },
  { name: '番茄拌魔芋', tags: ['diabetes', 'gout'], note: '茄泥拌魔芋，酸甜零脂' },
  { name: '轻食波奇饭（杂粮底）', tags: ['diabetes'], note: '杂粮底多菜，酱料另放' },
  { name: '食堂控糖套餐（杂粮饭+双菜一蛋白）', tags: ['diabetes'], note: '先菜后肉再饭，米饭半份' },
  { name: '低脂芝士片（夹全麦）', tags: ['diabetes'], note: '低脂芝士夹全麦，一片提香' },
  { name: '荞麦冷面（过水，酱减半）', tags: ['diabetes'], note: '不喝甜汤底，荞麦看配料' },
  { name: '泡鲁达替代版（无糖椰奶）', tags: ['diabetes'], note: '选无糖需煮燕麦自烤，别多吃' },
]
