// 「今天吃什么」分片：外卖版全国地方小吃与便利店（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const TAKEOUT_LOCAL_DISHES: FoodDish[] = [
  { name: '傣味包烧', tags: ['healthy', 'takeout'], note: '芭蕉叶包香茅烤鱼，烤制' },
  { name: '遵义豆花面', tags: ['healthy', 'takeout'], note: '宽面配嫩豆花，蘸水油辣少蘸' },
  { name: '客家算盘子', tags: ['healthy', 'takeout'], note: '芋头木薯粉搓珠，炒咸香' },
  { name: '莜面饨饨', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '莜面卷素馅蒸煮，西北控糖主食' },
  { name: '沔阳三蒸', tags: ['healthy', 'takeout'], note: '粉蒸鱼猪肉三样，软糯不油' },
  { name: '龙岩清汤粉', tags: ['healthy', 'takeout'], note: '米粉配清汤，加肉末酸菜' },
  { name: '肇庆裹蒸粽', tags: ['healthy', 'takeout'], note: '荷叶包绿豆五花肉，个大' },
  { name: '桂林恭城油茶', tags: ['healthy', 'takeout'], note: '油茶炒米花生，咸香回甘' },
  { name: '楚雄羊汤锅', tags: ['healthy', 'takeout'], note: '带骨羊汤锅，浓汤痛风慎' },
  { name: '昭通小肉串', tags: ['healthy', 'takeout'], note: '现串牛肉小把烧，蘸酱辣' },
  { name: '普洱豆汤米干', tags: ['healthy', 'takeout'], note: '豌豆糊泡米干，配卤料' },
  { name: '糌粑', tags: ['healthy', 'diabetes', 'takeout', 'gout'], note: '青稞面拌酥油茶捏团，顶饱' },
  { name: '镇江肴肉', tags: ['healthy', 'takeout'], note: '水晶蹄髈冻冷盘，腌制高脂少量' },
  { name: '湖州千张包', tags: ['healthy', 'takeout'], note: '百叶裹肉馅，配汤煮或蒸' },
  { name: '温州灯盏糕', tags: ['healthy', 'takeout'], note: '萝卜丝鸡蛋油炸盏，外酥内嫩' },
  { name: '玉林牛巴', tags: ['healthy', 'takeout'], note: '卤香牛肉干甜韧，多为预包装特产' },
  { name: '兴义刷把头', tags: ['healthy', 'takeout'], note: '干笋竹笋烧卖，蕨粉皮' },
  { name: '太原剔尖', tags: ['takeout'], note: '筷子旋出鱼形面，浇西红柿卤' },
  { name: '大同猫耳朵', tags: ['takeout'], note: '拇指捻小面卷，配羊肉臊子' },
  { name: '浑源凉粉', tags: ['takeout'], note: '土豆凉粉配莲花豆，醋辣爽口' },
  { name: '闻喜煮饼', tags: ['takeout'], note: '外壳翻砂蜜甜糯，多为预包装' },
  { name: '太谷饼', tags: ['takeout'], note: '晋商茶点外酥内绵，多为预包装' },
  { name: '平遥牛肉', tags: ['takeout'], note: '酱卤牛腱冷盘，痛风期少啃' },
  { name: '山西过油肉', tags: ['takeout'], note: '醋香爆炒里脊片，油大配饭狠' },
  { name: '泡泡油糕', tags: ['takeout'], note: '炸到鼓泡裹枣泥，趁热才脆' },
  { name: '羊杂割', tags: ['takeout'], note: '内脏浓汤驱寒，高嘌呤别贪碗' },
  { name: '忻州蒸肉', tags: ['takeout'], note: '小米裹肉粉蒸，配白菜垫底' },
  { name: '上党驴肉甩饼', tags: ['takeout'], note: '长治卷驴肉薄饼，焦香带葱' },
  { name: '晋城烧豆腐', tags: ['takeout'], note: '铁板卤水豆腐，砂锅煲热' },
  { name: '呼和浩特烧麦', tags: ['takeout'], note: '羊肉大葱皮薄如蝶，一笼管饱' },
  { name: '手把羊肉', tags: ['takeout'], note: '清煮蘸韭菜花，红肉高嘌呤适量' },
  { name: '莜面窝窝（内蒙）', tags: ['takeout', 'diabetes'], note: '羊肉汤灌窝窝，油大汤少喝' },
  { name: '蒙古锅茶', tags: ['takeout'], note: '砖茶加奶炒米，咸香顶饱' },
  { name: '巴盟烩酸菜', tags: ['takeout'], note: '腌酸菜烩肉土豆，汤咸控钠' },
  { name: '赤峰对夹', tags: ['takeout'], note: '酥饼夹熏猪肉，油香当正餐' },
  { name: '草原酸奶（咸口）', tags: ['healthy', 'takeout'], note: '无糖发酵浓稠，蛋白高解腻' },
  { name: '奶嚼口拌炒米', tags: ['takeout'], note: '奶皮拌炒米，糖脂偏高浅尝' },
  { name: '呼伦贝尔羊排', tags: ['takeout'], note: '炭烤肥瘦相间，痛风适量吃' },
  { name: '锦州烧烤', tags: ['takeout'], note: '生烤海鲜肉类刷酱，全国独一份' },
  { name: '炒鸡架', tags: ['takeout'], note: '沈阳铁板鸡架，甜辣带焦边' },
  { name: '老边饺子', tags: ['takeout'], note: '沈阳汤馅水饺，皮薄汁水多' },
  { name: '大连焖子', tags: ['takeout'], note: '地瓜粉煎坨淋麻酱蒜汁，外焦里糯' },
  { name: '鞍山肉枣', tags: ['takeout'], note: '枣形小熏肠，多为礼盒，钠高少量' },
  { name: '朝鲜族温面', tags: ['takeout'], note: '玉米细面配温汤，酸爽暖胃' },
  { name: '大连虾酱豆腐', tags: ['takeout'], note: '虾酱炒豆腐咸鲜，控钠少量' },
  { name: '辽阳小市羊汤', tags: ['takeout'], note: '白汤羊肉泡饼，浓汤痛风慎' },
  { name: '吉林煎粉', tags: ['takeout'], note: '煎地瓜粉块拌蒜辣，焦香软糯' },
  { name: '延边米肠', tags: ['takeout'], note: '猪肠灌糯米蒸，切片蘸辣酱' },
  { name: '吉林市酱骨架', tags: ['takeout'], note: '酱大骨吸骨髓，浓汤痛风慎' },
  { name: '公主岭白皮蒜（腌蒜）', tags: ['takeout'], note: '腌白皮蒜配粥，钠高解馋少量' },
  { name: '齐齐哈尔烤肉', tags: ['takeout'], note: '拌肉铁盘自烤，蘸干料吃' },
  { name: '大庆坑烤', tags: ['takeout'], note: '地坑焖烤鸡蛋土豆，焦香' },
  { name: '东北大饭包', tags: ['takeout'], note: '白菜叶包二米饭鸡蛋酱，一口闷' },
  { name: '黑河俄罗斯列巴', tags: ['takeout'], note: '大列巴果仁面包，酸甜耐存' },
  { name: '肇东小饼', tags: ['takeout'], note: '烤饼夹葱抹酱卷火腿' },
  { name: '哈尔滨烤鹅', tags: ['takeout'], note: '果木熏烤整鹅，皮脆肉厚' },
  { name: '淮安茶馓', tags: ['takeout'], note: '细面盘炸脆，撒葱花当零嘴' },
  { name: '苏州酒酿饼', tags: ['takeout'], note: '酵面团烙豆沙馅，春天限' },
  { name: '南京牛肉锅贴', tags: ['takeout'], note: '七分煎底脆皮，灌汁牛肉馅' },
  { name: '无锡排骨面', tags: ['takeout'], note: '酱排骨浇汤面，甜咸浓口' },
  { name: '常州麻糕', tags: ['takeout'], note: '葱油千层烧饼，酥到掉渣' },
  { name: '南通跳面', tags: ['takeout'], note: '小竹面和浇头，汤浓面弹' },
  { name: '泰州鱼汤面', tags: ['takeout'], note: '鲫鱼熬奶白汤，浓汤痛风适量' },
  { name: '盐城藕粉圆子', tags: ['takeout'], note: '藕皮做皮包五仁，甜糯小碗' },
  { name: '昆山奥灶面', tags: ['takeout'], note: '红油爆鱼白汤卤鸭，浇头双拼（痛风适量）' },
  { name: '徐州地锅鸡', tags: ['takeout'], note: '铁锅炖鸡贴饼子，浓油赤酱' },
  { name: '杭州片儿川', tags: ['takeout'], note: '雪菜笋片瘦肉面，鲜掉眉毛' },
  { name: '宁波烤菜', tags: ['takeout'], note: '苔菜慢火糖烤，咸甜软烂' },
  { name: '嘉兴肉粽', tags: ['takeout'], note: '黑猪肉蛋黄粽，糯米油润' },
  { name: '绍兴梅干菜焖肉', tags: ['takeout'], note: '霉干菜吸油脂蒸，咸香下饭' },
  { name: '金华酥饼', tags: ['takeout'], note: '梅干菜猪肉馅，炭炉烤到酥' },
  { name: '衢州搁袋饼', tags: ['takeout'], note: '油条塞进烧饼，刷酱加蛋' },
  { name: '台州食饼筒', tags: ['takeout'], note: '皮韧配菜自选，浇汤汁吃，异于润饼' },
  { name: '丽水敲肉羹', tags: ['takeout'], note: '红薯粉裹肉片羹，滑嫩热乎' },
  { name: '舟山海鲜面', tags: ['takeout'], note: '黄鱼虾米浇面，鲜汤海鲜味' },
  { name: '葱包桧', tags: ['takeout'], note: '葱油条压扁烙，刷甜面酱' },
  { name: '温州杏仁腐', tags: ['takeout'], note: '杏仁凝冻配水果，夏日消暑' },
  { name: '蚌埠烧饼夹里脊', tags: ['takeout'], note: '酥饼裹煎里脊，刷酱加蛋' },
  { name: '安庆江毛水饺', tags: ['takeout'], note: '薄皮鸡汤饺，蘸辣油' },
  { name: '芜湖小笼汤包', tags: ['takeout'], note: '灌汤皮薄带卤，先咬口吸汁' },
  { name: '徽州石头粿', tags: ['takeout'], note: '石头压烙馅饼，豆腐腊肉馅' },
  { name: '宿州撒汤', tags: ['takeout'], note: '麦仁冲鸡蛋糁汤，暖胃早餐' },
  { name: '马鞍山大肉面', tags: ['takeout'], note: '一块厚焖肉铺面，油重香浓' },
  { name: '泉州面线糊', tags: ['takeout'], note: '细面线勾芡汤，加醋肉大肠' },
  { name: '福州肉燕', tags: ['takeout'], note: '猪肉捶皮包馅，形似馄饨' },
  { name: '莆田焖饭', tags: ['takeout'], note: '海米板栗闷米饭，油润咸香' },
  { name: '客家芋子包', tags: ['takeout', 'healthy'], note: '芋泥做皮包肉笋，蒸制软糯' },
  { name: '三明煨豆腐', tags: ['healthy', 'takeout'], note: '白菜豆腐慢煨，清淡鲜甜' },
  { name: '闽南润饼菜', tags: ['takeout'], note: '薄饼卷十样炒菜，撒花生糖' },
  { name: '泉州土笋冻', tags: ['takeout'], note: '沙虫熬成冻，蘸蒜醋芥末（痛风避开）' },
  { name: '厦门满煎糕', tags: ['takeout'], note: '红糖花生夹心煎饼，甜软' },
  { name: '南昌瓦罐汤', tags: ['takeout'], note: '小罐慢煨肉饼汤，浓汤痛风适量' },
  { name: '景德镇冷粉', tags: ['takeout'], note: '粗米粉拌萝卜辣，冰凉酸辣' },
  { name: '萍乡小炒肉', tags: ['takeout'], note: '辣椒炒肉带汤汁，鲜辣费饭' },
  { name: '九江萝卜饼', tags: ['takeout'], note: '面浆煎萝卜丝饼，外酥辣香' },
  { name: '宜春茶油焖鸡', tags: ['takeout'], note: '茶油焖土鸡汤，油大适量' },
  { name: '上饶烫粉', tags: ['takeout'], note: '鲜粉现烫浇肉丝，汤清粉滑' },
  { name: '鹰潭牛肉粉', tags: ['takeout'], note: '麻辣牛肉浇粉，配青菜解腻' },
  { name: '新余水北豆腐', tags: ['healthy', 'gout', 'takeout'], note: '嫩豆腐清煮，豆腐中嘌呤缓解期适量' },
  { name: '抚州芋糍', tags: ['takeout', 'healthy'], note: '芋头捣烂裹米粉，蒸软蘸酱' },
  { name: '淄博烧烤（小饼卷肉）', tags: ['takeout'], note: '小饼卷肉蘸酱加葱，自己卷着吃' },
  { name: '济南油旋', tags: ['takeout'], note: '葱油螺旋小饼，外脆内软' },
  { name: '青岛流亭猪蹄', tags: ['takeout'], note: '酱卤猪蹄冻，痛风少啃' },
  { name: '潍坊肉火烧', tags: ['takeout'], note: '炉烤饼包大葱肉，皮酥肉汁' },
  { name: '临沂糁汤', tags: ['takeout'], note: '牛骨熬糊冲蛋花，浓汤适量' },
  { name: '济宁夹饼', tags: ['takeout'], note: '烧饼夹炸串火腿，刷酱加蛋' },
  { name: '威海鲅鱼煎饺', tags: ['takeout'], note: '鲅鱼馅煎饺，底脆馅鲜' },
  { name: '菏泽吊炉烧饼', tags: ['takeout'], note: '吊炉烤薄饼撒芝麻，配羊汤' },
  { name: '德州保店驴肉', tags: ['takeout'], note: '酱卤驴肉冷盘，高蛋白适量' },
  { name: '菏泽单县羊肉汤', tags: ['takeout'], note: '白汤羊肉泡饼，浓汤痛风慎' },
  { name: '洛阳牛肉汤饼', tags: ['takeout'], note: '黄牛汤泡饼丝，浓汤痛风慎' },
  { name: '安阳扁粉菜', tags: ['takeout'], note: '宽粉熬猪油汤，配豆腐青菜' },
  { name: '信阳焖罐肉', tags: ['takeout'], note: '陶罐焖五花肉，油重少量' },
  { name: '焦作炒怀山药', tags: ['healthy', 'gout', 'takeout'], note: '铁棍山药清炒，健脾清淡' },
  { name: '商丘垛子羊肉', tags: ['takeout'], note: '卤羊压块切片，冷盘蘸蒜汁' },
  { name: '濮阳壮馍', tags: ['takeout'], note: '厚饼烙肉葱，外皮焦香' },
  { name: '恩施张关合渣', tags: ['takeout'], note: '黄豆糊煮小菜，鼎锅烩香' },
  { name: '襄阳大虾面', tags: ['takeout'], note: '油焖大虾浇碱面，鲜辣油重' },
  { name: '荆州鱼糕', tags: ['healthy', 'takeout'], note: '鱼肉打蒸糕，白嫩无刺' },
  { name: '黄石港饼', tags: ['takeout'], note: '芝麻酥饼包冰糖橘饼，甜香' },
  { name: '孝感米酒蛋花', tags: ['takeout'], note: '糊汤米酒冲蛋，酒酿甜暖' },
  { name: '素斋套餐（菌菇时蔬）', tags: ['healthy', 'gout', 'takeout'], note: '菌菇时蔬素炒清淡，菌菇适量' },
  { name: '宜昌红油小面', tags: ['takeout'], note: '碱面浇麻辣红油，早餐重口' },
  { name: '郴州杀猪粉', tags: ['takeout'], note: '鲜猪杂现煮粉，汤浓适量' },
  { name: '邵阳米粉', tags: ['takeout'], note: '粗粉配猪血丸子，辣香厚' },
  { name: '衡阳卤粉', tags: ['takeout'], note: '米粉拌卤汁花生，干拌辣口' },
  { name: '永州喝喝（米糊）', tags: ['takeout'], note: '米糊配酸菜，地方早餐' },
  { name: '吉首米粉', tags: ['takeout'], note: '酸豆角肉末粉，湘西酸辣' },
  { name: '株洲黄贡椒炒肉', tags: ['takeout'], note: '黄贡椒炒肉，鲜辣上头' },
  { name: '顺德伦教糕', tags: ['takeout'], note: '米浆发酵蒸糕，爽滑微酸' },
  { name: '潮汕无米粿', tags: ['takeout'], note: '薯粉皮包韭菜，煎到透明' },
  { name: '佛山盲公丸', tags: ['takeout'], note: '猪肉手打丸子，弹牙浓汤' },
  { name: '湛江牛杂', tags: ['takeout'], note: '卤水牛杂萝卜，内脏高嘌呤急性期避开' },
  { name: '潮州蚝烙', tags: ['takeout'], note: '薯粉煎鲜蚝，蘸鱼露脆边' },
  { name: '台山黄鳝饭', tags: ['takeout'], note: '瓦煲焖鳝鱼饭，焦香锅巴' },
  { name: '广式流沙包', tags: ['takeout'], note: '咸甜馅包点，流心馅糖油偏高少食' },
  { name: '南宁卷筒粉', tags: ['takeout'], note: '米浆蒸皮包肉葱，淋黄皮酱' },
  { name: '柳州螺蛳鸭脚煲', tags: ['takeout'], note: '螺汤焖鸭脚豆腐泡，辣浓' },
  { name: '百色烧鸭粉', tags: ['takeout'], note: '烧鸭切块配米粉，皮脆卤香' },
  { name: '梧州龟苓膏', tags: ['takeout'], note: '苦寒仙草冻炼蜜，清热少量' },
  { name: '钦州猪脚粉', tags: ['takeout'], note: '卤猪脚配米粉，胶质浓汤' },
  { name: '北海越南卷粉', tags: ['takeout'], note: '米皮包木耳肉末，蘸鱼露' },
  { name: '崇左假蒌夹', tags: ['takeout'], note: '假蒌叶裹肉末煎，边地香' },
  { name: '贵港肉汤筒粉', tags: ['takeout'], note: '贵港重五香肉汤浇头，异于卷筒粉' },
  { name: '海口辣汤饭', tags: ['takeout'], note: '胡椒猪杂汤泡饭，暖胃辛辣' },
  { name: '文昌铺前糟粕醋', tags: ['takeout'], note: '酒糟酸汤涮海鲜，酸辣开胃' },
  { name: '海南粉（腌粉）', tags: ['takeout'], note: '细米粉拌十几种料，卤汁浓' },
  { name: '临高烤乳猪', tags: ['takeout'], note: '炭烤皮脆蘸白糖，油重少食' },
  { name: '陵水酸粉', tags: ['takeout'], note: '米烂配酸笋花生，酸香' },
  { name: '三亚港门粉', tags: ['takeout'], note: '细粉配炸鱼汤，鲜香清' },
  { name: '重庆糯米团', tags: ['takeout'], note: '稀豆花裹糯米包油条咸辣' },
  { name: '奉节盬子鸡', tags: ['takeout'], note: '陶盬蒸馏炖鸡，汤清肉烂' },
  { name: '荣昌铺盖面', tags: ['takeout'], note: '宽面片像铺盖，配杂酱' },
  { name: '黔江鸡杂', tags: ['takeout'], note: '泡椒炒鸡杂，脆辣下饭' },
  { name: '合川桃片', tags: ['takeout'], note: '糯米核桃蒸薄糕，预包装甜酥' },
  { name: '荣昌卤鹅', tags: ['takeout'], note: '五香卤鹅肉厚，痛风适量' },
  { name: '武隆碗碗羊肉', tags: ['takeout'], note: '小碗炖羊肉汤，浓汤少喝' },
  { name: '自贡鲜锅兔', tags: ['takeout'], note: '仔姜鲜椒爆兔，辣到跳' },
  { name: '乐山翘脚牛肉', tags: ['takeout'], note: '牛杂清汤蘸干碟，汤鲜适量' },
  { name: '宜宾李庄白肉', tags: ['takeout'], note: '白肉薄片卷蒜泥蘸水，肥口适量' },
  { name: '泸州白糕', tags: ['takeout'], note: '米浆蒸小圆糕，松软微甜（湖北叫碗糕）' },
  { name: '绵阳米粉', tags: ['takeout'], note: '细米粉浇肥肠牛肉臊，麻辣' },
  { name: '南充冬菜肉片', tags: ['takeout'], note: '冬菜炒肉，咸香下饭' },
  { name: '凉山烧烤', tags: ['takeout'], note: '小串五花肉蘸辣椒面，彝家' },
  { name: '雅安挞挞面', tags: ['takeout'], note: '手甩宽面浇肉臊，油重筋道' },
  { name: '成都蛋烘糕', tags: ['takeout'], note: '小蛋糕夹咸甜馅，街边现做' },
  { name: '贵阳肠旺面', tags: ['takeout'], note: '脆哨血旺肥肠面，油重辣' },
  { name: '凯里卷粉', tags: ['takeout'], note: '米皮卷折耳根，淋酸汤' },
  { name: '凯里米豆腐', tags: ['takeout'], note: '米浆凝固切块，浇酸辣汁' },
  { name: '黔西黄粑', tags: ['takeout'], note: '糯米红糖叶包蒸，甜糯' },
  { name: '安顺裹卷', tags: ['takeout'], note: '米皮卷海带酸豇豆，辣酱' },
  { name: '独山盐酸菜', tags: ['takeout'], note: '外卖多是瓶装咸菜，钠高少量' },
  { name: '铜仁社饭', tags: ['takeout'], note: '野葱腊肉糯米焖饭，香咸' },
  { name: '荔波风猪', tags: ['takeout'], note: '风干腊肉烤片，油重适量' },
  { name: '昆明豆花米线', tags: ['takeout'], note: '干浆米线拌豆花生，辣甜' },
  { name: '大理生皮', tags: ['takeout'], note: '火烧猪皮蘸梅子，慎食生' },
  { name: '建水臭豆腐', tags: ['takeout'], note: '烤豆腐蘸干辣椒面，臭香（豆制品适量）' },
  { name: '玉溪冰稀饭', tags: ['takeout'], note: '糯米冰镇浇红糖，暑天甜' },
  { name: '临沧鸡肉米干', tags: ['takeout'], note: '米干配土鸡帽，鲜香' },
  { name: '大理乳扇', tags: ['takeout'], note: '牛奶拉皮烤炸，蘸玫瑰酱' },
  { name: '拉萨甜茶', tags: ['takeout'], note: '酥砖茶冲奶白糖，藏式早茶' },
  { name: '牦牛肉干', tags: ['takeout'], note: '风干牦牛肉有嚼劲，高蛋白' },
  { name: '藏面', tags: ['takeout'], note: '牦牛骨汤配碱面，加辣酱' },
  { name: '鲁朗石锅鸡', tags: ['takeout'], note: '手掌参石锅炖藏鸡，汤浓' },
  { name: '西藏酸奶', tags: ['healthy', 'takeout'], note: '牦牛老酸奶浓酸，选原味或少糖' },
  { name: '林芝藏香猪', tags: ['takeout'], note: '烤藏香猪肋排，油香少食' },
  { name: '日喀则青稞饼', tags: ['takeout'], note: '青稞面烙薄饼，粗粮' },
  { name: '乾县锅盔', tags: ['takeout'], note: '咸阳乾县锅盔，厚实耐嚼' },
  { name: '渭南时辰包子', tags: ['takeout'], note: '油酥皮包肉馅，清晨吃最热' },
  { name: '汉中热面皮', tags: ['takeout'], note: '米浆蒸热面皮，配辣油豆芽' },
  { name: '安康蒸面', tags: ['takeout'], note: '蒸面皮拌豆芽蒜辣，筋' },
  { name: '榆林羊杂碎', tags: ['takeout'], note: '羊杂辣汤泡馍，浓汤痛风慎' },
  { name: '铜川咸汤面', tags: ['takeout'], note: '韭头辣子热汤面，咸香' },
  { name: '西安葫芦头', tags: ['takeout'], note: '猪大肠泡馍，肥浓适量' },
  { name: '陕北滚馍', tags: ['takeout'], note: '羊汤泡馍配辣，暖冬' },
  { name: '兰州灰豆子', tags: ['takeout'], note: '麻色豌豆红枣熬，甜沙' },
  { name: '天水呱呱', tags: ['takeout'], note: '荞凉粉块拌辣油，早餐' },
  { name: '张掖搓鱼面', tags: ['takeout'], note: '面搓小鱼状，炒配肉蔬' },
  { name: '庆城甜胚子', tags: ['takeout'], note: '燕麦酒酿微甜，冰镇' },
  { name: '临夏手抓', tags: ['takeout'], note: '羊肋白煮蘸椒盐，高嘌呤适量' },
  { name: '白银水盆羊肉', tags: ['takeout'], note: '清汤羊肉泡馍，早汤适量' },
  { name: '敦煌驴肉黄面', tags: ['takeout'], note: '细黄面浇驴肉汁，沙州名' },
  { name: '西宁狗浇尿饼', tags: ['takeout'], note: '油酥烙薄饼撒糖，甜脆' },
  { name: '青海焜锅馍', tags: ['takeout'], note: '铁焜烤大馍，外脆内实' },
  { name: '化隆拉面', tags: ['takeout'], note: '清真牛肉拉面，毛细到宽' },
  { name: '热干粉', tags: ['takeout'], note: '土豆凉粉配辣酱，西宁早' },
  { name: '羊肠面', tags: ['takeout'], note: '面灌羊肠配汤，重口适量' },
  { name: '银川烩羊杂', tags: ['takeout'], note: '羊杂辣汤烩，急性期避开缓解少量' },
  { name: '吴忠手抓羊肉', tags: ['takeout'], note: '滩羊白煮蘸蒜，肥嫩高嘌呤' },
  { name: '中卫蒿子面', tags: ['takeout'], note: '蒿粉和面配臊，筋道' },
  { name: '宁夏蒸羊羔', tags: ['healthy', 'takeout'], note: '清蒸小羊肉配葱，少油' },
  { name: '油香', tags: ['takeout'], note: '回族炸油饼，回节食品' },
  { name: '八宝盖碗茶', tags: ['takeout'], note: '红枣枸杞冰糖冲茶，甜饮' },
  { name: '甘草烤羊蹄（宁夏）', tags: ['takeout'], note: '甘草烤羊蹄，回甜不膻' },
  { name: '乌鲁木齐丁丁炒面', tags: ['takeout'], note: '小丁面配菜炒，酸香带辣' },
  { name: '喀什烤蛋', tags: ['takeout'], note: '罐烤鸡蛋灌调料，南疆味' },
  { name: '伊犁马肠子', tags: ['takeout'], note: '熏马肠切片，油香高嘌呤' },
  { name: '和田玛仁糖', tags: ['takeout'], note: '核桃坚果熬糖切块，新疆传统茶点' },
  { name: '新疆汤饭', tags: ['takeout'], note: '羊肉丁面片酸汤，暖身' },
  { name: '馕包肉', tags: ['takeout'], note: '羊肉炖汁浇馕块，浓油' },
  { name: '油塔子', tags: ['takeout'], note: '千层油蒸面点，层层酥软' },
  { name: '米泉凉皮子', tags: ['takeout'], note: '黄面凉皮配辣酱芥末' },
  { name: '便利店饭团（金枪鱼沙拉）', tags: ['takeout'], note: '三角饭团微波加热，快手早餐' },
  { name: '咸蛋黄饭团', tags: ['takeout'], note: '流沙蛋黄馅糯米，油润顶饱' },
  { name: '便利店便当（照烧鸡）', tags: ['takeout'], note: '自热便当浇汁饭，微波两分钟' },
  { name: '轻食便当（鸡胸杂粮）', tags: ['healthy', 'takeout', 'diabetes'], note: '酱料另配，主食不加糖当天吃完' },
  { name: '关东煮魔芋丝', tags: ['healthy', 'gout', 'takeout', 'diabetes'], note: '低卡魔芋结，汤底非素，只吃串' },
  { name: '现打茶叶蛋', tags: ['takeout'], note: '卤汁咸钠高，一天一个适量' },
  { name: '冰杯咖啡', tags: ['takeout'], note: '便利店冰杯倒浓缩，自带奶' },
  { name: '鲜奶杯（冷藏）', tags: ['healthy', 'takeout'], note: '巴氏鲜奶一小杯，补钙' },
  { name: '现磨豆浆（无糖）', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '热饮机接一杯，淡饮限一杯' },
  { name: '冰淇淋甜筒（香草）', tags: ['takeout'], note: '第二支半价，控糖别贪' },
  { name: '冷冻溏心蛋', tags: ['takeout'], note: '即开卤心蛋，加餐补蛋白' },
  { name: '鸡胸肉丸（即食）', tags: ['healthy', 'takeout'], note: '低脂高蛋白，选低钠少添加款' },
  { name: '海苔小饭团', tags: ['takeout'], note: '一口迷你饭团，海苔米香' },
  { name: '玉米杯（微波）', tags: ['takeout'], note: '即食甜玉米粒，控半杯' },
  { name: '燕麦牛奶杯', tags: ['healthy', 'takeout', 'diabetes'], note: '冷藏燕麦泡奶，早餐顶饿' },
  { name: '肉松卷面包', tags: ['takeout'], note: '沙拉酱肉松卷，油糖别当饭' },
  { name: '香辣嫩鱼堡', tags: ['takeout'], note: '炸鱼柳夹堡刷酱，趁热吃' },
  { name: '板烧鸡腿堡', tags: ['takeout'], note: '铁板煎鸡腿不带炸，少油些' },
  { name: '单人小碗菜（两荤一素）', tags: ['takeout'], note: '现炒小碗拼米饭，挑清炒少油炸' },
  { name: '肥牛饭（日式牛丼）', tags: ['takeout'], note: '洋葱肥牛浇汁饭，酱汁偏甜' },
  { name: '蒸菜套餐（真功夫式）', tags: ['healthy', 'takeout'], note: '瓦罐蒸品配饭，少油烟' },
  { name: '养生炖盅（山药排骨）', tags: ['takeout'], note: '小盅慢炖，浓汤痛风适量' },
  { name: '台式盐酥鸡', tags: ['takeout'], note: '九层塔炸鸡块，撒胡椒盐' },
  { name: '炸鸡桶（原味）', tags: ['takeout'], note: '外酥里嫩整块，油多分享' },
  { name: '脆皮手枪腿', tags: ['takeout'], note: '整只炸鸡腿外酥，油多分享' },
  { name: '红烧牛肉饭', tags: ['takeout'], note: '卤汁牛肉浇饭，配酸菜解腻' },
  { name: '铁板牛肉饭', tags: ['takeout'], note: '铁板烤肉铺饭，加生菜解腻' },
  { name: '鸡柳卷饼', tags: ['takeout'], note: '炸柳条塞卷饼，撒孜然辣' },
  { name: '炸酥肉（现炸）', tags: ['takeout'], note: '面糊裹五花肉炸，趁热撒椒盐' },
  { name: '铁板豆腐', tags: ['takeout'], note: '老豆腐煎脆淋辣酱，外焦里嫩' },
  { name: '铁板山药片', tags: ['takeout'], note: '铁板煎山药片，椒盐脆' },
  { name: '龙卷风土豆', tags: ['takeout'], note: '螺旋整颗炸土豆，撒辣椒粉' },
  { name: '现做鸡蛋汉堡', tags: ['takeout'], note: '蛋液肉末小汉堡，早餐热乎' },
  { name: '脆皮年糕', tags: ['takeout'], note: '煎年糕刷辣酱，外脆内糯' },
  { name: '绍兴臭豆腐', tags: ['takeout'], note: '黑豆腐炸脆灌汤汁，配蒜辣' },
  { name: '炒凉粉', tags: ['takeout'], note: '铁板炒绿豆凉粉，蒜香带焦' },
  { name: '现做糖葫芦', tags: ['takeout'], note: '水果裹糖衣，甜硬少啃牙' },
]
