// 「今天吃什么」分片：痛风低嘌呤（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const GOUT_DISHES: FoodDish[] = [
  { name: '牛奶蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '奶香嫩滑，双低嘌呤蛋白' },
  { name: '番茄炒花菜', tags: ['healthy', 'diabetes', 'gout'], note: '花菜脆嫩，茄汁开胃' },
  { name: '二米饭', tags: ['healthy', 'diabetes', 'gout'], note: '小米掺白米同蒸，粗细搭配' },
  { name: '凉拌黄瓜木耳', tags: ['healthy', 'diabetes', 'gout'], note: '双脆小凉菜，蒜醋汁' },
  { name: '鸭蛋', tags: ['healthy', 'gout'], note: '蛋类低嘌呤，蒸煮都行' },
  { name: '鹌鹑蛋（水煮）', tags: ['healthy', 'diabetes', 'gout'], note: '小巧低嘌呤，一次三五颗' },
  { name: '咸鸭蛋（少量）', tags: ['gout'], note: '蛋类低嘌呤，咸的少放盐' },
  { name: '番茄蒸蛋', tags: ['healthy', 'diabetes', 'gout'], note: '蛋嫩茄香，蒸制低嘌呤' },
  { name: '虾皮蛋花汤（少量虾皮）', tags: ['healthy', 'gout'], note: '虾皮一两克提鲜就行，别吃渣' },
  { name: '丝瓜炒鸭蛋', tags: ['gout'], note: '清甜软嫩，蛋类低嘌呤' },
  { name: '菠菜蛋花汤', tags: ['healthy', 'diabetes', 'gout'], note: '菠菜焯水，蛋花清汤' },
  { name: '豆腐蛋花汤', tags: ['healthy', 'gout'], note: '豆腐适量，蛋花低嘌呤' },
  { name: '南瓜蒸蛋', tags: ['healthy', 'gout'], note: '南瓜清甜，蛋羹嫩滑' },
  { name: '鸡蛋汤面（清汤）', tags: ['gout'], note: '鸡蛋面清水做底，不放肉汤' },
  { name: '鸡蛋粥', tags: ['gout'], note: '蛋花入粥，温和低嘌呤' },
  { name: '蛋花小米粥', tags: ['gout'], note: '小米暖胃，蛋花低嘌呤' },
  { name: '全蛋羹（少油）', tags: ['healthy', 'diabetes', 'gout'], note: '整蛋打散蒸，低嘌呤蛋白' },
  { name: '舒肥蛋', tags: ['healthy', 'gout'], note: '低温慢煮，嫩滑少油' },
  { name: '无糖双皮奶', tags: ['diabetes', 'gout'], note: '奶蛋甜品，无糖更友好' },
  { name: '奶粉（脱脂）', tags: ['gout'], note: '冲泡方便，低嘌呤蛋白' },
  { name: '开菲尔', tags: ['gout'], note: '发酵乳饮，低嘌呤护肠' },
  { name: '奶酪（少量）', tags: ['gout'], note: '奶制品低嘌呤，少量补钙' },
  { name: '茅屋奶酪', tags: ['healthy', 'gout'], note: '高蛋白低脂，拌面包都行' },
  { name: '低糖奶冻', tags: ['gout'], note: '奶冻靠代糖，一小份就收住' },
  { name: '无糖椰子冻（小份）', tags: ['gout'], note: '椰香冻冻，小份解馋' },
  { name: '奶香土豆泥（少油）', tags: ['gout'], note: '土豆低嘌呤，牛奶调泥' },
  { name: '蒸南瓜红枣蛋羹', tags: ['gout'], note: '南瓜蛋香，红枣几颗提甜' },
  { name: '牛奶麦片（低脂）', tags: ['diabetes', 'gout'], note: '奶泡燕麦，低嘌呤早餐' },
  { name: '土豆丝蛋饼', tags: ['gout'], note: '土豆擦丝摊蛋，管饱' },
  { name: '清蒸西兰花', tags: ['healthy', 'diabetes', 'gout'], note: '蒸制零油，脆嫩低嘌呤' },
  { name: '白灼西兰花', tags: ['healthy', 'diabetes', 'gout'], note: '水开烫软，淋少许生抽' },
  { name: '清炒佛手', tags: ['gout'], note: '佛手瓜清炒，脆嫩低嘌呤' },
  { name: '清蒸丝瓜', tags: ['healthy', 'diabetes', 'gout'], note: '蒸制软滑，清甜低嘌呤' },
  { name: '清炒茭白', tags: ['healthy', 'gout'], note: '茭白脆嫩，水乡时蔬' },
  { name: '清炒卷心菜', tags: ['healthy', 'diabetes', 'gout'], note: '手撕快炒，甜脆低嘌呤' },
  { name: '清蒸花菜', tags: ['healthy', 'diabetes', 'gout'], note: '蒸着吃，蘸汁都低嘌呤' },
  { name: '凉拌胡萝卜丝', tags: ['healthy', 'diabetes', 'gout'], note: '醋蒜拌丝，甜脆开胃' },
  { name: '醋拌萝卜丝', tags: ['healthy', 'gout'], note: '萝卜顺气，酸爽低卡' },
  { name: '凉拌芹菜花生（少盐）', tags: ['diabetes', 'gout'], note: '芹菜高纤，花生十来粒' },
  { name: '清炒黄瓜木耳', tags: ['healthy', 'diabetes', 'gout'], note: '双脆清爽，低嘌呤家常' },
  { name: '番茄炒木耳', tags: ['healthy', 'diabetes', 'gout'], note: '番茄木耳，酸甜开胃' },
  { name: '清炒南瓜片', tags: ['healthy', 'gout'], note: '嫩南瓜薄片，清甜低嘌呤' },
  { name: '蒸茄子淋酱（少油）', tags: ['healthy', 'diabetes', 'gout'], note: '整条蒸软撕条，蒜醋淋汁' },
  { name: '凉拌冬瓜条', tags: ['healthy', 'diabetes', 'gout'], note: '冬瓜焯凉，清爽低嘌呤' },
  { name: '蒜蓉蒸长豆角', tags: ['healthy', 'diabetes', 'gout'], note: '蒸制少油，豆角要蒸透' },
  { name: '清炒长豆角', tags: ['gout'], note: '豆角切小段，炒熟炒透' },
  { name: '清炒大白菜', tags: ['healthy', 'diabetes', 'gout'], note: '白菜清甜，快炒少油' },
  { name: '醋溜高丽菜', tags: ['gout'], note: '高丽菜醋炒，酸香下饭' },
  { name: '清炒鸡毛菜', tags: ['healthy', 'diabetes', 'gout'], note: '鸡毛菜易熟，大火快炒' },
  { name: '白灼芥菜（微苦款）', tags: ['diabetes', 'gout'], note: '芥菜微苦，清热下火' },
  { name: '清炒塌棵菜', tags: ['gout'], note: '塌棵菜软嫩，少油快炒' },
  { name: '白灼豆皮青菜（适量）', tags: ['diabetes', 'gout'], note: '豆皮适量，青菜多多' },
  { name: '香菇菜心（适量）', tags: ['diabetes', 'gout'], note: '香菇两朵提鲜，菜心低嘌呤' },
  { name: '口蘑炒莴笋（适量）', tags: ['diabetes', 'gout'], note: '口蘑少量，莴笋脆嫩' },
  { name: '杏鲍菇炒青菜（适量）', tags: ['gout'], note: '菌菇适量，青菜为主' },
  { name: '凉拌黄瓜皮蛋', tags: ['gout'], note: '皮蛋切块拌黄瓜，下饭' },
  { name: '生菜鸡蛋沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '生菜配水煮蛋，油醋汁' },
  { name: '番茄花菜沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '生花菜拌番茄，爽脆' },
  { name: '芹菜胡萝卜汁（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '连渣喝别滤渣，不加糖' },
  { name: '黄瓜番茄汁', tags: ['diabetes', 'gout'], note: '蔬果汁饮，不加糖更稳' },
  { name: '冬瓜炒白菜', tags: ['diabetes', 'gout'], note: '两样低嘌呤，清甜多汁' },
  { name: '蒸双色胡萝卜', tags: ['healthy', 'diabetes', 'gout'], note: '胡萝卜蒸软，微甜保营养' },
  { name: '番茄洋葱炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '洋葱微甜是天然甜，不放糖' },
  { name: '番茄菜花蛋汤', tags: ['healthy', 'diabetes', 'gout'], note: '蛋花蔬菜汤，低嘌呤主力' },
  { name: '蒸丝瓜豆角（时蔬拼）', tags: ['diabetes', 'gout'], note: '两样蒸熟，淋汁即食' },
  { name: '清炒西芹枸杞（少量）', tags: ['gout'], note: '西芹脆爽，枸杞一小把' },
  { name: '凉拌莴笋胡萝卜丝', tags: ['healthy', 'diabetes', 'gout'], note: '双色脆丝，少盐清爽' },
  { name: '蒜蓉蒸茭白', tags: ['diabetes', 'gout'], note: '茭白蒸软，蒜香提味' },
  { name: '白灼南瓜藤（嫩尖）', tags: ['diabetes', 'gout'], note: '南瓜嫩尖烫软，乡土时蔬' },
  { name: '清炒莴笋叶', tags: ['diabetes', 'gout'], note: '莴笋叶别扔，微苦清香' },
  { name: '糖渍番茄（无糖版）', tags: ['diabetes', 'gout'], note: '冰镇番茄撒代糖，夏日' },
  { name: '清蒸时蔬拼盘', tags: ['healthy', 'diabetes', 'gout'], note: '盘中时蔬一蒸，蘸汁清淡' },
  { name: '白灼双色萝卜片', tags: ['healthy', 'diabetes', 'gout'], note: '萝卜切薄片烫软' },
  { name: '素炒萝卜丝', tags: ['healthy', 'gout'], note: '萝卜擦丝素炒，通气低脂' },
  { name: '葱油茼蒿（少油）', tags: ['diabetes', 'gout'], note: '茼蒿清香，葱油几勺' },
  { name: '番茄冬瓜烩', tags: ['diabetes', 'gout'], note: '两样同烩，酸甜多汁' },
  { name: '蒸西葫芦盒（素馅）', tags: ['diabetes', 'gout'], note: '西葫芦夹素馅，蒸制清淡' },
  { name: '凉拌秋葵木耳', tags: ['diabetes', 'gout'], note: '秋葵木耳双脆，蒜醋汁' },
  { name: '芹菜叶鸡蛋汤', tags: ['healthy', 'diabetes', 'gout'], note: '芹菜叶别扔，蛋花清汤' },
  { name: '芋头粥（咸口）', tags: ['gout'], note: '芋头切丁煮粥，暖胃' },
  { name: '土豆炖白菜', tags: ['diabetes', 'gout'], note: '土豆当主食算，别配两份饭' },
  { name: '蒸土豆泥球', tags: ['gout'], note: '土豆蒸压成球，无油' },
  { name: '紫薯山药泥（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '两样蒸烂，本味微甜' },
  { name: '红薯饭', tags: ['diabetes', 'gout'], note: '红薯掺米煮饭，香甜' },
  { name: '紫薯饭', tags: ['diabetes', 'gout'], note: '紫薯煮饭，花青素多' },
  { name: '芋头饭', tags: ['gout'], note: '芋头切丁同焖，粉香' },
  { name: '南瓜饭', tags: ['gout'], note: '南瓜焖饭，清甜低嘌呤' },
  { name: '山药小米面糊', tags: ['gout'], note: '山药泥冲小米面，早餐' },
  { name: '小米山药粥', tags: ['gout'], note: '小米山药，温和养胃' },
  { name: '高粱米粥', tags: ['gout'], note: '高粱熬粥，粗粮低嘌呤' },
  { name: '青稞', tags: ['diabetes', 'gout'], note: '青稞β葡聚糖，低GI杂粮' },
  { name: '全麦饼干（无糖）', tags: ['diabetes', 'gout'], note: '一两块解馋，看配料无蔗糖' },
  { name: '燕麦麸粥', tags: ['diabetes', 'gout'], note: '麸皮纤维更高，冲糊即食' },
  { name: '米饭', tags: ['gout'], note: '白米饭低嘌呤，控制份量' },
  { name: '蒸米粉（粿条）', tags: ['gout'], note: '米粉粿条清蒸，少油拌汁' },
  { name: '清汤河粉', tags: ['gout'], note: '河粉要清水煮，外食别要肉汤底' },
  { name: '素炒河粉（少油）', tags: ['gout'], note: '豆芽少量下锅，河粉少油炒' },
  { name: '拌面（清汤少油）', tags: ['gout'], note: '挂面白煮，少油清拌' },
  { name: '素三鲜蒸饺', tags: ['diabetes', 'gout'], note: '蔬菜馅蒸饺，低嘌呤管饱' },
  { name: '糯米烧卖（少量）', tags: ['gout'], note: '糯米烧卖一个垫肚' },
  { name: '粢饭团（无榨菜油条）', tags: ['gout'], note: '糯米包蛋，早餐扎实' },
  { name: '糍粑（无糖少量）', tags: ['gout'], note: '糯米糍粑，无糖尝个味' },
  { name: '粽子（白米小个）', tags: ['gout'], note: '白米小粽一个，别贪多' },
  { name: '米饭饼', tags: ['gout'], note: '米浆烙饼，松软米香' },
  { name: '汤泡饭（清汤）', tags: ['gout'], note: '汤泡饭用清汤或白水，别配肉汤' },
  { name: '烙饼（少油）', tags: ['gout'], note: '白面烙饼，少油层少' },
  { name: '全麦面包（无糖）', tags: ['diabetes', 'gout'], note: '看配料表，无糖优先' },
  { name: '奶香小馒头', tags: ['gout'], note: '牛奶和面蒸，低嘌呤主食' },
  { name: '蒸米发糕', tags: ['gout'], note: '米浆蒸糕，蓬松微甜' },
  { name: '低糖蛋糕（小份）', tags: ['gout'], note: '蛋香为主，小份解馋' },
  { name: '苏打饼干（原味）', tags: ['gout'], note: '碱性零食，垫饥不升酸' },
  { name: '意大利面（番茄清酱）', tags: ['gout'], note: '清酱少油，别配肉酱' },
  { name: '面片汤（素）', tags: ['gout'], note: '面片煮软，青菜蛋花' },
  { name: '饸饹面（清汤）', tags: ['gout'], note: '饸饹面清水煮，汤底不放肉' },
  { name: '荞麦凉面（少酱）', tags: ['gout'], note: '荞麦过凉，麻酱少放' },
  { name: '燕麦米饭', tags: ['diabetes', 'gout'], note: '燕麦米掺白米，低GI' },
  { name: '胚芽米饭', tags: ['diabetes', 'gout'], note: '与杂豆燕麦掺半才算控糖主食' },
  { name: '米饭团（无馅）', tags: ['gout'], note: '米饭捏团，随手管饱' },
  { name: '素高汤（蔬菜清汤）', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜熬汤底，替代肉高汤' },
  { name: '冬瓜杂粮汤', tags: ['gout'], note: '冬瓜配杂豆，汤清量少豆' },
  { name: '萝卜白菜汤', tags: ['healthy', 'diabetes', 'gout'], note: '两样炖汤，冬夜暖身' },
  { name: '玉米胡萝卜清汤', tags: ['gout'], note: '玉米胡萝卜煮清汤底' },
  { name: '土豆芹菜叶汤', tags: ['gout'], note: '土豆煮化，芹菜叶提香' },
  { name: '丝瓜面线（清汤）', tags: ['gout'], note: '丝瓜面线用素汤，不放虾皮' },
  { name: '豆腐蔬菜汤', tags: ['gout'], note: '嫩豆腐适量，青菜清汤少盐' },
  { name: '山药番茄蛋汤', tags: ['healthy', 'diabetes', 'gout'], note: '山药嫩滑，番茄蛋花' },
  { name: '藕片汤（清煮）', tags: ['gout'], note: '鲜藕切片清煮，微甜' },
  { name: '冬瓜蛋花汤', tags: ['healthy', 'diabetes', 'gout'], note: '冬瓜清淡利水，蛋花用素汤' },
  { name: '什锦素汤煲', tags: ['gout'], note: '冰箱蔬菜一锅炖汤' },
  { name: '土豆番茄浓汤（无油）', tags: ['gout'], note: '番茄土豆熬浓，无油不放肉汤' },
  { name: '萝卜丝蛋汤', tags: ['gout'], note: '萝卜丝煮软，蛋花清汤' },
  { name: '玉米蛋花汤', tags: ['gout'], note: '玉米粒煮汤，蛋花漂浮' },
  { name: '家常烧鲤鱼（少油）', tags: ['gout'], note: '鲤鱼缓解期少量，别用浓汤烧' },
  { name: '白灼鲜虾（小份）', tags: ['healthy', 'diabetes', 'gout'], note: '缓解期小份尝鲜，急性期别碰' },
  { name: '水煮鱼片（痛风避开汤）', tags: ['gout'], note: '白肉鱼缓解期少量，吃片别喝汤' },
  { name: '黄鳝煲（少量）', tags: ['gout'], note: '缓解期小煲一次，浓汁别喝' },
  { name: '清蒸螃蟹（只吃蟹肉）', tags: ['gout'], note: '蟹肉中嘌呤，缓解期少量忌蟹黄' },
  { name: '卤小龙虾（少量）', tags: ['gout'], note: '缓解期吃几个虾尾，卤汁别泡饭' },
  { name: '白灼海参（蘸汁）', tags: ['healthy', 'diabetes', 'gout'], note: '海参嘌呤极低，高蛋白低脂' },
  { name: '小葱拌豆腐海蜇（适量海蜇）', tags: ['diabetes', 'gout'], note: '海蜇嘌呤低，少量拌食' },
  { name: '凉拌海蜇皮', tags: ['healthy', 'diabetes', 'gout'], note: '海蜇皮嘌呤很低，爽脆少放盐' },
  { name: '清蒸鳕鱼块', tags: ['healthy', 'diabetes', 'gout'], note: '鳕鱼缓解期吃一块，蒸的清淡' },
  { name: '清蒸黄花鱼（适量）', tags: ['gout'], note: '缓解期一小块，急性期避开' },
  { name: '香煎龙利鱼柳', tags: ['healthy', 'gout'], note: '市售多是巴沙鱼，缓解期少量' },
  { name: '银鱼跑蛋（适量）', tags: ['gout'], note: '用鲜银鱼小份，别下银鱼干' },
  { name: '炒鱼片（上浆滑炒）', tags: ['gout'], note: '草鱼片缓解期吃，一份分两餐' },
  { name: '焖锅鱼（清淡版）', tags: ['gout'], note: '白肉鱼缓解期少量，汤汁少喝' },
  { name: '白灼螺片（少量）', tags: ['diabetes', 'gout'], note: '螺片几只尝味，别连着汤汁' },
  { name: '北豆腐炖白菜（适量）', tags: ['diabetes', 'gout'], note: '北豆腐嘌呤中等，适量炖' },
  { name: '南豆腐汤（适量）', tags: ['gout'], note: '南豆腐含水多嘌呤低' },
  { name: '浓豆浆（限一杯）', tags: ['diabetes', 'gout'], note: '冲淡些喝一杯，缓解期可适量' },
  { name: '豆腐丝拌菠菜（适量）', tags: ['diabetes', 'gout'], note: '豆腐丝少量，菠菜焯水' },
  { name: '内酯豆腐（淋汁）', tags: ['healthy', 'diabetes', 'gout'], note: '豆腐适量一块，淋清汁就好' },
  { name: '鸡蛋豆腐（适量）', tags: ['gout'], note: '蛋做的豆腐，低嘌呤顺滑' },
  { name: '自制豆腐（低嘌呤家常）', tags: ['diabetes', 'gout'], note: '卤水点豆腐，一次半块' },
  { name: '豆腐条汤（适量）', tags: ['gout'], note: '豆腐切条煮汤，清汤少盐' },
  { name: '素烧豆腐（少油）', tags: ['gout'], note: '薄油快煎别油炸，烧汁少盐' },
  { name: '千张结烧青菜（适量）', tags: ['diabetes', 'gout'], note: '千张两三个结，青菜打底' },
  { name: '豆腐皮炒芹菜（适量）', tags: ['diabetes', 'gout'], note: '豆腐皮适量，芹菜高纤' },
  { name: '面筋（谷朊粉）清汤', tags: ['gout'], note: '面筋适量，清汤煮食' },
  { name: '烤麸（适量）', tags: ['gout'], note: '烤麸吸汁，少量尝味' },
  { name: '冻豆腐白菜煲（适量）', tags: ['diabetes', 'gout'], note: '冻豆腐适量，白菜管够' },
  { name: '豆腐圆子汤（素）', tags: ['gout'], note: '豆腐适量捏圆子，清汤别放肉' },
  { name: '甜豆腐花（少量糖）', tags: ['gout'], note: '豆花来一碗，糖水换成代糖' },
  { name: '豆腐脑蛋花羹', tags: ['diabetes', 'gout'], note: '豆花适量打蛋花，咸口少卤' },
  { name: '豆渣蒸蛋（少量）', tags: ['diabetes', 'gout'], note: '豆渣纤维多，蒸蛋增香' },
  { name: '炒豆腐泥（素）', tags: ['diabetes', 'gout'], note: '豆腐捏碎似炒蛋，适量' },
  { name: '豆腐乳（半块调味）', tags: ['gout'], note: '腐乳半块化开调味，别空吃' },
  { name: '哈密瓜（一小盘）', tags: ['gout'], note: '低嘌呤瓜果，控量' },
  { name: '香瓜', tags: ['gout'], note: '当季香瓜，一次半个或一小盘' },
  { name: '桑葚（小把）', tags: ['gout'], note: '花青素多，小把尝鲜' },
  { name: '荸荠（马蹄）', tags: ['gout'], note: '荸荠脆甜，煮水都行' },
  { name: '荸荠豆浆（少量）', tags: ['gout'], note: '荸荠打浆，豆类适量' },
  { name: '枇杷', tags: ['gout'], note: '当季枇杷，低嘌呤清甜' },
  { name: '椰青水', tags: ['gout'], note: '天然电解质水，别加糖' },
  { name: '凤梨（小块）', tags: ['gout'], note: '菠萝类酸甜，一小盘' },
  { name: '石榴', tags: ['gout'], note: '低嘌呤水果，籽多纤维足' },
  { name: '无花果（鲜两枚）', tags: ['gout'], note: '鲜无花果两枚，甜糯' },
  { name: '人参果', tags: ['gout'], note: '低糖清爽，低嘌呤' },
  { name: '柑橘', tags: ['diabetes', 'gout'], note: '一瓣一瓣吃，低GI' },
  { name: '金桔（几颗）', tags: ['gout'], note: '带皮嚼几颗，维C足' },
  { name: '李子（一个）', tags: ['gout'], note: '当季李子一个，酸甜' },
  { name: '木瓜牛奶', tags: ['gout'], note: '木瓜牛奶用代糖，不加白糖' },
  { name: '香蕉奶昔（无糖）', tags: ['gout'], note: '无糖也就一小杯，别当水喝' },
  { name: '蔓越莓（无糖干少量）', tags: ['gout'], note: '选无糖款，一小撮' },
  { name: '黑莓', tags: ['diabetes', 'gout'], note: '低GI浆果，抗氧化' },
  { name: '树莓', tags: ['diabetes', 'gout'], note: '高纤低糖，嘌呤低' },
  { name: '无糖银耳莲子羹', tags: ['diabetes', 'gout'], note: '莲子十几颗，银耳润燥' },
  { name: '冰糖炖梨（少糖）', tags: ['gout'], note: '梨块清炖就好，冰糖换成代糖' },
  { name: '藕粉羹（无糖）', tags: ['diabetes', 'gout'], note: '藕粉羹算主食，冲一小碗喝' },
  { name: '低果糖蔬菜汁', tags: ['gout'], note: '黄瓜芹菜打底，果糖低' },
  { name: '桃胶皂角米羹（无糖）', tags: ['gout'], note: '银耳打底，无糖清甜' },
  { name: '绿豆沙（无糖）', tags: ['diabetes', 'gout'], note: '干豆嘌呤偏高，无糖小碗偶尔' },
  { name: '板栗粥', tags: ['gout'], note: '板栗熬粥算主食，别再配饭' },
  { name: '白果（熟，少量）', tags: ['gout'], note: '熟白果几颗，别多' },
  { name: '百合莲子汤（无糖）', tags: ['healthy', 'gout'], note: '莲子配百合，煮成安神粥' },
  { name: '紫薯泥（无糖）', tags: ['diabetes', 'gout'], note: '蒸紫薯压泥，牛奶调稀' },
  { name: '香蕉燕麦杯（无糖）', tags: ['gout'], note: '香蕉压泥拌燕麦，免糖' },
  { name: '低脂可可（无糖）', tags: ['diabetes', 'gout'], note: '可可碱友好，不加糖' },
]
