// 「今天吃什么」分片：健康减脂轻食（2026-09-25 两波扩建批，六路×二采集 + 四路×二交叉验证，主会话合并）
// 纯内容数据，零业务逻辑
import type { FoodDish } from './types'

export const HEALTHY_FIT_DISHES: FoodDish[] = [
  { name: '低温慢煮鸡胸', tags: ['healthy', 'diabetes'], note: '嫩而不柴，减脂蛋白优选' },
  { name: '柠檬香煎鸡胸', tags: ['healthy', 'diabetes'], note: '柠檬提香，少油煎更清爽' },
  { name: '迷迭香烤鸡胸', tags: ['healthy', 'diabetes'], note: '香草腌过，烤制少油' },
  { name: '空气炸锅鸡胸', tags: ['healthy', 'diabetes'], note: '无油煎香，减脂懒人款' },
  { name: '黑椒洋葱鸡胸', tags: ['healthy', 'diabetes'], note: '黑椒碎自调，不用现成含糖汁' },
  { name: '番茄炖鸡胸', tags: ['healthy', 'diabetes'], note: '茄汁酸甜，鸡胸软嫩' },
  { name: '咖喱鸡胸（少油）', tags: ['healthy', 'diabetes'], note: '改用咖喱粉，不用咖喱块挂浓汁' },
  { name: '西兰花炒鸡胸', tags: ['healthy', 'diabetes'], note: '双高组合，减脂经典' },
  { name: '鸡胸肉炒芦笋', tags: ['healthy', 'diabetes'], note: '脆嫩清爽，蛋白质管够' },
  { name: '口蘑煎鸡胸', tags: ['healthy', 'diabetes'], note: '菌菇提鲜，少油慢煎' },
  { name: '芹菜炒鸡丁', tags: ['healthy', 'diabetes'], note: '芹菜脆爽，鸡丁低脂' },
  { name: '蒸鸡肉饼', tags: ['healthy', 'diabetes'], note: '嫩滑好消化，蒸制少油' },
  { name: '鸡肉丸子清汤', tags: ['healthy', 'diabetes'], note: '清汤煮丸，低脂暖胃' },
  { name: '香烤鸡腿排（去皮）', tags: ['healthy', 'diabetes'], note: '去皮烤香，嫩而不油' },
  { name: '盐焗鸡腿（去皮）', tags: ['healthy'], note: '去皮减脂，钠偏高注意频次' },
  { name: '木耳炒鸡片', tags: ['healthy'], note: '木耳脆，鸡片嫩，快手' },
  { name: '彩椒鸡丁碗', tags: ['healthy', 'diabetes'], note: '颜色好看，低脂高蛋白' },
  { name: '鸡胸肉藜麦碗', tags: ['healthy', 'diabetes'], note: '高蛋白配低GI，一碗管饱' },
  { name: '椒麻手撕鸡胸', tags: ['healthy', 'diabetes'], note: '椒麻开胃，少油版更清爽' },
  { name: '香煎牛排（少油）', tags: ['healthy', 'diabetes'], note: '优质蛋白，少油煎五分熟' },
  { name: '黑椒牛柳（少油）', tags: ['healthy', 'diabetes'], note: '黑椒碎调味，不用含糖酱' },
  { name: '彩椒牛柳', tags: ['healthy', 'diabetes'], note: '彩椒鲜甜，牛肉嫩滑' },
  { name: '孜然牛肉（少油）', tags: ['healthy', 'diabetes'], note: '孜然香浓，少油版更清爽' },
  { name: '芦笋炒牛柳', tags: ['healthy', 'diabetes'], note: '脆嫩双鲜，减脂友好' },
  { name: '牛肉炒西兰花', tags: ['healthy', 'diabetes'], note: '高蛋白高纤维，饱腹' },
  { name: '牛肉炒秋葵', tags: ['healthy', 'diabetes'], note: '秋葵滑嫩，牛肉补铁' },
  { name: '番茄炖牛腱', tags: ['healthy', 'diabetes'], note: '茄汁浓郁，牛腱软烂' },
  { name: '清炖牛肉（撇油）', tags: ['healthy', 'diabetes'], note: '撇去浮油，汤清味浓' },
  { name: '牛肉蔬菜汤', tags: ['healthy', 'diabetes'], note: '蔬菜多多，牛肉适量' },
  { name: '番茄牛肉丸汤', tags: ['healthy', 'diabetes'], note: '酸甜暖胃，丸子少油' },
  { name: '牛肉末炒番茄', tags: ['healthy', 'diabetes'], note: '茄汁下饭，牛肉末少许' },
  { name: '低脂牛肉沙拉', tags: ['healthy', 'diabetes'], note: '牛肉切片，油醋汁拌' },
  { name: '洋葱牛肉盖浇杂粮饭', tags: ['healthy'], note: '洋葱甜，配糙米更稳' },
  { name: '清蒸巴沙鱼', tags: ['healthy', 'diabetes'], note: '无刺嫩滑，减脂好选择' },
  { name: '香煎鳕鱼', tags: ['healthy'], note: '外金里嫩，少油煎制' },
  { name: '柠檬汁煎鳕鱼', tags: ['healthy', 'diabetes'], note: '柠檬解腥，白肉鱼低脂' },
  { name: '照烧三文鱼（少糖）', tags: ['healthy'], note: '照烧汁自调减糖，薄薄一层' },
  { name: '番茄焗三文鱼', tags: ['healthy'], note: '茄汁盖顶，烤箱少油' },
  { name: '香煎秋刀鱼', tags: ['healthy'], note: '皮脆肉香，挤柠檬更鲜' },
  { name: '蒜香烤鱼（少油）', tags: ['healthy'], note: '蒜香扑鼻，烤制省油' },
  { name: '清蒸小黄鱼', tags: ['healthy', 'diabetes'], note: '小黄鱼中嘌呤，一条刚好' },
  { name: '茄汁大虾', tags: ['healthy'], note: '鲜番茄打底，不用含糖酱' },
  { name: '芙蓉虾仁', tags: ['healthy', 'diabetes'], note: '蛋白裹虾，滑嫩清淡' },
  { name: '腰果虾仁', tags: ['healthy'], note: '生腰果烘香少量放，不过油' },
  { name: '香煎虾饼', tags: ['healthy'], note: '虾肉打饼，少油煎香' },
  { name: '鱼肉豆腐煲', tags: ['healthy'], note: '鱼片豆腐，一锅炖鲜' },
  { name: '茶叶蛋', tags: ['healthy', 'diabetes', 'gout'], note: '茶香入味，早餐方便蛋白（淡卤少盐）' },
  { name: '水波蛋', tags: ['healthy', 'diabetes', 'gout'], note: '无油水煮，溏心嫩滑' },
  { name: '番茄焗蛋', tags: ['healthy', 'diabetes', 'gout'], note: '茄汁烩蛋，酸甜下饭' },
  { name: '蔬菜烘蛋', tags: ['healthy', 'diabetes', 'gout'], note: '意式烘蛋，蔬菜多多' },
  { name: '口蘑炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '口蘑三五片，配蛋嫩滑快手' },
  { name: '虾仁烘蛋', tags: ['healthy', 'diabetes'], note: '双蛋白组合，少油烘制' },
  { name: '毛豆炒蛋', tags: ['healthy', 'diabetes', 'gout'], note: '毛豆清甜，高蛋白（豆制品适量）' },
  { name: '鸡蛋炒豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '蛋香豆嫩，豆腐适量下饭' },
  { name: '千张炒鸡蛋', tags: ['healthy', 'diabetes', 'gout'], note: '豆皮鸡蛋，植物蛋白（适量）' },
  { name: '香煎白豆腐', tags: ['healthy', 'diabetes', 'gout'], note: '煎至金黄，淋生抽（豆制品适量）' },
  { name: '菌菇炒豆干', tags: ['healthy', 'diabetes', 'gout'], note: '豆干香韧，菌菇提鲜（适量）' },
  { name: '红豆糙米饭', tags: ['healthy', 'diabetes', 'gout'], note: '豆不超米量四分之一，同煮' },
  { name: '三色藜麦饭', tags: ['healthy', 'diabetes', 'gout'], note: '三色藜麦，蛋白满满' },
  { name: '紫米糙米饭', tags: ['healthy', 'diabetes', 'gout'], note: '花青素多，粗细搭配' },
  { name: '燕麦黑米饭', tags: ['healthy', 'diabetes', 'gout'], note: '燕麦掺黑米，稳糖饱腹' },
  { name: '高粱米饭', tags: ['healthy', 'diabetes'], note: '粗粮掺米，低GI主食' },
  { name: '荞麦饭', tags: ['healthy', 'diabetes', 'gout'], note: '荞麦掺米，控糖友好' },
  { name: '玉米碴饭', tags: ['healthy', 'diabetes', 'gout'], note: '玉米香浓，粗细搭配' },
  { name: '南瓜藜麦饭', tags: ['healthy', 'diabetes', 'gout'], note: '南瓜清甜，藜麦低GI' },
  { name: '山药杂粮饭', tags: ['healthy', 'diabetes', 'gout'], note: '山药掺杂粮煮饭，算主食' },
  { name: '五谷杂粮饭', tags: ['healthy', 'diabetes'], note: '多样谷物，营养均衡' },
  { name: '鹰嘴豆饭', tags: ['healthy', 'diabetes'], note: '高纤维豆饭，饱腹（豆类适量）' },
  { name: '莜面鱼鱼', tags: ['healthy', 'diabetes'], note: '燕麦面搓鱼，蘸汁清淡' },
  { name: '荞麦焖面', tags: ['healthy', 'diabetes', 'gout'], note: '荞麦焖制，配菜少油' },
  { name: '全麦螺旋面', tags: ['healthy', 'diabetes'], note: '意面造型，全麦低GI' },
  { name: '燕麦麸皮粥', tags: ['healthy', 'diabetes', 'gout'], note: '麸皮纤维高，早餐暖胃' },
  { name: '藜麦粥', tags: ['healthy', 'diabetes', 'gout'], note: '藜麦煮粥，蛋白主食' },
  { name: '土豆泥（无油奶）', tags: ['healthy', 'gout'], note: '少油少盐，代替主食' },
  { name: '烤红薯条（无油）', tags: ['healthy'], note: '烤箱无油，薯香当主食' },
  { name: '玉米面饼（无糖）', tags: ['healthy', 'diabetes'], note: '玉米面香，无糖主食' },
  { name: '芋头杂粮饭', tags: ['healthy', 'diabetes', 'gout'], note: '芋头软糯，掺米更稳' },
  { name: '花菜米（菜花饭）', tags: ['healthy', 'diabetes', 'gout'], note: '花菜打米，碳水大减' },
  { name: '番茄花菜炒米', tags: ['healthy', 'diabetes', 'gout'], note: '花菜米配番茄，低卡主食' },
  { name: '魔芋米饭', tags: ['healthy', 'diabetes', 'gout'], note: '魔芋掺米，热量减半' },
  { name: '西葫芦面（zoodles）', tags: ['healthy', 'diabetes', 'gout'], note: '瓜丝作面，清爽低碳' },
  { name: '魔芋意面', tags: ['healthy', 'diabetes', 'gout'], note: '低卡意面，酱料选清汤' },
  { name: '香菇魔芋丝', tags: ['healthy', 'diabetes'], note: '魔芋吸汁，菌菇提鲜（痛风适量）' },
  { name: '番茄魔芋面', tags: ['healthy', 'diabetes', 'gout'], note: '茄汁拌魔芋，近零热量' },
  { name: '生菜包饭', tags: ['healthy', 'diabetes'], note: '生菜代饭叶，碳水更少' },
  { name: '魔芋丝结拌黄瓜', tags: ['healthy', 'diabetes', 'gout'], note: '爽脆低卡，蒜醋汁开胃' },
  { name: '冬瓜面（冬瓜丝）', tags: ['healthy', 'diabetes', 'gout'], note: '冬瓜切丝，清汤低碳' },
  { name: '牛油果沙拉碗', tags: ['healthy'], note: '牛油果优质脂，蔬菜打底' },
  { name: '金枪鱼沙拉', tags: ['healthy', 'diabetes'], note: '水浸金枪鱼，高蛋白低脂' },
  { name: '番茄罗勒沙拉', tags: ['healthy', 'diabetes'], note: '马苏里拉少许，橄榄油轻拌' },
  { name: '玉米沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '甜玉米配黄瓜，清爽当主食' },
  { name: '鸡蛋土豆沙拉', tags: ['healthy', 'gout'], note: '酸奶代替沙拉酱，管饱' },
  { name: '虾仁牛油果沙拉', tags: ['healthy'], note: '双鲜搭配，好脂高蛋白' },
  { name: '牛排蔬菜能量碗', tags: ['healthy', 'diabetes'], note: '牛肉杂粮，蔬菜堆满' },
  { name: '三文鱼波奇碗', tags: ['healthy', 'diabetes'], note: '糙米配三文鱼，清爽少酱' },
  { name: '日式豆腐沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '柴鱼一小撮提味，不食渣' },
  { name: '紫甘蓝沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '紫甘蓝脆，油醋汁拌' },
  { name: '苦菊沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '苦菊微苦，清爽解腻' },
  { name: '温沙拉（烤南瓜）', tags: ['healthy'], note: '南瓜无油烤或刷薄油，配绿叶' },
  { name: '藜麦牛油果碗', tags: ['healthy', 'diabetes'], note: '藜麦低GI，牛油果好脂' },
  { name: '墨西哥鸡肉碗', tags: ['healthy', 'diabetes'], note: '黑豆玉米鸡肉，一碗均衡' },
  { name: '凉拌手撕杏鲍菇', tags: ['healthy', 'gout'], note: '杏鲍菇撕条，蒜香爽口（适量）' },
  { name: '凉拌魔芋丝', tags: ['healthy', 'diabetes', 'gout', 'takeout'], note: '零卡蒜醋拌魔芋，外卖也常点' },
  { name: '凉拌菜花', tags: ['healthy', 'diabetes', 'gout'], note: '焯水拌蒜醋，脆爽低卡' },
  { name: '凉拌芦笋', tags: ['healthy', 'diabetes', 'gout'], note: '芦笋中嘌呤，适量焯水拌' },
  { name: '温拌双脆（藕丁莴笋）', tags: ['healthy', 'diabetes', 'gout'], note: '焯水温拌，爽脆低脂' },
  { name: '中式鸡丝荞麦沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '鸡丝缓解期适量，麻酱少许' },
  { name: '东北家常拌菜', tags: ['healthy', 'diabetes', 'gout'], note: '拉皮当主食算，别叠加米饭' },
  { name: '豆腐鱼片汤', tags: ['healthy', 'diabetes'], note: '清汤煮制，嫩滑高蛋白' },
  { name: '蔬菜浓汤（无奶油）', tags: ['healthy', 'diabetes', 'gout'], note: '蔬菜打浓，不放奶油' },
  { name: '番茄蔬菜汤', tags: ['healthy', 'diabetes', 'gout'], note: '番茄打底，蔬菜清甜' },
  { name: '杂菜豆腐羹', tags: ['healthy', 'gout'], note: '多色蔬菜豆腐，薄芡（适量）' },
  { name: '冬瓜薏米汤', tags: ['healthy', 'gout'], note: '冬瓜配薏米，煮碗清汤消暑' },
  { name: '玉米须冬瓜汤', tags: ['healthy', 'diabetes', 'gout'], note: '利水清淡，夏日好喝' },
  { name: '丝瓜瘦肉汤', tags: ['healthy', 'diabetes'], note: '丝瓜清甜，瘦肉少许' },
  { name: '苦瓜黄豆汤', tags: ['healthy', 'diabetes'], note: '苦瓜清苦，黄豆适量（痛风适量）' },
  { name: '蔬菜蛋花汤', tags: ['healthy', 'diabetes', 'gout'], note: '多色蔬菜淋蛋花，清淡' },
  { name: '西兰花浓汤', tags: ['healthy', 'diabetes'], note: '西兰花打浓，无奶油少盐' },
  { name: '秋葵蛋汤', tags: ['healthy', 'gout'], note: '秋葵滑嫩，蛋花清淡' },
  { name: '海带黄豆汤', tags: ['healthy', 'gout'], note: '海带一小片、黄豆一小把煮汤' },
  { name: '白萝卜虾皮汤', tags: ['healthy', 'gout'], note: '虾皮仅提鲜点缀，汤别多喝' },
  { name: '希腊酸奶（无糖）', tags: ['healthy', 'diabetes', 'gout'], note: '浓稠高蛋白，选无糖款' },
  { name: '坚果酸奶杯', tags: ['healthy', 'diabetes'], note: '无糖酸奶撒坚果，加餐' },
  { name: '燕麦坚果杯', tags: ['healthy', 'diabetes'], note: '燕麦配坚果，饱腹加餐' },
  { name: '巴旦木（原味适量）', tags: ['healthy', 'diabetes', 'gout'], note: '原味坚果，一小把就好' },
  { name: '核桃仁（适量）', tags: ['healthy', 'diabetes', 'gout'], note: '优质脂肪，每天几颗' },
  { name: '开心果（原味）', tags: ['healthy', 'diabetes', 'gout'], note: '带壳慢吃，原味少盐' },
  { name: '奇亚籽布丁', tags: ['healthy', 'diabetes', 'gout'], note: '奇亚籽泡奶，高纤维加餐' },
  { name: '亚麻籽燕麦', tags: ['healthy', 'diabetes'], note: '亚麻籽拌燕麦，优质脂肪加分' },
  { name: '苹果片配花生酱', tags: ['healthy'], note: '选无糖纯花生酱，薄薄一层' },
  { name: '香蕉燕麦饼（无糖）', tags: ['healthy'], note: '香蕉甜味，无糖烘焙' },
  { name: '胡萝卜条蘸鹰嘴豆泥', tags: ['healthy', 'diabetes'], note: '脆蔬配豆泥，加餐高纤维' },
  { name: '黄瓜条蘸酸奶酱', tags: ['healthy', 'diabetes', 'gout'], note: '清爽脆嫩，低卡解馋' },
  { name: '无糖黑巧（少量）', tags: ['healthy', 'diabetes'], note: '高可可低糖，一小块解馋' },
  { name: '无糖椰青水', tags: ['healthy', 'diabetes'], note: '天然电解质，选无糖款' },
  { name: '蓝莓酸奶杯', tags: ['healthy', 'diabetes'], note: '低GI莓果配无糖酸奶' },
  { name: '牛油果（半个）', tags: ['healthy', 'diabetes', 'gout'], note: '好脂肪，半个就够别多吃' },
  { name: '番石榴', tags: ['healthy', 'diabetes', 'gout'], note: '低GI高纤维，当季水果' },
  { name: '莲雾', tags: ['healthy', 'diabetes', 'gout'], note: '水分足糖低，清爽加餐' },
  { name: '杨桃', tags: ['healthy', 'gout'], note: '酸甜多汁，低嘌呤水果' },
  { name: '绿色蔬果昔', tags: ['healthy', 'diabetes'], note: '绿叶配蔬果，无糖打底' },
  { name: '全麦金枪鱼三明治', tags: ['healthy', 'diabetes'], note: '水浸金枪鱼，全麦低GI' },
  { name: '鸡蛋生菜三明治', tags: ['healthy', 'diabetes'], note: '鸡蛋生菜，少酱清爽' },
  { name: '全麦鸡肉三明治', tags: ['healthy', 'diabetes'], note: '鸡胸蔬菜全麦，带饭方便' },
  { name: '蔬菜卷饼', tags: ['healthy', 'diabetes'], note: '全麦饼卷时蔬，少酱' },
  { name: '鸡肉卷饼', tags: ['healthy', 'diabetes'], note: '全麦饼卷鸡胸生菜' },
  { name: '墨西哥鸡肉卷', tags: ['healthy'], note: '外卖卷饼少酱，拒加炸物料' },
  { name: '牛肉卷饼', tags: ['healthy', 'diabetes'], note: '牛肉蔬菜全麦饼，管饱' },
  { name: '全麦鸡蛋卷', tags: ['healthy', 'diabetes'], note: '滑蛋生菜全麦卷，早餐' },
  { name: '番茄鸡蛋三明治', tags: ['healthy'], note: '炒蛋番茄，少酱更清爽' },
  { name: '杂粮饭团（金枪鱼）', tags: ['healthy', 'diabetes'], note: '糙米包金枪鱼，便携加餐' },
  { name: '日式豆腐定食', tags: ['healthy', 'gout'], note: '冷豆腐配饭，清淡（适量）' },
  { name: '荞麦冷面（蘸汁）', tags: ['healthy', 'diabetes', 'gout'], note: '日式 soba 蘸汁，过水爽滑' },
  { name: '日式牛肉饭（少油）', tags: ['healthy'], note: '肥牛换瘦牛，酱汁少放' },
  { name: '茶泡饭（杂粮）', tags: ['healthy', 'diabetes'], note: '绿茶泡杂粮饭，清淡暖胃' },
  { name: '日式盐烤青花鱼', tags: ['healthy'], note: '撒盐烤制，无需放油' },
  { name: '荞麦寿司卷', tags: ['healthy'], note: '杂粮配蔬菜，米饭少放' },
  { name: '韩式豆腐汤（清汤）', tags: ['healthy', 'gout'], note: '清汤豆腐，微辣（适量）' },
  { name: '韩式海带汤', tags: ['healthy'], note: '海带牛肉少，清爽低卡（适量）' },
  { name: '韩式蔬菜烤菇包肉', tags: ['healthy', 'diabetes', 'gout'], note: '生菜包烤菇菌，少肉多菜（适量）' },
  { name: '韩式石锅拌杂粮饭', tags: ['healthy', 'diabetes'], note: '酱减半，辣拌酱另放更好' },
  { name: '三文鱼刺身盖饭', tags: ['healthy', 'diabetes'], note: '生鱼片配糙米，清淡少酱' },
  { name: '蒜香烤鸡胸', tags: ['healthy', 'diabetes'], note: '蒜香腌透，烤制少油' },
  { name: '罗勒焗鸡胸', tags: ['healthy', 'diabetes'], note: '香草焗烤，嫩而不柴' },
  { name: '鸡胸炒荷兰豆', tags: ['healthy', 'diabetes'], note: '荷兰豆脆，鸡胸低脂' },
  { name: '香煎银鳕鱼', tags: ['healthy'], note: '白肉细嫩，少油煎香' },
  { name: '清炒虾球', tags: ['healthy', 'diabetes'], note: '虾球弹嫩，少油清炒' },
  { name: '鲈鱼豆腐汤', tags: ['healthy', 'diabetes'], note: '清汤煮鱼，豆腐嫩滑' },
  { name: '菠菜炒鸡蛋', tags: ['healthy', 'diabetes', 'gout'], note: '绿叶配蛋，家常高蛋白' },
  { name: '玉米藜麦饭', tags: ['healthy', 'diabetes'], note: '玉米藜麦，低GI主食' },
  { name: '燕麦藜麦饭', tags: ['healthy', 'diabetes'], note: '燕麦藜麦，蛋白稳糖' },
  { name: '全麦花卷', tags: ['healthy', 'diabetes'], note: '全麦蒸制，控糖主食' },
  { name: '花菜炒鸡丁', tags: ['healthy', 'diabetes'], note: '花菜代饭，鸡丁低脂' },
  { name: '魔芋拌面', tags: ['healthy', 'diabetes', 'gout'], note: '魔芋替面，近零热量' },
  { name: '田园蔬菜沙拉', tags: ['healthy', 'gout'], note: '多色生菜，油醋汁拌' },
  { name: '番茄黄瓜沙拉', tags: ['healthy', 'diabetes', 'gout'], note: '番茄黄瓜，清爽低卡' },
  { name: '藜麦虾仁沙拉', tags: ['healthy', 'diabetes'], note: '藜麦虾仁，高蛋白主食' },
  { name: '鹰嘴豆沙拉', tags: ['healthy', 'diabetes'], note: '鹰嘴豆绵密，高纤维（豆类适量）' },
  { name: '玉米浓汤（无奶油）', tags: ['healthy'], note: '玉米自然甜，不放奶油' },
  { name: '冬瓜鲜肉丸汤', tags: ['healthy', 'diabetes'], note: '鲜肉丸配冬瓜，清汤不腻' },
  { name: '混合莓果', tags: ['healthy', 'diabetes', 'gout'], note: '蓝莓树莓，低GI加餐' },
  { name: '烤鹰嘴豆', tags: ['healthy', 'diabetes', 'gout'], note: '干豆零食，一小把隔日一次' },
  { name: '全麦蔬菜三明治', tags: ['healthy', 'diabetes'], note: '全麦夹时蔬，少酱清爽' },
  { name: '韩式烤瘦牛肉', tags: ['healthy', 'diabetes'], note: '腌汁不放糖和梨泥' },
  { name: '日式咖喱鸡（糙米）', tags: ['healthy'], note: '咖喱粉调，不用含油糖咖喱块' },
]
