/**
 * 统一业务错误类
 * code: 机器可读错误码（前端用于 i18n 翻译）
 * statusCode: HTTP 状态码（默认 400）
 * detail: 可选的上下文信息（如字段名、限制值）
 */
export class AppError extends Error {
  code: string
  statusCode: number
  detail: unknown

  constructor(code: string, statusCode: number = 400, detail: unknown = null) {
    super(code)
    this.code = code
    this.statusCode = statusCode
    this.detail = detail
  }
}

// ─── 错误码常量 ───
export const E = {
  // 认证
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  // REQ-042: 画师封禁独立态（登录拒绝）
  ARTIST_BANNED: 'ARTIST_BANNED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  // 桌面端记账式会话（REQ-014 安全口径一，v73）：设备账本被撕（管理员踢出/全端踢人），客户端应引导重新登录。
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  ADMIN_REQUIRED: 'ADMIN_REQUIRED',
  // F-9（审计批F）: 旧登录码时代错误码 CODE_INVALID / CODE_EXPIRED / CODE_TOO_MANY_ATTEMPTS
  // 已退役删除（REQ-027 TOTP 上线后后端不再产生；前端 LOGIN_CODES 白名单由批 G 同步清理）
  QQ_NOT_REGISTERED: 'QQ_NOT_REGISTERED',
  // REQ-027: TOTP 动态口令
  TOTP_NOT_BOUND: 'TOTP_NOT_BOUND',
  TOTP_INVALID: 'TOTP_INVALID',
  TOTP_LOCKED: 'TOTP_LOCKED',
  TOTP_BIND_INVALID: 'TOTP_BIND_INVALID',
  // 会话门禁批：动态口令未绑定（被重置/未完成绑定）的画师不允许持有任何有效会话（登录态门禁 + Passkey 登录入口共用）
  TOTP_BIND_REQUIRED: 'TOTP_BIND_REQUIRED',
  // REQ-040: WebAuthn Passkey
  WEBAUTHN_CHALLENGE_INVALID: 'WEBAUTHN_CHALLENGE_INVALID',
  WEBAUTHN_REGISTRATION_FAILED: 'WEBAUTHN_REGISTRATION_FAILED',
  WEBAUTHN_AUTHENTICATION_FAILED: 'WEBAUTHN_AUTHENTICATION_FAILED',
  WEBAUTHN_CREDENTIAL_EXISTS: 'WEBAUTHN_CREDENTIAL_EXISTS',
  WEBAUTHN_CREDENTIAL_NOT_FOUND: 'WEBAUTHN_CREDENTIAL_NOT_FOUND',
  // REQ-040: TOTP 自助重绑
  REBIND_COOLDOWN: 'REBIND_COOLDOWN',
  REBIND_NO_CREDENTIAL: 'REBIND_NO_CREDENTIAL',
  // REQ-039: 邀请码注册
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_CANNOT_REVOKE: 'INVITE_CANNOT_REVOKE',
  ONBOARDING_DISABLED: 'ONBOARDING_DISABLED',

  // 画师
  ARTIST_NOT_FOUND: 'ARTIST_NOT_FOUND',
  NAME_EMPTY: 'NAME_EMPTY',
  CODE_FORMAT: 'CODE_FORMAT',
  CODE_TAKEN: 'CODE_TAKEN',
  QQ_TAKEN: 'QQ_TAKEN',
  SUBDOMAIN_TAKEN: 'SUBDOMAIN_TAKEN',
  INVALID_STATUS: 'INVALID_STATUS',
  INVALID_URL: 'INVALID_URL',

  // 流程
  STAGE_NOT_FOUND: 'STAGE_NOT_FOUND',
  STAGE_NAME_EMPTY: 'STAGE_NAME_EMPTY',
  FINAL_CANNOT_DISABLE: 'FINAL_CANNOT_DISABLE',
  FINAL_CANNOT_DELETE: 'FINAL_CANNOT_DELETE',
  FINAL_READONLY: 'FINAL_READONLY',
  MAX_INSTALLMENTS: 'MAX_INSTALLMENTS',
  FINAL_TOO_LOW: 'FINAL_TOO_LOW',
  MIN_STAGES: 'MIN_STAGES',
  REORDER_LENGTH: 'REORDER_LENGTH',
  REORDER_INVALID: 'REORDER_INVALID',
  REORDER_DUPLICATE: 'REORDER_DUPLICATE',
  NO_FINAL: 'NO_FINAL',
  NOT_PAYMENT_STAGE: 'NOT_PAYMENT_STAGE',
  BP_TOO_LOW: 'BP_TOO_LOW',
  BP_TOO_HIGH: 'BP_TOO_HIGH',
  NO_PAYMENT_NODE: 'NO_PAYMENT_NODE',
  SUM_NOT_100: 'SUM_NOT_100',

  // 订单
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_OWNED: 'ORDER_NOT_OWNED',
  // F1 围剿：客户凭 QQ+订单号查询已退役（高熵令牌取代）
  MY_ORDERS_RETIRED: 'MY_ORDERS_RETIRED',
  LOOKUP_RETIRED: 'LOOKUP_RETIRED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  // P2-F9: 终态订单收款状态守卫（cancelled 仅冲正 / delivered 拒正收款）
  PAYMENT_STATUS_BLOCKED: 'PAYMENT_STATUS_BLOCKED',
  // D-1（R-5/P3-1）: 订单 version 乐观锁冲突（旧快照写入被拒）
  ORDER_CONFLICT: 'ORDER_CONFLICT',
  DELIVER_WRONG_STATUS: 'DELIVER_WRONG_STATUS',
  TIER_NOT_FOUND: 'TIER_NOT_FOUND',
  ILLEGAL_PATH: 'ILLEGAL_PATH',
  MISSING_FILE: 'MISSING_FILE',
  // REQ-022 F1: 发布为作品
  PUBLISH_WRONG_STATUS: 'PUBLISH_WRONG_STATUS',
  DELIVERABLE_NOT_FOUND: 'DELIVERABLE_NOT_FOUND',

  // 通用
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION: 'VALIDATION',
  RATE_LIMITED: 'RATE_LIMITED',
  MISSING_PARAMS: 'MISSING_PARAMS',

  // 输入校验
  QQ_REQUIRED: 'QQ_REQUIRED',
  QQ_FORMAT: 'QQ_FORMAT',
  MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',

  // 订单输入
  ARTIST_NOT_OPEN: 'ARTIST_NOT_OPEN',
  RULES_NOT_AGREED: 'RULES_NOT_AGREED',
  STATUS_REQUIRED: 'STATUS_REQUIRED',
  NOTE_EMPTY: 'NOTE_EMPTY',
  ORDER_INVALID_ID: 'ORDER_INVALID_ID',

  // 画师扩展
  SUBDOMAIN_FORMAT: 'SUBDOMAIN_FORMAT',

  // 订单扩展
  ORDER_INVALID_STATUS: 'ORDER_INVALID_STATUS',
  QUEUE_EMPTY: 'QUEUE_EMPTY',
  QUEUE_NOT_OWNED: 'QUEUE_NOT_OWNED',
  QUEUE_LENGTH: 'QUEUE_LENGTH',
  QUEUE_DUPLICATE: 'QUEUE_DUPLICATE',
  INVALID_PRIORITY: 'INVALID_PRIORITY',

  // 上传
  ILLEGAL_FILE_TYPE: 'ILLEGAL_FILE_TYPE',
  UNSUPPORTED_FORMAT: 'UNSUPPORTED_FORMAT',

  // 埋点（REQ-033）
  INVALID_EVENT_PAYLOAD: 'INVALID_EVENT_PAYLOAD',

  // 管理员
  ADMIN_VERIFY_FAILED: 'ADMIN_VERIFY_FAILED',

  // 增项选择（SPEC-PRICE-2：用途/加急各只生效一个）
  ADDON_SELECTION_MUTEX: 'ADDON_SELECTION_MUTEX',

  // 计算
  PRICING_CALC_FAILED: 'PRICING_CALC_FAILED',

  // 价格（v0.11）
  INVALID_PRICE: 'INVALID_PRICE',

  // 焦点图（v0.11）
  FOCUS_IMAGE_NOT_FOUND: 'FOCUS_IMAGE_NOT_FOUND',
  FOCUS_IMAGE_NOT_OWNED: 'FOCUS_IMAGE_NOT_OWNED',
  INVALID_FOCUS_MODE: 'INVALID_FOCUS_MODE',

  // 外链（v0.12 R15）
  LINKS_TOO_MANY: 'LINKS_TOO_MANY',
  LINK_URL_INVALID: 'LINK_URL_INVALID',

  // 社交平台（v0.38 REQ-022 F2）
  PLATFORM_NOT_FOUND: 'PLATFORM_NOT_FOUND',
  PLATFORM_NAME_EMPTY: 'PLATFORM_NAME_EMPTY',
  PLATFORM_ICON_REQUIRED: 'PLATFORM_ICON_REQUIRED',
  PLATFORM_DOMAIN_INVALID: 'PLATFORM_DOMAIN_INVALID',
  PLATFORM_DOMAIN_TAKEN: 'PLATFORM_DOMAIN_TAKEN',

  // 图库（v0.12 R18）
  REFERENCES_LIMIT: 'REFERENCES_LIMIT',
  REFERENCE_DUPLICATE: 'REFERENCE_DUPLICATE',

  // 备注附图（v0.12 R19）
  NOTE_IMAGE_PATH_INVALID: 'NOTE_IMAGE_PATH_INVALID',

  // 流程跟踪（v0.14）
  TRACK_ALREADY_ON: 'TRACK_ALREADY_ON',
  NO_WORKFLOW_TEMPLATE: 'NO_WORKFLOW_TEMPLATE',

  // 备注删除（v0.15 R46）
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  SYSTEM_NOTE_PROTECTED: 'SYSTEM_NOTE_PROTECTED',

  // 强调色（v0.15 R49）
  INVALID_ACCENT_COLOR: 'INVALID_ACCENT_COLOR',

  // 截稿日（v0.15 R51）
  INVALID_DEADLINE: 'INVALID_DEADLINE',

  // 开工日（#35: 交叉校验）
  INVALID_START_DATE: 'INVALID_START_DATE',

  // 公告过期日（#36: 不得早于今天）
  INVALID_ANNOUNCEMENT_DATE: 'INVALID_ANNOUNCEMENT_DATE',

  // 下单页模板（v0.16 R58-7）
  INVALID_ORDER_TEMPLATE: 'INVALID_ORDER_TEMPLATE',

  // 平台链接（v0.17 R58-8）
  PLATFORM_URLS_TOO_MANY: 'PLATFORM_URLS_TOO_MANY',
  PLATFORM_URL_INVALID: 'PLATFORM_URL_INVALID',

  // 灵感标签（v0.17）
  TAGS_TOO_MANY: 'TAGS_TOO_MANY',

  // 附加工作项（v0.17 SPEC-003）
  EXTRA_ITEM_LIMIT: 'EXTRA_ITEM_LIMIT',
  ORDER_FINAL_STATE: 'ORDER_FINAL_STATE',
  // audit-a R-2: 取消已收款订单需确认
  CANCEL_WITH_PAYMENT: 'CANCEL_WITH_PAYMENT',
  // 815 拍板 #1：取消撤销窗口过期
  CANCEL_UNDO_EXPIRED: 'CANCEL_UNDO_EXPIRED',
  // 815 拍板 #4：交付文件一次性下载
  DOWNLOAD_LOCKED: 'DOWNLOAD_LOCKED',
  DOWNLOAD_COOLDOWN: 'DOWNLOAD_COOLDOWN',

  // 名额与缓冲（v0.17 SPEC-004）
  BATCH_FULL: 'BATCH_FULL',
  INVALID_BATCH_LIMIT: 'INVALID_BATCH_LIMIT',
  NOT_BUFFER_ORDER: 'NOT_BUFFER_ORDER',

  // 流程（v0.19 P1-5）
    STAGE_IN_USE: 'STAGE_IN_USE',

    // 流程重置（v0.24 P0-1）
    STAGES_RESET_BLOCKED: 'STAGES_RESET_BLOCKED',

    // 流程变更守卫（批4 B10）
    WORKFLOW_PAYMENT_IN_USE: 'WORKFLOW_PAYMENT_IN_USE',

  // 作品
  ARTWORK_NOT_FOUND: 'ARTWORK_NOT_FOUND',
  // 封面上限（Beta 冲刺 T8，用户 2026-08-06 拍板）
  COVER_LIMIT_REACHED: 'COVER_LIMIT_REACHED',

  // 档位三态（v0.24 #10）
  TIER_NOT_AVAILABLE: 'TIER_NOT_AVAILABLE',

  // 折扣码（v0.31 F3）
  DISCOUNT_CODE_NOT_FOUND: 'DISCOUNT_CODE_NOT_FOUND',
  DISCOUNT_CODE_TAKEN: 'DISCOUNT_CODE_TAKEN',
  DISCOUNT_CODE_INVALID: 'DISCOUNT_CODE_INVALID',
  DISCOUNT_CODE_EXPIRED: 'DISCOUNT_CODE_EXPIRED',
  DISCOUNT_CODE_EXHAUSTED: 'DISCOUNT_CODE_EXHAUSTED',
  DISCOUNT_DISABLED: 'DISCOUNT_DISABLED',

  // 多画风（v0.32 REQ-023）
  STYLE_NOT_FOUND: 'STYLE_NOT_FOUND',
  STYLE_NAME_EMPTY: 'STYLE_NAME_EMPTY',
  STYLE_SIZE_NOT_FOUND: 'STYLE_SIZE_NOT_FOUND',
  STYLE_SIZE_NAME_EMPTY: 'STYLE_SIZE_NAME_EMPTY',
  STYLE_SIZE_INVALID_PRICE: 'STYLE_SIZE_INVALID_PRICE',
  STYLE_SIZE_NOT_AVAILABLE: 'STYLE_SIZE_NOT_AVAILABLE',
  ADDON_TEMPLATE_NOT_FOUND: 'ADDON_TEMPLATE_NOT_FOUND',
  ADDON_TEMPLATE_NAME_EMPTY: 'ADDON_TEMPLATE_NAME_EMPTY',
  ADDON_TEMPLATE_INVALID_PRICE: 'ADDON_TEMPLATE_INVALID_PRICE',
  ADDON_TEMPLATE_INVALID_CONTROL: 'ADDON_TEMPLATE_INVALID_CONTROL',
  ADDON_TEMPLATE_INVALID_PRICING: 'ADDON_TEMPLATE_INVALID_PRICING',
  STYLE_ADDON_NOT_FOUND: 'STYLE_ADDON_NOT_FOUND',
  STYLE_ADDON_DUPLICATE: 'STYLE_ADDON_DUPLICATE',
  SIZE_OVERRIDE_NOT_FOUND: 'SIZE_OVERRIDE_NOT_FOUND',

  // 计价引擎（v0.37 REQ-025）
  PRICING_CONSERVATION: 'PRICING_CONSERVATION',
  PRICE_CHANGE_AFTER_DONE: 'PRICE_CHANGE_AFTER_DONE'
} as const

// ─── 错误码 → 中文用户友好消息 ───
// 全局错误处理器优先查此表，未命中则回退到 error.message
export const ERROR_MESSAGES: Record<string, string> = {
  // 认证
  NOT_LOGGED_IN: '请先登录',
  SESSION_EXPIRED: '登录已过期，请重新登录',
  ACCOUNT_NOT_FOUND: '账号不存在',
  ACCOUNT_DISABLED: '账号已被禁用',
  ARTIST_BANNED: '账号已被封禁，如有疑问请联系管理员',
  TOKEN_REVOKED: '登录已失效，请重新登录',
  // 桌面端记账式会话（v73）：设备被踢出信任清单（换机/被盗场景管理员操作）
  DEVICE_REVOKED: '该设备已被移出信任清单，请重新登录',
  ADMIN_REQUIRED: '需要管理员权限',
  // F-9（审计批F）: 旧登录码时代错误码已退役删除（见 E 枚举同注释）
  QQ_NOT_REGISTERED: '该QQ号尚未注册',
  // REQ-027: TOTP 动态口令
  TOTP_NOT_BOUND: '该画师尚未绑定动态口令，请联系管理员绑定',
  TOTP_INVALID: 'QQ号或动态口令错误',
  TOTP_LOCKED: '尝试次数过多，账号已临时锁定，请稍后再试',
  TOTP_BIND_INVALID: '动态口令错误，请让画师确认验证器上当前显示的 6 位码',
  TOTP_BIND_REQUIRED: '你的动态口令绑定已失效（可能刚被重置或绑定未完成），请重新完成绑定流程，或联系管理员处理',
  // REQ-040: WebAuthn Passkey
  WEBAUTHN_CHALLENGE_INVALID: '验证超时或 Challenge 无效，请重试',
  WEBAUTHN_REGISTRATION_FAILED: 'Passkey 注册失败，请重试',
  WEBAUTHN_AUTHENTICATION_FAILED: '身份验证失败，请重试',
  WEBAUTHN_CREDENTIAL_EXISTS: '该设备已注册',
  WEBAUTHN_CREDENTIAL_NOT_FOUND: 'Passkey 凭据不存在',
  // REQ-040: TOTP 自助重绑
  REBIND_COOLDOWN: '重绑操作过于频繁，请在 24 小时后再试',
  REBIND_NO_CREDENTIAL: '没有可用的验证方式，请联系管理员重绑',
  // REQ-039: 邀请码注册
  INVITE_INVALID: '邀请码无效、已使用或已过期',
  INVITE_CANNOT_REVOKE: '仅未使用的邀请码可吊销',
  ONBOARDING_DISABLED: '当前未开启邀请入驻，请联系管理员开通',

  // 画师
  ARTIST_NOT_FOUND: '画师不存在',
  NAME_EMPTY: '名称不能为空',
  CODE_FORMAT: '身份码格式不正确（仅限大写字母和数字，2-20 位）',
  CODE_TAKEN: '该身份码已被使用',
  QQ_TAKEN: '该QQ号已被注册',
  SUBDOMAIN_TAKEN: '该主页标识已被使用',
  INVALID_STATUS: '无效的状态值',
  INVALID_URL: '链接格式不正确',
  SUBDOMAIN_FORMAT: '主页标识格式不正确',

  // 流程
  STAGE_NOT_FOUND: '流程节点不存在',
  STAGE_NAME_EMPTY: '节点名称不能为空',
  FINAL_CANNOT_DISABLE: '交付节点不能禁用',
  FINAL_CANNOT_DELETE: '交付节点不能删除',
  FINAL_READONLY: '交付节点不可修改',
  MAX_INSTALLMENTS: '分期数已达上限',
  FINAL_TOO_LOW: '尾款比例过低',
  MIN_STAGES: '流程节点数不能少于最低要求',
  REORDER_LENGTH: '排序列表长度不匹配',
  REORDER_INVALID: '排序列表包含无效节点',
  REORDER_DUPLICATE: '排序列表存在重复',
  NO_FINAL: '缺少交付节点',
  NOT_PAYMENT_STAGE: '该节点不是收款节点',
  BP_TOO_LOW: '比例过低',
  BP_TOO_HIGH: '比例过高',
  NO_PAYMENT_NODE: '没有收款节点',
  SUM_NOT_100: '各期比例之和必须为100%',

  // 订单
  ORDER_NOT_FOUND: '订单不存在',
  ORDER_NOT_OWNED: '该订单不属于你，无权操作',
  // F1 围剿：退役文案——指引客户使用保存的追踪链接或联系画师补发
  MY_ORDERS_RETIRED: '「我的订单」查询已下线，请使用下单时保存的追踪链接，或联系画师补发',
  LOOKUP_RETIRED: '「订单查询」已下线，请使用下单时保存的追踪链接，或联系画师补发',
  INVALID_TRANSITION: '不允许的状态变更',
  PAYMENT_STATUS_BLOCKED: '当前订单状态不允许该收款操作',
  ORDER_CONFLICT: '订单已被其他操作更新，请刷新后重试',
  DELIVER_WRONG_STATUS: '当前状态不允许交付',
  TIER_NOT_FOUND: '价格档位不存在',
  ORDER_INVALID_STATUS: '无效的订单状态',
  QUEUE_EMPTY: '排序列表不能为空',
  QUEUE_NOT_OWNED: '队列中包含不属于你的订单',
  QUEUE_LENGTH: '排序列表长度与实际队列不匹配',
  QUEUE_DUPLICATE: '排序列表存在重复订单',
  INVALID_PRIORITY: '无效的优先级',
  ORDER_INVALID_ID: '无效的订单ID',

  // 上传
  ILLEGAL_FILE_TYPE: '不支持的文件类型',
  UNSUPPORTED_FORMAT: '不支持的文件格式',
  ILLEGAL_PATH: '非法的文件路径',
  MISSING_FILE: '缺少文件',
  // REQ-022 F1: 发布为作品
  PUBLISH_WRONG_STATUS: '仅已交付（delivered）的订单可发布为作品',
  DELIVERABLE_NOT_FOUND: '交付文件不存在或不属于该订单',

  // 埋点（REQ-033）
  INVALID_EVENT_PAYLOAD: '事件扩展数据过大（单事件序列化 ≤2KB）',

  // 通用
  NOT_FOUND: '资源不存在',
  VALIDATION: '请求参数格式不正确',
  RATE_LIMITED: '操作过于频繁，请稍后再试',
  MISSING_PARAMS: '缺少必要参数',

  // 输入校验
  QQ_REQUIRED: '请填写QQ号',
  QQ_FORMAT: 'QQ号格式不正确（5-15位数字）',
  MISSING_CREDENTIALS: '请输入QQ号和登录码',

  // 订单输入
  ARTIST_NOT_OPEN: '该画师当前不接受新约稿',
  RULES_NOT_AGREED: '请先阅读并同意约稿须知',
  STATUS_REQUIRED: '请指定状态',
  NOTE_EMPTY: '备注内容不能为空',

  // 管理员
  ADMIN_VERIFY_FAILED: '管理员验证失败',

  // 增项选择（SPEC-PRICE-2）
  ADDON_SELECTION_MUTEX: '用途/加急增项各只能选择一个生效',

  // 计算
  PRICING_CALC_FAILED: '价格计算失败',

  // 价格（v0.11）
  INVALID_PRICE: '价格无效（须为正整数，单位：分，上限 100000000 分 = 100 万元）',

  // 焦点图（v0.11）
  FOCUS_IMAGE_NOT_FOUND: '参考图不存在',
  FOCUS_IMAGE_NOT_OWNED: '该参考图不属于此订单',
  INVALID_FOCUS_MODE: '无效的焦点图模式（可选：off/small/large）',

  // 外链（v0.12 R15）
  LINKS_TOO_MANY: '外链数量不能超过8条',
  LINK_URL_INVALID: '外链地址格式不正确（须以 http:// 或 https:// 开头）',

  // 社交平台（v0.38 REQ-022 F2）
  PLATFORM_NOT_FOUND: '社交平台不存在',
  PLATFORM_NAME_EMPTY: '平台名称不能为空',
  PLATFORM_ICON_REQUIRED: '平台图标键（icon_key）与单字兜底（fallback_char）至少填一项',
  PLATFORM_DOMAIN_INVALID: '平台域名格式不正确（不含协议/路径/端口）',
  PLATFORM_DOMAIN_TAKEN: '该域名已被其他启用平台占用',

  // 图库（v0.12 R18）
  REFERENCES_LIMIT: '参考图总数不能超过20张',
  REFERENCE_DUPLICATE: '该图片已在图库中',

  // 备注附图（v0.12 R19）
  NOTE_IMAGE_PATH_INVALID: '备注附图路径不合法',

  // 流程跟踪（v0.14）
  TRACK_ALREADY_ON: '该订单已启用流程跟踪',
  NO_WORKFLOW_TEMPLATE: '请先创建工作流模板（至少 1 个节点）',

  // 备注删除（v0.15 R46）
  NOTE_NOT_FOUND: '备注不存在',
  SYSTEM_NOTE_PROTECTED: '系统备注不可删除',

  // 强调色（v0.15 R49）
  INVALID_ACCENT_COLOR: '无效的强调色（仅允许预设色值）',

  // 截稿日（v0.15 R51）
  INVALID_DEADLINE: '截稿日格式无效（须为 ISO 8601）',

  // 开工日（#35: 交叉校验）
  INVALID_START_DATE: '开工日不能晚于截稿日',

  // 公告过期日（#36: 不得早于今天）
  INVALID_ANNOUNCEMENT_DATE: '公告过期日不能早于今天',

  // 下单页模板（v0.16 R58-7）
  INVALID_ORDER_TEMPLATE: '无效的下单页模板',

  // 平台链接（v0.17 R58-8）
  PLATFORM_URLS_TOO_MANY: '平台链接数量不能超过10条',
  PLATFORM_URL_INVALID: '平台链接格式不正确（须以 http:// 或 https:// 开头）',

  // 灵感标签（v0.17）
  TAGS_TOO_MANY: '灵感标签数量不能超过20个',

  // 附加工作项（v0.17 SPEC-003）
  EXTRA_ITEM_LIMIT: '附加工作项数量不能超过20条',
  ORDER_FINAL_STATE: '已交付或已取消的订单不能添加附加项',
  CANCEL_WITH_PAYMENT: '订单已有收款，取消前请确认退款安排',
  // 815 拍板 #1
  CANCEL_UNDO_EXPIRED: '撤销窗口已过（取消后 5 秒内可撤销）',
  // 815 拍板 #4
  DOWNLOAD_LOCKED: '该交付文件已下载过并被锁定，需画师再许可后才能再次下载',
  DOWNLOAD_COOLDOWN: '下载尝试过于频繁，请稍后重试',

  // 名额与缓冲（v0.17 SPEC-004）
  BATCH_FULL: '该画师已接满，暂时无法下单',
  INVALID_BATCH_LIMIT: '名额设置无效（正式位+缓冲位至少为1）',
  NOT_BUFFER_ORDER: '该订单不在缓冲区',

  // 流程（v0.19 P1-5）
    STAGE_IN_USE: '该节点下有进行中的订单，请先完成或转移后再删除',

    // 流程重置（v0.24 P0-1）
    STAGES_RESET_BLOCKED: '有 {count} 个进行中订单，请先完成或关闭流程跟踪后再重置工作流',

    // 流程变更守卫（批4 B10）
    WORKFLOW_PAYMENT_IN_USE: '有 {count} 个进行中的订单已引用收款节点，调整收款结构会影响这些订单的节点锁定与收款计划；请先完成订单或稍后再试',

  // 作品（v0.25 #5）
  ARTWORK_NOT_FOUND: '作品不存在',
  // 封面上限（Beta 冲刺 T8，用户 2026-08-06 拍板）
  COVER_LIMIT_REACHED: '封面最多 6 张',

  // 档位三态（v0.24 #10）
  TIER_NOT_AVAILABLE: '该档位暂不接受下单',

  // 折扣码（v0.31 F3）
  DISCOUNT_CODE_NOT_FOUND: '折扣码不存在',
  DISCOUNT_CODE_TAKEN: '该折扣码已被使用',
  DISCOUNT_CODE_INVALID: '折扣码无效',
  DISCOUNT_CODE_EXPIRED: '折扣码已过期',
  DISCOUNT_CODE_EXHAUSTED: '折扣码使用次数已达上限',
  DISCOUNT_DISABLED: '该画师未开启折扣码功能',

  // 多画风（v0.32 REQ-023）
  STYLE_NOT_FOUND: '画风不存在',
  STYLE_NAME_EMPTY: '画风名称不能为空',
  STYLE_SIZE_NOT_FOUND: '尺寸不存在',
  STYLE_SIZE_NAME_EMPTY: '尺寸名称不能为空',
  STYLE_SIZE_INVALID_PRICE: '尺寸价格无效',
  STYLE_SIZE_NOT_AVAILABLE: '该尺寸暂不接受约稿',
  ADDON_TEMPLATE_NOT_FOUND: '增项模板不存在',
  ADDON_TEMPLATE_NAME_EMPTY: '增项模板名称不能为空',
  ADDON_TEMPLATE_INVALID_PRICE: '增项模板价格无效',
  ADDON_TEMPLATE_INVALID_CONTROL: '无效的控件类型',
  ADDON_TEMPLATE_INVALID_PRICING: '无效的计价模式',
  STYLE_ADDON_NOT_FOUND: '画风增项不存在',
  STYLE_ADDON_DUPLICATE: '该增项已导入此画风',
  SIZE_OVERRIDE_NOT_FOUND: '尺寸覆盖不存在',

  // 计价引擎（v0.37 REQ-025）
  PRICING_CONSERVATION: '计价数据不守恒，操作已拒绝（请刷新后重试）',
  PRICE_CHANGE_AFTER_DONE: '订单已完成，改价请通过增减附加项操作（done 半终态仅允许条目化变动）'
}

